Repository Eventual-Inc/Daft, pull requests merged in 2022-10, with the labels that each got.

#237 Skip questions flag for TPC-H benchmarking
  benchmarking/tpch/__main__.py
Labels: benchmarking

#244 Dump metrics CSV during benchmarking with --output_csv flag
  benchmarking/tpch/__main__.py
Labels: benchmarking

#246 Log exceptions in TPC-H benchmarking
  benchmarking/tpch/__main__.py
Labels: benchmarking

#251 add pickle5 to requirements when under python3.8
  poetry.lock
  pyproject.toml
Labels: bug

#254 Update docs to reflect yanked 0.0.12 version
  docs/source/release_notes.rst
  docs/source/release_notes/0.0.13.rst
  pyproject.toml
Labels: documentation

#257 Fix explode column pruning optimizer bug
  daft/dataframe/dataframe.py
  daft/logical/logical_plan.py
  tests/dataframe_cookbook/test_explodes.py
Labels: bug

#247 Add null testing for operators and fix mod operator
  daft/runners/blocks.py
  tests/test_expression_types.py
Labels: bug

#268 Fixes and unit tests for aggregations on null items
  daft/runners/blocks.py
  tests/conftest.py
  tests/dataframe_cookbook/test_filter.py
  tests/null_tests/__init__.py
  tests/null_tests/test_aggregations.py
Labels: bug

#270 v0.0.14 documentation
  README.md
  docs/source/index.rst
  docs/source/release_notes.rst
  docs/source/release_notes/0.0.13.rst
  docs/source/release_notes/0.0.14.rst
  pyproject.toml
Labels: documentation

#276 Search Sorted Offset Fix for Arrow Views
  daft/experimental/schema.py
  daft/internal/kernels/hashing.cc
  daft/internal/kernels/memory_view.h
  daft/internal/kernels/search_sorted.cc
  tests/internal/test_search_sorted.py
Labels: bug

#280 Fix type inference in DataFrame.from_pydict
  daft/dataframe/dataframe.py
  daft/runners/partitioning.py
  tests/dataframe_cookbook/test_dataloading.py
Labels: bug

#287 v0.0.15 release notes
  docs/source/release_notes.rst
  docs/source/release_notes/0.0.15.rst
  docs/source/release_notes/_template.rst
  pyproject.toml
Labels: documentation

#293 Add Cast expression operator
  daft/execution/operators.py
  daft/expressions.py
  daft/runners/blocks.py
  daft/types.py
  tests/expression_operators/__init__.py
  tests/expression_operators/test_cast.py
  tests/expression_operators/test_datetime.py
  tests/expression_operators/test_if_else.py
  tests/expression_operators/test_null.py
  tests/expression_operators/test_string.py
  tests/expression_operators/test_url.py
  tests/test_expression_types.py
Labels: enhancement

#292 Add HTTP URL handling for DataFrame.from_parquet
  daft/execution/logical_op_runners.py
Labels: enhancement

#295 Documentation updates
  README.md
  README.rst
  pyproject.toml
Labels: documentation

#296 Modify landing page and add header to Daft website
  docs/source/_static/amazon-s3-logo.png
  docs/source/_static/arrow-logo.png
  docs/source/_static/azure-blob-store.png
  docs/source/_static/discord-logo.svg
  docs/source/_static/github-logo.png
  docs/source/_static/google-cloud-storage.png
  docs/source/_static/header.css
  docs/source/_static/icon-menu-close.svg
  docs/source/_static/icon-menu-dots.svg
  docs/source/_static/jupyter-logo.png
  docs/source/_static/landing-page.css
  docs/source/_static/mobile-menu.js
  docs/source/_static/numpy-logo.png
  docs/source/_static/pandas-logo.png
  docs/source/_static/parquet-logo.png
  docs/source/_static/polars-logo.svg
  docs/source/_static/pytorch-logo.png
  docs/source/_static/ray-logo.png
  docs/source/_static/scikit-learn-logo.png
  docs/source/_static/tensorflow-logo.png
  docs/source/_templates/layout.html
  docs/source/_templates/sections/header.html
  docs/source/_templates/sections/landing-page-body.html
  docs/source/_templates/sections/mobile-menu.html
  docs/source/api_docs.rst
  docs/source/conf.py
  docs/source/docs/api_docs/context.rst
  docs/source/docs/api_docs/dataframe.rst
  docs/source/docs/api_docs/expressions.rst
  docs/source/docs/api_docs/groupby.rst
  docs/source/docs/api_docs/index.rst
  docs/source/docs/api_docs/udf.rst
  docs/source/docs/index.rst
  docs/source/docs/learn/10-min.ipynb
  docs/source/docs/learn/index.rst
  docs/source/docs/learn/install.rst
  docs/source/docs/learn/quickstart.ipynb
  docs/source/docs/learn/tutorials.rst
  docs/source/docs/learn/user_guides.rst
  docs/source/docs/learn/user_guides/dataframes.rst
  docs/source/docs/learn/user_guides/expressions.rst
  docs/source/docs/learn/user_guides/remote_cluster_execution.rst
  docs/source/docs/learn/user_guides/types_and_ops.rst
  docs/source/docs/learn/user_guides/udf.rst
  docs/source/docs/release_notes/0.0.13.rst
  docs/source/docs/release_notes/0.0.14.rst
  docs/source/docs/release_notes/0.0.16.rst
  docs/source/docs/release_notes/_template.rst
  docs/source/docs/release_notes/index.rst
  docs/source/index.rst
  docs/source/learn.rst
  docs/source/release_notes.rst
Labels: documentation

#300 Fix quantile calculations in sort
  daft/runners/partitioning.py
  daft/runners/shuffle_ops.py
  tests/runners/test_partitioning.py
Labels: bug
