Repository Eventual-Inc/Daft, pull requests merged in 2023-11, with the labels that each got.

#1562 [CHORE] [ScanOperator-Follow-Ons-1] Pointer Equality using Arc newtype instead of on `dyn ScanOperator` trait object
  src/daft-plan/src/builder.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/planner.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
Labels: chore

#1563 [CHORE] [ScanOperator-Follow-Ons-2] Refactor MicroPartition to have non-optional TableMetadata
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/agg.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/ops/concat.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/ops/partition.rs
  src/daft-micropartition/src/ops/slice.rs
  src/daft-micropartition/src/ops/sort.rs
  src/daft-micropartition/src/ops/take.rs
  src/daft-micropartition/src/python.rs
Labels: chore

#1564 [CHORE] [ScanOperator-Follow-Ons-3] Integrate GlobScanOperator with new scan node builder
  daft/daft.pyi
  daft/io/common.py
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
Labels: chore

#1565 [CHORE][ScanOperator 2/3] Refactor ScanTask to be multi-file and removes ScanTaskBatch
  daft/daft.pyi
  daft/execution/rust_physical_plan_shim.py
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
Labels: chore

#1566 [BUG][ScanOperator 3/3] Incremental bugfixes for daft v2 scans
  Cargo.lock
  daft/io/common.py
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
Labels: bug

#1559 [FEAT][ScanOperator 1/3] Add MVP e2e `ScanOperator` integration.
  Cargo.lock
  daft/daft.pyi
  daft/execution/execution_step.py
  daft/execution/rust_physical_plan_shim.py
  daft/io/_csv.py
  daft/io/_parquet.py
  daft/io/common.py
  daft/logical/builder.py
  daft/table/micropartition.py
  daft/table/table.py
  daft/table/table_io.py
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/agg.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/ops/partition.rs
  src/daft-micropartition/src/ops/slice.rs
  src/daft-micropartition/src/ops/sort.rs
  src/daft-micropartition/src/ops/take.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-plan/src/test/mod.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/py_object_serde.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/storage_config.rs
  src/daft-stats/src/partition_spec.rs
  src/daft-stats/src/table_metadata.rs
  tests/table/table_io/test_csv.py
  tests/table/table_io/test_parquet.py
Labels: enhancement

#1580 [BUG] add allow threads for io pool operations
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/python.rs
Labels: bug

#1581 [BUG] Fix Deadlock with ScanOperators in `to_physical_plan_scheduler` and show iostats for glob and from_scan_task
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-scan/src/glob.rs
Labels: bug

#1578 [FEAT] [Scan Operator] Add Python I/O support (+ JSON) to `MicroPartition` reads
  src/daft-csv/src/read.rs
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  tests/dataframe/test_creation.py
Labels: enhancement

#1577 [CHORE] Convert GlobScanOperator to perform streaming into result and take a list of glob paths
  Cargo.lock
  daft/daft.pyi
  daft/io/common.py
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
Labels: chore

#1588 [BUG] Use multithreaded tokio runtime with one thread for multithreaded_io=False
  src/daft-io/src/lib.rs
Labels: bug

#1579 [CHORE] Use DAFT_MICROPARTITIONS as shared feature flag for data catalog support
  daft/io/common.py
  src/daft-io/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
  tests/dataframe/test_creation.py
Labels: chore

#1593 [BUG] Update requirements for typing_extensions
  pyproject.toml
Labels: bug

#1586 [FEAT] [Scan Operator] Integrate `size_bytes` with `ScanOperator`s
  daft/daft.pyi
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/runners/partitioning.py
  daft/table/micropartition.py
  src/daft-io/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
Labels: enhancement

#1590 [FEAT] [Scan Operator] Add `ChunkSpec` for specifying format-specific per-file row subset selection for `ScanTask`s.
  daft/daft.pyi
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
Labels: enhancement

#1595 [FEAT] [Scan Operator] Refactor planning and execution code to use shared `Pushdowns` struct.
  src/daft-micropartition/src/micropartition.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-plan/src/test/mod.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
Labels: enhancement

#1592 [FEAT] Add translation of IOConfig to PyArrow filesystem arguments
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/filesystem.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/logical/builder.py
  daft/table/schema_inference.py
  daft/table/table_io.py
  src/common/io-config/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/sink_info.rs
  src/daft-scan/src/py_object_serde.rs
  src/daft-scan/src/storage_config.rs
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_write_files_s3_minio.py
Labels: enhancement

#1597 [BUG] clean up ray scheduler threads after computing partial results
  daft/runners/ray_runner.py
  tests/ray/runner.py
Labels: bug

#1584 [CHORE] add IOStats to all micropartition ops
  src/daft-io/src/stats.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/agg.rs
  src/daft-micropartition/src/ops/concat.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/ops/partition.rs
  src/daft-micropartition/src/ops/slice.rs
  src/daft-micropartition/src/ops/sort.rs
  src/daft-micropartition/src/ops/take.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/python.rs
Labels: chore

#1603 [CHORE] delete unused wheel tools
  tools/wheels/__init__.py
  tools/wheels/_vendor/__init__.py
  tools/wheels/_vendor/wheel/LICENSE.txt
  tools/wheels/_vendor/wheel/__init__.py
  tools/wheels/_vendor/wheel/cli/__init__.py
  tools/wheels/_vendor/wheel/cli/convert.py
  tools/wheels/_vendor/wheel/cli/pack.py
  tools/wheels/_vendor/wheel/cli/unpack.py
  tools/wheels/_vendor/wheel/pkginfo.py
  tools/wheels/_vendor/wheel/util.py
  tools/wheels/_vendor/wheel/wheelfile.py
  tools/wheels/fix-and-copy-wheel.py
  tools/wheels/tmpdirs.py
  tools/wheels/tools.py
  tools/wheels/wheeltools.py
Labels: chore

#1604 [PERF] Speed Up MicroPartition Ops when we know the result is empty
  src/daft-core/src/series/ops/take.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/ops/slice.rs
  src/daft-micropartition/src/ops/take.rs
Labels: performance

#1605 [PERF][REVERT] Reverts: use pyarrow table for pickling rather than ChunkedArray (#1488)
  daft/series.py
Labels: performance

#1611 [BUG] remove f strings from logging
  daft/analytics.py
  daft/execution/physical_plan.py
  daft/runners/profiler.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/table/table.py
Labels: bug

#1608 [BUG] Manually specify region in tutorial read_json
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Labels: bug, documentation

#1612 [BUG] enable fixed size binary ingest to daft binary
  daft/datatype.py
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/utils/arrow.rs
Labels: bug

#1615 [BUG] Add better handling for case where glob of parquet files returns empty
  daft/table/table.py
  tests/integration/io/parquet/test_reads_s3_minio.py
Labels: bug

#1617 [BUG] Self-concat breaks with the RayRunner
  daft/runners/ray_runner.py
  tests/dataframe/test_concat.py
Labels: bug

#1618 [CHORE] drop ray default dep to make room for Pydantic > 2.0
  pyproject.toml
  requirements-dev.txt
Labels: chore

#1619 [CHORE] delete old rule runners
  daft/internal/rule.py
  daft/internal/rule_runner.py
  daft/internal/treenode.py
Labels: chore

#1616 [BUG] Roundtrip tests for CSVs and Parquet
  tests/io/test_csv_roundtrip.py
  tests/io/test_parquet_roundtrip.py
Labels: bug

#1622 [CHORE] update azure storage blobs to 0.17.0
  Cargo.lock
  src/daft-io/Cargo.toml
Labels: chore

#1620 [CHORE] update fsspecs (s3, gcs, aldfs) in lockstep
  requirements-dev.txt
  tests/integration/io/test_list_files_http.py
Labels: chore

#1625 [BUG] Fix parquet timestamp tz roundtrip inference
  Cargo.lock
  Cargo.toml
  tests/io/test_parquet_roundtrip.py
Labels: bug

#1609 [FEAT] Enable Progress Bars for PyRunner and RayRunner
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/expressions/expressions.py
  daft/runners/progress_bar.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  pyproject.toml
Labels: enhancement

#1561 [FEAT] Iceberg Scan Operator
  .github/workflows/python-package.yml
  daft/__init__.py
  daft/daft.pyi
  daft/iceberg/__init__.py
  daft/iceberg/iceberg_scan.py
  daft/io/__init__.py
  daft/io/_iceberg.py
  daft/io/scan.py
  pyproject.toml
  requirements-dev.txt
  src/common/io-config/src/s3.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-stats/src/partition_spec.rs
  tests/integration/iceberg/conftest.py
  tests/integration/iceberg/docker-compose/docker-compose.yml
  tests/integration/iceberg/test_table_load.py
Labels: enhancement

#1628 [BUG] raise error if non valid parquet file (less than parquet footer size)
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/stream_reader.rs
  tests/table/table_io/test_parquet.py
Labels: bug

#1629 [BUG] Filter out size-0 directory marker files during s3 globs
  src/daft-io/src/object_store_glob.rs
  tests/integration/io/test_list_files_gcs.py
Labels: bug

#1631 [CHORE] add ray client to deps
  pyproject.toml
  requirements-dev.txt
Labels: chore

#1626 [BUG] Fix CSV roundtrip for decimals (actually an f64->decimal casting bug)
  src/daft-core/src/array/ops/cast.rs
  tests/io/test_csv_roundtrip.py
Labels: bug

#1582 Enabling quote, comment and escape character
  daft/daft.pyi
  daft/execution/execution_step.py
  daft/io/_csv.py
  daft/logical/schema.py
  daft/runners/partitioning.py
  daft/table/micropartition.py
  daft/table/table.py
  daft/table/table_io.py
  src/daft-csv/src/lib.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/python.rs
  src/daft-csv/src/read.rs
  src/daft-csv/test/iris_tiny_comment.csv
  src/daft-csv/test/iris_tiny_escape.csv
  src/daft-csv/test/iris_tiny_single_quote.csv
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  tests/table/table_io/test_csv.py
Labels: enhancement

#1635 [CHORE] Fix style lints from #1582
  daft/daft.pyi
  daft/io/_csv.py
  daft/table/table_io.py
  src/daft-csv/src/lib.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/file_format.rs
Labels: chore

#1649 [CHORE] Fixed bug in ray version
  daft/datatype.py
  daft/runners/ray_runner.py
  tests/ray/test_datasets.py
Labels: bug

#1654 [CHORE] enable refresh on tqdm total updates
  daft/runners/progress_bar.py
Labels: chore

#1651 [FEAT] Use cached preview from `df.collect()` in `df.show()`.
  daft/dataframe/dataframe.py
  tests/dataframe/test_show.py
Labels: enhancement

#1614 [FEAT] [CSV Reader] Bulk CSV reader + general CSV reader refactor
  Cargo.lock
  daft/daft.pyi
  daft/logical/schema.py
  daft/table/micropartition.py
  daft/table/schema_inference.py
  daft/table/table.py
  daft/table/table_io.py
  src/daft-csv/Cargo.toml
  src/daft-csv/src/lib.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/options.rs
  src/daft-csv/src/python.rs
  src/daft-csv/src/read.rs
  src/daft-decoding/src/deserialize.rs
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/glob.rs
Labels: enhancement

#1637 [FEAT] 1606 - Adding hour expression in date util
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/date.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/date.rs
  src/daft-dsl/src/functions/temporal/hour.rs
  src/daft-dsl/src/functions/temporal/mod.rs
  src/daft-dsl/src/python.rs
  tests/series/test_temporal_ops.py
Labels: enhancement

#1655 [FEAT] Print the results of a df.show() to stdout if running in non-interactive mode
  daft/dataframe/dataframe.py
  daft/runners/progress_bar.py
  tests/dataframe/test_show.py
Labels: enhancement

#1657 [CHORE] pin ray to 2.7.1 if less than 3.8
  requirements-dev.txt
Labels: chore

#1661 [CHORE] pin pandas for 3.8
  requirements-dev.txt
Labels: chore

#1660 [PERF] Remove calls to `remote_len_partition`
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  daft/runners/runner_io.py
Labels: performance

#1662 [FEAT] Dynamic Responsive Printing of Tables, Schema and Series
  Cargo.lock
  Cargo.toml
  daft/dataframe/dataframe.py
  src/daft-core/Cargo.toml
  src/daft-core/src/schema.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/utils/display_table.rs
  src/daft-core/src/utils/mod.rs
  src/daft-csv/src/read.rs
  src/daft-table/Cargo.toml
  src/daft-table/src/lib.rs
  tests/dataframe/test_repr.py
  tests/series/test_tensor.py
  tests/test_schema.py
  tests/utils.py
Labels: enhancement

#1663 [FEAT] add retries to s3 credential provider timeouts
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1664 [BUG] favor char indices instead of slicing to deal with unicode
  src/daft-core/src/utils/display_table.rs
  tests/dataframe/test_repr.py
Labels: bug

#1632 [BUG] Add an allowlist of DataTypes that ColumnRangeStatistics supports and validation of TableStatistics
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/src/statistics/column_range.rs
  src/daft-parquet/src/statistics/table_stats.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-stats/src/table_stats.rs
Labels: bug

#1673 [FEAT] show number of truncated columns
  src/daft-core/src/utils/display_table.rs
Labels: enhancement

#1676 [CHORE] Bring in TreeNode and Refactor Expression Traversal to use TreeNode
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/expressions/expressions.py
  src/common/treenode/Cargo.toml
  src/common/treenode/src/lib.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/treenode.rs
Labels: chore

#1677 [CHORE] Favor traversal over visitors
  src/daft-dsl/src/optimization.rs
Labels: chore

#1678 [BUG] Check queue state while waiting to place inside
  daft/runners/ray_runner.py
  tests/ray/runner.py
Labels: bug

#1680 [FEAT] Partitioning exprs for Iceberg
  daft/daft.pyi
  daft/series.py
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-dsl/src/functions/partitioning/mod.rs
  src/daft-dsl/src/python.rs
  tests/series/test_partitioning.py
Labels: enhancement

#1681 [BUG] fix off by 1 for retries for cred provider
  src/daft-io/src/s3_like.rs
Labels: bug

#1683 [FEAT] Temporal Literals for Date and Timestamp
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/utils/display_table.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
Labels: enhancement

#1685 [CHORE] Bump Iceberg Version and V1 of caching
  .github/workflows/python-package.yml
  tests/integration/iceberg/docker-compose/Dockerfile
Labels: chore
