Repository Eventual-Inc/Daft, pull requests merged in 2023-10, with the labels that each got.

#1451 [CHORE] update s3 connection defaults
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
Labels: chore

#1450 [FEAT] Native `glob` functionality
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/glob.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/python.rs
  tests/integration/io/test_list_files_s3_minio.py
Labels: enhancement

#1452 [PERF] Native globbing early stopping
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/glob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/benchmarks/__init__.py
  tests/integration/io/benchmarks/test_benchmark_glob.py
  tests/integration/io/test_list_files_s3_minio.py
Labels: performance

#1461 [PERF] Local filesystem parquet reader
  Cargo.lock
  Cargo.toml
  src/daft-io/Cargo.toml
  src/daft-io/src/lib.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  tests/assets/parquet-data/mvp.parquet
  tests/integration/io/parquet/test_reads_public_data.py
  tests/table/table_io/test_parquet.py
Labels: performance

#1473 [BUG] Don't remove all handles and Only use handler for files in `src/`
  daft/logging.py
Labels: bug

#1474 [BUG] fix circ import with pythonpath is set
  daft/logging.py
Labels: bug

#1471 [Hotfix] Change to streaming reader for CSV schema inference.
  daft/table/schema_inference.py
Labels: performance

#1472 [BUG] Fixes globbing on windows by consolidating on posix-style paths
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/object_store_glob.rs
  src/daft-io/src/s3_like.rs
  tests/io/test_list_files_local.py
Labels: bug

#1479 [FEAT] Streaming CSV reads
  daft/table/table.py
  daft/table/table_io.py
Labels: enhancement

#1481 [CHORE] Create SECURITY.md
  SECURITY.md
Labels: chore

#1480 [PERF] Update number of cores on every iteration
  daft/runners/ray_runner.py
Labels: performance

#1482 [CHORE] Add tests and fixes for Azure globbing
  tests/integration/io/test_list_files_azure.py
Labels: bug, chore

#1484 [PERF] Pass-through multithreaded_io flag in read_parquet
  daft/daft.pyi
  daft/execution/execution_step.py
  daft/io/_parquet.py
  daft/table/table_io.py
  src/common/io-config/src/python.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/s3_like.rs
  src/daft-plan/src/source_info/file_format.rs
Labels: performance

#1485 [PERF] Update default max_connections 64->8 because it is now per-io-thread
  daft/io/_parquet.py
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/s3_like.rs
Labels: performance

#1487 [CHORE] Update default num_tries on S3Config to 25
  src/common/io-config/src/s3.rs
Labels: chore

#1490 [PERF] Use region from system and leverage cached credentials when making new clients
  src/daft-io/src/lib.rs
  src/daft-io/src/s3_like.rs
Labels: performance

#1491 [CHORE] Add Workflow to build artifacts and upload to S3
  .github/workflows/build-artifact-s3.yml
  .github/workflows/python-package.yml
Labels: chore

#1492 [BUG] fix script to upload file 1 at a time
  .github/workflows/build-artifact-s3.yml
Labels: bug

#1488 [PERF] Use pyarrow table for pickling rather than ChunkedArray
  daft/series.py
Labels: performance

#1494 [BUG] Fix local globbing of current directory
  src/daft-io/src/local.rs
  tests/io/test_list_files_local.py
Labels: bug

#1493 [FEAT] IOStats for Native Reader
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/python.rs
  src/daft-csv/src/read.rs
  src/daft-dsl/src/functions/uri/download.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/object_store_glob.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-io/src/stats.rs
  src/daft-io/src/stream_utils.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/read_planner.rs
Labels: enhancement

#1489 [CHORE] Refactor logging
  benchmarking/tpch/__main__.py
  benchmarking/tpch/data_generation.py
  benchmarking/tpch/pipelined_data_generation.py
  daft/__init__.py
  daft/context.py
  daft/dataframe/to_torch.py
  daft/execution/physical_plan.py
  daft/filesystem.py
  daft/internal/rule_runner.py
  daft/internal/treenode.py
  daft/logging.py
  daft/logical/optimizer.py
  daft/runners/profiler.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/table/table.py
  daft/udf_library/url_udfs.py
  pyproject.toml
  src/daft-table/src/lib.rs
Labels: chore

#1495 [BUG] Fix handling of special characters in S3LikeSource
  src/daft-io/src/s3_like.rs
Labels: bug

#1470 [PERF] Micropartition, lazy loading and Column Stats
  Cargo.lock
  Cargo.toml
  src/daft-core/src/array/ops/repr.rs
  src/daft-dsl/src/lib.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/column_stats/arithmetic.rs
  src/daft-micropartition/src/column_stats/comparison.rs
  src/daft-micropartition/src/column_stats/from_parquet.rs
  src/daft-micropartition/src/column_stats/logical.rs
  src/daft-micropartition/src/column_stats/mod.rs
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/table_stats/mod.rs
  src/daft-micropartition/src/utils/deserialize.rs
  src/daft-micropartition/src/utils/mod.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/read.rs
Labels: performance

#1499 [CHORE] Better logging for physical plan
  daft/execution/execution_step.py
  daft/logging.py
  daft/runners/pyrunner.py
Labels: chore

#1498 [PERF] Add "eager mode" to limits and use in .show()
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/physical_plan.py
  daft/execution/physical_plan_factory.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/optimizer.py
  daft/logical/rust_logical_plan.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/limit.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/physical_ops/limit.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
Labels: performance

#1501 [FEAT] Add streaming + parallel CSV reader, with decompression support.
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/execution/execution_step.py
  daft/io/_csv.py
  daft/runners/partitioning.py
  daft/table/table.py
  daft/table/table_io.py
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/pseudo_arrow/mod.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/array_impl/mod.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/series_like.rs
  src/daft-csv/Cargo.toml
  src/daft-csv/src/compression.rs
  src/daft-csv/src/lib.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/python.rs
  src/daft-csv/src/read.rs
  src/daft-csv/test/iris_tiny.csv
  src/daft-csv/test/iris_tiny.csv.br
  src/daft-csv/test/iris_tiny.csv.bz2
  src/daft-csv/test/iris_tiny.csv.deflate
  src/daft-csv/test/iris_tiny.csv.gz
  src/daft-csv/test/iris_tiny.csv.lzma
  src/daft-csv/test/iris_tiny.csv.xz
  src/daft-csv/test/iris_tiny.csv.zl
  src/daft-csv/test/iris_tiny.csv.zst
  src/daft-csv/test/iris_tiny_bar_delimiter.csv
  src/daft-csv/test/iris_tiny_conflicting_dtypes.csv
  src/daft-csv/test/iris_tiny_empty_lines.csv
  src/daft-csv/test/iris_tiny_invalid_header_cols_mismatch.csv
  src/daft-csv/test/iris_tiny_invalid_no_header_variable_num_cols.csv
  src/daft-csv/test/iris_tiny_no_headers.csv
  src/daft-csv/test/iris_tiny_nulls.csv
  src/daft-io/Cargo.toml
  src/daft-plan/src/source_info/file_format.rs
  src/daft-table/src/lib.rs
Labels: enhancement

#1505 [FEAT] Enable pickling for MicroPartitions
  Cargo.lock
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-micropartition/src/table_metadata.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  tests/table/test_micropartition.py
Labels: documentation, enhancement

#1521 [CHORE] Skip IO integration tests if being run from dependabot
  .github/workflows/python-package.yml
Labels: chore

#1519 [FEAT] implement series serde
  daft/daft.pyi
  daft/series.py
  src/daft-core/src/array/boolean.rs
  src/daft-core/src/array/from.rs
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/serdes.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/serdes.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  tests/series/test_series.py
Labels: enhancement

#1513 [FEAT] Scan Operator Trait
  Cargo.lock
  Cargo.toml
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/agg.rs
  src/daft-micropartition/src/ops/concat.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/ops/partition.rs
  src/daft-micropartition/src/ops/slice.rs
  src/daft-micropartition/src/ops/take.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/lib.rs
  src/daft-scan/src/table_metadata.rs
Labels: enhancement

#1523 [BUG] [CSV Reader] Fix CSV parsing bugs around nulls and timestamps.
  Cargo.lock
  Cargo.toml
  src/daft-core/Cargo.toml
  src/daft-csv/Cargo.toml
  src/daft-csv/src/deserialize.rs
  src/daft-csv/src/inference.rs
  src/daft-csv/src/lib.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  src/daft-csv/test/iris_tiny_all_null_column.csv
Labels: bug

#1522 [BUG] Re-raise exceptions in rayrunner
  daft/runners/ray_runner.py
Labels: bug

#1527 [CHORE] bring up fixtures for iceberg
  .github/workflows/nightlies-tests.yml
  .github/workflows/python-package.yml
  tests/integration/iceberg/__init__.py
  tests/integration/iceberg/docker-compose/Dockerfile
  tests/integration/iceberg/docker-compose/check-license
  tests/integration/iceberg/docker-compose/docker-compose-azurite.yml
  tests/integration/iceberg/docker-compose/docker-compose-gcs-server.yml
  tests/integration/iceberg/docker-compose/docker-compose.yml
  tests/integration/iceberg/docker-compose/entrypoint.sh
  tests/integration/iceberg/docker-compose/provision.py
  tests/integration/iceberg/docker-compose/run-azurite.sh
  tests/integration/iceberg/docker-compose/run-gcs-server.sh
  tests/integration/iceberg/docker-compose/run-minio.sh
  tests/integration/iceberg/docker-compose/spark-defaults.conf
  tests/integration/io/docker-compose/Dockerfile.nginx
  tests/integration/io/docker-compose/Dockerfile.s3_retry_server
  tests/integration/io/docker-compose/docker-compose.yml
  tests/integration/io/docker-compose/nginx-serve-static-files.conf
  tests/integration/io/docker-compose/retry_server/__init__.py
  tests/integration/io/docker-compose/retry_server/main.py
  tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
  tests/integration/io/docker-compose/retry_server/routers/__init__.py
  tests/integration/io/docker-compose/retry_server/routers/get_retries_parquet_bucket.py
  tests/integration/io/docker-compose/retry_server/routers/head_retries_parquet_bucket.py
  tests/integration/io/docker-compose/retry_server/routers/rate_limited_echo_gets_bucket.py
  tests/integration/io/docker-compose/retry_server/utils/__init__.py
  tests/integration/io/docker-compose/retry_server/utils/parquet_generation.py
  tests/integration/io/docker-compose/retry_server/utils/responses.py
Labels: chore

#1526 [FEAT] Anonymous Scan Operator
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/lib.rs
Labels: enhancement

#1530 [BUG] Fix timestamp timezone parsing bug in CSVs
  src/daft-csv/src/deserialize.rs
  tests/dataframe/test_temporals.py
Labels: bug

#1467 [CHORE] Soft deprecation of fsspec from user-facing APIs
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/filesystem.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  daft/io/file_path.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner_io.py
  daft/udf_library/url_udfs.py
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/matching.rs
  tests/cookbook/test_dataloading.py
  tests/dataframe/test_creation.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_url_download_public_aws_s3.py
  tests/integration/io/test_url_download_s3_minio.py
  tests/udf_library/test_url_udfs.py
Labels: chore

#1532 [CHORE] Allow release-drafter to increment minor version
  .github/release-drafter.yml
Labels: chore

#1533 [CHORE] Move code from daft-csv to daft-decoding
  Cargo.lock
  src/daft-csv/Cargo.toml
  src/daft-csv/src/lib.rs
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  src/daft-csv/src/schema.rs
  src/daft-decoding/Cargo.toml
  src/daft-decoding/src/deserialize.rs
  src/daft-decoding/src/inference.rs
  src/daft-decoding/src/lib.rs
Labels: chore

#1537 [CHORE] changes to partition field and field creation
  daft/daft.pyi
  daft/logical/schema.py
  src/daft-core/src/python/field.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/lib.rs
Labels: chore

#1538 [CHORE] [New Query Planner] [1/N] Remove Python query planner.
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/physical_plan_factory.py
  daft/io/common.py
  daft/io/file_path.py
  daft/logical/aggregation_plan_builder.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/optimizer.py
  daft/logical/rust_logical_plan.py
  daft/plan_scheduler/__init__.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/planner/__init__.py
  daft/planner/planner.py
  daft/planner/py_planner.py
  daft/runners/ray_runner.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/optimizer/__init__.py
  tests/optimizer/conftest.py
  tests/optimizer/test_drop_projections.py
  tests/optimizer/test_drop_repartition.py
  tests/optimizer/test_fold_projections.py
  tests/optimizer/test_prune_columns.py
  tests/optimizer/test_pushdown_clauses_into_scan.py
  tests/optimizer/test_pushdown_limit.py
  tests/optimizer/test_pushdown_predicates.py
Labels: chore

#1539 [BUG] Fix credentials issues in colab/CI
  daft/daft.pyi
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  src/daft-plan/src/source_info/storage_config.rs
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
  tutorials/image_querying/top_n_red_color.ipynb
  tutorials/text_to_image/using_cloud_with_ray.ipynb
Labels: bug, documentation

#1540 [FEAT] [New Query Planner] [2/N] Push partition spec into physical plan, remove Coalesce logical op.
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/io/file_path.py
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/partitioning.py
  src/daft-csv/Cargo.toml
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/coalesce.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_ops/repartition.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/in_memory.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/source_info/mod.rs
Labels: enhancement

#1550 [FEAT] GlobScanOperator
  Cargo.lock
  daft/daft.pyi
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/object_store_glob.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  tests/integration/io/test_list_files_s3_minio.py
Labels: enhancement

#1554 [CHORE] Revert "Bump pandas from 2.0.3 to 2.1.2"
  requirements-dev.txt
Labels: chore

#1555 [BUG] Fix reads of empty parquet files
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/stream_reader.rs
  tests/table/table_io/test_parquet.py
Labels: bug

#1556 [CHORE] Fix bad merge conflict in GlobScanOperator wrt CSV schema inference
  src/daft-scan/src/glob.rs
Labels: chore
