Repository Eventual-Inc/Daft, pull requests merged in 2023-07, with the labels that each got.

#1115 [CHORE] Pin Pydantic to < 2
  requirements-dev.txt
Labels: chore

#1113 [FEAT] Ranged Get Native Downloader
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1125 [BUG] Ownership of Runtime and Clients
  .pre-commit-config.yaml
  Cargo.lock
  src/daft-core/src/series/series_like.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  tests/udf_library/test_url_udfs.py
Labels: bug

#1127 [CHORE] Use workspace for cargo check
  .pre-commit-config.yaml
  src/daft-io/src/http.rs
Labels: chore

#1128 [BUG] Fix ownership model of IOClient
  src/daft-io/src/lib.rs
  src/daft-io/src/s3_like.rs
Labels: bug

#1130 [CHORE] No-op test for various parquet files
  tests/integration/parquet/__init__.py
  tests/integration/parquet/test_remote_reads.py
Labels: chore

#1141 [CHORE] Update README.rst typo
  README.rst
Labels: documentation, chore

#1107 [FEAT] Native Parquet Downloader
  Cargo.lock
  Cargo.toml
  daft/table/table.py
  src/daft-core/Cargo.toml
  src/daft-core/src/schema.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/lib.rs
Labels: enhancement

#1150 [DOCS] Add Flyte example
  tutorials/flyte/.dockerignore
  tutorials/flyte/Dockerfile
  tutorials/flyte/README.md
  tutorials/flyte/app.py
  tutorials/flyte/notebook.ipynb
Labels: documentation

#1152 [CHORE] Cleans up IO integration test fixtures for re-use
  tests/integration/io/conftest.py
  tests/integration/io/test_url_download_s3_minio.py
Labels: chore

#1151 [CHORE] Add parquet benchmarking
  benchmarking/parquet/README.md
  benchmarking/parquet/__init__.py
  benchmarking/parquet/conftest.py
  benchmarking/parquet/test_num_rowgroups.py
Labels: chore

#1154 [CHORE] Native Parquet Integration Tests
  daft/table/table.py
  src/daft-parquet/src/read.rs
  tests/integration/parquet/test_remote_reads.py
Labels: chore

#1156 [CHORE] [CI] use smarter github rust cache action
  .github/workflows/daft-profiling.yml
  .github/workflows/property-based-tests.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  .github/workflows/ray-compatibility.yml
Labels: chore

#1157 [CHORE] move parquet unit tests under io
  tests/integration/io/parquet/__init__.py
  tests/integration/io/parquet/test_remote_reads.py
Labels: chore

#1158 [CHORE] cache all crates
  .github/workflows/daft-profiling.yml
  .github/workflows/property-based-tests.yml
  .github/workflows/python-package.yml
  .github/workflows/ray-compatibility.yml
Labels: chore

#1073 [FEAT] [Tensor] Add support for `Tensor` and `FixedShapeTensor` types.
  Cargo.lock
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/runners/partitioning.py
  daft/runners/ray_runner.py
  daft/series.py
  daft/table/table.py
  daft/udf.py
  daft/utils.py
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/ops/tensor.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/ffi.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  tests/dataframe/test_creation.py
  tests/dataframe/test_logical_type.py
  tests/expressions/test_udf.py
  tests/ray/test_datasets.py
  tests/series/test_cast.py
  tests/series/test_concat.py
  tests/series/test_filter.py
  tests/series/test_if_else.py
  tests/series/test_size_bytes.py
  tests/series/test_take.py
  tests/series/test_tensor.py
  tests/table/test_from_py.py
Labels: enhancement

#1161 [CHORE] Enable Parquet Integration tests for decimal types
  tests/integration/io/parquet/test_remote_reads.py
Labels: chore

#1170 [DOCS] Add docs for tensor dtype
  docs/source/api_docs/datatype.rst
  docs/source/learn/user_guides/datatypes.rst
Labels: documentation

#1172 [PERF] Simple Read Planner and RangeReader for Native Parquet Reader
  daft/table/table.py
  src/daft-io/src/s3_like.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/read_planner.rs
Labels: performance

#1160 [CHORE] More Parquet benchmarking
  benchmarking/parquet/README.md
  benchmarking/parquet/benchmark-requirements.txt
  benchmarking/parquet/conftest.py
  benchmarking/parquet/test_num_rowgroups.py
Labels: chore

#1175 [FEAT] Add .image.crop Expression
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/image.rs
  src/daft-dsl/src/functions/image/crop.rs
  src/daft-dsl/src/functions/image/mod.rs
  src/daft-dsl/src/python.rs
  tests/table/image/__init__.py
  tests/table/image/test_crop.py
Labels: enhancement

#1184 [CHORE] Exclude JSON pre-commit fixer for ipynb files
  .pre-commit-config.yaml
Labels: chore

#1180 [FEAT] Consolidate to list namespace
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/functions/list/lengths.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-table/src/ops/explode.rs
  tests/series/test_cast.py
  tests/table/list/test_list_lengths.py
Labels: documentation, enhancement

#1186 [DOCS] Fix broken link to Ray Datasets docs
  docs/source/dataframe_comparison.rst
Labels: documentation

#1187 [CHORE] Bump cargo version to 0.1.9
  Cargo.lock
  Cargo.toml
Labels: chore

#1191 [FEAT] parquet reader refactor, add parquet_stats_reader and parquet_schema_reader (1/2)
  daft/logical/schema.py
  daft/table/table.py
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/read_planner.rs
Labels: enhancement

#1193 [PERF] native streaming parquet
  Cargo.lock
  Cargo.toml
  src/daft-io/Cargo.toml
  src/daft-io/src/lib.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/read_planner.rs
Labels: performance

#1201 [CHORE] Update versions to 0.1.10
  Cargo.lock
  Cargo.toml
Labels: chore

#1203 [BUG] Set SSL paths on linux
  daft/io/__init__.py
Labels: bug
