Repository Eventual-Inc/Daft, pull requests merged in 2023-08, with the labels that each got.

#1206 [CHORE] Add s3 fixtures for retrying logic
  .github/workflows/python-package.yml
  tests/integration/docker-compose/Dockerfile.s3_retry_server
  tests/integration/docker-compose/docker-compose.yml
  tests/integration/docker-compose/retry_server/__init__.py
  tests/integration/docker-compose/retry_server/main.py
  tests/integration/docker-compose/retry_server/retry-server-requirements.txt
  tests/integration/docker-compose/retry_server/routers/__init__.py
  tests/integration/docker-compose/retry_server/routers/get_retries_bucket.py
  tests/integration/docker-compose/retry_server/routers/head_retries_bucket.py
  tests/integration/docker-compose/retry_server/utils/__init__.py
  tests/integration/docker-compose/retry_server/utils/parquet_generation.py
  tests/integration/docker-compose/retry_server/utils/responses.py
  tests/integration/io/conftest.py
  tests/integration/io/parquet/test_reads_local_fixtures.py
  tests/integration/io/parquet/test_reads_public_data.py
Labels: chore

#1209 [BUG] add explict target for aarch64 linux
  .github/workflows/python-publish.yml
Labels: bug

#1211 [CHORE] Add pytest marker for integration
  tests/conftest.py
Labels: chore

#1214 [BUG] try manylinux 2 28
  .github/workflows/python-publish.yml
Labels: bug

#1220 [CHORE] Add endpoints to simulate rate-limiting on AWS S3 buckets
  tests/integration/docker-compose/retry_server/main.py
  tests/integration/docker-compose/retry_server/retry-server-requirements.txt
  tests/integration/docker-compose/retry_server/routers/get_retries_parquet_bucket.py
  tests/integration/docker-compose/retry_server/routers/head_retries_parquet_bucket.py
  tests/integration/docker-compose/retry_server/routers/rate_limited_echo_gets_bucket.py
  tests/integration/docker-compose/retry_server/utils/responses.py
  tests/integration/io/parquet/test_reads_local_fixtures.py
  tests/integration/io/test_url_download_s3_local_retry_server.py
Labels: chore

#1219 [CHORE] integration tests for nightly platform wheels
  .github/workflows/nightlies-tests.yml
  tests/integration/docker-compose/Dockerfile.nginx
  tests/integration/docker-compose/Dockerfile.s3_retry_server
Labels: chore

#1223 [CHORE] disable mac test for lack of docker
  .github/workflows/nightlies-tests.yml
Labels: chore

#1224 [FEAT] add session token as input to io config
  src/daft-io/src/config.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/conftest.py
  tests/integration/io/test_url_download_private_aws_s3.py
  tests/integration/io/test_url_download_public_aws_s3.py
Labels: enhancement

#1225 [FEAT] native parquet correctness checks
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/read.rs
Labels: enhancement

#1226 [BUG] correct type when printing incorrect row count
  src/daft-parquet/src/read.rs
Labels: bug

#1227 [DOCS][CHORE] Add docs for IOConfig and S3Config
  daft/io/config.py
  docs/source/api_docs/input_output.rst
  src/daft-dsl/src/python.rs
  src/daft-io/src/python.rs
  src/daft-parquet/src/python.rs
Labels: documentation, chore

#1228 [DOCS] Fix daft.read_parquet link
  daft/io/__init__.py
  daft/io/_parquet.py
  daft/table/table.py
  src/daft-parquet/src/python.rs
Labels: documentation

#1229 [CHORE] Add unit tests for int96 timestamps
  tests/table/table_io/test_parquet.py
  tests/table/table_io/test_read_time_cast.py
Labels: chore

#1233 [PERF] Native Parquet Bulk Reader
  benchmarking/parquet/conftest.py
  benchmarking/parquet/test_bulk_reads.py
  daft/table/table.py
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: performance

#1245 [CHORE] [New Query Planner] Introduce `LogicalPlanBuilder` and `QueryPlanner` interfaces to hide query planner implementations.
  daft/context.py
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  daft/io/file_path.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/rust_logical_plan.py
  daft/planner/__init__.py
  daft/planner/planner.py
  daft/planner/py_planner.py
  daft/planner/rust_planner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  tests/dataframe/test_accessors.py
  tests/optimizer/test_drop_projections.py
  tests/optimizer/test_drop_repartition.py
  tests/optimizer/test_fold_projections.py
  tests/optimizer/test_prune_columns.py
  tests/optimizer/test_pushdown_clauses_into_scan.py
  tests/optimizer/test_pushdown_limit.py
  tests/optimizer/test_pushdown_predicates.py
Labels: chore

#1244 [FEAT] Native Downloader add Retry Config parameters
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/config.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/conftest.py
  tests/integration/io/test_url_download_s3_local_retry_server.py
Labels: enhancement

#1247 [BUG] Fix decimal byte arrays
  Cargo.lock
  Cargo.toml
  tests/integration/io/parquet/test_reads_public_data.py
Labels: bug

#1250 [FEAT] Add Azure Support for Native Downloader
  .github/workflows/python-package.yml
  Cargo.lock
  daft/io/__init__.py
  daft/io/config.py
  pyproject.toml
  requirements-dev.txt
  src/common/error/src/error.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/config.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/metadata.rs
  tests/integration/io/conftest.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_url_download_http.py
  tests/integration/io/test_url_download_public_aws_s3.py
  tests/integration/io/test_url_download_public_azure.py
Labels: enhancement

#1251 [BUG] drop native-tls (openssl) for azure which was a default feature
  Cargo.lock
  src/daft-io/Cargo.toml
Labels: bug

#1248 [FEAT] [New Query Planner] Add support for Sort, Repartition, and Distinct in new query planner.
  daft/execution/physical_plan.py
  daft/execution/physical_plan_factory.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/distinct.rs
  src/daft-plan/src/ops/mod.rs
  src/daft-plan/src/ops/repartition.rs
  src/daft-plan/src/ops/sort.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_ops/fanout.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/reduce.rs
  src/daft-plan/src/physical_ops/sort.rs
  src/daft-plan/src/physical_ops/split.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  tests/cookbook/test_sorting.py
  tests/dataframe/test_distinct.py
  tests/dataframe/test_sort.py
Labels: enhancement

#1253 [CHORE] Update test to only use store_schema kwarg for pa>=11
  tests/table/table_io/test_parquet.py
Labels: chore

#1252 [FEAT] [New Query Planner] Add support for tabular writes.
  daft/execution/rust_physical_plan_shim.py
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/mod.rs
  src/daft-plan/src/ops/sink.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/sink_info.rs
  tests/cookbook/test_write.py
Labels: enhancement

#1254 [FEAT] [New Query Planner] Add support for Concat.
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/concat.rs
  src/daft-plan/src/ops/mod.rs
  src/daft-plan/src/physical_ops/concat.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  tests/dataframe/test_concat.py
Labels: enhancement

#1256 [FEAT] [New Query Plan] Add support for Projection and Coalesce, enable many tests
  daft/execution/rust_physical_plan_shim.py
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/coalesce.rs
  src/daft-plan/src/ops/mod.rs
  src/daft-plan/src/ops/project.rs
  src/daft-plan/src/physical_ops/flatten.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  tests/cookbook/test_distinct.py
  tests/cookbook/test_filter.py
  tests/cookbook/test_write.py
  tests/dataframe/test_accessors.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_decimals.py
  tests/dataframe/test_distinct.py
  tests/dataframe/test_filter.py
  tests/dataframe/test_getitem.py
  tests/dataframe/test_iter.py
  tests/dataframe/test_logical_type.py
  tests/dataframe/test_repartition.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_select.py
  tests/dataframe/test_show.py
  tests/dataframe/test_sort.py
  tests/dataframe/test_temporals.py
  tests/dataframe/test_to_integrations.py
  tests/dataframe/test_with_column.py
Labels: enhancement

#1258 [FEAT] [New Query Planner] Add support for Explode.
  daft/execution/rust_physical_plan_shim.py
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/explode.rs
  src/daft-plan/src/ops/mod.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  tests/dataframe/test_explode.py
Labels: enhancement

#1262 [FEAT] Add Schema.from_pyarrow
  daft/logical/schema.py
  tests/test_schema.py
Labels: enhancement

#1265 [FEAT] [New Query Planner] Support for Ray runner in new query planner.
  daft/__init__.py
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/optimizer.py
  daft/logical/rust_logical_plan.py
  daft/planner/__init__.py
  daft/planner/planner.py
  daft/planner/py_planner.py
  daft/planner/rust_planner.py
  daft/resource_request.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  docs/source/learn/user_guides/udf.rst
  src/daft-core/src/schema.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/project.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_ops/agg.rs
  src/daft-plan/src/physical_ops/coalesce.rs
  src/daft-plan/src/physical_ops/concat.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/fanout.rs
  src/daft-plan/src/physical_ops/filter.rs
  src/daft-plan/src/physical_ops/flatten.rs
  src/daft-plan/src/physical_ops/in_memory.rs
  src/daft-plan/src/physical_ops/join.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/limit.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_ops/reduce.rs
  src/daft-plan/src/physical_ops/sort.rs
  src/daft-plan/src/physical_ops/split.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/resource_request.rs
  src/daft-plan/src/sink_info.rs
  src/daft-plan/src/source_info.rs
  tests/conftest.py
  tests/optimizer/test_fold_projections.py
  tests/test_resource_requests.py
  tests_legacy/__init__.py
  tutorials/text_to_image/text_to_image_generation.ipynb
Labels: documentation, enhancement

#1272 [FEAT] [New Query Planner] Groupby support, aggregation fixes, support for remaining aggregation ops
  daft/execution/rust_physical_plan_shim.py
  daft/logical/rust_logical_plan.py
  src/daft-core/src/datatypes/field.rs
  src/daft-dsl/src/expr.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/ops/agg.rs
  src/daft-plan/src/physical_ops/agg.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  tests/cookbook/test_aggregations.py
  tests/dataframe/test_aggregations.py
Labels: enhancement

#1271 [FEAT] native google cloud reader
  Cargo.lock
  daft/io/__init__.py
  pyproject.toml
  requirements-dev.txt
  src/daft-io/Cargo.toml
  src/daft-io/src/config.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/parquet/test_reads_local_fixtures.py
  tests/integration/io/parquet/test_reads_public_data.py
Labels: enhancement

#1273 [FEAT] [New Query Planner] Add support for `df.count_rows().
  daft/expressions/expressions.py
  daft/logical/rust_logical_plan.py
  daft/series.py
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/mean.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/count_mode.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/planner.rs
  src/daft-table/src/lib.rs
  src/lib.rs
  tests/cookbook/test_count_rows.py
Labels: enhancement

#1255 [CHORE] Bump rust nightly channel date
  rust-toolchain.toml
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/array/pseudo_arrow/python.rs
  src/daft-core/src/kernels/utf8.rs
  src/daft-io/src/s3_like.rs
  src/daft-parquet/src/file.rs
Labels: chore

#1274 [FEAT] [New Query Planner] All functional tests pass + add to CI.
  .github/workflows/python-package.yml
  daft/context.py
  daft/logical/rust_logical_plan.py
  tests/conftest.py
  tests/cookbook/test_aggregations.py
  tests/cookbook/test_count_rows.py
  tests/cookbook/test_distinct.py
  tests/cookbook/test_filter.py
  tests/cookbook/test_joins.py
  tests/cookbook/test_sorting.py
  tests/cookbook/test_write.py
  tests/dataframe/test_accessors.py
  tests/dataframe/test_aggregations.py
  tests/dataframe/test_concat.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_decimals.py
  tests/dataframe/test_distinct.py
  tests/dataframe/test_explode.py
  tests/dataframe/test_filter.py
  tests/dataframe/test_getitem.py
  tests/dataframe/test_iter.py
  tests/dataframe/test_joins.py
  tests/dataframe/test_logical_type.py
  tests/dataframe/test_repartition.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_select.py
  tests/dataframe/test_show.py
  tests/dataframe/test_sort.py
  tests/dataframe/test_temporals.py
  tests/dataframe/test_to_integrations.py
  tests/dataframe/test_with_column.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_url_download_public_aws_s3.py
  tests/integration/io/test_url_download_s3_minio.py
  tests/optimizer/conftest.py
  tests/test_resource_requests.py
Labels: enhancement

#1275 [BUG] Use manylinux_2_24 for aarch64 linux to be able to publish manylinux2014
  .github/workflows/python-publish.yml
  pyproject.toml
Labels: bug

#1279 [CHORE] reduce severity of region reroute logs to debug
  src/daft-io/src/s3_like.rs
Labels: chore

#1283 [FEAT] Add Flag to_arrow to convert large string arrays
  daft/table/table.py
Labels: enhancement

#1284 [FEAT] [New Query Planner] Add optimization framework and `PushDownFilter` rule.
  daft/logical/rust_logical_plan.py
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/float/mod.rs
  src/daft-dsl/src/functions/image/mod.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/partial_udf.rs
  src/daft-dsl/src/functions/temporal/mod.rs
  src/daft-dsl/src/functions/uri/mod.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/pyobject.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/agg.rs
  src/daft-plan/src/ops/join.rs
  src/daft-plan/src/ops/repartition.rs
  src/daft-plan/src/ops/sink.rs
  src/daft-plan/src/ops/sort.rs
  src/daft-plan/src/ops/source.rs
  src/daft-plan/src/optimization/mod.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/mod.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/rule.rs
  src/daft-plan/src/optimization/rules/utils.rs
Labels: enhancement

#1289 [CHORE] Refactor Series downcast and LogicalArrayImpl
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/arange.rs
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-core/src/series/ops/broadcast.rs
  src/daft-core/src/series/ops/concat.rs
  src/daft-core/src/series/ops/date.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/float.rs
  src/daft-core/src/series/ops/groups.rs
  src/daft-core/src/series/ops/hash.rs
  src/daft-core/src/series/ops/image.rs
  src/daft-core/src/series/ops/not.rs
  src/daft-core/src/series/ops/search_sorted.rs
  src/daft-core/src/series/ops/sort.rs
  src/daft-dsl/src/lit.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/groups.rs
  src/daft-table/src/ops/joins/hash_join.rs
Labels: chore

#1287 [CHORE] Implement growables for array types
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/python_growable.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-dsl/src/functions/float/is_nan.rs
  tests/benchmarks/test_if_else.py
Labels: chore

#1298 [FEAT] add flag to use multithreaded io for parquet_read_table
  daft/table/table.py
  src/daft-io/src/lib.rs
  src/daft-parquet/src/python.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: enhancement

#1292 [FEAT] [New Query Planner] Add logical plan hashing, rule batches, fixed-point policies, early optimizer termination, and optimization cycle detection.
  Cargo.lock
  daft/expressions/expressions.py
  daft/runners/partitioning.py
  daft/udf.py
  src/daft-core/Cargo.toml
  src/daft-core/src/schema.rs
  src/daft-core/src/utils/hashable_float_wrapper.rs
  src/daft-core/src/utils/mod.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/python/partial_udf.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/pyobject.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/agg.rs
  src/daft-plan/src/ops/coalesce.rs
  src/daft-plan/src/ops/concat.rs
  src/daft-plan/src/ops/distinct.rs
  src/daft-plan/src/ops/explode.rs
  src/daft-plan/src/ops/filter.rs
  src/daft-plan/src/ops/join.rs
  src/daft-plan/src/ops/limit.rs
  src/daft-plan/src/ops/project.rs
  src/daft-plan/src/ops/repartition.rs
  src/daft-plan/src/ops/sink.rs
  src/daft-plan/src/ops/sort.rs
  src/daft-plan/src/ops/source.rs
  src/daft-plan/src/optimization/logical_plan_tracker.rs
  src/daft-plan/src/optimization/mod.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/mod.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/rule.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/resource_request.rs
  src/daft-plan/src/sink_info.rs
  src/daft-plan/src/source_info.rs
  src/daft-plan/src/test/mod.rs
Labels: enhancement

#1297 [CHORE] Refactor growables to return a Series instead of concrete arrays
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/python_growable.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/datatypes/matching.rs
Labels: chore

#1301 [CHORE] Code reduction in growable macros + logical if/else refactor
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/series/array_impl/logical_array.rs
Labels: chore

#1305 [CHORE] Refactor Growable traits and downcast for lifetimes
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/ops/downcast.rs
Labels: chore

#1308 [FEAT] add row group support to daft parquet reader
  daft/table/table.py
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: enhancement

#1309 [BUG] make seperate file for new query planner
  .github/workflows/python-package.yml
Labels: bug

#1281 [CHORE] Implementations of FixedSizeListArray
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/nested_growable.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/datatypes/nested_arrays.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/mod.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/series/ops/concat.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/image.rs
  src/daft-table/src/lib.rs
  tests/series/test_slice.py
  tests/table/test_broadcasts.py
  tests/table/test_table_aggs.py
  tests/table/test_take.py
Labels: chore

#1318 [CHORE] Add fix for list schema inference tests using PyArrow 13.0.0
  tests/table/table_io/test_parquet.py
Labels: chore

#1319 [CHORE] Move FixedSizeListArray to array/fixed_size_list_array.rs
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/nested_growable.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/downcast.rs
Labels: chore

#1322 [CHORE] pin pyarrow to 12 for ray compat tests
  requirements-dev.txt
Labels: chore

#1323 [CHORE] drop flag for non native compile for daft profiling
  .github/workflows/daft-profiling.yml
Labels: chore

#1300 [FEAT] [New Query Planner] Add support for `PushDownLimit`
  src/daft-plan/src/lib.rs
  src/daft-plan/src/ops/source.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/mod.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
Labels: enhancement

#1326 [CHORE] StructArray refactors
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/nested_growable.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/ops/tensor.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/list.rs
  tests/series/test_cast.py
  tests/table/test_from_py.py
Labels: chore

#1302 [FEAT] [New Query Planner] Add support for `DropRepartition`
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/mod.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/planner.rs
Labels: enhancement

#1324 [FEAT] S3 Native List Impl for a directory
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1307 [FEAT] [New Query Planner] Refactor file globbing logic by exposing `FileInfos` to Python
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/physical_plan_factory.py
  daft/execution/rust_physical_plan_shim.py
  daft/filesystem.py
  daft/io/common.py
  daft/io/file_path.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/optimizer.py
  daft/logical/rust_logical_plan.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner_io.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/ops/source.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/source_info.rs
  src/daft-plan/src/test/mod.rs
  tests/cookbook/test_dataloading.py
  tests/cookbook/test_image.py
  tests/optimizer/test_pushdown_clauses_into_scan.py
Labels: enhancement

#1327 [CHORE] [New Query Planner] Remove `ExpressionsProjection` from builder, move validation into `Op::try_new()`
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/ops/concat.rs
  src/daft-plan/src/ops/filter.rs
  src/daft-plan/src/ops/join.rs
  src/daft-plan/src/ops/sort.rs
  src/daft-plan/src/optimization/logical_plan_tracker.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  tests/dataframe/test_joins.py
  tests/dataframe/test_sort.py
Labels: chore
