Repository Eventual-Inc/Daft, pull requests merged in 2023-01, with the labels that each got.

#414 Fix schema inferencing column ID conflicts on RayRunner
  daft/dataframe/dataframe.py
  daft/runners/partitioning.py
Labels: bug

#416 0.0.20 Documentation
  docs/source/docs/release_notes/0.0.20.rst
  docs/source/docs/release_notes/index.rst
Labels: documentation

#417 Add twine install to publishing steps
  .github/workflows/python-publish.yml
  docs/source/docs/release_notes/0.0.20.rst
Labels: bug

#424 Add DAFT_PKG_BUILD_TYPE to python-publish CI job
  .github/workflows/python-publish.yml
Labels: build

#429 Typos in telemetry docs
  docs/source/docs/telemetry.rst
Labels: documentation

#431 Refreshes our 10 minute tutorial
  daft/viz/repr.py
  docs/source/docs/learn/10-min.ipynb
Labels: documentation

#299 Sorts on non-column expression
  daft/runners/partitioning.py
  tests/dataframe_cookbook/test_sorting.py
  tests/runners/test_partitioning.py
Labels: bug

#454 Add changelog for 0.0.21
  Cargo.lock
  Cargo.toml
  docs/source/docs/release_notes/0.0.21.rst
Labels: documentation

#489 Remove walrus operators for Py 3.7 compatibility
  daft/execution/physical_plan.py
  daft/runners/dynamic_runner.py
  daft/runners/ray_runner.py
Labels: bug

#509 Refactor tutorials
  docs/source/conf.py
  docs/source/docs/learn/10-min.ipynb
  docs/source/docs/learn/index.rst
  docs/source/docs/learn/quickstart.ipynb
  docs/source/docs/learn/tutorials.rst
  docs/source/docs/learn/user_guides/udf.rst
  tutorials/image_querying/top_n_red_color.ipynb
  tutorials/mnist.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
Labels: documentation

#525 Add simple unit tests for Aggs
  daft/dataframe/dataframe.py
  tests/dataframe_cookbook/test_aggregations.py
Labels: tests
