Repository Eventual-Inc/Daft, pull requests merged in 2023-09, with the labels that each got.

#1333 [BUG] [New Query Planner] Revert file info partition column names.
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/logical/logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/source_info.rs
  tests/cookbook/test_dataloading.py
  tests/cookbook/test_image.py
Labels: bug

#1335 [CHORE] factor io config into common code
  Cargo.lock
  Cargo.toml
  src/common/io-config/Cargo.toml
  src/common/io-config/src/azure.rs
  src/common/io-config/src/config.rs
  src/common/io-config/src/gcs.rs
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/uri/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/read.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/source_info.rs
Labels: chore

#1336 [BUG] Fix Table.read_parquet behavior when it encounters arrow_schema
  Cargo.lock
  Cargo.toml
  tests/table/table_io/test_parquet.py
Labels: bug

#1344 [CHORE] Switch to openssl
  .pre-commit-config.yaml
  Cargo.lock
  daft/filesystem.py
  src/daft-io/Cargo.toml
  tools/check_for_rustls.sh
Labels: chore

#1345 [CHORE] install perl before maturin
  .github/workflows/python-publish.yml
Labels: chore

#1329 [CHORE] Add new ListArray
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/nested_growable.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/ops/tensor.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/list.rs
  tests/series/test_tensor.py
Labels: chore

#1330 [CHORE] Add a Growable factory method
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/bitmap_growable.rs
  src/daft-core/src/array/growable/fixed_size_list_growable.rs
  src/daft-core/src/array/growable/list_growable.rs
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/nested_growable.rs
  src/daft-core/src/array/growable/python_growable.rs
  src/daft-core/src/array/growable/struct_growable.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/struct_array.rs
Labels: chore

#1331 [CHORE] Add Series::full_null/empty/from_arrow to reduce code duplication
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/series/mod.rs
  src/daft-table/src/lib.rs
Labels: chore

#1349 [PERF] Optimize filter on nested growables
  src/daft-core/src/array/growable/fixed_size_list_growable.rs
  src/daft-core/src/array/growable/list_growable.rs
  src/daft-core/src/array/growable/struct_growable.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/full.rs
  tests/benchmarks/test_filter.py
Labels: performance

#1350 [PERF] Add microbenchmarks for takes
  tests/benchmarks/test_take.py
Labels: performance

#1352 [BUG] propagate parquet io error instead of panicking
  src/daft-parquet/src/read_planner.rs
Labels: bug

#1351 [CHORE] Fix List/FixedSizeList DataType to hold a dtype instead of Field
  daft/datatype.py
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/growable/fixed_size_list_growable.rs
  src/daft-core/src/array/growable/list_growable.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/field.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/image.rs
  src/daft-core/src/utils/supertype.rs
  src/daft-dsl/src/functions/image/crop.rs
  tests/dataframe/test_creation.py
  tests/dataframe/test_logical_type.py
  tests/series/test_cast.py
  tests/series/test_concat.py
  tests/series/test_embedding.py
  tests/series/test_if_else.py
  tests/table/table_io/test_json.py
  tests/table/table_io/test_parquet.py
  tests/table/test_broadcasts.py
  tests/table/test_from_py.py
  tests/table/test_table_aggs.py
  tests/test_schema.py
Labels: chore

#1355 [BUG] Schema Display should use dtype Display instead of Debug
  src/daft-core/src/schema.rs
Labels: bug

#1356 [CHORE] Add status code to IO integration tests
  tests/integration/docker-compose/retry_server/routers/get_retries_parquet_bucket.py
  tests/integration/docker-compose/retry_server/routers/head_retries_parquet_bucket.py
  tests/integration/docker-compose/retry_server/routers/rate_limited_echo_gets_bucket.py
  tests/integration/docker-compose/retry_server/utils/responses.py
  tests/integration/io/parquet/test_reads_local_fixtures.py
Labels: chore

#1354 [CHORE] [New Query Planner] Add simple `df.explain()` option; change to fixed-point policy for rule batch
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/rust_logical_plan.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/optimizer.rs
Labels: chore

#1359 [BUG] Respect `multithreaded_io` flag when reading parquet
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
Labels: bug

#1361 [PERF] enable jemalloc with background threads
  .github/workflows/python-publish.yml
  Cargo.lock
  Cargo.toml
  src/daft-parquet/src/file.rs
  src/lib.rs
Labels: performance

#1362 [FEAT] export jemalloc arm64 flag inside container
  .github/workflows/python-publish.yml
Labels: enhancement

#1360 [FEAT] Add flag to limit number of connections to S3
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1363 [FEAT] Add configurable io thread pool size
  daft/io/__init__.py
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  tests/integration/io/test_url_download_public_aws_s3.py
Labels: enhancement

#1365 [PERF] Used owned Stream in Parquet Page Iterator
  Cargo.lock
  Cargo.toml
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/read_planner.rs
Labels: performance

#1366 [FEAT] Native Parquet Reader into pyarrow directly
  benchmarking/parquet/conftest.py
  daft/table/__init__.py
  daft/table/table.py
  src/daft-core/src/ffi.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  tests/assets/parquet-data/parquet-with-schema-metadata.parquet
  tests/integration/io/parquet/test_reads_public_data.py
Labels: enhancement

#1357 [FEAT] [New Query Planner] Add support for fsspec filesystems to new query planner.
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/physical_plan_factory.py
  daft/execution/rust_physical_plan_shim.py
  daft/filesystem.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  daft/logical/builder.py
  daft/logical/logical_plan.py
  daft/logical/optimizer.py
  daft/logical/rust_logical_plan.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner_io.py
  daft/table/schema_inference.py
  daft/table/table_io.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/agg.rs
  src/daft-plan/src/logical_ops/coalesce.rs
  src/daft-plan/src/logical_ops/concat.rs
  src/daft-plan/src/logical_ops/distinct.rs
  src/daft-plan/src/logical_ops/explode.rs
  src/daft-plan/src/logical_ops/filter.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_ops/limit.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_ops/repartition.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/logical_ops/sort.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/source_info.rs
  src/daft-plan/src/source_info/file_format.rs
  src/daft-plan/src/source_info/file_info.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-plan/src/source_info/py_object_serde.rs
  src/daft-plan/src/source_info/storage_config.rs
  src/daft-plan/src/test/mod.rs
  tests/dataframe/test_creation.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_url_download_public_aws_s3.py
  tests/integration/io/test_url_download_s3_minio.py
  tests/optimizer/test_pushdown_clauses_into_scan.py
  tests/table/table_io/test_parquet.py
Labels: enhancement

#1358 [CHORE] [New Query Planner] Misc. user-facing error tweaks to improve UX.
  Cargo.lock
  daft/dataframe/dataframe.py
  daft/logging.py
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/field.rs
  src/daft-core/src/schema.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/list/explode.rs
  src/daft-dsl/src/functions/list/join.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/agg.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  tests/cookbook/test_count_rows.py
  tests/dataframe/test_explode.py
Labels: chore

#1373 [CHORE] pin azure-storage-blob due to breaking new version
  requirements-dev.txt
Labels: chore

#1378 [CHORE] add retries for broken link checker
  .github/workflows/broken-link-checker.yml
Labels: chore

#1377 [CHORE] Add stubs and improve comments for pyo3-exposed abstractions, + driveby type/bug fixes.
  daft/__init__.py
  daft/context.py
  daft/daft.pyi
  daft/datasources.py
  daft/io/common.py
  daft/logging.py
  daft/logical/schema.py
  daft/runners/ray_runner.py
  daft/runners/runner_io.py
  daft/table/table.py
  daft/udf.py
  src/daft-core/src/datatypes/image_format.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/join.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/resource_request.rs
  src/daft-plan/src/source_info/file_format.rs
  src/daft-plan/src/source_info/file_info.rs
  src/daft-plan/src/source_info/storage_config.rs
Labels: chore

#1385 [FEAT] Implement .dt.year/month/day for timestamp types
  daft/daft.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/date.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/date.rs
  src/daft-dsl/src/functions/temporal/date.rs
  src/daft-dsl/src/functions/temporal/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/conftest.py
  tests/expressions/typing/test_dt.py
  tests/series/test_temporal_ops.py
Labels: documentation, enhancement

#1353 [FEAT] Native Recursive File Lister
  Cargo.lock
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/object_io.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-plan/src/test/mod.rs
  tests/integration/io/conftest.py
  tests/integration/io/test_list_files_s3_minio.py
Labels: enhancement

#1396 [FEAT] bulk parquet pyarrow reader
  benchmarking/parquet/conftest.py
  daft/daft.pyi
  daft/table/__init__.py
  daft/table/table.py
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: enhancement

#1395 [FEAT] Native S3 Client: allow disabling ssl verification or checking hostnames
  Cargo.lock
  daft/daft.pyi
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1399 [FEAT] Parameter to set num_parallel_tasks for bulk readers
  daft/daft.pyi
  daft/table/table.py
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
Labels: enhancement

#1397 [BUG] Fix public API decorator type annotations.
  daft/api_annotations.py
Labels: bug

#1398 [FEAT] [New Query Planner] Enable new query planner by default.
  daft/context.py
Labels: enhancement

#1401 [BUG] Fixes to S3 Native Lister with correct Error propagation
  src/daft-io/src/lib.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/conftest.py
  tests/integration/io/test_list_files_s3_minio.py
Labels: bug

#1392 [FEAT] Native Rust listing of GCS
  .github/workflows/python-package.yml
  src/daft-io/src/google_cloud.rs
  tests/integration/io/test_list_files_gcs.py
Labels: enhancement

#1402 [BUG] add test cases for bulk minio reading
  tests/integration/io/conftest.py
  tests/integration/io/parquet/test_reads_s3_minio.py
Labels: bug

#1404 [FEAT] Native S3 Lister, support trailing slashes and fix panics when connection is dropped for tokio
  src/daft-io/src/lib.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/test_list_files_s3_minio.py
Labels: enhancement

#1394 [CHORE] Centralize pyo3 pickling around `__reduce__` + bincode macro.
  daft/daft.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  daft/logical/schema.py
  src/daft-core/src/count_mode.rs
  src/daft-core/src/datatypes/image_format.rs
  src/daft-core/src/datatypes/image_mode.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/field.rs
  src/daft-core/src/python/schema.rs
  src/daft-core/src/utils/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/join.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/resource_request.rs
  src/daft-plan/src/source_info/file_format.rs
  src/daft-plan/src/source_info/file_info.rs
  src/daft-plan/src/source_info/storage_config.rs
Labels: chore

#1410 [FEAT] enable path style for s3 custom endpoints by default
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1411 [BUG] force upload of anaconda nightly wheels
  ci/upload_wheels.sh
Labels: bug

#1412 [BUG] Fix gs listing to include 0 sized marker files
  src/daft-io/src/google_cloud.rs
  tests/integration/io/test_list_files_gcs.py
Labels: bug

#1415 [BUG] Anaconda client don't upload src wheels
  ci/upload_wheels.sh
Labels: bug

#1414 [FEAT] Add debug logging to s3 native apis
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1386 [FEAT] Add support for windows in daft
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  daft/filesystem.py
  requirements-dev.txt
  src/daft-io/src/lib.rs
  src/lib.rs
  tests/cookbook/test_dataloading.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_repr.py
  tests/integration/test_tpch.py
  tests/series/test_concat.py
  tests/series/test_tensor.py
  tests/table/table_io/test_parquet.py
  tests/test_schema.py
  tests/udf_library/test_url_udfs.py
Labels: enhancement

#1417 [CHORE] macos xl runners are 0.32/minute not hour...
  .github/workflows/python-publish.yml
Labels: chore

#1418 [BUG] patch workspace version when building wheels
  tools/patch_package_version.py
Labels: bug

#1419 [CHORE] add caching for pip wheels
  .github/workflows/python-package.yml
Labels: chore

#1430 [BUG] [Docs] Allow source code discovery to fail silently for pyo3-defined classes when generating docs.
  daft/__init__.py
  docs/source/api_docs/datatype_image_mode/daft.ImageMode.from_mode_string.rst
  docs/source/conf.py
Labels: bug, documentation

#1435 [BUG] Fix runner check at plan execution time for new query planner
  daft/daft.pyi
  daft/execution/rust_physical_plan_shim.py
  daft/planner/planner.py
  daft/planner/py_planner.py
  daft/planner/rust_planner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  src/daft-plan/src/physical_plan.rs
Labels: bug

#1443 [BUG] Fix scheme bug in GCS anonymous mode
  src/daft-io/src/s3_like.rs
  tests/integration/io/test_list_files_gcs.py
Labels: bug

#1442 [BUG] Fix num input partitions in coalesce.
  src/daft-plan/src/planner.rs
  tests/dataframe/test_repartition.py
Labels: bug

#1405 [FEAT] Native listing of http URLs
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/http.rs
  tests/integration/docker-compose/nginx-serve-static-files.conf
  tests/integration/io/conftest.py
  tests/integration/io/test_list_files_http.py
Labels: enhancement

#1449 [FEAT] Add local native filesystem globbing.
  Cargo.lock
  Cargo.toml
  src/common/error/src/error.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  tests/integration/io/test_list_files_local.py
Labels: enhancement

#1409 [FEAT] Add `.str.split()` API for splitting string columns.
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/split.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_split.py
Labels: enhancement
