Repository Eventual-Inc/Daft, pull requests merged in 2023-12, with the labels that each got.

#1687 [CHORE] Iceberg Image Caching
  .github/workflows/python-package.yml
Labels: chore

#1686 [CHORE] Remove usage of credentials in workflows
  .github/workflows/python-package.yml
  tests/integration/io/conftest.py
  tests/integration/io/test_list_files_gcs.py
  tests/integration/io/test_url_download_private_aws_s3.py
Labels: chore

#1684 [FEAT] Enable MicroPartitions by default
  benchmarking/parquet/conftest.py
  daft/dataframe/dataframe.py
  daft/dataframe/preview.py
  daft/execution/execution_step.py
  daft/execution/rust_physical_plan_shim.py
  daft/filesystem.py
  daft/io/common.py
  daft/io/file_path.py
  daft/logical/map_partition_ops.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  daft/table/__init__.py
  daft/table/micropartition.py
  daft/table/schema_inference.py
  daft/table/table_io.py
  tests/benchmarks/test_filter.py
  tests/benchmarks/test_if_else.py
  tests/benchmarks/test_take.py
  tests/conftest.py
  tests/dataframe/test_creation.py
  tests/expressions/test_expressions.py
  tests/expressions/test_expressions_projection.py
  tests/expressions/test_udf.py
  tests/expressions/typing/conftest.py
  tests/integration/io/parquet/test_reads_local_fixtures.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/parquet/test_reads_s3_minio.py
  tests/table/image/test_crop.py
  tests/table/list/test_list_join.py
  tests/table/list/test_list_lengths.py
  tests/table/table_io/test_csv.py
  tests/table/table_io/test_json.py
  tests/table/table_io/test_parquet.py
  tests/table/table_io/test_read_time_cast.py
  tests/table/test_blackbox_kernels.py
  tests/table/test_broadcasts.py
  tests/table/test_concat.py
  tests/table/test_eval.py
  tests/table/test_explodes.py
  tests/table/test_filter.py
  tests/table/test_from_py.py
  tests/table/test_head.py
  tests/table/test_joins.py
  tests/table/test_partitioning.py
  tests/table/test_size_bytes.py
  tests/table/test_sorting.py
  tests/table/test_table_aggs.py
  tests/table/test_take.py
  tests/table/utf8/test_compares.py
  tests/table/utf8/test_length.py
  tests/table/utf8/test_split.py
  tests/test_schema.py
Labels: enhancement

#1682 [CHORE] drop s3 compat mode for gcs for anonymous mode
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/google_cloud.rs
Labels: chore

#1689 [FEAT] Enable Comparison between timestamp / dates
  daft/datatype.py
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/utils/supertype.rs
  src/daft-dsl/src/expr.rs
  tests/expressions/typing/conftest.py
  tests/series/test_comparisons.py
Labels: enhancement

#1690 [BUG] Allow for use of Ray jobs for benchmarking
  benchmarking/tpch/__main__.py
  benchmarking/tpch/ray_job_runner.py
Labels: bug

#1691 [CHORE] Add warmup step for remote tpch benchmarking
  benchmarking/tpch/__main__.py
Labels: chore

#1700 [FEAT] Add daft.context.set_config function for setting configurations globally
  Cargo.lock
  Cargo.toml
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  src/common/daft-config/Cargo.toml
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/planner.rs
  src/lib.rs
  tests/conftest.py
  tests/io/test_merge_scan_tasks.py
Labels: enhancement

#1692 [FEAT] Add smart planning of ScanTasks starting with merging by filesizes
  Cargo.lock
  Cargo.toml
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  src/common/daft-config/Cargo.toml
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/planner.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-stats/src/partition_spec.rs
  src/lib.rs
  tests/conftest.py
  tests/io/test_merge_scan_tasks.py
Labels: enhancement

#1703 [DOCS] Add notebooks used for pydata global 2023 presentation
  tutorials/intro.ipynb
  tutorials/talks_and_demos/pydata_global_2023.ipynb
Labels: documentation

#1709 [BUG] Fix set_config logic so it can be called after call to set runner
  daft/context.py
Labels: bug

#1706 [FEAT] [Join Optimizations] Add broadcast join.
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/io/file_path.py
  daft/logical/builder.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/physical_ops/broadcast_join.rs
  src/daft-plan/src/physical_ops/hash_join.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-table/src/ops/joins/hash_join.rs
  tests/dataframe/test_joins.py
Labels: enhancement

#1718 [BUG] [Hotfix] [Join Optimization] Fix pre-partitioned check for larger side of join.
  src/daft-plan/src/planner.rs
Labels: bug

#1710 [FEAT] Add ability to set global IOConfig
  Cargo.lock
  daft/__init__.py
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/io/_csv.py
  daft/io/_iceberg.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/logical/builder.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  docs/source/api_docs/context.rst
  src/common/daft-config/Cargo.toml
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/planner.rs
  tests/conftest.py
  tests/dataframe/test_joins.py
  tests/io/test_merge_scan_tasks.py
Labels: documentation, enhancement

#1721 [DOCS] Add anonymous io_config for notebook
  tutorials/intro.ipynb
Labels: documentation

#1723 [CHORE] update dev version to 0.2.0 dev
  Cargo.lock
  Cargo.toml
Labels: chore

#1724 [PERF] Predicate Pushdown for CSV Reader
  Cargo.lock
  daft/daft.pyi
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/datatypes/field.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/series/mod.rs
  src/daft-csv/Cargo.toml
  src/daft-csv/src/options.rs
  src/daft-csv/src/read.rs
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-scan/src/glob.rs
  src/daft-table/src/ffi.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/python.rs
  tests/assets/sampled-tpch.csv
  tests/integration/io/csv/__init__.py
  tests/integration/io/csv/test_read_pushdowns.py
  tests/integration/io/parquet/test_read_pushdowns.py
Labels: performance

#1727 [PERF] Json Predicate Pushdown while reading
  Cargo.lock
  src/daft-csv/src/read.rs
  src/daft-json/Cargo.toml
  src/daft-json/src/options.rs
  src/daft-json/src/read.rs
  src/daft-micropartition/src/micropartition.rs
  tests/assets/sampled-tpch.jsonl
  tests/integration/io/jsonl/__init__.py
  tests/integration/io/jsonl/test_read_pushdown.py
Labels: performance

#1728 [BUG] [Hotfix] Fix limit pushdown test.
  src/daft-plan/src/optimization/rules/push_down_limit.rs
Labels: bug

#1729 [FEAT] annotate ray tasks with name of instructions
  daft/execution/execution_step.py
  daft/runners/progress_bar.py
  daft/runners/ray_runner.py
Labels: enhancement

#1731 [BUG] Apply the default IOConfig in daft.from_glob_path
  daft/io/file_path.py
Labels: bug

#1732 [CHORE] Generate S3 manifests
  .github/workflows/build-artifact-s3.yml
  tools/generate_whl_html_manifest.py
Labels: chore

#1730 [PERF] Predicate Pushdown into Scan Operator
  Cargo.lock
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/test/mod.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/lib.rs
  src/daft-stats/src/table_stats.rs
Labels: performance

#1734 [CHORE] Clean up Repr for GlobScanOperator and Explain
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-scan/src/glob.rs
Labels: chore

#1735 [BUG] Fix comparing date and timestamps
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/datatypes/binary_ops.rs
  tests/series/test_cast.py
  tests/series/test_comparisons.py
Labels: bug

#1745 [BUG] bugfix when cluster has no workers and key error happens when fetching num cores
  daft/runners/ray_runner.py
Labels: bug

#1736 [DOCS] Add documentation on memory
  docs/source/learn/user_guides.rst
  docs/source/learn/user_guides/memory.rst
  docs/source/learn/user_guides/udf.rst
Labels: documentation

#1746 [CHORE] kernel override for notebook checker
  .github/workflows/notebook-checker.yml
Labels: chore

#1748 [PERF] Greatly speed up Variable Length Concat
  src/daft-core/src/array/ops/concat.rs
  tests/benchmarks/test_concat.py
Labels: performance

#1749 [PERF] Speed up CSV Reader with SIMD and reduced allocations
  Cargo.lock
  src/daft-decoding/Cargo.toml
  src/daft-decoding/src/deserialize.rs
  src/daft-decoding/src/inference.rs
Labels: performance

#1750 [BUG] Concat Fix when Variable Length Array is sliced
  src/daft-core/src/array/ops/concat.rs
  tests/series/test_concat.py
Labels: bug

#1752 [DOCS] Add proper robots.txt and sitemap.xml to index only latest and stable
  docs/source/_html/robots.txt
  docs/source/_html/sitemap-override.xml
  docs/source/conf.py
Labels: documentation

#1753 Revert "[DOCS] Add proper robots.txt and sitemap.xml to index only latest and stable"
  docs/source/_html/robots.txt
  docs/source/_html/sitemap-override.xml
  docs/source/conf.py
Labels: documentation

#1688 [PERF] Iceberg Partition Pruning
  Cargo.lock
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/iceberg/iceberg_scan.py
  daft/io/scan.py
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-dsl/src/functions/partitioning/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/rules/mod.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/utils.rs
  src/daft-plan/src/physical_ops/empty_scan.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-scan/src/expr_rewriter.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  tests/integration/iceberg/test_partition_pruning.py
  tests/integration/iceberg/test_table_load.py
  tests/series/test_partitioning.py
Labels: enhancement, performance
