Repository Eventual-Inc/Daft, pull requests merged in 2023-06, with the labels that each got.

#982 HTML escape strings that contain html in _repr_html_
  daft/viz/repr.py
Labels: bug

#983 Revert change to optimizer to perform deepcopy of logical plan
  daft/internal/rule_runner.py
  tests/udf_library/test_url_udfs.py
Labels: bug

#987 Release notes for 0.1.4
  Cargo.lock
  Cargo.toml
  docs/source/release_notes/0.1.4.rst
Labels: documentation

#988 Update release/index.rst with 0.1.4
  docs/source/release_notes/index.rst
Labels: documentation

#1000 Change header to include blog
  docs/source/_templates/sections/header.html
  docs/source/_templates/sections/mobile-menu.html
Labels: documentation

#989 Add kernels for .list.join on a list[utf8] column
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  src/array/ops/list.rs
  src/dsl/functions/list/join.rs
  src/dsl/functions/list/mod.rs
  src/python/expr.rs
  src/series/ops/list.rs
  tests/table/list/__init__.py
  tests/table/list/test_list_join.py
Labels: enhancement

#1038 Fix links to ray.io latest docs
  daft/convert.py
  daft/dataframe/dataframe.py
  docs/source/release_notes/0.0.18.rst
Labels: documentation

#1043 [CHORE] Fix footer of release-drafter
  .github/release-drafter.yml
Labels: chore

#1044 [CHORE] Fix CI TPCH data generation for old deprecated kwarg
  benchmarking/tpch/data_generation.py
Labels: chore

#1045 [CHORE] Add a GitHub action to enforce labels are added to the PR before merging
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/release-drafter.yml
Labels: chore

#1047 [CHORE] Update cargo version to v0.1.6
  Cargo.lock
  Cargo.toml
Labels: chore

#1053 [CHORE][CI] Use pyarrow Table sort API that's compatible with older pyarrow versions
  tests/ray/test_datasets.py
Labels: chore

#1054 [CHORE] Add new trigger to run PR label enforcement after Release Drafter
  .github/workflows/enforce-pr-labels.yml
Labels: chore

#1055 [CHORE] Fix naming of "Release Drafter" workflow in trigger
  .github/workflows/enforce-pr-labels.yml
Labels: chore

#1057 [CHORE] Inline the label enforcer into the release drafter wf
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/release-drafter.yml
Labels: chore

#1052 [FEAT] [Images] [8/N] Add encoding and resizing support for fixed-shape images.
  src/array/ops/cast.rs
  src/array/ops/image.rs
  src/array/ops/take.rs
  src/datatypes/dtype.rs
  src/datatypes/image_mode.rs
  src/datatypes/logical.rs
  src/dsl/expr.rs
  src/dsl/functions/float/is_nan.rs
  src/dsl/functions/image/decode.rs
  src/dsl/functions/image/encode.rs
  src/dsl/functions/image/resize.rs
  src/dsl/functions/list/explode.rs
  src/dsl/functions/list/join.rs
  src/dsl/functions/mod.rs
  src/dsl/functions/numeric/abs.rs
  src/dsl/functions/python/udf.rs
  src/dsl/functions/temporal/day.rs
  src/dsl/functions/temporal/day_of_week.rs
  src/dsl/functions/temporal/month.rs
  src/dsl/functions/temporal/year.rs
  src/dsl/functions/utf8/contains.rs
  src/dsl/functions/utf8/endswith.rs
  src/dsl/functions/utf8/length.rs
  src/dsl/functions/utf8/startswith.rs
  src/python/datatype.rs
  src/series/ops/image.rs
  tests/series/test_image.py
Labels: enhancement

#1063 [FEAT] Automatically cast logical types to Python objects on `Series.to_pylist()`.
  daft/datatype.py
  daft/series.py
  src/array/ops/cast.rs
  src/python/datatype.rs
  tests/cookbook/test_image.py
  tests/series/test_cast.py
  tests/series/test_embedding.py
  tests/series/test_image.py
Labels: enhancement

#1066 [BUG] [CI] Fix merge conflict due to out-of-date base.
  tests/series/test_image.py
Labels: bug

#1049 [DOCS] Remove release notes from documentation, link to Github instead
  docs/source/conf.py
  docs/source/index.rst
  docs/source/learn/index.rst
  docs/source/release_notes/0.0.13.rst
  docs/source/release_notes/0.0.14.rst
  docs/source/release_notes/0.0.16.rst
  docs/source/release_notes/0.0.17.rst
  docs/source/release_notes/0.0.18.rst
  docs/source/release_notes/0.0.19.rst
  docs/source/release_notes/0.0.20.rst
  docs/source/release_notes/0.0.21.rst
  docs/source/release_notes/0.0.22.rst
  docs/source/release_notes/0.0.23.rst
  docs/source/release_notes/0.0.24.rst
  docs/source/release_notes/0.1.0.rst
  docs/source/release_notes/0.1.1.rst
  docs/source/release_notes/0.1.2.rst
  docs/source/release_notes/0.1.3.rst
  docs/source/release_notes/0.1.4.rst
  docs/source/release_notes/0.1.5.rst
  docs/source/release_notes/_template.rst
  docs/source/release_notes/index.rst
Labels: documentation

#1061 [PERF] Rust based url downloading with error handling
  .github/workflows/python-package.yml
  Cargo.lock
  Cargo.toml
  codecov.yml
  daft/context.py
  daft/expressions/expressions.py
  daft/series.py
  src/array/from.rs
  src/array/ops/take.rs
  src/dsl/functions/mod.rs
  src/dsl/functions/uri/download.rs
  src/dsl/functions/uri/mod.rs
  src/error.rs
  src/io/http.rs
  src/io/local.rs
  src/io/mod.rs
  src/io/object_io.rs
  src/io/s3_like.rs
  src/lib.rs
  src/python/error.rs
  src/python/expr.rs
  src/schema.rs
  src/series/ops/mod.rs
  src/series/ops/url.rs
  src/table/ops/joins/mod.rs
  tests/udf_library/test_url_udfs.py
Labels: performance, rust

#1067 [FEAT] [Images] [9/N] Infer `Image` type for PIL images on ingress.
  src/array/ops/cast.rs
  src/datatypes/image_mode.rs
  src/python/series.rs
  tests/dataframe/test_logical_type.py
  tests/series/test_cast.py
  tests/series/test_image.py
Labels: enhancement

#1078 [BUG] Reenable HTML viz hooks for np.ndarray and PIL Images
  daft/series.py
  daft/viz/html_viz_hooks.py
  src/array/ops/repr.rs
  src/python/series.rs
  tests/dataframe/test_logical_type.py
  tests/dataframe/test_repr.py
  tests/series/test_image.py
Labels: bug

#1084 [CHORE] Fix filepath for autogeneration of .list.join docs
  docs/source/api_docs/expressions.rst
Labels: documentation, chore

#1088 [CHORE] unpin numpy version for py<3.8
  requirements-dev.txt
Labels: chore

#1087 [CHORE] Refactor integration test to use wheel built for release
  .github/workflows/python-package.yml
Labels: chore

#1085 [CHORE] set dependabot schedule to weekly
  .github/dependabot.yml
Labels: chore

#1090 [FEAT] Enable Native Downloader IO Config
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.toml
  daft/expressions/expressions.py
  daft/io/__init__.py
  daft/series.py
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/uri/download.rs
  src/daft-dsl/src/functions/uri/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/config.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/lib.rs
Labels: enhancement

#1097 [FEAT] Better styling of large dataframe cells in HTML
  src/daft-core/src/schema.rs
  src/daft-table/src/lib.rs
  tests/dataframe/test_repr.py
Labels: enhancement

#1098 [FEAT] Automatic Region Retrying for S3 Native Downloader
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1099 [CHORE] Use maturin directly instead of multiplatform build step
  .github/workflows/python-package.yml
Labels: chore

#1100 [BUG] S3 Downloader set default region when region not detected
  src/daft-io/src/s3_like.rs
Labels: bug

#1101 [CHORE] Fix CI caching to cache integration test builds separately
  .github/workflows/python-package.yml
Labels: chore

#1102 [FEAT] Enable reading a list of URLs in read_* APIs
  daft/api_annotations.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/common.py
  daft/io/file_path.py
  daft/io/parquet.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner_io.py
  tests/dataframe/test_creation.py
Labels: enhancement

#1105 [FEAT] Native S3 Downloader Anonymous Mode
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/config.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1104 [CHORE] Cache build artifacts in target folder
  .github/workflows/daft-profiling.yml
  .github/workflows/property-based-tests.yml
  .github/workflows/python-package.yml
  .github/workflows/ray-compatibility.yml
Labels: chore

#1083 [CHORE] Adding more test fixtures for different I/O sources
  .github/workflows/python-package.yml
  pyproject.toml
  requirements-dev.txt
  src/daft-io/src/python.rs
  tests/integration/docker-compose/Dockerfile.nginx
  tests/integration/docker-compose/docker-compose.yml
  tests/integration/docker-compose/nginx-serve-static-files.conf
  tests/integration/io/__init__.py
  tests/integration/io/conftest.py
  tests/integration/io/test_url_download_http.py
  tests/integration/io/test_url_download_local.py
  tests/integration/io/test_url_download_public_aws_s3.py
  tests/integration/io/test_url_download_s3_minio.py
Labels: chore

#1110 [DOCS] Update image tutorials with `.image` namespaced expressions
  tutorials/image_querying/top_n_red_color.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
Labels: documentation

#1109 [CHORE] Update README.rst for image downloading
  README.rst
Labels: documentation, chore

#1111 [CHORE] Install wheel together with requirements in release build
  .github/workflows/python-publish.yml
Labels: chore

#1112 [CHORE] Remove rogue print statement
  daft/api_annotations.py
Labels: chore
