Repository Eventual-Inc/Daft, pull requests merged in 2024-06, with the labels that each got.

#2333 [FEAT] Add additional Azure authentication methods
  Cargo.lock
  daft/daft.pyi
  daft/io/_iceberg.py
  daft/io/object_store_options.py
  src/common/io-config/src/azure.rs
  src/common/io-config/src/gcs.rs
  src/common/io-config/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
Labels: enhancement

#2269 [FEAT] Implement str.substr Expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/substr.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_substr.py
Labels: documentation, enhancement

#2336 [BUG] Use os.path.join in read_hudi only for local fs
  daft/filesystem.py
  daft/hudi/hudi_scan.py
  daft/hudi/pyhudi/table.py
  daft/hudi/pyhudi/timeline.py
  daft/hudi/pyhudi/utils.py
Labels: bug

#2329 [FEAT] Public Delta Lake writer
  daft/__init__.py
  daft/api_annotations.py
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/delta_lake/delta_lake_storage_function.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/io/__init__.py
  daft/io/_delta_lake.py
  daft/io/catalog.py
  daft/io/object_store_options.py
  daft/logical/builder.py
  daft/table/table_io.py
  docs/source/api_docs/creation.rst
  docs/source/api_docs/dataframe.rst
  docs/source/user_guide/integrations/delta_lake.rst
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/sink_info.rs
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
  tests/io/delta_lake/test_table_write.py
  tutorials/delta_lake/1-local-image-batch-inference.ipynb
  tutorials/delta_lake/2-distributed-batch-inference.ipynb
  tutorials/delta_lake/3-pytorch-ray-single-node-training.ipynb
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
Labels: documentation, enhancement

#2338 [BUG] Add Retry on Streaming Errors when collecting stream into bytes
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
Labels: bug

#2339 [FEAT] [New Executor] [1/N] Move physical plan scheduler to new crate, misc. refactorings + drive-bys for new executor
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/mod.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/adaptive.rs
  src/daft-scheduler/src/lib.rs
  src/daft-scheduler/src/scheduler.rs
  src/lib.rs
  tests/cookbook/conftest.py
  tests/cookbook/test_filter.py
Labels: enhancement

#2342 [FEAT] Introduce terminal wrap around when explaining plans
  Cargo.lock
  src/daft-plan/Cargo.toml
  src/daft-plan/src/display.rs
Labels: enhancement

#2345 [BUG] Allow any file extension in Azure directory listing test
  tests/integration/io/test_list_files_azure.py
Labels: bug

#2344 [BUG] Allow nulls in partition column
  src/daft-scan/src/python.rs
  src/daft-stats/src/partition_spec.rs
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
Labels: bug

#2349 [BUG] Azure and Iceberg read and write fixes
  .github/workflows/python-package.yml
  benchmarking/parquet/benchmark-requirements.txt
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/filesystem.py
  requirements-dev.txt
  src/daft-io/src/azure_blob.rs
  tests/assets/pyiceberg_catalog.db
  tests/integration/iceberg/conftest.py
  tests/integration/iceberg/test_cloud_load.py
Labels: bug

#2326 [BUG] Allow variable columns in CSV
  daft/daft.pyi
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  daft/runners/partitioning.py
  daft/table/schema_inference.py
  daft/table/table_io.py
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/options.rs
  src/daft-csv/src/read.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
  tests/dataframe/test_creation.py
  tests/table/table_io/test_csv.py
Labels: bug

#2346 [CHORE]: make parquet metadata (de)serializable
  src/arrow2/Cargo.toml
  src/arrow2/src/datatypes/field.rs
  src/arrow2/src/datatypes/mod.rs
  src/arrow2/src/datatypes/physical_type.rs
  src/arrow2/src/datatypes/schema.rs
  src/arrow2/src/io/json_integration/mod.rs
  src/arrow2/src/types/mod.rs
  src/parquet2/Cargo.toml
  src/parquet2/src/indexes/intervals.rs
  src/parquet2/src/metadata/column_chunk_metadata.rs
  src/parquet2/src/metadata/column_descriptor.rs
  src/parquet2/src/metadata/column_order.rs
  src/parquet2/src/metadata/file_metadata.rs
  src/parquet2/src/metadata/row_metadata.rs
  src/parquet2/src/metadata/schema_descriptor.rs
  src/parquet2/src/metadata/sort.rs
  src/parquet2/src/parquet_bridge.rs
  src/parquet2/src/schema/types/basic_type.rs
  src/parquet2/src/schema/types/converted_type.rs
  src/parquet2/src/schema/types/parquet_type.rs
  src/parquet2/src/schema/types/physical_type.rs
Labels: documentation, chore

#2352 [CHORE] Bump chrono to 0.4.38
  Cargo.toml
  src/daft-core/src/array/ops/time.rs
  src/daft-decoding/src/deserialize.rs
  src/daft-json/src/decoding.rs
  src/daft-json/src/read.rs
Labels: chore

#2340 [FEAT] [New Executor] [2/N] daft-execution crate + proof-of-concept compute ops and partition reference + metadata model for new executor.
  Cargo.lock
  Cargo.toml
  src/daft-execution/Cargo.toml
  src/daft-execution/src/lib.rs
  src/daft-execution/src/ops/filter.rs
  src/daft-execution/src/ops/fused.rs
  src/daft-execution/src/ops/join.rs
  src/daft-execution/src/ops/limit.rs
  src/daft-execution/src/ops/mod.rs
  src/daft-execution/src/ops/monotonically_increasing_id.rs
  src/daft-execution/src/ops/project.rs
  src/daft-execution/src/ops/scan.rs
  src/daft-execution/src/ops/shuffle.rs
  src/daft-execution/src/ops/sort.rs
  src/daft-execution/src/partition/mod.rs
  src/daft-execution/src/partition/partition_ref.rs
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/resource_request.rs
  src/lib.rs
Labels: enhancement

#2354 [DOCS] the project currently uses ray which is not compatible with python 3.12
  CONTRIBUTING.md
Labels: documentation

#2361 [DOCS] improve SQL docs
  docs/source/user_guide/basic_concepts/read-and-write.rst
  docs/source/user_guide/integrations/sql.rst
Labels: documentation

#2368 [DOCS] Add tutorial for Data + AI Summit 2024
  tutorials/talks_and_demos/data-ai-summit-2024.ipynb
Labels: documentation

#2325 [FEAT] Add more context when UDFs fail
  daft/udf.py
  tests/dataframe/test_iter.py
  tests/expressions/test_udf.py
  tests/integration/io/test_url_download_http.py
  tests/udf_library/test_url_udfs.py
Labels: enhancement

#2362 [CHORE] Run doctests in CI
  .github/workflows/python-package.yml
  Cargo.lock
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  src/common/daft-config/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/utils/display_table.rs
Labels: chore

#2371 [EXPRESSIONS] Implement Expression.float.is_inf
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/float.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/float.rs
  src/daft-dsl/src/functions/float/is_inf.rs
  src/daft-dsl/src/functions/float/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_float.py
  tests/series/test_float.py
  tests/table/test_filter.py
Labels: documentation

#2372 [DOCS] add Delta writer functionality
  docs/source/user_guide/integrations/delta_lake.rst
Labels: documentation

#2376 [BUG] enable empty stats for deltalake
  daft/daft.pyi
  daft/delta_lake/delta_lake_scan.py
  src/daft-scan/src/python.rs
Labels: bug

#2378 [EXPRESSIONS] Add missing doc gen for Expression.float.is_nan
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
Labels: documentation

#2313 [FEAT] fill_nan and not_nan expressions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/float.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/float.rs
  src/daft-dsl/src/functions/float/fill_nan.rs
  src/daft-dsl/src/functions/float/mod.rs
  src/daft-dsl/src/functions/float/not_nan.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_float.py
  tests/series/test_float.py
  tests/table/test_fill.py
  tests/table/test_filter.py
Labels: documentation, enhancement

#2374 [BUG]: ide completions for expr namespaces
  daft/expressions/expressions.py
Labels: bug

#2377 [FEAT] Add Unity Catalog support
  daft/io/_delta_lake.py
  daft/unity_catalog/__init__.py
  daft/unity_catalog/unity_catalog.py
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/delta_lake.rst
  docs/source/user_guide/integrations/unity-catalog.rst
  pyproject.toml
  requirements-dev.txt
Labels: documentation, enhancement

#2390 [BUG] Fix IO integration tests
  tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
Labels: bug

#2389 [FEAT] Implement arctan2 expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/apply.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/trigonometry.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/trigonometry.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/functions/numeric/trigonometry.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: documentation, enhancement

#2379 [FEAT] Implement Anti and Semi Join
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/hudi/hudi_scan.py
  src/daft-core/src/join.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/ops/hash.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  tests/dataframe/test_joins.py
Labels: enhancement

#2381 [BUG] `with_column` with existing column name should not reorder columns
  src/daft-plan/src/builder.rs
  tests/dataframe/test_select.py
  tests/dataframe/test_with_column.py
  tests/dataframe/test_with_columns.py
Labels: bug

#2353 [FEAT] date and timestamp parsers
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/datatypes/time_unit.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/to_date.rs
  src/daft-dsl/src/functions/utf8/to_datetime.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_to_date.py
  tests/table/utf8/test_to_datetime.py
Labels: documentation, enhancement

#2347 [FEAT] [New Executor] [3/N] Full execution model prototype.
  Cargo.lock
  daft/context.py
  daft/daft.pyi
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/pyrunner.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-execution/Cargo.toml
  src/daft-execution/src/executor/local/local_executor.rs
  src/daft-execution/src/executor/local/local_partition_ref.rs
  src/daft-execution/src/executor/local/mod.rs
  src/daft-execution/src/executor/mod.rs
  src/daft-execution/src/executor/ray/mod.rs
  src/daft-execution/src/executor/ray/ray_executor.rs
  src/daft-execution/src/executor/ray/ray_partition_ref.rs
  src/daft-execution/src/executor/resource_manager.rs
  src/daft-execution/src/lib.rs
  src/daft-execution/src/ops/fused.rs
  src/daft-execution/src/partition/mod.rs
  src/daft-execution/src/partition/virtual_partition.rs
  src/daft-execution/src/scheduler/bulk.rs
  src/daft-execution/src/scheduler/channel.rs
  src/daft-execution/src/scheduler/mod.rs
  src/daft-execution/src/scheduler/streaming.rs
  src/daft-execution/src/scheduler/task_state.rs
  src/daft-execution/src/stage/exchange/collect.rs
  src/daft-execution/src/stage/exchange/mod.rs
  src/daft-execution/src/stage/exchange/shuffle.rs
  src/daft-execution/src/stage/exchange/sort.rs
  src/daft-execution/src/stage/mod.rs
  src/daft-execution/src/stage/planner.rs
  src/daft-execution/src/stage/run.rs
  src/daft-execution/src/stage/runner.rs
  src/daft-execution/src/stage/sink/collect.rs
  src/daft-execution/src/stage/sink/limit.rs
  src/daft-execution/src/stage/sink/mod.rs
  src/daft-execution/src/task/mod.rs
  src/daft-execution/src/test/mod.rs
  src/daft-execution/src/tree/builder.rs
  src/daft-execution/src/tree/mod.rs
  src/daft-execution/src/tree/op_state_tree.rs
  src/daft-execution/src/tree/op_tree.rs
  src/daft-execution/src/tree/queue.rs
  src/daft-execution/src/tree/topological_sort.rs
  src/daft-execution/src/tree/translate.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/storage_config.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
Labels: enhancement

#2357 [FEAT] Replace schema_hints with schema and infer_schema for read_json
  daft/io/_json.py
  tests/dataframe/test_creation.py
Labels: enhancement

#2393 [FEAT] Add manual auth for GCS and Iceberg GCS auth support
  Cargo.lock
  daft/daft.pyi
  daft/io/_iceberg.py
  src/common/io-config/src/gcs.rs
  src/common/io-config/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/google_cloud.rs
Labels: enhancement

#2416 [FEAT] print more info when hitting todo in stage planner
  src/daft-execution/src/stage/planner.rs
Labels: enhancement

#2415 [BUG] Slice array if necessary when casting from list to fixed size list
  src/daft-core/src/array/ops/cast.rs
  tests/series/test_slice.py
Labels: bug

#2403 [FEAT] Fixed Size Binary Type v2
  daft/daft.pyi
  daft/datatype.py
  src/arrow2/src/array/fixed_size_binary/mod.rs
  src/arrow2/src/compute/cast/binary_to.rs
  src/arrow2/src/compute/cast/mod.rs
  src/daft-core/src/array/from.rs
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/array/ops/is_in.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/serdes.rs
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/kernels/hashing.rs
  src/daft-core/src/kernels/search_sorted.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/hash.rs
  src/daft-core/src/series/serdes.rs
  src/daft-core/src/utils/arrow.rs
  src/daft-core/src/utils/supertype.rs
  src/daft-stats/src/column_stats/mod.rs
  tests/expressions/typing/conftest.py
  tests/series/test_cast.py
  tests/series/test_comparisons.py
  tests/series/test_filter.py
  tests/series/test_hash.py
  tests/series/test_if_else.py
  tests/series/test_series.py
  tests/series/test_size_bytes.py
  tests/series/test_take.py
  tests/table/test_from_py.py
  tests/table/test_sorting.py
  tests/table/test_table_aggs.py
  tests/test_datatypes.py
Labels: enhancement

#2401 [BUG] [New Executor] Drain channel in limit sink
  src/daft-execution/src/stage/sink/limit.rs
Labels: bug

#2419 [BUG] Remove debug print
  src/daft-table/src/ops/joins/hash_join.rs
Labels: bug

#2398 [FEAT]: hash expr
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/hash.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/table/test_hash.py
Labels: enhancement

#2426 [FEAT] Add ability to specify snapshot_id for iceberg read
  daft/iceberg/iceberg_scan.py
  daft/io/_iceberg.py
  tests/integration/iceberg/docker-compose/provision.py
  tests/integration/iceberg/test_table_load.py
Labels: enhancement

#2428 [BUG] Raise error when Ray Data tensor cannot be pickled and disable compliant nested types
  .github/workflows/python-package.yml
  benchmarking/parquet/benchmark-requirements.txt
  daft/dataframe/dataframe.py
  daft/runners/partitioning.py
  daft/table/micropartition.py
  daft/table/table.py
  daft/table/table_io.py
  requirements-dev.txt
  tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
  tests/integration/sql/test_sql.py
  tests/series/test_if_else.py
Labels: bug

#2436 [FEAT] Add bearer token authentication for Azure
  daft/daft.pyi
  daft/io/object_store_options.py
  src/common/io-config/src/azure.rs
  src/common/io-config/src/python.rs
  src/daft-io/src/azure_blob.rs
Labels: enhancement

#2440 [DOCS] Update unity-catalog docs to include installation
  docs/source/user_guide/integrations/unity-catalog.rst
Labels: documentation

#2438 [DOCS] Improve groupby and agg docs
  daft/dataframe/dataframe.py
Labels: documentation

#2439 [BUG] Enable display of time64 with seconds unit
  src/daft-core/src/utils/display_table.rs
Labels: bug

#2365 [FEAT] Bitwise 'AND' 'OR' 'XOR' Operations
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/bitwise.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/comparison.rs
  src/daft-core/src/series/series_like.rs
  src/daft-stats/src/partition_spec.rs
  src/daft-table/src/lib.rs
  tests/expressions/typing/conftest.py
  tests/expressions/typing/test_logical.py
  tests/series/test_bitwise.py
  tests/table/test_bitwise.py
Labels: enhancement

#2441 [BUG] Fix time type inference
  src/daft-decoding/src/inference.rs
  src/daft-json/src/inference.rs
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
  src/daft-json/test/dtypes.jsonl
Labels: bug

#2367 [FEAT] Add struct get syntactic sugar
  Cargo.lock
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/agg.rs
  src/daft-plan/src/logical_ops/explode.rs
  src/daft-plan/src/logical_ops/filter.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_ops/pivot.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_ops/repartition.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/logical_ops/sort.rs
  src/daft-plan/src/logical_ops/unpivot.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  tests/dataframe/test_getter_sugar.py
Labels: enhancement

#2421 [FEAT]: write lance
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/table_io.py
  pyproject.toml
  src/daft-execution/src/stage/planner.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/physical_ops/lance_write.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/sink_info.rs
  src/daft-scheduler/src/scheduler.rs
  tests/io/lancedb/test_lancedb_writes.py
Labels: enhancement

#2431 [FEAT] Add MinHash expression
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/minhash.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/minhash.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/functions/minhash.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-minhash/Cargo.toml
  src/daft-minhash/benches/minhash.rs
  src/daft-minhash/src/lib.rs
  src/daft-minhash/src/minhash.rs
  tests/expressions/test_expressions.py
  tests/series/test_minhash.py
  tests/table/test_minhash.py
Labels: documentation, enhancement

#2446 [FEAT] thread through transport errors
  src/arrow2/src/io/parquet/mod.rs
  src/common/error/src/error.rs
  src/parquet2/src/error.rs
Labels: enhancement

#2447 [FEAT] Add Schema.to_pyarrow_schema()
  daft/__init__.py
  daft/daft.pyi
  daft/logical/schema.py
  docs/source/api_docs/index.rst
  docs/source/api_docs/schema.rst
  src/daft-core/src/python/schema.rs
  tests/test_schema.py
Labels: documentation, enhancement

#2445 [BUG] Add retries to pyarrow write_dataset call
  daft/table/table_io.py
Labels: bug

#2449 [FEAT] Add a IOConfig.http with initial option for user_agent
  daft/daft.pyi
  daft/io/__init__.py
  src/common/io-config/src/config.rs
  src/common/io-config/src/http.rs
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
Labels: enhancement

#2448 [BUG] Use estimated in-memory size for scan task merging and resource requests
  daft/execution/rust_physical_plan_shim.py
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/io/test_merge_scan_tasks.py
Labels: bug

#2450 [FEAT] String normalize expression
  Cargo.lock
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/normalize.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_normalize.py
Labels: documentation, enhancement

#2452 [DOCS] Remove unsupported map get doc example
  daft/expressions/expressions.py
Labels: documentation
