Repository Eventual-Inc/Daft, pull requests merged in 2024-10, with the labels that each got.

#2979 [CHORE] ignore 45e2944e
  .git-blame-ignore-revs
Labels: chore

#2931 [DOCS] Fix docs to add SQL capabilities
  daft/daft/__init__.pyi
  daft/sql/_sql_funcs.py
  daft/sql/sql.py
  docs/source/10-min.ipynb
  docs/source/api_docs/index.rst
  docs/source/api_docs/sql.rst
  docs/source/conf.py
  docs/source/ext/__init__.py
  docs/source/ext/sql_autosummary.py
  docs/source/index.rst
  docs/source/migration_guides/coming_from_dask.rst
  docs/source/user_guide/aggregations.rst
  docs/source/user_guide/basic_concepts.rst
  docs/source/user_guide/basic_concepts/dataframe_introduction.rst
  docs/source/user_guide/basic_concepts/expressions.rst
  docs/source/user_guide/basic_concepts/introduction.rst
  docs/source/user_guide/daft_in_depth.rst
  docs/source/user_guide/dataframe-operations.rst
  docs/source/user_guide/datatypes.rst
  docs/source/user_guide/expressions.rst
  docs/source/user_guide/fotw/fotw-001-images.ipynb
  docs/source/user_guide/index.rst
  docs/source/user_guide/read-and-write.rst
  docs/source/user_guide/sql.rst
  docs/source/user_guide/udf.rst
  requirements-dev.txt
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-sql/src/modules/float.rs
  src/daft-sql/src/modules/image/crop.rs
  src/daft-sql/src/modules/image/decode.rs
  src/daft-sql/src/modules/image/encode.rs
  src/daft-sql/src/modules/image/resize.rs
  src/daft-sql/src/modules/image/to_mode.rs
  src/daft-sql/src/modules/json.rs
  src/daft-sql/src/modules/list.rs
  src/daft-sql/src/modules/map.rs
  src/daft-sql/src/modules/numeric.rs
  src/daft-sql/src/modules/partitioning.rs
  src/daft-sql/src/modules/structs.rs
  src/daft-sql/src/modules/temporal.rs
  src/daft-sql/src/modules/utf8.rs
  src/daft-sql/src/python.rs
Labels: documentation

#2974 [FEAT]: sql `read_deltalake` function
  Cargo.lock
  src/common/file-formats/src/file_format_config.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-scan/src/lib.rs
  src/daft-schema/src/time_unit.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/error.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/modules/config.rs
  src/daft-sql/src/modules/image/resize.rs
  src/daft-sql/src/modules/mod.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/table_provider/mod.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  tests/sql/test_table_funcs.py
Labels: enhancement

#2990 [BUG]: error messages for add
  src/daft-core/src/datatypes/infer_datatype.rs
Labels: bug

#2877 [BUG] Fix join errors with same key name joins (resolves #2649)
  Cargo.lock
  src/daft-plan/Cargo.toml
  src/daft-plan/src/logical_ops/join.rs
  tests/dataframe/test_joins.py
Labels: bug

#2987 [BUG] Add resources to Ray stateful UDF actor
  daft/execution/physical_plan.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  tests/actor_pool/test_pyactor_pool.py
  tests/test_resource_requests.py
Labels: bug

#3001 [DOCS] Update readme to correctly reflect new messaging
  README.rst
Labels: documentation

#2998 [BUG] Fix actor pool project splitting when column is not renamed
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
Labels: bug

#2942 [DOCS] Naming consistency of `length` functions
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  tests/series/test_cast.py
  tests/table/list/test_list_count_length.py
  tutorials/delta_lake/2-distributed-batch-inference.ipynb
Labels: documentation, enhancement

#3006 [DOCS] Update readme to use python syntax highlighting
  README.rst
Labels: documentation

#3011 [FEAT] Infer timedelta literal as duration
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/utils/display.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  tests/dataframe/test_temporals.py
  tests/expressions/test_expressions.py
Labels: enhancement

#2902 [FEAT] add `list.value_counts()`
  .cargo/config.toml
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/arrow2/src/array/list/mod.rs
  src/arrow2/src/array/map/mod.rs
  src/arrow2/src/array/mod.rs
  src/arrow2/src/array/struct_/mod.rs
  src/arrow2/src/compute/cast/mod.rs
  src/arrow2/src/datatypes/mod.rs
  src/arrow2/src/error.rs
  src/arrow2/src/offset.rs
  src/common/tracing/src/lib.rs
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/arrow2/comparison.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/map.rs
  src/daft-core/src/array/ops/sparse_tensor.rs
  src/daft-core/src/array/serdes.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/concat.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-core/src/series/ops/map.rs
  src/daft-core/src/series/serdes.rs
  src/daft-dsl/src/functions/map/get.rs
  src/daft-functions/src/list/mod.rs
  src/daft-functions/src/list/value_counts.rs
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/field.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-schema/src/schema.rs
  src/daft-sql/src/planner.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-stats/src/table_stats.rs
  src/daft-table/src/ffi.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/repr_html.rs
  tests/expressions/test_expressions.py
  tests/integration/iceberg/test_table_load.py
  tests/io/test_parquet_roundtrip.py
  tests/table/map/test_map_get.py
Labels: enhancement

#2944 [DOC] fix link in doc
  docs/source/migration_guides/coming_from_dask.rst
Labels: documentation

#3012 [BUG] Pass parquet2 io errors correctly into arrow2
  Cargo.lock
  src/arrow2/src/io/parquet/mod.rs
  src/common/error/Cargo.toml
  src/common/error/src/error.rs
Labels: bug

#3010 [FEAT] Cast SparseTensor and FixedShapeSparseTensor to Python
  src/daft-core/src/array/ops/cast.rs
  tests/series/test_cast.py
Labels: enhancement

#3019 [FEAT] agg_list support for list and struct types
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/struct_array.rs
  tests/table/test_table_aggs.py
Labels: enhancement

#3022 [FEAT] Add time travel to read_deltalake
  daft/delta_lake/delta_lake_scan.py
  daft/io/_deltalake.py
  tests/io/delta_lake/test_table_read.py
Labels: enhancement

#3005 [FEAT] Implement standard deviation
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/dataframe.rst
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/mean.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/stddev.rs
  src/daft-core/src/datatypes/agg_ops.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/utils/mod.rs
  src/daft-core/src/utils/stats.rs
  src/daft-dsl/src/arithmetic/mod.rs
  src/daft-dsl/src/arithmetic/tests.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/expr/tests.rs
  src/daft-dsl/src/functions/map/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/partitioning/mod.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/functions/sketch/mod.rs
  src/daft-dsl/src/functions/struct_/mod.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/join/mod.rs
  src/daft-dsl/src/join/tests.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/resolve_expr/mod.rs
  src/daft-dsl/src/resolve_expr/tests.rs
  src/daft-functions/src/list/mean.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-schema/src/dtype.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-table/src/lib.rs
  tests/dataframe/test_stddev.py
Labels: documentation, enhancement

#2918 [CHORE] Enable read_sql for swordfish
  .github/workflows/python-package.yml
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sources/empty_scan.rs
  src/daft-local-execution/src/sources/mod.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/src/python.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
Labels: chore

#3026 [BUG] Fix reading of logical types from Parquet files in s3
  src/daft-parquet/src/file.rs
Labels: bug

#3027 [BUG] Fix reading of logical types from streaming parquet
  src/daft-parquet/src/stream_reader.rs
Labels: bug

#3032 [DOCUMENTATION] add value counts to rst
  docs/source/api_docs/expressions.rst
Labels: documentation, chore

#3030 [BUG] Register super extension on to_arrow
  daft/logical/schema.py
  daft/series.py
Labels: bug

#2953 [FEAT] Include file paths as column from read_parquet/csv/json
  daft/daft/__init__.pyi
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  src/daft-csv/src/read.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  tests/dataframe/test_creation.py
  tests/integration/io/test_s3_reads_include_path.py
Labels: enhancement

#2975 [FEAT] Iceberg MOR for streaming parquet
  .github/workflows/python-package.yml
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
Labels: enhancement

#3035 [BUG] Sampling without replacement not working
  src/daft-table/src/lib.rs
  tests/dataframe/test_sample.py
Labels: bug

#3039 [BUG] Fix intersection checking when unioning schemas
  daft/logical/schema.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-schema/src/schema.rs
Labels: bug

#3040 [CHORE] update feature request
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: chore

#3023 [FEAT] Enable to_json_string for physical plan
  Cargo.lock
  daft/daft/__init__.pyi
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
Labels: enhancement

#3053 [BUG] Fix write_deltalake add action file path prefix
  daft/table/table_io.py
  src/daft-parquet/src/lib.rs
  tests/io/delta_lake/test_table_write.py
Labels: bug

#3018 [FEAT]: Interval dtype
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/datatype.py
  daft/expressions/__init__.py
  daft/expressions/expressions.py
  src/arrow2/src/compute/arithmetics/time.rs
  src/arrow2/src/compute/cast/primitive_to.rs
  src/arrow2/src/ffi/schema.rs
  src/arrow2/src/temporal_conversions.rs
  src/arrow2/src/types/native.rs
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/array/prelude.rs
  src/daft-core/src/array/serdes.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/datatypes/interval.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/datatypes/prelude.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/serdes.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-table/src/repr_html.rs
  tests/dataframe/test_temporals.py
  tests/expressions/test_cosine_distance.py
  tests/sql/test_temporal_exprs.py
Labels: enhancement

#3062 [FEAT]: sql between
  src/daft-sql/src/planner.rs
  tests/sql/test_exprs.py
Labels: enhancement

#3063 [BUG]: sql functions case sensitivit
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  tests/sql/test_exprs.py
Labels: bug

#2925 [CHORE] Enable lancedb reads for native executor
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  tests/io/lancedb/test_lancedb_reads.py
Labels: chore

#3066 [FEAT]: sql tbl alias, and compount ident for joins
  src/daft-sql/src/modules/aggs.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/table_provider/mod.rs
  tests/sql/test_joins.py
  tests/sql/test_sql.py
Labels: enhancement

#3002 [FEAT] Add stateful actor context and set CUDA_VISIBLE_DEVICES
  Cargo.lock
  daft/dependencies.py
  daft/internal/gpu.py
  daft/runners/pyrunner.py
  src/common/resource-request/Cargo.toml
  src/common/resource-request/src/lib.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
  tests/actor_pool/test_actor_cuda_devices.py
  tests/actor_pool/test_pyactor_pool.py
  tests/sql/test_sql.py
  tests/test_resource_requests.py
Labels: enhancement

#3074 [BUG]: joins with duplicate column names and qualified table expansion
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/dataframe/test_joins.py
  tests/sql/test_joins.py
Labels: bug

#3084 [CHORE]: replace the `.venv` value with global variable `VENV`
  Makefile
Labels: chore

#3028 [BUG] Fix actor pool initialization in ray client mode
  daft/context.py
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/execution/native_executor.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/io/file_path.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  src/daft-scheduler/src/scheduler.rs
Labels: bug

#3079 [FEAT] Enable sample for swordfish
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  tests/dataframe/test_sample.py
Labels: enhancement

#3080 [BUG] Fix into_partitions to use a more naive approach without materialization
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
Labels: bug

#3098 [BUG] Disable Linux SSL CERT override
  daft/io/__init__.py
Labels: bug

#3099 [PERF] Remove stateful actor child materialization limit
  daft/execution/physical_plan.py
Labels: performance

#3081 [FEAT] Enable pivot for swordfish
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/pivot.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  tests/dataframe/test_pivot.py
Labels: enhancement

#2860 [FEAT] Outer joins for native executor
  src/arrow2/src/array/growable/primitive.rs
  src/daft-core/src/prelude.rs
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/probeable/mod.rs
  tests/cookbook/test_joins.py
  tests/dataframe/test_joins.py
Labels: enhancement

#3078 [FEAT] Enable unpivot for swordfish
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/unpivot.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  tests/dataframe/test_unpivot.py
Labels: enhancement

#2976 [FEAT] Enable concat for swordfish
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  tests/dataframe/test_approx_count_distinct.py
  tests/dataframe/test_concat.py
  tests/dataframe/test_sample.py
  tests/dataframe/test_transform.py
Labels: enhancement

#3087 [FEAT]: add sql DISTINCT
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: enhancement

#3094 [BUG] Add over clause in read_sql percentile reads
  .github/workflows/python-package.yml
  daft/sql/sql_scan.py
  requirements-dev.txt
  src/daft-dsl/src/expr/mod.rs
  tests/integration/sql/conftest.py
  tests/integration/sql/docker-compose/docker-compose.yml
  tests/integration/sql/test_sql.py
Labels: bug

#3104 [BUG] Autodetect AWS region during deltalake scan
  daft/delta_lake/delta_lake_scan.py
  daft/io/aws_config.py
  daft/io/catalog.py
Labels: bug

#3077 [FEAT] Enable explode for swordfish
  Cargo.lock
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/explode.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  tests/dataframe/test_explode.py
  tests/dataframe/test_wildcard.py
  tests/sql/test_list_exprs.py
Labels: enhancement

#3068 [BUG] Bump up max_header_size
  src/daft-parquet/src/file.rs
  src/parquet2/src/read/page/stream.rs
Labels: bug

#3086 [FEAT]: sql `IN` operator
  src/daft-dsl/src/lit.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_exprs.py
Labels: enhancement

#2986 [FEAT] Compute pool for native executor
  Cargo.lock
  Cargo.toml
  src/common/runtime/Cargo.toml
  src/common/runtime/src/lib.rs
  src/daft-csv/Cargo.toml
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/tokenize/bpe.rs
  src/daft-functions/src/uri/download.rs
  src/daft-functions/src/uri/upload.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-json/Cargo.toml
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/explode.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/pivot.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/intermediate_ops/unpivot.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/read.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/glob.rs
  src/daft-scan/src/storage_config.rs
Labels: enhancement

#3055 [PERF] Add a parallel local CSV reader
  Cargo.lock
  src/arrow2/src/io/csv/read_async/reader.rs
  src/daft-csv/Cargo.toml
  src/daft-csv/src/lib.rs
  src/daft-csv/src/local.rs
  src/daft-csv/src/local/pool.rs
  src/daft-csv/src/read.rs
  src/daft-decoding/src/deserialize.rs
Labels: performance

#3064 [FEAT] Add floor division
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/lib.rs
  tests/series/test_arithmetic.py
  tests/sql/test_binary_op_exprs.py
  tests/table/numeric/test_numeric.py
Labels: enhancement

#3130 [DOCS] Update banner on README.rst
  README.rst
Labels: documentation

#3110 [FEAT]: sql cross join
  src/common/error/src/error.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/join_key_set.rs
  src/daft-plan/src/logical_optimization/mod.rs
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/eliminate_cross_join.rs
  src/daft-plan/src/logical_optimization/rules/mod.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-sql/src/planner.rs
Labels: enhancement

#3131 [BUG] fix type widening for rem
  daft/daft/__init__.pyi
  daft/datatype.py
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-schema/src/python/datatype.rs
  tests/series/test_arithmetic.py
Labels: bug

#3083 [CHORE] Refactor shuffles to use a unified ShuffleExchange PhysicalPlan variant
  daft/execution/rust_physical_plan_shim.py
  src/daft-plan/src/display.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_ops/coalesce.rs
  src/daft-plan/src/physical_ops/fanout.rs
  src/daft-plan/src/physical_ops/flatten.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/reduce.rs
  src/daft-plan/src/physical_ops/shuffle_exchange.rs
  src/daft-plan/src/physical_ops/split.rs
  src/daft-plan/src/physical_optimization/rules/drop_repartition.rs
  src/daft-plan/src/physical_optimization/rules/reorder_partition_keys.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
Labels: chore

#3144 [CHORE] Add rust cache to s3 build artifacts action
  .github/workflows/build-artifact-s3.yml
Labels: chore

#3127 [FEAT] Swordfish Stateful UDF support
  daft/execution/stateful_actor.py
  daft/runners/pyrunner.py
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  tests/expressions/test_udf.py
Labels: enhancement

#3147 [CHORE] (Revert:) Add rust cache to s3 build artifacts action
  .github/workflows/build-artifact-s3.yml
Labels: chore

#3146 [FEAT] Support SQL `INTERVAL`
  Cargo.lock
  src/daft-sql/Cargo.toml
  src/daft-sql/src/planner.rs
  tests/sql/test_exprs.py
Labels: enhancement

#3150 [BUG]: between panic on unsupported types
  src/daft-core/src/series/ops/between.rs
Labels: bug

#3143 [FEAT] dec128 math
  src/arrow2/src/compute/arithmetics/decimal/mul.rs
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/growable/arrow_growable.rs
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/apply.rs
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/array/ops/is_in.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/sum.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/ops/truncate.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/array/prelude.rs
  src/daft-core/src/array/serdes.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/datatypes/prelude.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/serdes.rs
  src/daft-dsl/src/lit.rs
  src/daft-functions/src/distance/cosine.rs
  src/daft-functions/src/hash.rs
  src/daft-parquet/src/statistics/column_range.rs
  src/daft-schema/src/dtype.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-table/src/repr_html.rs
  tests/series/test_arithmetic.py
  tests/series/test_comparisons.py
Labels: enhancement

#3154 [FEAT] enable decimal between
  src/daft-core/src/array/ops/between.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/series/ops/between.rs
  src/daft-schema/src/dtype.rs
  tests/table/test_between.py
Labels: enhancement

#3137 [FEAT]: Sql common table expressions (CTE's)
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: enhancement

#3052 [FEATURE] add min_hash alternate hashers
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/minhash.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/minhash.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/minhash.rs
  src/daft-hash/Cargo.toml
  src/daft-hash/src/lib.rs
  src/daft-minhash/Cargo.toml
  src/daft-minhash/benches/minhash.rs
  src/daft-minhash/benches/windowed.rs
  src/daft-minhash/build.rs
  src/daft-minhash/src/lib.rs
  src/daft-minhash/src/minhash.rs
  src/daft-minhash/src/tests.rs
  src/daft-minhash/src/windowed.rs
  src/daft-sql/src/modules/hashing.rs
  tests/series/test_minhash.py
  tests/sql/test_exprs.py
  tests/table/test_minhash.py
Labels: chore

#3135 [CHORE] Enable debug in test profile
  Cargo.toml
Labels: chore

#3153 [FEAT]: sql concat and stddev
  src/daft-sql/src/modules/aggs.rs
  src/daft-sql/src/modules/utf8.rs
  tests/sql/test_aggs.py
  tests/sql/test_utf8_exprs.py
Labels: enhancement

#3100 [FEAT]: Throw error for invalid ** usage outside folder segments (e.g. /tmp/**.csv)
  src/daft-io/src/object_store_glob.rs
  tests/integration/io/parquet/test_reads_s3_minio.py
  tests/io/test_list_files_local.py
Labels: enhancement

#2992 [FEAT] Streaming physical writes for native executor
  Cargo.lock
  Cargo.toml
  daft/io/writer.py
  daft/table/partitioning.py
  src/daft-core/src/utils/identity_hash_set.rs
  src/daft-io/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/buffer.rs
  src/daft-local-execution/src/dispatcher.rs
  src/daft-local-execution/src/intermediate_ops/buffer.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-micropartition/src/ops/concat.rs
  src/daft-micropartition/src/python.rs
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/sink_info.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/hash.rs
  src/daft-table/src/probeable/probe_set.rs
  src/daft-table/src/probeable/probe_table.rs
  src/daft-writers/Cargo.toml
  src/daft-writers/src/batch.rs
  src/daft-writers/src/file.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/partition.rs
  src/daft-writers/src/physical.rs
  src/daft-writers/src/python.rs
  src/daft-writers/src/test.rs
  tests/benchmarks/conftest.py
  tests/benchmarks/test_local_tpch.py
  tests/benchmarks/test_streaming_writes.py
  tests/cookbook/test_write.py
  tests/dataframe/test_decimals.py
  tests/dataframe/test_temporals.py
  tests/io/test_csv_roundtrip.py
  tests/io/test_parquet_roundtrip.py
  tests/io/test_s3_credentials_refresh.py
Labels: enhancement

#3128 [CHORE] Cancel tasks spawned on compute runtime
  src/common/runtime/src/lib.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-scan/src/glob.rs
Labels: chore
