Repository Eventual-Inc/Daft, pull requests merged in 2024-12, with the labels that each got.

#3396 [CHORE] Write tpch parquet files one at a time
  benchmarking/tpch/data_generation.py
Labels: chore

#3426 [FEAT] Add cluster profiles
  .github/assets/.template.yaml
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/run-cluster.yaml
Labels: enhancement

#3136 [FEAT]: Support `.clip` function
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/clip.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/clip.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-functions/src/numeric/clip.rs
  src/daft-functions/src/numeric/mod.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/modules/numeric.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/conftest.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/numeric/test_numeric.py
Labels: documentation, enhancement

#3461 [FEAT] run cluster on commit
  .github/assets/.template.yaml
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/run-cluster.yaml
  pyproject.toml
Labels: enhancement

#3473 [CHORE] Address comments on previous PR
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/run-cluster.yaml
Labels: chore

#3472 [CHORE] Add warning in PyRunner to switch to Native
  daft/runners/pyrunner.py
Labels: chore

#3455 [FEAT] Add `count-distinct` aggregation
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/list/mod.rs
  src/daft-functions/src/list/unique_count.rs
  src/daft-functions/src/python/list.rs
  src/daft-functions/src/python/mod.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-table/src/lib.rs
  tests/dataframe/test_approx_count_distinct.py
  tests/dataframe/test_count_distinct.py
Labels: enhancement

#3405 [CHORE] Add tests for parquet size estimations
  daft/daft/testing.pyi
  src/daft-scan/src/python.rs
  src/lib.rs
  tests/test_size_estimations.py
Labels: chore

#3484 [BUG] Block on parquet schema future in estimate_size_bytes
  src/daft-scan/src/python.rs
Labels: bug

#3459 [FEAT] extend `build-commit` workflow to support different compile-archs
  .github/ci-scripts/constants.py
  .github/ci-scripts/get_wheel_name_from_s3.py
  .github/ci-scripts/upload_wheel_to_s3.py
  .github/ci-scripts/wheellib.py
  .github/workflows/build-commit.yaml
Labels: enhancement

#3362 [FEAT] connect: support basic column operations
  src/daft-connect/src/lib.rs
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/datatype.rs
  src/daft-connect/src/translation/expr.rs
  src/daft-connect/src/translation/expr/unresolved_function.rs
  tests/connect/test_basic_column.py
Labels: enhancement

#3350 [FEAT] connect: add binary operators
  src/daft-connect/src/translation/expr/unresolved_function.rs
Labels: enhancement

#3481 [BUG]: dont panic on count(distinct)
  src/daft-sql/src/modules/aggs.rs
Labels: bug

#3487 [BUG] Fix build commit workflow
  .github/ci-scripts/get_wheel_name_from_s3.py
  .github/workflows/build-commit.yaml
Labels: bug

#3477 [FEAT] Support parquet RLE decoding for booleans
  src/arrow2/src/io/parquet/read/deserialize/boolean/basic.rs
  src/parquet2/src/encoding/hybrid_rle/decoder.rs
  tests/io/test_parquet_roundtrip.py
Labels: enhancement

#3363 [FEAT] connect: createDataFrame
  Cargo.lock
  Cargo.toml
  daft/dataframe/dataframe.py
  src/arrow2/src/io/ipc/read/common.rs
  src/arrow2/src/io/ipc/read/mod.rs
  src/daft-connect/Cargo.toml
  src/daft-connect/src/lib.rs
  src/daft-connect/src/op/execute/root.rs
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/datatype.rs
  src/daft-connect/src/translation/datatype/codec.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/local_relation.rs
  src/daft-connect/src/translation/logical_plan/project.rs
  src/daft-connect/src/translation/logical_plan/range.rs
  src/daft-connect/src/translation/logical_plan/to_df.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-logical-plan/src/builder.rs
  tests/connect/conftest.py
  tests/connect/test_create_df.py
Labels: enhancement

#3351 [FEAT] connect: add modulus operator and withColumns support
  src/daft-connect/src/translation/expr/unresolved_function.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/with_columns.rs
  tests/connect/test_group_by.py
Labels: enhancement

#3488 [FEAT] Enable Actor Pool UDFs by default
  daft/daft/__init__.pyi
  daft/execution/actor_pool_udf.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/stateful_actor.py
  daft/expressions/expressions.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/udf.py
  docs/source/api_docs/udf.rst
  docs/source/user_guide/udf.rst
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/functions/python/udf_runtime_binding.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/pyobj_serde.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/resolve_expr/mod.rs
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/ops/actor_pool_project.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/split_actor_pool_projects.rs
  src/daft-physical-plan/src/ops/actor_pool_project.rs
  src/daft-table/src/ops/agg.rs
  tests/actor_pool/test_actor_cuda_devices.py
  tests/actor_pool/test_pyactor_pool.py
  tests/actor_pool/test_ray_actor_pool.py
  tests/expressions/test_udf.py
  tests/test_resource_requests.py
Labels: documentation, enhancement

#3460 [FEAT] Respect resource request for projections in swordfish
  src/common/resource-request/src/lib.rs
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  tests/test_resource_requests.py
Labels: enhancement

#2837 [FEAT] add register-table helper to sql-catalog
  daft/sql/sql.py
Labels: enhancement

#3492 [FEAT] shuffle testing
  .github/assets/template.yaml
  .github/ci-scripts/format_env_vars.py
  .github/ci-scripts/read_inline_metadata.py
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/run-cluster.yaml
  .github/working-dir/shuffle_testing.py
Labels: enhancement

#3393 [FEAT]: expr simplifier
  daft/delta_lake/delta_lake_scan.py
  daft/hudi/hudi_scan.py
  daft/iceberg/iceberg_scan.py
  daft/io/_generator.py
  daft/io/_lance.py
  daft/sql/sql_scan.py
  src/common/scan-info/src/scan_operator.rs
  src/common/scan-info/src/test/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/simplify_expressions.rs
  src/daft-logical-plan/src/treenode.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
Labels: enhancement

#3359 [CHORE] connect, test: `df.withColumn`
  tests/connect/test_with_column.py
Labels: enhancement, chore

#3499 [FEAT] connect: remove excessive warnings from spark connect
  src/daft-connect/src/translation/expr.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/schema.rs
Labels: enhancement

#3493 [CHORE] use conventional commits
  .github/workflows/pr-labeller.yml
Labels: chore

#3503 ci(release-drafter): use conventional commit labels
  .github/release-drafter.yml
Labels: ci

#3437 feat: cross join
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/table/micropartition.py
  src/daft-core/src/join.rs
  src/daft-core/src/lib.rs
  src/daft-local-execution/src/intermediate_ops/cross_join.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/cross_join_collect.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/python.rs
  src/daft-physical-plan/src/display.rs
  src/daft-physical-plan/src/ops/cross_join.rs
  src/daft-physical-plan/src/ops/mod.rs
  src/daft-physical-plan/src/optimization/rules/reorder_partition_keys.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-table/src/ops/joins/mod.rs
  tests/dataframe/test_joins.py
  tests/sql/test_joins.py
Labels: enhancement, feat

#3495 fix(tpcds): fix bugs in tpcds datagen script
  benchmarking/tpcds/datagen.py
Labels: bug, fix

#3457 feat(parquet): Target parquet writes by size bytes instead of rows
  daft/io/writer.py
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-writers/src/batch.rs
  src/daft-writers/src/file.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/partition.rs
  src/daft-writers/src/pyarrow.rs
  src/daft-writers/src/test.rs
Labels: enhancement, feat

#3490 feat(parquet): Limit parallel tasks in remote parquet reader
  Cargo.lock
  benchmarking/parquet/conftest.py
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-parquet/src/utils.rs
Labels: enhancement, feat

#3507 fix(run-cluster-workflow): Add null check when parsing metadata
  .github/ci-scripts/templatize_ray_config.py
Labels: fix

#3508 refactor(swordfish): Generic broadcast state bridge
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/cross_join.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/cross_join_collect.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/state_bridge.rs
Labels: refactor

#3516 ci: add a tool to launch workloads on cluster
  tools/gha_run_cluster_job.py
Labels: ci

#3515 refactor: create a rust based `PartitionSet`
  Cargo.lock
  src/daft-connect/Cargo.toml
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/local_relation.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/partitioning.rs
Labels: refactor

#3514 test: Add more size estimation tests from our s3 bucket
  tests/test_size_estimations.py
Labels: test

#3521 feat(list): add fixed-size list support for value_counts
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-functions/src/list/value_counts.rs
  tests/expressions/test_expressions.py
Labels: feat

#3509 feat(tpcds-benchmarking): Add basic tpcds benchmarking for local testing
  .gitignore
  benchmarking/tpcds/__init__.py
  benchmarking/tpcds/__main__.py
  benchmarking/tpcds/datagen.py
  benchmarking/tpcds/helpers.py
  benchmarking/tpcds/ray_entrypoint.py
Labels: feat

#3501 feat(optimizer): Add scaffolding to create join graphs from logical plans
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/mod.rs
Labels: feat

#3541 ci: Add "build" label type to accepted PR titles
  .github/workflows/pr-labeller.yml
Labels: ci

#3540 build: Use uv for maturin builds instead
  Makefile
Labels: build

#3544 fix: boolean and/or expressions with null
  src/daft-core/src/array/ops/comparison.rs
  tests/series/test_comparisons.py
  tests/table/test_between.py
Labels: fix

#3539 feat: Add iterators to more types
  src/daft-core/src/array/iterator.rs
Labels: feat

#3360 feat(connect): add parquet support
  Cargo.lock
  Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/lib.rs
  src/daft-connect/src/op/execute.rs
  src/daft-connect/src/op/execute/root.rs
  src/daft-connect/src/op/execute/write.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/project.rs
  src/daft-connect/src/translation/logical_plan/read.rs
  src/daft-connect/src/translation/logical_plan/read/data_source.rs
  src/daft-connect/src/translation/logical_plan/to_df.rs
  src/daft-connect/src/translation/logical_plan/with_columns.rs
  src/daft-connect/src/translation/schema.rs
  tests/connect/test_parquet.py
Labels: enhancement, blocked, feat

#3522 feat: Unity Catalog writes using `daft.DataFrame.write_deltalake()`
  daft/dataframe/dataframe.py
  daft/unity_catalog/unity_catalog.py
  requirements-dev.txt
Labels: feat

#3546 feat: Make serialization code not unwrap and panic on failures
  benchmarking/tpcds/ray_entrypoint.py
  src/common/py-serde/src/python.rs
Labels: feat

#3346 feat(connect): add `df.filter`
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/filter.rs
  tests/connect/test_filter.py
Labels: enhancement, feat

#3536 feat: support for basic subquery execution
  src/daft-dsl/src/expr/mod.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/drop_repartition.rs
  src/daft-logical-plan/src/optimization/rules/lift_project_from_agg.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/split_actor_pool_projects.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-logical-plan/src/optimization/test/mod.rs
  src/daft-sql/src/planner.rs
  tests/benchmarks/test_local_tpch.py
  tests/sql/test_utf8_exprs.py
Labels: feat

#3345 feat(connect): add drop support
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/drop.rs
  tests/connect/test_drop.py
Labels: enhancement, feat

#3553 feat: Implement count-distinct for sql
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/aggs.rs
  tests/sql/test_aggs.py
Labels: feat

#3505 feat(shuffles): Locality aware pre shuffle merge
  daft/execution/execution_step.py
  daft/execution/shuffles/pre_shuffle_merge.py
  daft/runners/ray_runner.py
  src/common/daft-config/src/lib.rs
Labels: feat

#3548 feat(swordfish): Enable left/right joins to build probe table on either side
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  tests/sql/test_joins.py
Labels: feat

#3565 perf: lazily import pyiceberg and unity catalog if available
  daft/catalog/__init__.py
Labels: perf

#3542 docs: update tpch benchmark link
  docs/source/faq/benchmarks.rst
Labels: docs

#3534 feat(swordfish): Optimize grouped aggregations
  daft/context.py
  daft/daft/__init__.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/grouped_aggregate.rs
  src/daft-local-execution/src/sinks/mod.rs
  tests/dataframe/test_intersect.py
  tests/sql/test_aggs.py
Labels: feat

#3580 feat(connect): support `DdlParse`
  Cargo.lock
  Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/lib.rs
  src/daft-schema/src/schema.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/connect/test_analyze_plan.py
Labels: feat

#3584 ci: Add ability to array-ify args and run multiple jobs
  .github/ci-scripts/job_runner.py
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/run-cluster.yaml
  benchmarking/tpcds/ray_entrypoint.py
Labels: ci

#3570 chore: move symbolic and boolean algebra code into new crate
  Cargo.lock
  Cargo.toml
  src/common/scan-info/Cargo.toml
  src/common/scan-info/src/expr_rewriter.rs
  src/daft-algebra/Cargo.toml
  src/daft-algebra/src/boolean.rs
  src/daft-algebra/src/lib.rs
  src/daft-algebra/src/simplify.rs
  src/daft-dsl/src/optimization.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/simplify_expressions.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/planner.rs
Labels: chore

#3583 perf: filter null join key optimization rule
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/filter_null_join_key.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
Labels: perf

#3596 chore: Fix ordering in sql tests + pin docker images in read_sql tests
  tests/dataframe/test_intersect.py
  tests/integration/sql/docker-compose/docker-compose.yml
  tests/sql/test_sql.py
Labels: chore

#3588 ci: Always download logs
  .github/workflows/run-cluster.yaml
Labels: ci

#3554 refactor: allow InMemory to take in non python based entries
  Cargo.lock
  Cargo.toml
  src/common/partitioning/Cargo.toml
  src/common/partitioning/src/lib.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/op/execute/root.rs
  src/daft-connect/src/op/execute/write.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/datatype/codec.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/drop.rs
  src/daft-connect/src/translation/logical_plan/filter.rs
  src/daft-connect/src/translation/logical_plan/local_relation.rs
  src/daft-connect/src/translation/logical_plan/project.rs
  src/daft-connect/src/translation/logical_plan/range.rs
  src/daft-connect/src/translation/logical_plan/read.rs
  src/daft-connect/src/translation/logical_plan/to_df.rs
  src/daft-connect/src/translation/logical_plan/with_columns.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/source_info/mod.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/lib.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/partitioning.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/adaptive.rs
Labels: refactor

#3560 feat(connect): df.show
  src/daft-connect/src/session.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-dsl/src/lit.rs
  tests/connect/test_show.py
Labels: feat

#3602 fix: use arrow's schema instead of spark's for local rel
  Cargo.lock
  src/daft-connect/Cargo.toml
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/datatype.rs
  src/daft-connect/src/translation/datatype/codec.rs
  src/daft-connect/src/translation/logical_plan/local_relation.rs
  src/daft-core/src/array/mod.rs
Labels: fix

#3607 test(connect): add more tests for `createDataFrame`
  tests/connect/test_create_df.py
Labels: test

#3604 fix(udf): udf call with empty table and batch size
  daft/udf.py
  tests/expressions/test_udf.py
Labels: fix

#3592 chore!: drop support for Python 3.8
  .github/workflows/build-artifact-s3.yml
  .github/workflows/nightlies-tests.yml
  .github/workflows/notebook-checker.yml
  .github/workflows/property-based-tests.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  .ruff.toml
  Cargo.toml
  daft/dataframe/dataframe.py
  daft/pickle/cloudpickle.py
  daft/pickle/compat.py
  pyproject.toml
  requirements-dev.txt
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
  tests/io/delta_lake/test_table_write.py
  tests/io/lancedb/test_lancedb_writes.py
  tests/series/test_temporal_ops.py
  tests/test_datatypes.py
Labels: chore, breaking change

#3571 feat(swordfish): Progress Bar
  Cargo.lock
  daft/runners/progress_bar.py
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/progress_bar.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/source.rs
Labels: feat

#3608 feat: Default native runner
  daft/context.py
  daft/dataframe/dataframe.py
  daft/runners/pyrunner.py
  src/daft-local-plan/src/translate.rs
Labels: feat

#3613 chore: add warning for native runner
  daft/context.py
Labels: chore

#3612 chore!: upgrade Ray pins and pyarrow pins
  .github/workflows/python-package.yml
  daft/table/table_io.py
  pyproject.toml
  tests/integration/iceberg/conftest.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
  tests/io/delta_lake/test_table_write.py
  tests/io/hudi/test_table_read.py
  tests/io/iceberg/test_iceberg_writes.py
  tests/io/lancedb/test_lancedb_reads.py
  tests/io/lancedb/test_lancedb_writes.py
Labels: chore, breaking change

#3595 docs: daft documentation v2
  .pre-commit-config.yaml
  docs-v2/10min.ipynb
  docs-v2/advanced/distributed.md
  docs-v2/advanced/memory.md
  docs-v2/advanced/partitioning.md
  docs-v2/core_concepts.md
  docs-v2/core_concepts/aggregations.md
  docs-v2/core_concepts/dataframe.md
  docs-v2/core_concepts/datatypes.md
  docs-v2/core_concepts/expressions.md
  docs-v2/core_concepts/read_write.md
  docs-v2/core_concepts/sql.md
  docs-v2/core_concepts/udf.md
  docs-v2/img/architecture.png
  docs-v2/img/daft.png
  docs-v2/img/daft_diagram.png
  docs-v2/img/execution_model.png
  docs-v2/img/favicon.png
  docs-v2/img/in_memory_data_representation.png
  docs-v2/img/sql_distributed_read.png
  docs-v2/index.md
  docs-v2/install.md
  docs-v2/integrations/aws.md
  docs-v2/integrations/azure.md
  docs-v2/integrations/delta_lake.md
  docs-v2/integrations/hudi.md
  docs-v2/integrations/huggingface.md
  docs-v2/integrations/iceberg.md
  docs-v2/integrations/ray.md
  docs-v2/integrations/sql.md
  docs-v2/integrations/unity_catalog.md
  docs-v2/migration/dask_migration.md
  docs-v2/quickstart.ipynb
  docs-v2/quickstart.md
  docs-v2/resources/architecture.md
  docs-v2/resources/benchmarks/tpch-1000sf.html
  docs-v2/resources/benchmarks/tpch-100sf.html
  docs-v2/resources/benchmarks/tpch-nodes-count-daft-1000-sf.html
  docs-v2/resources/benchmarks/tpch.md
  docs-v2/resources/dataframe_comparison.md
  docs-v2/resources/telemetry.md
  docs-v2/resources/tutorials.md
  docs-v2/terms.md
  mkdocs.yml
Labels: docs

#3606 ci: Add build step to run-cluster
  .github/workflows/build-commit.yaml
  .github/workflows/run-cluster.yaml
Labels: ci

#3361 feat(connect): read/write → csv, write → json
  src/daft-connect/src/op/execute/write.rs
  src/daft-connect/src/translation/logical_plan/read/data_source.rs
  tests/connect/test_csv.py
Labels: feat

#3610 test(connect): verify `show()`output
  tests/connect/test_show.py
Labels: test

#3386 feat(connect): `with_columns_renamed`
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/with_columns_renamed.rs
  tests/connect/test_with_columns_renamed.py
Labels: feat

#3623 perf(optimizer): convert filter predicate to CNF to push through join
  src/daft-algebra/src/boolean.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
Labels: perf

#3625 ci: Output results in a CSV format
  .github/ci-scripts/job_runner.py
  .github/workflows/run-cluster.yaml
Labels: ci

#3618 feat(connect): add more unresolved functions
  src/daft-connect/src/translation/expr/unresolved_function.rs
  tests/connect/test_unresolved.py
Labels: feat

#3616 feat(optimizer): Implement naive join ordering
  Cargo.lock
  src/common/scan-info/src/test/mod.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/mod.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
  src/daft-logical-plan/src/test/mod.rs
  src/daft-physical-plan/src/test/mod.rs
Labels: feat

#3630 fix: unity catalog import from write_deltalake
  daft/dataframe/dataframe.py
Labels: fix

#3631 chore: Fix csv benchmark test
  tests/microbenchmarks/test_file_read.py
Labels: chore

#3626 chore: Build progress bar only on first update
  daft/runners/progress_bar.py
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/progress_bar.rs
Labels: chore

#3518 feat(expressions): Extend Expression.url.upload() to support row-specific URLs
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-functions/src/python/uri.rs
  src/daft-functions/src/uri/mod.rs
  src/daft-functions/src/uri/upload.rs
  src/daft-io/src/lib.rs
  tests/io/test_url_upload_local.py
Labels: p1, feat

#3633 feat: support new PyIceberg IO properties and custom IOConfig in write_iceberg
  daft/dataframe/dataframe.py
  daft/io/_iceberg.py
  daft/logical/builder.py
Labels: feat
