Repository Eventual-Inc/Daft, pull requests merged in 2024-03, with the labels that each got.

#1879 [Catalogs] [Delta Lake] Add initial support for reading from Delta Lake.
  .github/workflows/python-package.yml
  daft/__init__.py
  daft/daft.pyi
  daft/delta_lake/__init__.py
  daft/delta_lake/delta_lake_scan.py
  daft/expressions/expressions.py
  daft/iceberg/iceberg_scan.py
  daft/io/__init__.py
  daft/io/_delta_lake.py
  docs/source/api_docs/creation.rst
  pyproject.toml
  requirements-dev.txt
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/utils/display_table.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-scan/src/expr_rewriter.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-stats/src/partition_spec.rs
  src/daft-stats/src/table_stats.rs
  src/daft-table/src/lib.rs
  tests/integration/iceberg/docker-compose/run-minio.sh
  tests/io/delta_lake/__init__.py
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/mock_s3_server.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
  tests/utils.py
Labels: documentation

#1959 [FEAT] MapArray
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/datatype.py
  daft/series.py
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/serdes.rs
  src/daft-core/src/utils/arrow.rs
  src/daft-core/src/utils/supertype.rs
  src/daft-stats/src/column_stats/mod.rs
  tests/dataframe/test_creation.py
  tests/integration/iceberg/test_table_load.py
  tests/io/delta_lake/conftest.py
  tests/io/test_parquet.py
  tests/io/test_parquet_roundtrip.py
  tests/series/test_concat.py
  tests/series/test_if_else.py
  tests/table/test_from_py.py
  tests/test_schema.py
Labels: enhancement

#1969 [DOCS] [Delta Lake] Add user guide for Delta Lake reads.
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/delta_lake.rst
  docs/source/user_guide/poweruser/scaling-up.rst
Labels: documentation

#1972 [CHORE] Set DAFT_ANALYTICS_ENABLED=0 in nightly tests
  .github/workflows/nightlies-tests.yml
Labels: chore

#1975 [CHORE] Disables anonymous mode for S3 accesses in DeltaLake
  daft/delta_lake/delta_lake_scan.py
Labels: chore

#1982 [CHORE] Simplify cast to schema
  Cargo.lock
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/lib.rs
Labels: chore

#1984 [FEAT] Enable UDF to handle arbitrary number of Daft series
  daft/udf.py
  tests/expressions/test_udf.py
Labels: enhancement

#1961 [CHORE] [Repartitioning] Refactor + hide `PartitionSpec` and rename to `ClusteringSpec`.
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/repartition.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_ops/empty_scan.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/in_memory.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/test/mod.rs
Labels: chore

#1970 [CHORE] [Catalogs] [Delta Lake] Add test coverage for Delta Lake reads on Azure.
  .github/workflows/python-package.yml
  daft/daft.pyi
  daft/delta_lake/delta_lake_scan.py
  requirements-dev.txt
  src/common/io-config/src/azure.rs
  src/common/io-config/src/python.rs
  src/daft-io/src/azure_blob.rs
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/mock_s3_server.py
  tests/io/test_url_download_local.py
Labels: chore

#1991 [FEAT] [Catalogs] [Delta Lake] Add support for AWS Glue Catalog and Databricks Unity Catalog integrations to Delta Lake reader
  daft/__init__.py
  daft/io/__init__.py
  daft/io/_delta_lake.py
  daft/io/catalog.py
  pyproject.toml
  requirements-dev.txt
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/mock_aws_server.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
Labels: enhancement

#1999 [BUG] Filter out marker files from glob scan
  src/daft-io/src/object_store_glob.rs
  tests/integration/io/parquet/test_reads_s3_minio.py
Labels: bug

#2002 [CHORE] [Hotfix] Remove pyarrow upper bound for Windows.
  pyproject.toml
Labels: chore

#2008 [BUG] Fix struct getters on logical types
  src/daft-core/src/series/array_impl/logical_array.rs
  tests/table/struct/test_struct_get.py
Labels: bug

#1990 [FEAT] Support reading Parquet files with Field ID
  daft/daft.pyi
  daft/iceberg/iceberg_scan.py
  daft/iceberg/schema_field_id_mapping_visitor.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/integration/iceberg/docker-compose/provision.py
  tests/integration/iceberg/test_table_load.py
Labels: enhancement

#2006 [BUG] skip metadata check for field equality
  requirements-dev.txt
  src/daft-core/src/datatypes/field.rs
  tests/integration/iceberg/test_pyiceberg_written_table_load.py
Labels: bug

#2003 [FEAT] Add str.capitalize() function
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/capitalize.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_capitalize.py
Labels: enhancement

#2012 [DOCS] Fix stale docs in df.write_csv
  daft/dataframe/dataframe.py
Labels: documentation

#2000 [FEAT] Top level global expressions
  benchmarking/tpch/answers.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/logical/builder.py
  daft/series.py
  src/daft-core/src/python/series.rs
  src/daft-plan/src/builder.rs
  tests/benchmarks/test_groups_and_aggs.py
  tests/benchmarks/test_join.py
  tests/benchmarks/test_sort.py
  tests/cookbook/test_aggregations.py
  tests/cookbook/test_literals.py
  tests/cookbook/test_pandas_cookbook.py
  tests/dataframe/test_aggregations.py
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_aggs.py
  tests/table/test_table_aggs.py
Labels: enhancement

#1943 [FEAT] read_sql
  .github/workflows/python-package.yml
  daft/__init__.py
  daft/context.py
  daft/daft.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  daft/io/__init__.py
  daft/io/_sql.py
  daft/logical/schema.py
  daft/runners/partitioning.py
  daft/sql/__init__.py
  daft/sql/sql_reader.py
  daft/sql/sql_scan.py
  daft/table/table_io.py
  docs/source/api_docs/creation.rst
  docs/source/user_guide/basic_concepts/read-and-write.rst
  pyproject.toml
  requirements-dev.txt
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/schema.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/planner.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/integration/sql/__init__.py
  tests/integration/sql/conftest.py
  tests/integration/sql/docker-compose/docker-compose.yml
  tests/integration/sql/test_sql.py
  tests/io/test_csv_roundtrip.py
  tests/io/test_parquet_roundtrip.py
  tests/table/test_from_py.py
Labels: documentation, enhancement

#2013 [BUG] deltalake read pq splitting bug
  src/daft-micropartition/src/micropartition.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/io/delta_lake/test_table_read.py
Labels: bug

#2019 [BUG] Disable Numeric and String comparison
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/series/ops/is_in.rs
  src/daft-dsl/src/expr.rs
  tests/expressions/typing/test_compare.py
  tests/series/test_comparisons.py
  tests/table/test_is_in.py
Labels: bug

#2017 [BUG] Fix connector-x and psycopg dependencies for CI
  requirements-dev.txt
Labels: bug

#2022 [CHORE] Fix is_in docs
  docs/source/api_docs/expressions.rst
Labels: documentation, chore

#2018 [DOCS] [Hotfix] [Delta Lake] Break data skipping optimizations into different section.
  docs/source/user_guide/integrations/delta_lake.rst
Labels: documentation

#2024 [CHORE] Unskip tensor tests in test_parquet_roundtrip.py
  tests/io/test_parquet_roundtrip.py
Labels: chore

#2016 [FEAT] iceberg writes unpartitioned
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/table_io.py
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/physical_ops/iceberg_write.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/sink_info.rs
  tests/integration/iceberg/test_pyiceberg_written_table_load.py
  tests/io/iceberg/__init__.py
  tests/io/iceberg/test_iceberg_writes.py
Labels: enhancement

#2025 [CHORE] Add global aggregation docs and error on improper aggregation usage
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  src/daft-plan/src/builder.rs
Labels: documentation, chore

#2027 [FEAT] Add str.left() funtion
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/left.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_left.py
Labels: enhancement

#2020 [FEAT] Add str.extract() function
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/extract.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_extract.py
Labels: documentation, enhancement

#2029 [PERF] [Delta Lake] Add IO multithreading arg to `daft.read_delta_lake()`.
  daft/io/_delta_lake.py
Labels: performance

#2030 [CHORE] Exclude Twitter and LinkedIn from broken link checker
  .github/workflows/broken-link-checker.yml
Labels: chore

#2033 [FEAT] Allow passing on_error="null" to ignore decoding errors in image decode
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/image.rs
  src/daft-dsl/src/functions/image/decode.rs
  src/daft-dsl/src/functions/image/mod.rs
  src/daft-dsl/src/python.rs
  tests/series/test_image.py
Labels: enhancement

#2034 [BUG] Fix all-null ImageArray length issues
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/series/ops/downcast.rs
  tests/table/image/test_decode.py
Labels: bug

#2035 [FEAT] drop psutil in favor of our own tool
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/runners/pyrunner.py
  pyproject.toml
  src/common/system-info/Cargo.toml
  src/common/system-info/src/lib.rs
  src/lib.rs
  tests/test_resource_requests.py
Labels: enhancement

#2037 [FEAT] Sign expression implemtation
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/sign.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/sign.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/functions/numeric/sign.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: enhancement

#2038 [FEAT] Add str.extract_all expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/extract_all.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_extract_all.py
Labels: documentation, enhancement

#2042 [BUG] enable dependabot for iceberg int tests
  .github/workflows/python-package.yml
Labels: bug

#2043 [CHORE] upgrade upload/download artifact github action
  .github/workflows/daft-profiling.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
Labels: chore

#2015 [CHORE] Add column range stats from read_sql
  daft/daft.pyi
  daft/sql/sql_scan.py
  src/daft-scan/src/python.rs
Labels: chore

#2041 [FEAT] round expression implemtation
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/round.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/round.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/functions/numeric/round.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: enhancement

#2026 [CHORE] Add tpch test for read sql
  benchmarking/tpch/data_generation.py
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/sql/sql_reader.py
  daft/sql/sql_scan.py
  daft/table/table_io.py
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  tests/integration/sql/test_sql.py
  tests/integration/sql/test_sql_tpch.py
Labels: chore

#2047 [CHORE] Refactor sql tpch tests
  .github/workflows/python-package.yml
  tests/integration/conftest.py
  tests/integration/test_tpch.py
Labels: chore

#2049 [CHORE] Remove autouse from gen_tpch fixture
  tests/integration/conftest.py
Labels: chore

#2051 [BUG] Fix if_else series naming from predicate broadcast
  src/daft-core/src/array/ops/if_else.rs
  tests/table/test_if_else.py
Labels: bug

#2053 [DOCS] Add docs for write_iceberg
  docs/source/api_docs/dataframe.rst
Labels: documentation

#2054 [BUG] Allow for writes to s3a and s3n paths
  daft/filesystem.py
  tests/integration/io/test_write_files_s3_minio.py
Labels: bug
