Repository Eventual-Inc/Daft, pull requests merged in 2024-11, with the labels that each got.

#3155 [BUG] Separate PartitionTask done from results
  daft/execution/execution_step.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  tests/physical_plan/test_physical_plan_buffering.py
Labels: bug

#2487 Temporal docs added to expressions.rst
  docs/source/user_guide/expressions.rst
Labels: documentation

#3148 [FEAT] Add better detection of Ray Job environment
  daft/context.py
Labels: enhancement

#3164 [CHORE] Swordfish specific test fixtures
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/pivot.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  tests/conftest.py
  tests/cookbook/conftest.py
  tests/cookbook/test_aggregations.py
  tests/cookbook/test_computations.py
  tests/cookbook/test_count_rows.py
  tests/cookbook/test_dataloading.py
  tests/cookbook/test_distinct.py
  tests/cookbook/test_filter.py
  tests/cookbook/test_image.py
  tests/cookbook/test_joins.py
  tests/cookbook/test_pandas_cookbook.py
  tests/cookbook/test_sorting.py
  tests/cookbook/test_write.py
  tests/dataframe/test_aggregations.py
  tests/dataframe/test_approx_count_distinct.py
  tests/dataframe/test_concat.py
  tests/dataframe/test_distinct.py
  tests/dataframe/test_iter.py
  tests/dataframe/test_joins.py
  tests/dataframe/test_map_groups.py
  tests/dataframe/test_pivot.py
  tests/dataframe/test_sort.py
  tests/dataframe/test_stddev.py
  tests/dataframe/test_unpivot.py
Labels: chore

#3029 [FEAT] Support hive partitioned reads
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  src/common/error/src/error.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-plan/src/builder.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/hive.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  tests/io/test_hive_style_partitions.py
Labels: enhancement

#3161 [FEAT] Support null safe equal in joins
  daft/daft/__init__.pyi
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/table/micropartition.py
  src/daft-core/src/array/ops/arrow2/comparison.rs
  src/daft-core/src/utils/dyn_compare.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/python.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_optimization/rules/eliminate_cross_join.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/broadcast_join.rs
  src/daft-plan/src/physical_ops/hash_join.rs
  src/daft-plan/src/physical_optimization/rules/reorder_partition_keys.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/ops/groups.rs
  src/daft-table/src/ops/hash.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/probeable/mod.rs
  src/daft-table/src/probeable/probe_set.rs
  src/daft-table/src/probeable/probe_table.rs
  src/daft-table/src/python.rs
  tests/table/test_joins.py
Labels: enhancement

#3165 [FEAT] Infer Azure storage account from uri
  Cargo.lock
  Cargo.toml
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  tests/integration/io/parquet/test_reads_azure.py
Labels: enhancement

#3179 [CHORE] Add tests for decimal casting
  Cargo.lock
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/series/mod.rs
Labels: chore

#3177 [BUG]: Sql groupby and orderby with aliases and projections
  src/daft-sql/src/error.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: bug

#3160 [FEAT] Streaming Catalog Writes
  daft/daft/__init__.pyi
  daft/delta_lake/delta_lake_write.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/iceberg/iceberg_write.py
  daft/io/writer.py
  daft/logical/builder.py
  daft/table/table_io.py
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/sink_info.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-writers/src/catalog.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/python.rs
  tests/io/delta_lake/test_table_write.py
  tests/io/iceberg/test_iceberg_writes.py
Labels: enhancement

#3166 [FEAT] Support null equal safe join in SQL
  src/daft-plan/src/logical_optimization/rules/eliminate_cross_join.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_joins.py
Labels: enhancement

#3108 [FEAT] Overwrite mode for write parquet/csv
  daft/dataframe/dataframe.py
  daft/filesystem.py
  tests/io/test_write_modes.py
Labels: enhancement

#3188 [FEAT]: sql "extract" temporal function
  src/daft-sql/src/planner.rs
  tests/sql/test_temporal_exprs.py
Labels: documentation, enhancement

#3240 [DOCS] Update Iceberg roadmap on docs
  docs/source/user_guide/integrations/iceberg.rst
Labels: documentation

#3243 [CHORE] Fix flaky test in test_decimal_to_decimal_cast
  src/daft-core/src/array/ops/cast.rs
Labels: chore

#3178 [FEAT] Native Runner
  .github/workflows/python-package.yml
  Cargo.lock
  daft/context.py
  daft/io/writer.py
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  docs/source/user_guide/poweruser/partitioning.rst
  src/common/daft-config/Cargo.toml
  src/common/daft-config/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/dispatcher.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/empty_scan.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  tests/actor_pool/test_actor_cuda_devices.py
  tests/benchmarks/conftest.py
  tests/benchmarks/test_local_tpch.py
  tests/benchmarks/test_streaming_writes.py
  tests/conftest.py
  tests/cookbook/conftest.py
  tests/cookbook/test_joins.py
  tests/dataframe/test_joins.py
  tests/dataframe/test_monotonically_increasing_id.py
  tests/integration/io/test_s3_reads_include_path.py
  tests/io/delta_lake/test_table_write.py
  tests/io/iceberg/test_iceberg_writes.py
  tests/io/lancedb/test_lancedb_writes.py
  tests/io/test_write_modes.py
  tests/test_resource_requests.py
Labels: documentation, enhancement

#3159 [CHORE] implement mean and stddev for decimal
  src/daft-core/src/array/iterator.rs
  src/daft-core/src/array/ops/mean.rs
  src/daft-core/src/datatypes/agg_ops.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/agg/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-functions/src/list/mean.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  tests/dataframe/test_decimals.py
  tests/table/test_table_aggs.py
  tests/test_schema.py
Labels: chore

#2880 [DOCS] Changing docs for UDF
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/udf.py
  docs/source/api_docs/udf.rst
  tests/actor_pool/test_actor_cuda_devices.py
  tests/test_resource_requests.py
Labels: documentation

#3190 [BUG]: orderby with aggs
  src/daft-sql/src/planner.rs
  tests/sql/test_orderbys.py
  tests/sql/test_sql.py
Labels: bug

#3189 [FEAT] add spark-connect protocol
  Cargo.lock
  Cargo.toml
  src/generated/spark-connect/Cargo.toml
  src/generated/spark-connect/src/lib.rs
  src/scripts/spark-connect-generation/Cargo.lock
  src/scripts/spark-connect-generation/Cargo.toml
  src/scripts/spark-connect-generation/build.rs
  src/scripts/spark-connect-generation/proto/spark/connect/base.proto
  src/scripts/spark-connect-generation/proto/spark/connect/catalog.proto
  src/scripts/spark-connect-generation/proto/spark/connect/commands.proto
  src/scripts/spark-connect-generation/proto/spark/connect/common.proto
  src/scripts/spark-connect-generation/proto/spark/connect/example_plugins.proto
  src/scripts/spark-connect-generation/proto/spark/connect/expressions.proto
  src/scripts/spark-connect-generation/proto/spark/connect/relations.proto
  src/scripts/spark-connect-generation/proto/spark/connect/types.proto
  src/scripts/spark-connect-generation/src/main.rs
Labels: enhancement

#3113 [FEAT] Add tracing for runner
  daft/daft/__init__.pyi
  daft/runners/ray_metrics.py
  daft/runners/ray_runner.py
  daft/runners/ray_tracing.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
Labels: enhancement

#3252 [DOCS] Fix typo in write_parquet's parameters
  daft/dataframe/dataframe.py
Labels: documentation

#3253 [PERF] Harden GCP Retries
  Cargo.lock
  daft/daft/__init__.pyi
  src/common/io-config/Cargo.toml
  src/common/io-config/src/gcs.rs
  src/common/io-config/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/google_cloud.rs
  src/daft-sql/src/modules/config.rs
  tests/integration/io/parquet/test_reads_public_data.py
  tools/check_for_rustls.sh
Labels: performance

#3241 [FEAT]: Sql joins with duplicate cols
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/optimization/rules/eliminate_cross_join.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_joins.py
Labels: enhancement

#3261 [FEAT] Add initial Spark Connect support
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  requirements-dev.txt
  src/daft-connect/Cargo.toml
  src/daft-connect/src/config.rs
  src/daft-connect/src/err.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/main.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/util.rs
  src/daft-local-execution/src/lib.rs
  src/daft-table/src/lib.rs
  src/lib.rs
  src/scripts/spark-connect-generation/Cargo.lock
  tests/connect/__init__.py
  tests/connect/test_config_simple.py
Labels: enhancement

#3250 [CHORE] Remove daft-scan dependency from planning crates
  .github/workflows/python-package.yml
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/logical/builder.py
  src/common/io-config/Cargo.toml
  src/common/scan-info/Cargo.toml
  src/common/scan-info/src/expr_rewriter.rs
  src/common/scan-info/src/lib.rs
  src/common/scan-info/src/partitioning.rs
  src/common/scan-info/src/pushdowns.rs
  src/common/scan-info/src/python.rs
  src/common/scan-info/src/scan_operator.rs
  src/common/scan-info/src/scan_task.rs
  src/common/scan-info/src/test/mod.rs
  src/daft-dsl/Cargo.toml
  src/daft-functions-json/Cargo.toml
  src/daft-functions/Cargo.toml
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-plan/Cargo.toml
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/lib.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/source_info/mod.rs
  src/daft-logical-plan/src/test/mod.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/ops/scan.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/test/mod.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/builder.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/table_provider/mod.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  src/lib.rs
Labels: chore

#3258 [FEAT] Adds a `read_generator` method that reads tables from a generator
  daft/io/_generator.py
Labels: enhancement

#3269 [DOCS] Set canonical link
  docs/source/conf.py
Labels: documentation

#3271 [DOCS] Use an absolute path for the canonical link
  docs/source/conf.py
Labels: documentation

#3265 [CHORE]: remove daft-table dependency from daft-logical-plan
  .github/workflows/python-package.yml
  Cargo.lock
  daft/daft/__init__.pyi
  daft/io/file_path.py
  daft/runners/ray_runner.py
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/source_info/file_info.rs
  src/daft-table/Cargo.toml
  src/daft-table/src/lib.rs
  src/daft-table/src/python.rs
Labels: chore

#3134 [FEAT] Support intersect as a DataFrame API
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  tests/dataframe/test_intersect.py
Labels: enhancement

#3273 [BUG]: bad merge from intersect PR
  src/daft-logical-plan/src/ops/set_operations.rs
Labels: bug

#3267 [FEAT] implement range operation and data streaming
  Cargo.lock
  src/daft-connect/Cargo.toml
  src/daft-connect/src/command.rs
  src/daft-connect/src/convert.rs
  src/daft-connect/src/convert/data_conversion.rs
  src/daft-connect/src/convert/data_conversion/range.rs
  src/daft-connect/src/convert/formatting.rs
  src/daft-connect/src/convert/schema_conversion.rs
  src/daft-connect/src/err.rs
  src/daft-connect/src/lib.rs
  tests/connect/test_range_simple.py
Labels: enhancement

#3246 [CHORE] Expose read_sql partition bound strategy and default to min-max
  daft/io/_sql.py
  daft/sql/sql_scan.py
  tests/integration/sql/test_sql.py
Labels: chore

#3270 [BUG] Cleanup context side-effects
  benchmarking/tpch/__main__.py
  daft/analytics.py
  daft/context.py
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/expressions/expressions.py
  daft/io/_deltalake.py
  daft/io/_hudi.py
  daft/io/_iceberg.py
  daft/io/_parquet.py
  daft/io/file_path.py
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  daft/utils.py
  tests/actor_pool/test_actor_cuda_devices.py
  tests/actor_pool/test_pyactor_pool.py
  tests/benchmarks/test_local_tpch.py
  tests/conftest.py
  tests/cookbook/conftest.py
  tests/cookbook/test_joins.py
  tests/dataframe/test_iter.py
  tests/dataframe/test_joins.py
  tests/dataframe/test_monotonically_increasing_id.py
  tests/io/delta_lake/test_table_write.py
  tests/io/iceberg/test_iceberg_writes.py
  tests/io/lancedb/test_lancedb_writes.py
  tests/microbenchmarks/test_file_read.py
  tests/ray/runner.py
  tests/ray/test_dask.py
  tests/ray/test_datasets.py
  tests/series/test_concat.py
  tests/series/test_filter.py
  tests/series/test_if_else.py
  tests/series/test_size_bytes.py
  tests/series/test_take.py
  tests/table/test_from_py.py
  tests/test_analytics.py
  tests/test_resource_requests.py
  tests/udf_library/test_url_udfs.py
Labels: bug

#3149 [FEAT] Minimal indices dtype for FixedShapeSparseTensors
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/sparse_tensor.rs
  src/daft-schema/src/dtype.rs
  tests/series/test_cast.py
  tests/series/test_sparse_tensor.py
Labels: documentation, enhancement

#3275 [BUG] Always run telemetry codepath
  daft/__init__.py
  daft/analytics.py
  tests/test_analytics.py
  tests/test_context.py
Labels: bug

#3276 [CHORE] Remove the concept of runner configs
  benchmarking/tpch/__main__.py
  daft/context.py
  daft/runners/ray_runner.py
  tests/test_context.py
Labels: chore

#3279 [CHORE] add daftrunner env to install and test step
  .github/workflows/python-publish.yml
Labels: chore

#3191 [FEAT] Pre Shuffle Merge Strategy
  daft/context.py
  daft/daft/__init__.pyi
  daft/execution/shuffles/pre_shuffle_merge.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-physical-plan/src/ops/shuffle_exchange.rs
  src/daft-physical-plan/src/optimization/rules/drop_repartition.rs
  src/daft-physical-plan/src/optimization/rules/reorder_partition_keys.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
  tests/dataframe/test_shuffles.py
Labels: enhancement

#3283 [CHORE] Allow manual launch of release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#3284 [CHORE] Fix style in workflow file
  .github/workflows/release-drafter.yml
Labels: chore

#3274 [FEAT] SQL union/union all and sql intersect
  src/daft-core/src/utils/supertype.rs
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-sql/src/planner.rs
  tests/sql/set_ops.py
Labels: enhancement

#3272 [CHORE]: defer Expr subquery error until eval
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/optimization.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-sql/src/planner.rs
  src/daft-table/Cargo.toml
  src/daft-table/src/lib.rs
  src/parquet2/src/schema/io_message/from_message.rs
Labels: chore

#3291 [BUG]: panic in sql subquery
  src/daft-sql/src/planner.rs
Labels: bug

#3278 [BUG] Fix writes for empty dataframes if target directory does not exist
  daft/filesystem.py
  daft/table/table_io.py
  tests/cookbook/test_write.py
  tests/io/test_write_modes.py
Labels: bug

#3281 [CHORE] Possibility to create environment with system installed uv
  Makefile
Labels: chore

#3298 [DOCS] Update incomplete SQL doc pages
  src/daft-sql/src/modules/config.rs
  src/daft-sql/src/modules/hashing.rs
  src/daft-sql/src/modules/utf8.rs
Labels: documentation

#3297 [BUG] Check env in benchmarking script
  benchmarking/tpch/__main__.py
Labels: bug

#3296 [FEAT] Support for aggregation expressions that use multiple AggExprs
  Cargo.lock
  Cargo.toml
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/resolve_expr/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-plan/src/plan.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/actor_pool_project.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/explode.rs
  src/daft-logical-plan/src/ops/filter.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/pivot.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/ops/repartition.rs
  src/daft-logical-plan/src/ops/sink.rs
  src/daft-logical-plan/src/ops/sort.rs
  src/daft-logical-plan/src/ops/unpivot.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/lift_project_from_agg.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/physical_planner/mod.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
  tests/dataframe/test_aggregations.py
Labels: enhancement

#3295 [CHORE]: better subquery handling
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/optimization.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/lib.rs
Labels: chore

#3290 [BUG] Partially qualified joins `join a.x = y` and `join x = b.y`
  benchmarking/tpcds/queries/72.sql
  daft/dataframe/dataframe.py
  src/daft-sql/src/planner.rs
  tests/sql/test_joins.py
Labels: bug

#3299 [FEAT] Lance writes for swordfish
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-writers/src/catalog.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/physical.rs
  src/daft-writers/src/pyarrow.rs
  tests/io/lancedb/test_lancedb_writes.py
Labels: enhancement

#3256 [CHORE] Swordfish refactors
  Cargo.lock
  src/common/runtime/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/dispatcher.rs
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/explode.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/intermediate_ops/unpivot.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-execution/src/sources/source.rs
Labels: chore

#3303 [DOCS] Fix typo in limit example
  daft/dataframe/dataframe.py
Labels: documentation

#3294 [FEAT]: allow `is_in` to take in `Vec<Expr>` instead of `Expr`
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-core/src/series/ops/concat.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/lib.rs
  tests/sql/test_exprs.py
Labels: enhancement

#3036 [FEAT] Daft Catalog API
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/catalog/__init__.py
  daft/catalog/pyiceberg.py
  daft/catalog/python_catalog.py
  daft/catalog/unity.py
  daft/daft/catalog.pyi
  daft/io/catalog.py
  src/common/error/src/error.rs
  src/daft-catalog/Cargo.toml
  src/daft-catalog/python-catalog/Cargo.toml
  src/daft-catalog/python-catalog/src/lib.rs
  src/daft-catalog/python-catalog/src/python.rs
  src/daft-catalog/src/data_catalog.rs
  src/daft-catalog/src/data_catalog_table.rs
  src/daft-catalog/src/errors.rs
  src/daft-catalog/src/lib.rs
  src/daft-catalog/src/python.rs
  src/lib.rs
  tests/integration/iceberg/conftest.py
  tests/integration/iceberg/test_cloud_load.py
  tests/integration/iceberg/test_partition_pruning.py
  tests/integration/iceberg/test_pyiceberg_written_table_load.py
  tests/integration/iceberg/test_table_load.py
Labels: enhancement

#3306 [BUG] Fixes regexp_replace expression
  src/daft-sql/src/modules/utf8.rs
  tests/sql/test_utf8_exprs.py
Labels: bug

#3255 [FEAT]: SQL read_csv
  .pre-commit-config.yaml
  src/daft-scan/src/builder.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/table_provider/mod.rs
  src/daft-sql/src/table_provider/read_csv.rs
  tests/assets/mvp.csv
  tests/sql/test_table_funcs.py
Labels: enhancement

#3333 [BUG]: tbl alias with join
  src/daft-sql/src/planner.rs
  tests/sql/test_joins.py
Labels: bug

#3304 [FEAT] Support for correlated subqueries in SQL (not yet executable)
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/optimization.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-schema/src/schema.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/table_provider/mod.rs
  src/daft-table/src/lib.rs
Labels: enhancement

#3335 [CHORE] Fix join alias test
  tests/sql/test_joins.py
Labels: chore

#3301 [CHORE]: prepare for nulls first/last kernels
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/expressions/expressions.py
  daft/logical/builder.py
  daft/series.py
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-core/src/series/ops/sort.rs
  src/daft-core/src/series/series_like.rs
  src/daft-core/src/utils/mod.rs
  src/daft-functions/src/list/sort.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/sort.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-micropartition/src/ops/sort.rs
  src/daft-micropartition/src/python.rs
  src/daft-physical-plan/src/ops/sort.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/modules/list.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/ops/groups.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/ops/sort.rs
  src/daft-table/src/python.rs
Labels: chore

#3180 [FEAT] Monotonically Increasing Id for Swordfish
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/monotonically_increasing_id.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-micropartition/src/python.rs
  tests/dataframe/test_monotonically_increasing_id.py
Labels: enhancement

#3308 [FEAT] daft-connect range use python generator
  Cargo.lock
  Cargo.toml
  daft/io/_range.py
  src/daft-connect/Cargo.toml
  src/daft-connect/src/convert.rs
  src/daft-connect/src/convert/data_conversion.rs
  src/daft-connect/src/convert/data_conversion/range.rs
  src/daft-connect/src/convert/formatting.rs
  src/daft-connect/src/err.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/main.rs
  src/daft-connect/src/op.rs
  src/daft-connect/src/op/execute.rs
  src/daft-connect/src/op/execute/root.rs
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-micropartition/Cargo.toml
  tests/connect/test_range_simple.py
  xyz
Labels: enhancement

#3337 [FEAT]: allow for implicit coercion between str & date
  src/daft-core/src/datatypes/infer_datatype.rs
  tests/dataframe/test_temporals.py
  tests/sql/test_temporal_exprs.py
Labels: enhancement

#3339 [BUG] Implement deserialize for Python objects serialized as sequences
  src/common/py-serde/src/python.rs
  tests/io/test_s3_credentials_refresh.py
Labels: bug

#3341 [FEAT] consolidate Spark session fixture into conftest.py
  Cargo.lock
  daft/daft/__init__.pyi
  src/daft-connect/Cargo.toml
  src/daft-connect/src/lib.rs
  tests/connect/__init__.py
  tests/connect/conftest.py
  tests/connect/test_config_simple.py
  tests/connect/test_range_simple.py
Labels: enhancement

#3370 [CHORE] delete empty file xyz
  xyz
Labels: chore

#3326 [FEAT] connect: collect
  tests/connect/test_collect.py
Labels: enhancement

#3378 [CHORE] connect: Optimize plans in connect
  Cargo.lock
  src/daft-connect/Cargo.toml
  src/daft-connect/src/op/execute/root.rs
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/run.rs
  src/daft-logical-plan/src/builder.rs
Labels: chore

#3371 [FEAT] Filter predicates in SQL join
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
Labels: enhancement

#3342 [FEAT] connect: add alias support
  Cargo.lock
  Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/lib.rs
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/datatype.rs
  src/daft-connect/src/translation/expr.rs
  src/daft-connect/src/translation/expr/unresolved_function.rs
  src/daft-connect/src/translation/literal.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/project.rs
  src/daft-connect/src/translation/logical_plan/range.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-dsl/src/lit.rs
  tests/connect/test_alias.py
Labels: enhancement

#3355 [FEAT] connect: `to_daft_*` use ref instead of value
  src/daft-connect/src/translation/expr.rs
  src/daft-connect/src/translation/expr/unresolved_function.rs
  src/daft-connect/src/translation/literal.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/project.rs
Labels: enhancement

#3309 [FEAT] connect: add `df.limit` and `df.first`
  src/daft-connect/src/translation/logical_plan.rs
  tests/connect/test_limit_simple.py
Labels: enhancement

#3344 [FEAT] connect: Add support for `select`
  tests/connect/test_select.py
Labels: enhancement

#3392 [CHORE] Add TPC-H queries in SQL
  benchmarking/tpch/queries/01.sql
  benchmarking/tpch/queries/02.sql
  benchmarking/tpch/queries/03.sql
  benchmarking/tpch/queries/04.sql
  benchmarking/tpch/queries/05.sql
  benchmarking/tpch/queries/06.sql
  benchmarking/tpch/queries/07.sql
  benchmarking/tpch/queries/08.sql
  benchmarking/tpch/queries/09.sql
  benchmarking/tpch/queries/10.sql
  benchmarking/tpch/queries/11.sql
  benchmarking/tpch/queries/12.sql
  benchmarking/tpch/queries/13.sql
  benchmarking/tpch/queries/14.sql
  benchmarking/tpch/queries/15.sql
  benchmarking/tpch/queries/16.sql
  benchmarking/tpch/queries/17.sql
  benchmarking/tpch/queries/18.sql
  benchmarking/tpch/queries/19.sql
  benchmarking/tpch/queries/20.sql
  benchmarking/tpch/queries/21.sql
  benchmarking/tpch/queries/22.sql
Labels: chore

#3398 [FEAT] Build release python wheels and upload to AWS S3
  .github/actions/install/action.yaml
  .github/workflows/build-commit.yaml
Labels: enhancement

#3399 [FEAT] Enable group by keys in aggregation expressions
  src/daft-dsl/src/resolve_expr/mod.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/pivot.rs
  tests/dataframe/test_aggregations.py
Labels: enhancement

#3400 [CHORE] Change IOConfig to be serialized into binary instead of JSON
  Cargo.lock
  daft/daft/__init__.pyi
  daft/io/config.py
  src/common/io-config/Cargo.toml
  src/common/io-config/src/python.rs
Labels: chore

#3402 [FEAT] Create new run workflow
  .github/workflows/run-command-on-ray.yaml
Labels: enhancement

#3385 [CHORE] connect: add tests for `df.take()` method
  tests/connect/test_take.py
Labels: enhancement, chore

#3403 [FEAT] Add steps to spin up, submit job, and spin down ray clusters
  .github/assets/benchmarking_ray_config.yaml
  .github/workflows/build-commit.yaml
  .github/workflows/run-cluster.yaml
  .github/workflows/run-command-on-ray.yaml
Labels: enhancement

#3404 [FEAT] Add ability to run arbitrary command on a set working directory
  .github/workflows/run-cluster.yaml
  .github/working-dir/README.md
  .github/working-dir/simple.py
Labels: enhancement

#3406 [FEAT] Add ability to download log files from ray-cluster
  .github/workflows/run-cluster.yaml
Labels: enhancement

#3409 [FEAT] Get native execution enablement from DAFT_RUNNER
  src/common/daft-config/src/lib.rs
Labels: enhancement

#3401 [CHORE] Cleanup ExprResolver
  src/daft-dsl/src/resolve_expr/mod.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/pivot.rs
Labels: chore

#3422 [BUG] Fix run-cluster passing in environment variables wrongly
  .github/workflows/run-cluster.yaml
Labels: bug

#3427 [BUG] Terminate nodes instead of stopping them
  .github/assets/benchmarking_ray_config.yaml
  .github/workflows/run-cluster.yaml
Labels: bug

#3430 [BUG] Replace semicolons in filenames with underscore
  .github/workflows/run-cluster.yaml
Labels: bug

#3431 [CHORE] Update execution config to turn on Ray tracing
  daft/context.py
Labels: chore

#3353 [CHORE] connect: `df.schema`
  tests/connect/test_schema.py
Labels: enhancement, chore

#3428 [DOCS] Add missing list expression entries
  docs/source/api_docs/expressions.rst
Labels: documentation

#3442 [CHORE] Explain block_on function in common-runtime
  src/common/runtime/src/lib.rs
Labels: chore

#3432 [FEAT] migrate schema inference → async, block at py boundary
  Cargo.lock
  Cargo.toml
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/python.rs
  src/daft-json/src/python.rs
  src/daft-json/src/schema.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/builder.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/table_provider/read_csv.rs
  src/daft-sql/src/table_provider/read_parquet.rs
Labels: enhancement

#3445 [CHORE] Put empty table when building probe table
  src/daft-local-execution/src/sinks/hash_join_build.rs
  tests/dataframe/test_joins.py
Labels: chore

#3446 [CHORE] Add schemas for remaining local plan ops
  src/daft-local-plan/src/plan.rs
Labels: chore

#3429 [CHORE] Remove CountMode and ResourceRequest from public API
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  src/daft-core/src/count_mode.rs
Labels: chore

#3448 [FEAT] add pyiceberg 0.8.0 support
  daft/dataframe/dataframe.py
  pyproject.toml
Labels: enhancement

#3451 [BUG] Include storage options in lance write commit
  daft/dataframe/dataframe.py
  tests/integration/io/conftest.py
  tests/io/lancedb/test_lancedb_writes.py
Labels: bug

#3449 [DOCS] Shorten union of Literals
  daft/.ruff.toml
  daft/context.py
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/filesystem.py
  daft/runners/runner.py
  daft/series.py
  daft/table/table.py
  daft/udf_library/url_udfs.py
Labels: documentation

#3453 [BUG] Explicitly set IO config in unity catalog load table
  daft/unity_catalog/unity_catalog.py
Labels: bug

#3436 [BUG] Remove enum imports from match statements
  src/daft-core/src/datatypes/matching.rs
Labels: bug

#3456 [BUG] Fix extension type display
  src/daft-schema/src/dtype.rs
Labels: bug
