Repository Eventual-Inc/Daft, pull requests merged in 2024-02, with the labels that each got.

#1816 [DOCS] Refactor expressions docs layout
  daft/__init__.py
  daft/dataframe/__init__.py
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  docs/source/api_docs/configs.rst
  docs/source/api_docs/creation.rst
  docs/source/api_docs/dataframe.rst
  docs/source/api_docs/datatype.rst
  docs/source/api_docs/datatype_image_mode/daft.ImageMode.from_mode_string.rst
  docs/source/api_docs/datatype_image_mode/daft.ImageMode.rst
  docs/source/api_docs/datetype_image_format/daft.ImageFormat.from_format_string.rst
  docs/source/api_docs/datetype_image_format/daft.ImageFormat.rst
  docs/source/api_docs/expressions.rst
  docs/source/api_docs/groupby.rst
  docs/source/api_docs/index.rst
  docs/source/api_docs/io_configs.rst
  docs/source/api_docs/series.rst
  docs/source/api_docs/series/daft.Series.rst
  docs/source/conf.py
  docs/source/user_guide/daft_in_depth/datatypes.rst
  requirements-dev.txt
Labels: documentation

#1830 [DOCS] Add dedicated Iceberg page
  docs/source/user_guide/cheatsheet.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/data_catalogs.rst
  docs/source/user_guide/integrations/iceberg.rst
Labels: documentation

#1825 [FEAT] Add group_by.map_groups
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/treenode.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/planner.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/agg.rs
  tests/cookbook/conftest.py
  tests/cookbook/test_aggregations.py
  tests/dataframe/test_map_groups.py
Labels: enhancement

#1835 [DOCS] Add type conversions between iceberg and daft
  docs/source/user_guide/integrations/iceberg.rst
Labels: documentation

#1842 [CHORE] Remove empty line from map_groups docstring
  daft/dataframe/dataframe.py
Labels: chore

#1833 [BUG] Fix empty struct fields
  daft/arrow_utils.py
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/ffi.rs
  src/daft-json/src/inference.rs
  tests/dataframe/test_creation.py
  tests/dataframe/test_repr.py
  tests/table/test_from_py.py
Labels: bug

#1832 [BUG] Incorrect expression naming for struct get
  src/daft-dsl/src/expr.rs
Labels: bug

#1841 [BUG] [Parquet] Fix double-await on `JoinHandle`s concurrency bug in Parquet reader.
  src/common/io-config/src/s3.rs
  src/daft-io/src/lib.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/read_planner.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: bug

#1799 [PERF] Split parquet scan tasks into individual row groups
  daft/context.py
  daft/daft.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/src/planner.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-scan/src/storage_config.rs
  tests/conftest.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/io/test_merge_scan_tasks.py
Labels: performance

#1850 [BUG] Scan Operator Fix + Physical Plan Scan Task Summary
  src/daft-core/src/schema.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
Labels: bug

#1851 [DOCS] Add docs for Azure IO
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/microsoft-azure.rst
Labels: documentation

#1827 [FEAT] _add_monotonically_increasing_id method for Dataframe
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/logical/builder.py
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_ops/monotonically_increasing_id.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/monotonically_increasing_id.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/python.rs
  tests/dataframe/test_monotonically_increasing_id.py
  tests/table/test_monotonically_increasing_id.py
Labels: enhancement

#1853 [CHORE] Fix monotonically_increasing_id physical op
  src/daft-plan/src/physical_ops/monotonically_increasing_id.rs
  src/daft-plan/src/physical_plan.rs
Labels: chore

#1855 [DOCS] Add docs for AWS S3 IO
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/aws.rst
Labels: documentation

#1845 [BUG] Schema hints not working properly for json reads
  src/daft-micropartition/src/micropartition.rs
  tests/dataframe/test_creation.py
Labels: bug

#1857 [BUG] Protect Global Context With Mutex
  daft/context.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
Labels: bug

#1856 [FEAT] Enable Requester Pay for S3 reads
  daft/daft.pyi
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#1870 [CHORE] Update segment logging to use restricted set of IDs
  daft/analytics.py
Labels: chore

#1868 [FEAT] show full schema on request
  daft/daft.pyi
  daft/logical/schema.py
  daft/viz/dataframe_display.py
  src/daft-core/src/python/schema.rs
  src/daft-core/src/schema.rs
  src/daft-core/src/utils/display_table.rs
  tests/dataframe/test_repr.py
  tests/test_schema.py
Labels: enhancement

#1875 [DOCS] Drop use of "Complex Data" in favor of multimodal
  README.rst
  docs/source/_static/dataframe-comp-table.csv
  docs/source/faq/dataframe_comparison.rst
  docs/source/index.rst
  docs/source/user_guide/basic_concepts/introduction.rst
  docs/source/user_guide/daft_in_depth/datatypes.rst
  pyproject.toml
Labels: documentation

#1861 [PERF] Set min_partitions for post aggregation shuffles
  daft/context.py
  daft/daft.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/src/planner.rs
  tests/dataframe/test_aggregations.py
Labels: performance

#1874 [DOCS] Change show_optimized kwarg to show_all
  docs/source/user_guide/basic_concepts/dataframe_introduction.rst
  tutorials/image_querying/top_n_red_color.ipynb
  tutorials/intro.ipynb
Labels: documentation

#1880 [CHORE] Left-align headers in reprs
  src/daft-core/src/schema.rs
  src/daft-table/src/lib.rs
  tests/dataframe/test_repr.py
Labels: chore

#1882 [BUG] Fix bug with merge tasks that allows for tasks larger than max size allowed
  src/daft-scan/src/scan_task_iters.rs
  tests/io/test_merge_scan_tasks.py
Labels: bug

#1886 [BUG] Attempt to skip IMDS if region or credentials are provided
  src/daft-io/src/s3_like.rs
Labels: bug

#1887 [DOCS] Improve .str.concat docs
  daft/expressions/expressions.py
Labels: documentation

#1884 [BUG] Fix Ray autoscaling from zero worker CPUs
  daft/runners/ray_runner.py
Labels: bug

#1888 [BUG] dont create dirs if non local fs
  daft/table/table_io.py
Labels: bug

#1891 [FEAT] perform head operation instead of list when given a file without regex or /
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_store_glob.rs
  tests/integration/io/test_list_files_http.py
Labels: enhancement

#1897 [PERF] Parallel glob
  src/daft-scan/src/glob.rs
Labels: performance

#1902 [CHORE] Update segment endpoint
  daft/analytics.py
Labels: chore

#1889 [CHORE] Populate previews only when show() or __repr__() is called
  daft/dataframe/dataframe.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  tests/cookbook/test_write.py
  tests/dataframe/test_decimals.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_show.py
  tests/dataframe/test_temporals.py
Labels: chore

#1935 [DOCS] Update schema hints documentation
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
Labels: documentation

#1896 [DOCS] Add documentation for using and developing Daft on Ray
  CONTRIBUTING.md
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/ray.rst
Labels: documentation

#1942 [FEAT] Add str.upper() function
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/upper.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_upper.py
Labels: enhancement

#1944 [FEAT] Add str.lstrip() and str.rstrip() functions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/lstrip.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/rstrip.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_lstrip.py
  tests/table/utf8/test_rstrip.py
Labels: enhancement

#1892 [FEAT] Time Array
  daft/daft.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/date.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/hash.rs
  src/daft-core/src/series/serdes.rs
  src/daft-core/src/utils/display_table.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/conftest.py
  tests/io/test_csv_roundtrip.py
  tests/io/test_parquet_roundtrip.py
  tests/series/test_cast.py
  tests/series/test_hash.py
  tests/series/test_size_bytes.py
  tests/series/test_sort.py
  tests/series/test_take.py
  tests/table/test_from_py.py
Labels: enhancement

#1946 [CHORE] Remove non-`MicroPartition` and non-`ScanOperator` paths
  .github/workflows/python-package.yml
  daft/daft.pyi
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/io/_csv.py
  daft/io/_iceberg.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  daft/logical/builder.py
  daft/logical/schema.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner_io.py
  daft/table/__init__.py
  src/daft-core/src/python/schema.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/optimization/logical_plan_tracker.rs
  src/daft-plan/src/optimization/mod.rs
  src/daft-plan/src/optimization/optimizer.rs
  src/daft-plan/src/optimization/rules/drop_repartition.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/optimization/rules/push_down_limit.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/optimization/test/mod.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-plan/src/test/mod.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  tests/dataframe/test_creation.py
  tests/integration/io/parquet/test_reads_s3_minio.py
  tests/io/test_merge_scan_tasks.py
Labels: chore

#1951 [DOCS] Fix notebooks by falling back on null for URL downloads
  tutorials/text_to_image/using_cloud_with_ray.ipynb
Labels: documentation

#1950 [PERF] Spread scan tasks over Ray cluster.
  daft/execution/execution_step.py
  daft/execution/rust_physical_plan_shim.py
  daft/runners/ray_runner.py
Labels: performance

#1901 [PERF] scan task in memory estimate
  Cargo.lock
  daft/daft.pyi
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/schema.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-stats/src/lib.rs
  src/daft-stats/src/table_stats.rs
Labels: performance

#1960 [FEAT] adding floor function
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/floor.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/floor.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/functions/numeric/floor.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: enhancement

#1941 [FEAT] `any_value` groupby aggregation
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/logical/builder.py
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/treenode.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/planner.rs
  src/daft-table/src/lib.rs
  tests/table/test_table_aggs.py
Labels: enhancement
