Repository Eventual-Inc/Daft, pull requests merged in 2024-09, with the labels that each got.

#2771 [CHORE] Add check for stateful UDF outside of project
  daft/daft.pyi
  daft/dataframe/dataframe.py
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/resolve_expr.rs
  src/daft-plan/src/logical_ops/actor_pool_project.rs
  src/daft-plan/src/logical_ops/agg.rs
  src/daft-plan/src/logical_ops/explode.rs
  src/daft-plan/src/logical_ops/filter.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_ops/pivot.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_ops/repartition.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/logical_ops/sort.rs
  src/daft-plan/src/logical_ops/unpivot.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
Labels: chore

#2781 [CHORE] Rename vpartition -> micropartition
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/native_executor.py
  daft/execution/physical_plan.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
Labels: chore

#2764 [FEAT]: sql image_encode and image_resize
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/from_iter.rs
  src/daft-dsl/src/functions/image/encode.rs
  src/daft-dsl/src/functions/image/mod.rs
  src/daft-dsl/src/functions/image/resize.rs
  src/daft-dsl/src/functions/image/to_mode.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/image/crop.rs
  src/daft-functions/src/image/encode.rs
  src/daft-functions/src/image/mod.rs
  src/daft-functions/src/image/resize.rs
  src/daft-functions/src/image/to_mode.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/image.rs
  src/daft-sql/src/modules/image/crop.rs
  src/daft-sql/src/modules/image/decode.rs
  src/daft-sql/src/modules/image/encode.rs
  src/daft-sql/src/modules/image/mod.rs
  src/daft-sql/src/modules/image/resize.rs
  src/daft-sql/src/modules/image/to_mode.rs
  src/daft-sql/src/planner.rs
Labels: enhancement

#2785 [CHORE] Implement thiserror::Error for DaftError and arrow2::Error
  Cargo.lock
  Cargo.toml
  src/arrow2/Cargo.toml
  src/arrow2/src/error.rs
  src/common/error/Cargo.toml
  src/common/error/src/error.rs
  src/common/error/src/python.rs
  src/daft-core/src/array/ops/utf8.rs
  src/parquet2/Cargo.toml
  src/parquet2/src/error.rs
  tests/table/json/test_json_query.py
Labels: chore

#2792 [CHORE] Enable all targets for cargo check
  .pre-commit-config.yaml
Labels: chore

#2677 [FEAT] Add runner logic in PyRunner for ActorPoolProject
  daft/daft.pyi
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/expressions/expressions.py
  daft/pickle/cloudpickle.py
  daft/pickle/cloudpickle_fast.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  src/common/resource-request/src/lib.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/functions/python/udf_runtime_binding.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
  src/daft-scheduler/src/scheduler.rs
  tests/actor_pool/__init__.py
  tests/actor_pool/test_pyactor_pool.py
Labels: enhancement

#2790 [BUG] Groupby with alias not working
  src/daft-plan/src/physical_planner/translate.rs
  tests/dataframe/test_aggregations.py
  tests/dataframe/test_approx_percentiles_aggregations.py
  tests/dataframe/test_map_groups.py
Labels: bug

#2775 [FEAT] Adds str.length_bytes() function
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/length_bytes.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-sql/src/modules/utf8.rs
  tests/series/test_utf8_ops.py
Labels: documentation, enhancement

#2797 [CHORE] Use treenode for tree traversal in logical optimizer rules
  src/common/treenode/src/lib.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/mod.rs
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/drop_repartition.rs
  src/daft-plan/src/logical_optimization/rules/mod.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/rule.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
  src/daft-plan/src/logical_optimization/test/mod.rs
Labels: chore

#2800 [BUG] Propogate S3Config.num_tries to pyarrow S3 filesystem
  daft/filesystem.py
Labels: bug

#2801 [DOCS] Casting matrix
  daft/expressions/expressions.py
  tests/series/test_cast.py
Labels: documentation

#2805 [DOCS] Add grouping and aggregation docs
  daft/dataframe/dataframe.py
  docs/source/api_docs/expressions.rst
  docs/source/user_guide/daft_in_depth/aggregations.rst
Labels: documentation

#2802 [CHORE] Remove user-facing arguments for casting to Ray's tensor type
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/runners/partitioning.py
  daft/runners/ray_runner.py
  daft/series.py
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-core/src/python/datatype.rs
  tests/dataframe/test_creation.py
Labels: chore

#2811 [DOCS] Fix documentation errors
  docs/source/10-min.ipynb
  docs/source/migration_guides/coming_from_dask.rst
  docs/source/user_guide/fotw/fotw-001-images.ipynb
  docs/source/user_guide/fotw/index.rst
Labels: documentation

#2812 [BUG] Perform cleanup of tasks and results when iterator is deleted
  daft/runners/pyrunner.py
Labels: bug

#2803 [DOCS] Enable hosted docs preview
  .github/workflows/build-docs.yml
  .github/workflows/python-package.yml
Labels: documentation

#2814 [CHORE] Update netlify publishing
  .github/workflows/build-docs.yml
Labels: documentation, chore

#2780 [PERF] Use to_arrow_iter in to_arrow to avoid unnecessary array concats
  daft/dataframe/dataframe.py
  src/daft-core/src/ffi.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/schema.rs
Labels: performance

#2799 [FEAT] [SQL] Add global agg support for SQL
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: enhancement

#2809 [FEAT] Ellipsize glob scan paths
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
Labels: enhancement

#2794 [CHORE] Add `derive_more` to get rid of manual `Display` impls
  Cargo.lock
  Cargo.toml
  daft/expressions/expressions.py
  src/common/display/src/table_display.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/count_mode.rs
  src/daft-core/src/join.rs
  src/daft-core/src/series/mod.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-schema/Cargo.toml
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/field.rs
  src/daft-schema/src/image_format.rs
  src/daft-schema/src/image_mode.rs
  src/daft-schema/src/schema.rs
  src/daft-schema/src/time_unit.rs
  tests/series/test_tensor.py
Labels: chore

#2819 [CHORE] Remove enum imports daft core
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/trigonometry.rs
  src/daft-core/src/count_mode.rs
  src/daft-core/src/datatypes/agg_ops.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/join.rs
  src/daft-core/src/kernels/hashing.rs
  src/daft-core/src/kernels/search_sorted.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/ops/abs.rs
  src/daft-core/src/series/ops/ceil.rs
  src/daft-core/src/series/ops/exp.rs
  src/daft-core/src/series/ops/floor.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-core/src/series/ops/log.rs
  src/daft-core/src/series/ops/round.rs
  src/daft-core/src/series/ops/sign.rs
  src/daft-core/src/series/serdes.rs
  src/daft-core/src/utils/supertype.rs
Labels: chore

#2823 [DOCS] Trigger the workflow after PR Labeler runs
  .github/workflows/build-docs.yml
Labels: documentation

#2813 [CHORE] Break daft-plan/daft-scheduler dependency on daft-io
  Cargo.lock
  Cargo.toml
  src/common/file-formats/Cargo.toml
  src/common/file-formats/src/file_format.rs
  src/common/file-formats/src/file_format_config.rs
  src/common/file-formats/src/lib.rs
  src/common/file-formats/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/sink_info.rs
  src/daft-plan/src/test/mod.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
  src/lib.rs
Labels: chore

#2821 [DOCS] Add docs to hash and hash to docs
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
Labels: documentation

#2820 [CHORE] Cleanup display impls - follow-up PR
  daft/expressions/expressions.py
  src/common/display/src/table_display.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/field.rs
  src/daft-schema/src/schema.rs
  tests/series/test_tensor.py
Labels: chore

#2804 [CHORE]: Move image kernel out of daft-core
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/daft/image.pyi
  daft/series.py
  src/common/display/src/table_display.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/image_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/image.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/take.rs
  src/daft-core/src/series/series_like.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/image/crop.rs
  src/daft-functions/src/image/decode.rs
  src/daft-functions/src/image/encode.rs
  src/daft-functions/src/image/resize.rs
  src/daft-functions/src/image/to_mode.rs
  src/daft-image/Cargo.toml
  src/daft-image/src/counting_writer.rs
  src/daft-image/src/image_buffer.rs
  src/daft-image/src/iters.rs
  src/daft-image/src/lib.rs
  src/daft-image/src/ops.rs
  src/daft-image/src/python.rs
  src/daft-image/src/series.rs
  src/daft-table/Cargo.toml
  src/daft-table/src/lib.rs
  src/daft-table/src/repr_html.rs
  src/lib.rs
Labels: chore

#2793 [CHORE] Update PyO3 and use their new Bound API
  Cargo.lock
  Cargo.toml
  src/common/arrow-ffi/src/lib.rs
  src/common/daft-config/Cargo.toml
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/common/file-formats/src/file_format_config.rs
  src/common/file-formats/src/python.rs
  src/common/io-config/src/python.rs
  src/common/py-serde/src/python.rs
  src/common/resource-request/src/lib.rs
  src/common/system-info/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/python/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-csv/src/lib.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/pyobj_serde.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/image/mod.rs
  src/daft-functions/src/lib.rs
  src/daft-image/src/python.rs
  src/daft-io/src/python.rs
  src/daft-json/Cargo.toml
  src/daft-json/src/lib.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/run.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scheduler/src/adaptive.rs
  src/daft-scheduler/src/lib.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-schema/src/python/mod.rs
  src/daft-schema/src/python/schema.rs
  src/daft-sql/src/lib.rs
  src/daft-table/Cargo.toml
  src/daft-table/src/ffi.rs
  src/daft-table/src/python.rs
  src/lib.rs
Labels: chore

#2827 [CHORE] Ensure compatibility with deltalake version v0.19
  .github/workflows/python-package.yml
  benchmarking/parquet/benchmark-requirements.txt
  daft/dataframe/dataframe.py
  daft/io/__init__.py
  daft/io/_deltalake.py
  daft/table/table_io.py
  requirements-dev.txt
  src/arrow2/src/io/parquet/read/schema/convert.rs
  tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
  tests/io/delta_lake/conftest.py
Labels: chore

#2829 [CHORE] Decouple Ray tensor types from main Daft logic
  daft/datatype.py
  daft/runners/ray_runner.py
  daft/series.py
  tests/series/test_concat.py
Labels: chore

#2828 [CHORE]: Move jq out of core
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/json.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/ops/json.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/functions/json/mod.rs
  src/daft-dsl/src/functions/json/query.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions-json/Cargo.toml
  src/daft-functions-json/src/expr.rs
  src/daft-functions-json/src/lib.rs
  src/daft-functions/Cargo.toml
  src/lib.rs
Labels: chore

#2824 [FEAT] Delta lake allow unsafe rename for local writes
  daft/dataframe/dataframe.py
Labels: documentation, enhancement

#2832 [FEAT]: sql count(*)
  src/daft-sql/src/modules/aggs.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: enhancement

#2834 [FEAT]: sql float operations
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/float/fill_nan.rs
  src/daft-dsl/src/functions/float/is_nan.rs
  src/daft-dsl/src/functions/float/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/float/fill_nan.rs
  src/daft-functions/src/float/is_inf.rs
  src/daft-functions/src/float/is_nan.rs
  src/daft-functions/src/float/mod.rs
  src/daft-functions/src/float/not_nan.rs
  src/daft-functions/src/lib.rs
  src/daft-sql/src/modules/float.rs
  tests/sql/test_float_exprs.py
Labels: enhancement

#2798 [CHORE] Concretize casting semantics for temporal + decimal types
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/cast.rs
  src/daft-schema/src/time_unit.rs
  tests/integration/sql/conftest.py
  tests/integration/sql/test_sql.py
  tests/series/test_cast.py
Labels: chore

#2816 [FEAT] Add `to_pylist` on DataFrame
  daft/dataframe/dataframe.py
  docs/source/api_docs/dataframe.rst
  tests/dataframe/test_to_pylist.py
Labels: documentation, enhancement

#2818 [BUG] Avoid reconstructing sql query in read_sql
  daft/sql/sql_connection.py
  daft/sql/sql_scan.py
  daft/table/table_io.py
Labels: bug

#2843 [BUG]: Sql groupby fix
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: bug

#2853 [FEAT]: Dataframe.filter method
  daft/dataframe/dataframe.py
  docs/source/api_docs/dataframe.rst
  tests/dataframe/test_filter.py
Labels: documentation, enhancement

#2855 [CHORE] Add native executor to CI
  .github/workflows/python-package.yml
  tests/cookbook/test_aggregations.py
  tests/cookbook/test_joins.py
  tests/cookbook/test_pandas_cookbook.py
  tests/cookbook/test_write.py
  tests/dataframe/test_aggregations.py
  tests/dataframe/test_approx_count_distinct.py
  tests/dataframe/test_approx_percentiles_aggregations.py
  tests/dataframe/test_concat.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_decimals.py
  tests/dataframe/test_distinct.py
  tests/dataframe/test_explode.py
  tests/dataframe/test_iter.py
  tests/dataframe/test_joins.py
  tests/dataframe/test_map_groups.py
  tests/dataframe/test_monotonically_increasing_id.py
  tests/dataframe/test_pivot.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_sample.py
  tests/dataframe/test_sort.py
  tests/dataframe/test_temporals.py
  tests/dataframe/test_transform.py
  tests/dataframe/test_unpivot.py
  tests/dataframe/test_wildcard.py
  tests/integration/iceberg/conftest.py
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/test_table_write.py
  tests/io/iceberg/test_iceberg_writes.py
  tests/io/lancedb/test_lancedb_reads.py
  tests/io/lancedb/test_lancedb_writes.py
  tests/io/test_csv_roundtrip.py
  tests/io/test_parquet.py
  tests/io/test_parquet_roundtrip.py
  tests/io/test_s3_credentials_refresh.py
  tests/test_resource_requests.py
Labels: chore

#2743 [FEAT] Add left/right/anti/semi joins to native executor
  Cargo.lock
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/probeable/mod.rs
  src/daft-table/src/probeable/probe_set.rs
  src/daft-table/src/probeable/probe_table.rs
  tests/dataframe/test_joins.py
Labels: enhancement

#2756 [CHORE] Change TPC-H q4 and q22 answers to use new join types
  benchmarking/tpch/__main__.py
  benchmarking/tpch/answers.py
  benchmarking/tpch/ray_job_runner.py
Labels: chore

#2826 [PERF] Lazily import heavy modules to speed up import times
  daft/.ruff.toml
  daft/arrow_utils.py
  daft/daft/__init__.pyi
  daft/dataframe/preview.py
  daft/datatype.py
  daft/delta_lake/delta_lake_scan.py
  daft/dependencies.py
  daft/execution/execution_step.py
  daft/execution/native_executor.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/expressions/expressions.py
  daft/filesystem.py
  daft/hudi/hudi_scan.py
  daft/hudi/pyhudi/filegroup.py
  daft/hudi/pyhudi/table.py
  daft/hudi/pyhudi/timeline.py
  daft/hudi/pyhudi/utils.py
  daft/iceberg/iceberg_scan.py
  daft/iceberg/schema_field_id_mapping_visitor.py
  daft/internal/gpu.py
  daft/io/_deltalake.py
  daft/io/common.py
  daft/io/object_store_options.py
  daft/io/scan.py
  daft/lazy_import.py
  daft/logical/builder.py
  daft/logical/map_partition_ops.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/partitioning.py
  daft/runners/progress_bar.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/runners/runner.py
  daft/runners/runner_io.py
  daft/series.py
  daft/sql/sql_connection.py
  daft/sql/sql_scan.py
  daft/table/micropartition.py
  daft/table/schema_inference.py
  daft/table/table.py
  daft/table/table_io.py
  daft/udf.py
  daft/unity_catalog/__init__.py
  daft/utils.py
  daft/viz/dataframe_display.py
  daft/viz/html_viz_hooks.py
  tests/dataframe/test_logical_type.py
  tests/series/test_embedding.py
  tests/series/test_image.py
  tests/series/test_tensor.py
  tests/table/table_io/test_csv.py
Labels: performance

#2854 [CHORE]: move list functions from daft-dsl to daft-functions
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/list/chunk.rs
  src/daft-dsl/src/functions/list/count.rs
  src/daft-dsl/src/functions/list/explode.rs
  src/daft-dsl/src/functions/list/max.rs
  src/daft-dsl/src/functions/list/mean.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/functions/list/sum.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/list/chunk.rs
  src/daft-functions/src/list/count.rs
  src/daft-functions/src/list/explode.rs
  src/daft-functions/src/list/get.rs
  src/daft-functions/src/list/join.rs
  src/daft-functions/src/list/max.rs
  src/daft-functions/src/list/mean.rs
  src/daft-functions/src/list/min.rs
  src/daft-functions/src/list/mod.rs
  src/daft-functions/src/list/slice.rs
  src/daft-functions/src/list/sum.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/logical_ops/explode.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/ops/explode.rs
Labels: chore

#2868 [BUG] Fix concat expression typing
  daft/expressions/expressions.py
Labels: bug

#2844 [FEAT]: `shuffle_join_default_partitions` param
  daft/context.py
  daft/daft/__init__.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/src/physical_planner/translate.rs
  tests/dataframe/test_joins.py
Labels: enhancement

#2856 [FEAT]: sql list operations
  src/daft-functions/src/lib.rs
  src/daft-functions/src/list/count.rs
  src/daft-functions/src/list/mod.rs
  src/daft-functions/src/list/sort.rs
  src/daft-sql/src/modules/list.rs
  tests/sql/test_list_exprs.py
Labels: enhancement

#2858 [FEAT]: SQL temporal functions
  Cargo.lock
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/temporal/date.rs
  src/daft-dsl/src/functions/temporal/day.rs
  src/daft-dsl/src/functions/temporal/day_of_week.rs
  src/daft-dsl/src/functions/temporal/hour.rs
  src/daft-dsl/src/functions/temporal/minute.rs
  src/daft-dsl/src/functions/temporal/mod.rs
  src/daft-dsl/src/functions/temporal/month.rs
  src/daft-dsl/src/functions/temporal/second.rs
  src/daft-dsl/src/functions/temporal/time.rs
  src/daft-dsl/src/functions/temporal/truncate.rs
  src/daft-dsl/src/functions/temporal/year.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/lib.rs
  src/daft-functions/src/temporal/mod.rs
  src/daft-functions/src/temporal/truncate.rs
  src/daft-sql/src/modules/temporal.rs
  tests/sql/test_temporal_exprs.py
Labels: enhancement

#2842 [FEAT] Iceberg partitioned writes
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/expressions/expressions.py
  daft/iceberg/iceberg_scan.py
  daft/iceberg/iceberg_write.py
  daft/logical/builder.py
  daft/table/partitioning.py
  daft/table/table_io.py
  src/daft-core/src/array/ops/truncate.rs
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/sink_info.rs
  src/daft-scheduler/src/scheduler.rs
  tests/cookbook/test_write.py
  tests/io/iceberg/test_iceberg_writes.py
  tests/series/test_partitioning.py
Labels: enhancement

#2872 [CHORE] Move codspeed interactive tests to local files
  tests/benchmarks/test_interactive_reads.py
Labels: chore

#2874 [CHORE] Update documentation for config variables
  daft/context.py
Labels: chore

#2873 Revert "[FEAT]: `shuffle_join_default_partitions` param"
  daft/context.py
  daft/daft/__init__.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/src/physical_planner/translate.rs
  tests/dataframe/test_joins.py
Labels: enhancement

#2885 [BUG] Fix partitioning SQL scans on empty tables
  daft/sql/sql_scan.py
  tests/conftest.py
  tests/integration/sql/conftest.py
  tests/integration/sql/test_sql.py
Labels: bug

#2864 [FEAT] [SQL] Enable SQL query to run on callers scoped variables
  daft/daft/__init__.pyi
  daft/sql/sql.py
  src/daft-sql/src/catalog.rs
  src/daft-sql/src/python.rs
  tests/sql/test_sql.py
Labels: enhancement

#2722 [FEAT] Add Sparse Tensor logical type
  daft/daft/__init__.pyi
  daft/datatype.py
  daft/table/table.py
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/sparse_tensor.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/ops/tensor.rs
  src/daft-core/src/array/prelude.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/datatypes/prelude.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/serdes.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-table/src/repr_html.rs
  tests/benchmarks/conftest.py
  tests/io/test_parquet_roundtrip.py
  tests/series/test_sparse_tensor.py
Labels: enhancement

#2895 [CHORE] ignore vendored crates for codecov
  codecov.yml
Labels: chore

#2870 [FEAT]: add sql support for "DATE <date>" and "DATETIME <datetime>"
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
Labels: enhancement

#2907 [CHORE]: Move daft.sql.sql module to daft.sql
  daft/__init__.py
  daft/sql/__init__.py
Labels: chore

#2886 [CHORE]: bump sqlparser version
  Cargo.lock
  Cargo.toml
  src/daft-sql/src/planner.rs
Labels: chore

#2869 [FEAT]: add partitioning_* functions to sql
  src/daft-sql/src/modules/partitioning.rs
  tests/sql/test_partitioning_exprs.py
Labels: enhancement

#2909 [BUG] Fix display for decimal types
  src/daft-schema/src/dtype.rs
Labels: bug

#2884 [FEAT] Delta Lake partitioned writing
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/iceberg/iceberg_write.py
  daft/logical/builder.py
  daft/table/partitioning.py
  daft/table/table_io.py
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/sink_info.rs
  src/daft-scheduler/src/scheduler.rs
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/test_table_write.py
Labels: enhancement

#2893 [FEAT] UTF8 to binary coercion flag
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/table/table.py
  src/arrow2/src/io/parquet/read/schema/convert.rs
  src/arrow2/src/io/parquet/read/schema/mod.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-scan/src/glob.rs
  tests/assets/parquet-data/invalid_utf8.parquet
  tests/table/table_io/test_parquet.py
Labels: enhancement

#2891 [FEAT]: [SQL] struct subscript and json_query
  Cargo.lock
  src/daft-sql/Cargo.toml
  src/daft-sql/src/modules/json.rs
  src/daft-sql/src/modules/map.rs
  src/daft-sql/src/modules/structs.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_nested_access.py
Labels: enhancement

#2881 [FEAT] Add ability for RayRunner to run actor pool projects (beta feature)
  daft/execution/physical_plan.py
  daft/runners/ray_runner.py
  daft/udf.py
  tests/actor_pool/test_ray_actor_pool.py
Labels: enhancement

#2847 [FEAT] `agg_concat` doesn't work on strings
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-dsl/src/expr.rs
  tests/table/test_table_aggs.py
Labels: enhancement

#2919 [BUG] Use dashes for machete dependency ignores
  Cargo.toml
  src/arrow2/Cargo.toml
  src/daft-io/Cargo.toml
  src/daft-schema/Cargo.toml
Labels: bug

#2915 [CHORE] Enable sources to return empty tables
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  tests/cookbook/test_pandas_cookbook.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_sort.py
Labels: chore

#2926 [CHORE] Fix issues from nightly tests
  src/daft-dsl/src/resolve_expr.rs
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Labels: documentation, chore

#2932 [CHORE] update GH bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#2934 [CHORE] update GH template name from md to yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#2917 [BUG] Enable groupby with alias for native executor
  src/daft-local-execution/src/pipeline.rs
  tests/cookbook/test_aggregations.py
  tests/dataframe/test_aggregations.py
  tests/dataframe/test_approx_percentiles_aggregations.py
  tests/dataframe/test_distinct.py
  tests/dataframe/test_map_groups.py
Labels: bug

#2930 [CHORE] add pytest to vscode settings.json
  .vscode/settings.json
Labels: chore

#2937 [BUG]: sql nested and wildcard
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_exprs.py
Labels: bug

#2876 [CHORE] Refactor Binary Ops
  Cargo.toml
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/mod.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-core/src/series/ops/between.rs
  src/daft-core/src/series/ops/comparison.rs
  src/daft-core/src/series/ops/is_in.rs
  src/daft-core/src/series/ops/logical.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/series_like.rs
  src/daft-core/src/series/utils/mod.rs
  src/daft-core/src/series/utils/python_fn.rs
  src/daft-core/src/utils/mod.rs
Labels: chore

#2920 [CHORE] pin cargo machete to 0.7.0
  .github/workflows/python-package.yml
Labels: chore

#2916 [BUG] improve error reporting for multistatement sql
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: bug

#2672 [CHORE] Enable test_creation and test_parquet for native executor
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/stream_reader.rs
  tests/dataframe/test_creation.py
  tests/io/test_parquet.py
Labels: bug, chore

#2956 [FEAT] Enable init args for stateful UDFs
  daft/daft/__init__.pyi
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/udf.py
  src/common/daft-config/src/python.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_udf.py
Labels: enhancement

#2965 [DOCS] Add docs on to_arrow and as_arrow
  src/daft-core/src/array/ops/as_arrow.rs
Labels: documentation

#2970 [DOCS] update arch png
  docs/source/_static/high_level_architecture.png
Labels: documentation

#2948 [FEAT]: SQL add hash and minhash
  src/daft-functions/src/minhash.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/hashing.rs
  src/daft-sql/src/modules/mod.rs
  tests/sql/test_exprs.py
Labels: enhancement

#2952 [BUG] Writes from empty partitions should return empty micropartitions with non-null schema
  daft/iceberg/iceberg_write.py
  daft/table/table_io.py
  tests/cookbook/test_write.py
  tests/io/delta_lake/test_table_write.py
  tests/io/iceberg/test_iceberg_writes.py
Labels: bug
