Repository Eventual-Inc/Daft, pull requests merged in 2024-05, with the labels that each got.

#2214 [BUG] Propagate errors when hitting them in parquet byte stream
  src/daft-io/src/lib.rs
  src/daft-io/src/object_io.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/read_planner.rs
Labels: bug

#2210 [Docs] Add Dask to DF Comparison FAQ
  docs/source/faq/dataframe_comparison.rst
  docs/source/migration_guides/coming_from_dask.rst
Labels: documentation

#2180 .sqrt() expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/sqrt.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/sqrt.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/functions/numeric/sqrt.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: documentation, enhancement

#2195 [FEAT] Read from LanceDB
  daft/__init__.py
  daft/daft.pyi
  daft/delta_lake/delta_lake_scan.py
  daft/io/__init__.py
  daft/io/_lance.py
  daft/io/object_store_options.py
  pyproject.toml
  requirements-dev.txt
  src/daft-micropartition/src/micropartition.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
  tests/io/lancedb/__init__.py
  tests/io/lancedb/test_lancedb_reads.py
Labels: enhancement

#2183 [FEAT] pivot
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/micropartition.py
  daft/table/table.py
  docs/source/api_docs/dataframe.rst
  src/daft-micropartition/src/ops/mod.rs
  src/daft-micropartition/src/ops/pivot.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/agg.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_ops/pivot.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/pivot.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/ops/mod.rs
  src/daft-table/src/ops/pivot.rs
  src/daft-table/src/python.rs
  tests/dataframe/test_pivot.py
  tests/table/test_pivot.py
Labels: documentation, enhancement

#2218 [DOCS] Add read_lance docs
  daft/io/_lance.py
  docs/source/api_docs/creation.rst
Labels: documentation

#2179 [FEAT] Approximate quantile aggregation (pulled into main)
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  src/daft-core/Cargo.toml
  src/daft-core/src/array/from.rs
  src/daft-core/src/array/ops/approx_sketch.rs
  src/daft-core/src/array/ops/merge_sketch.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/sketch_percentile.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/sketch_percentile.rs
  src/daft-core/src/utils/hashable_float_wrapper.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/sketch/mod.rs
  src/daft-dsl/src/functions/sketch/percentile.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-sketch/Cargo.toml
  src/daft-sketch/src/arrow2_serde.rs
  src/daft-table/src/lib.rs
  tests/cookbook/test_aggregations.py
  tests/dataframe/test_approx_percentiles_aggregations.py
Labels: documentation, enhancement

#2216 [PERF] enable metadata preservation across materialization points
  daft/dataframe/dataframe.py
  daft/execution/physical_plan.py
  daft/io/file_path.py
  daft/runners/partitioning.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
Labels: performance

#2222 [PERF] Evaluate only true/false side of if_else if predicate is boolean
  src/daft-dsl/src/expr.rs
  src/daft-table/src/lib.rs
  tests/table/test_if_else.py
Labels: performance

#2223 [DOCS] LinkedIn Big Data meetup tutorial
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
Labels: documentation

#2198 [FEAT] Add string repeat functionality
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/repeat.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_repeat.py
Labels: documentation, enhancement

#2229 [CHORE]: remove trait aliases
  src/daft-csv/src/read.rs
  src/daft-json/src/read.rs
Labels: chore

#2232 [CHORE] Mount provision.py for iceberg integration tests
  tests/integration/iceberg/docker-compose/Dockerfile
  tests/integration/iceberg/docker-compose/docker-compose.yml
Labels: chore

#2228 [PERF]: swap out json_deserializer for simd_json
  Cargo.lock
  src/daft-json/Cargo.toml
  src/daft-json/src/decoding.rs
  src/daft-json/src/deserializer.rs
  src/daft-json/src/inference.rs
  src/daft-json/src/lib.rs
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
Labels: performance

#2224 [CHORE] Return &str for expression name
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/list/count.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/explode.rs
  src/daft-table/src/ops/joins/mod.rs
Labels: chore

#2225 [DOCS] Add `read_hudi` in the api docs
  docs/source/api_docs/creation.rst
Labels: documentation

#2204 [FEAT] Add unpivot
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/micropartition.py
  docs/source/api_docs/dataframe.rst
  src/daft-core/src/array/ops/arrow2/sort/primitive/sort.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/if_else.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/search_sorted.rs
  src/daft-micropartition/src/ops/mod.rs
  src/daft-micropartition/src/ops/unpivot.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_ops/unpivot.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_ops/unpivot.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/ops/mod.rs
  src/daft-table/src/ops/unpivot.rs
  tests/dataframe/test_unpivot.py
Labels: documentation, enhancement

#2243 [FEAT] AWS Profile override in S3Config
  daft/daft.pyi
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#2226 [DOCS] Add user guide for read_sql
  daft/io/_sql.py
  docs/source/_static/sql_distributed_read.png
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/sql.rst
Labels: documentation

#2244 [BUG] route abfss to AzureBlob
  daft/filesystem.py
  daft/io/object_store_options.py
  src/daft-io/src/lib.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: bug

#2157 [FEAT] Add rpad and lpad expressions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/lpad.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/rpad.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_lpad.py
  tests/table/utf8/test_rpad.py
Labels: documentation, enhancement

#2248 [CHORE] Skip demo notebook
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
Labels: documentation, chore

#2242 [CHORE] Allow multiple group_bys for pivot
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-micropartition/src/ops/pivot.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/pivot.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/pivot.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/ops/pivot.rs
  src/daft-table/src/python.rs
  tests/dataframe/test_pivot.py
  tests/table/test_pivot.py
Labels: chore

#2166 [FEAT] Add left, right, and outer joins
  CONTRIBUTING.md
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  daft/table/micropartition.py
  daft/table/table.py
  src/daft-core/src/join.rs
  src/daft-core/src/lib.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/physical_ops/broadcast_join.rs
  src/daft-plan/src/physical_ops/hash_join.rs
  src/daft-plan/src/physical_ops/sort_merge_join.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/python.rs
  tests/benchmarks/test_join.py
  tests/dataframe/test_joins.py
Labels: enhancement

#2176 [PERF] Adaptive Query Execution
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/io/file_path.py
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/partitioning.py
  daft/runners/progress_bar.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-csv/src/read.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/partitioning.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/mod.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-plan/src/physical_planner/python.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-scan/src/lib.rs
Labels: performance

#2245 [CHORE] Improve timestamp repr
  src/daft-core/src/array/ops/cast.rs
  tests/expressions/test_expressions.py
  tests/series/test_cast.py
Labels: chore

#2251 [BUG] Fix tab completion on expression namespaced accessors
  daft/expressions/expressions.py
Labels: bug

#2250 [CHORE] Drop Python 3.7
  .github/workflows/notebook-checker.yml
  .github/workflows/property-based-tests.yml
  .github/workflows/python-package.yml
  .ruff.toml
  Cargo.toml
  daft/api_annotations.py
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/expressions/expressions.py
  daft/filesystem.py
  daft/logical/schema.py
  daft/runners/partitioning.py
  daft/series.py
  daft/udf_library/url_udfs.py
  pyproject.toml
  tests/expressions/typing/conftest.py
  tests/integration/iceberg/conftest.py
  tests/io/iceberg/test_iceberg_writes.py
  tests/io/lancedb/test_lancedb_reads.py
Labels: chore

#2252 [FEAT] Allow returning of pyarrow arrays from UDFs
  daft/udf.py
  tests/expressions/test_udf.py
Labels: enhancement

#2256 [DOCS] Add quick docs for struct datatype
  daft/datatype.py
Labels: documentation

#2258 [CHORE] Enable CI checks for AQE in CI and refactor CI job organization
  .github/workflows/python-package.yml
  src/daft-plan/src/logical_plan.rs
Labels: chore

#2259 [CHORE] turn on cov again
  .github/workflows/python-package.yml
  codecov.yml
Labels: chore

#2268 [FEAT] Handle Hudi empty timeline
  daft/hudi/pyhudi/table.py
  daft/hudi/pyhudi/timeline.py
  tests/io/hudi/conftest.py
  tests/io/hudi/data/v6_empty.sql
  tests/io/hudi/data/v6_empty.zip
  tests/io/hudi/test_table_read.py
Labels: enhancement

#2084 [FEAT] Test for partition evolution
  tests/integration/iceberg/docker-compose/provision.py
  tests/integration/iceberg/test_table_load.py
Labels: enhancement

#2276 [CHORE] Clean up string kernel code
  src/daft-core/src/series/ops/utf8.rs
Labels: chore

#2267 [BUG] Fix red line in Jupyter notebook
  daft/runners/progress_bar.py
Labels: bug

#2255 [FEAT] Map Getter
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/map.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/map.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/functions/map/get.rs
  src/daft-dsl/src/functions/map/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  tests/table/map/__init__.py
  tests/table/map/test_map_get.py
Labels: documentation, enhancement

#2234 [FEAT] extract minute second and time component
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/time.rs
  src/daft-dsl/src/functions/temporal/minute.rs
  src/daft-dsl/src/functions/temporal/mod.rs
  src/daft-dsl/src/functions/temporal/second.rs
  src/daft-dsl/src/functions/temporal/time.rs
  src/daft-dsl/src/python.rs
  tests/series/test_temporal_ops.py
Labels: documentation, enhancement

#2281 [DOCS] Add iceberg summit tutorial notebook
  tutorials/talks_and_demos/iceberg_summit_2024.ipynb
Labels: documentation

#2264 [PERF]: local json reader
  Cargo.lock
  src/daft-core/src/schema.rs
  src/daft-json/Cargo.toml
  src/daft-json/src/decoding.rs
  src/daft-json/src/lib.rs
  src/daft-json/src/local.rs
  src/daft-json/src/options.rs
  src/daft-json/src/read.rs
Labels: performance

#2289 [CHORE] Pin requests to fix docker-py CI issue
  requirements-dev.txt
Labels: chore

#2291 [BUG] Fix multi-output tasks in RayRunner
  daft/runners/ray_runner.py
  tests/dataframe/test_repartition.py
Labels: bug

#2304 [FEAT] Delta Lake Writer (non-public API)
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/delta_lake/delta_lake_storage_function.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/table_io.py
  requirements-dev.txt
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/physical_ops/deltalake_write.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/sink_info.rs
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_read_pushdowns.py
  tests/io/delta_lake/test_table_write.py
Labels: enhancement

#2306 [CHORE]: Don't use record fields
  daft/iceberg/iceberg_scan.py
Labels: chore

#2283 [FEAT] like and ilike functions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/ilike.rs
  src/daft-dsl/src/functions/utf8/like.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_ilike.py
  tests/table/utf8/test_like.py
Labels: documentation, enhancement

#2296 [FEAT] Use detached named actor for RayRunner
  daft/runners/ray_runner.py
Labels: enhancement

#2322 [FEAT] implement timeout for parquet reader
  daft/daft.pyi
  daft/table/table.py
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  tests/integration/io/parquet/test_reads_public_data.py
Labels: enhancement

#2323 [FEAT] Add function to refresh logger state for rust
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/daft.pyi
  src/lib.rs
Labels: enhancement

#2321 [BUG]Fix missing columns after join
  src/daft-plan/src/logical_ops/join.rs
  tests/dataframe/test_joins.py
Labels: bug

#2320 [FEAT] Allow for printing of plans to a file
  daft/dataframe/dataframe.py
Labels: enhancement

#2324 [EXPRESSIONS] Add log with custom base
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/log.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/log.rs
  src/daft-dsl/src/functions/numeric/log.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: documentation

#2327 [CHORE] Show full schema in html repr
  daft/daft.pyi
  daft/logical/schema.py
  daft/viz/dataframe_display.py
  src/daft-core/src/python/schema.rs
  src/daft-core/src/schema.rs
  tests/dataframe/test_repr.py
  tests/test_schema.py
  tests/utils.py
Labels: chore

#2301 [FEAT] Expression between
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/utils.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/between.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/series/ops/between.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/partitioning.rs
  src/daft-table/src/lib.rs
  tests/table/test_between.py
Labels: documentation, enhancement

#2330 [BUG] Translate mssql to tsql in read_sql scan
  daft/sql/sql_scan.py
Labels: bug

#2233 [FEAT] Custom S3 Credentials Provider
  Cargo.lock
  daft/daft.pyi
  daft/io/__init__.py
  docs/source/api_docs/configs.rst
  src/common/io-config/Cargo.toml
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/common/py-serde/Cargo.toml
  src/common/py-serde/src/lib.rs
  src/common/py-serde/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/sink_info.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  tests/io/delta_lake/conftest.py
  tests/io/mock_aws_server.py
  tests/io/test_s3_credentials_refresh.py
Labels: documentation, enhancement
