Repository Eventual-Inc/Daft, pull requests merged in 2024-04, with the labels that each got.

#2011 [FEAT] Support Hudi reader
  daft/__init__.py
  daft/hudi/__init__.py
  daft/hudi/hudi_scan.py
  daft/hudi/pyhudi/__init__.py
  daft/hudi/pyhudi/filegroup.py
  daft/hudi/pyhudi/table.py
  daft/hudi/pyhudi/timeline.py
  daft/hudi/pyhudi/utils.py
  daft/io/__init__.py
  daft/io/_hudi.py
  tests/io/hudi/__init__.py
  tests/io/hudi/conftest.py
  tests/io/hudi/data/0.x_cow_partitioned.zip
  tests/io/hudi/test_table_read.py
Labels: enhancement

#2044 [FEAT] Enable str.split using regex pattern
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/split.rs
  src/daft-dsl/src/python.rs
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_split.py
Labels: enhancement

#2048 [FEAT] Add str.replace expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-dsl/src/functions/utf8/mod.rs
  src/daft-dsl/src/functions/utf8/replace.rs
  src/daft-dsl/src/python.rs
  tests/expressions/typing/test_str.py
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_replace.py
Labels: documentation, enhancement

#2055 [FEAT] improve error message for s3 streaming error
  src/daft-io/src/s3_like.rs
Labels: enhancement

#2077 [CHORE] Use docker compose instead of docker-compose in builds
  .github/workflows/python-package.yml
Labels: chore

#2078 [BUG] produce only a single sdist
  .github/workflows/python-publish.yml
Labels: bug

#2057 [DOCS] Add ml batch inference tutorials
  daft/table/table_io.py
  docs/source/user_guide/tutorials.rst
  tutorials/delta_lake/1-local-image-batch-inference.ipynb
  tutorials/delta_lake/2-distributed-batch-inference.ipynb
  tutorials/delta_lake/3-pytorch-ray-single-node-training.ipynb
Labels: documentation

#2082 [DOCSA] Fix typos on 10-min tutorial
  docs/source/10-min.ipynb
Labels: documentation

#2075 Fix docs typo
  docs/source/index.rst
Labels: documentation

#2085 [CHORE] fix empty data and pattern case in str expressions
  src/daft-core/src/array/ops/utf8.rs
  tests/series/test_utf8_ops.py
Labels: chore

#2088 [CHORE] Add link to good first issues in readme
  README.rst
Labels: documentation, chore

#2090 [FEAT] Add daft-sketch subcrate and arrow2 serialization functionality
  Cargo.lock
  Cargo.toml
  src/daft-sketch/Cargo.toml
  src/daft-sketch/src/arrow2_serde.rs
  src/daft-sketch/src/lib.rs
Labels: enhancement

#2097 [CHORE] Skip deltalake notebooks for CI
  tutorials/delta_lake/1-local-image-batch-inference.ipynb
  tutorials/delta_lake/2-distributed-batch-inference.ipynb
  tutorials/delta_lake/3-pytorch-ray-single-node-training.ipynb
Labels: documentation, chore

#2087 [CHORE] Refactor string kernels
  src/daft-core/src/array/ops/utf8.rs
  tests/series/test_utf8_ops.py
Labels: chore

#2101 [DOCS] Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#2071 [FEAT] Allow sql alchemy connection factory as input to read_sql
  daft/daft.pyi
  daft/io/_sql.py
  daft/sql/sql_connection.py
  daft/sql/sql_reader.py
  daft/sql/sql_scan.py
  daft/table/table_io.py
  pyproject.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  tests/integration/sql/test_sql.py
Labels: enhancement

#2032 [FEAT] Add basic list aggregations
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/datatypes/agg_ops.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/list/count.rs
  src/daft-dsl/src/functions/list/max.rs
  src/daft-dsl/src/functions/list/mean.rs
  src/daft-dsl/src/functions/list/min.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/functions/list/sum.rs
  src/daft-dsl/src/python.rs
  src/daft-table/src/ops/explode.rs
  tests/table/list/test_list_count_lengths.py
  tests/table/list/test_list_lengths.py
  tests/table/list/test_list_numeric_aggs.py
Labels: enhancement

#2089 [FEAT] fill_null expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/null.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/treenode.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-table/src/lib.rs
  tests/expressions/typing/test_null.py
  tests/series/test_fill_null.py
  tests/table/test_fill_null.py
Labels: enhancement

#2106 [FEAT] Add option to S3Config to force virtual addressing
  daft/daft.pyi
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#2116 [CHORE] Update .gitignore for JetBrains IDE and pyenv user
  .gitignore
Labels: chore

#2114 [CHORE] Using `uv` in MakeFile
  Makefile
  requirements-dev.txt
Labels: enhancement

#2112 [FEAT] sin/cos/tan expression implementation
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/trigonometry.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/trigonometry.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/functions/numeric/trigonometry.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: enhancement

#2115 [FEAT] exp expression implementation
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/exp.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/exp.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/functions/numeric/exp.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: enhancement

#2117 [CHORE] FunctionEvaluator directly receive `FunctionExpr`
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/float/is_nan.rs
  src/daft-dsl/src/functions/image/crop.rs
  src/daft-dsl/src/functions/image/decode.rs
  src/daft-dsl/src/functions/image/encode.rs
  src/daft-dsl/src/functions/image/resize.rs
  src/daft-dsl/src/functions/json/query.rs
  src/daft-dsl/src/functions/list/count.rs
  src/daft-dsl/src/functions/list/explode.rs
  src/daft-dsl/src/functions/list/get.rs
  src/daft-dsl/src/functions/list/join.rs
  src/daft-dsl/src/functions/list/max.rs
  src/daft-dsl/src/functions/list/mean.rs
  src/daft-dsl/src/functions/list/min.rs
  src/daft-dsl/src/functions/list/sum.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/numeric/abs.rs
  src/daft-dsl/src/functions/numeric/ceil.rs
  src/daft-dsl/src/functions/numeric/floor.rs
  src/daft-dsl/src/functions/numeric/round.rs
  src/daft-dsl/src/functions/numeric/sign.rs
  src/daft-dsl/src/functions/numeric/trigonometry.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/functions/struct_/get.rs
  src/daft-dsl/src/functions/temporal/date.rs
  src/daft-dsl/src/functions/temporal/day.rs
  src/daft-dsl/src/functions/temporal/day_of_week.rs
  src/daft-dsl/src/functions/temporal/hour.rs
  src/daft-dsl/src/functions/temporal/month.rs
  src/daft-dsl/src/functions/temporal/year.rs
  src/daft-dsl/src/functions/uri/download.rs
  src/daft-dsl/src/functions/utf8/capitalize.rs
  src/daft-dsl/src/functions/utf8/contains.rs
  src/daft-dsl/src/functions/utf8/endswith.rs
  src/daft-dsl/src/functions/utf8/extract.rs
  src/daft-dsl/src/functions/utf8/extract_all.rs
  src/daft-dsl/src/functions/utf8/find.rs
  src/daft-dsl/src/functions/utf8/left.rs
  src/daft-dsl/src/functions/utf8/length.rs
  src/daft-dsl/src/functions/utf8/lower.rs
  src/daft-dsl/src/functions/utf8/lstrip.rs
  src/daft-dsl/src/functions/utf8/match_.rs
  src/daft-dsl/src/functions/utf8/replace.rs
  src/daft-dsl/src/functions/utf8/reverse.rs
  src/daft-dsl/src/functions/utf8/right.rs
  src/daft-dsl/src/functions/utf8/rstrip.rs
  src/daft-dsl/src/functions/utf8/split.rs
  src/daft-dsl/src/functions/utf8/startswith.rs
  src/daft-dsl/src/functions/utf8/upper.rs
  src/daft-table/src/lib.rs
Labels: chore

#2119 [CHORE] FunctionExpr and exp
  src/daft-dsl/src/functions/numeric/exp.rs
Labels: chore

#2120 [CHORE] refactors for ruff [1/n]
  benchmarking/tpch/__main__.py
  benchmarking/tpch/pipelined_data_generation.py
  daft/dataframe/dataframe.py
  daft/dataframe/to_torch.py
  daft/expressions/expressions.py
  daft/iceberg/iceberg_scan.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/udf_library/url_udfs.py
  daft/utils.py
  tests/conftest.py
  tests/cookbook/conftest.py
  tests/cookbook/test_dataloading.py
  tests/cookbook/test_image.py
  tests/cookbook/test_literals.py
  tests/cookbook/test_pandas_cookbook.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_sort.py
  tests/dataframe/test_temporals.py
  tests/expressions/test_expressions.py
  tests/expressions/test_expressions_projection.py
  tests/integration/iceberg/docker-compose/provision.py
  tests/integration/iceberg/test_table_load.py
  tests/integration/io/benchmarks/test_benchmark_glob.py
  tests/integration/io/conftest.py
  tests/integration/io/parquet/test_reads_s3_minio.py
  tests/integration/io/test_list_files_http.py
  tests/integration/io/test_list_files_s3_minio.py
  tests/integration/io/test_url_download_private_aws_s3.py
  tests/integration/sql/conftest.py
  tests/io/conftest.py
  tests/io/delta_lake/conftest.py
  tests/io/delta_lake/mock_aws_server.py
  tests/io/test_list_files_local.py
  tests/io/test_parquet.py
  tests/io/test_url_download_local.py
  tests/property_based_testing/strategies.py
  tests/series/test_arithmetic.py
  tests/series/test_comparisons.py
  tests/series/test_concat.py
  tests/series/test_hash.py
  tests/series/test_series.py
  tests/series/test_sort.py
  tests/table/table_io/test_parquet.py
  tests/table/test_eval.py
  tests/table/test_joins.py
Labels: chore

#2123 [FEAT] Implements other trigonometry expressions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/trigonometry.rs
  src/daft-core/src/python/series.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: enhancement

#2110 [DOCS] Update iceberg integration docs to add writes
  docs/source/user_guide/integrations/iceberg.rst
Labels: documentation

#2126 [CHORE] Fix build command
  Makefile
Labels: chore

#2134 [CHORE] Fix documentation build with uv
  .readthedocs.yaml
Labels: chore

#2135 [CHORE] Fixing readthedocs build
  .readthedocs.yaml
Labels: chore

#2113 deltalake _delta_lake.py: Allow Glue catalog cross account access
  daft/io/_delta_lake.py
Labels: enhancement

#2118 [BUG] Fix reading partition key columns in DeltaLake
  src/daft-micropartition/src/micropartition.rs
  tests/integration/iceberg/test_table_load.py
  tests/io/delta_lake/test_table_read_pushdowns.py
Labels: bug

#2137 [FEAT] Add S3Config.from_env functionality
  daft/daft.pyi
  src/common/io-config/src/python.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#2141 [CHORE] Fix the labeller CI step which is not triggering
  .github/workflows/release-drafter.yml
Labels: chore

#2143 [CHORE] Fix underlines in README
  README.rst
Labels: documentation, chore

#2147 [CHORE] Bottom Up Logical To Physical translation
  src/daft-plan/src/planner.rs
Labels: chore

#2150 [CHORE] collect all tests before running pytest so check for import errors
  .github/workflows/python-package.yml
Labels: chore

#2151 [CHORE] Rearrange modules in `daft-plan` crate
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/logical_plan_tracker.rs
  src/daft-plan/src/logical_optimization/mod.rs
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/drop_repartition.rs
  src/daft-plan/src/logical_optimization/rules/mod.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/rule.rs
  src/daft-plan/src/logical_optimization/test/mod.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_planner/mod.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-plan/src/physical_planner/translate.rs
Labels: chore

#2144 [FEAT] Improve query building in read_sql
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/io/_sql.py
  daft/runners/partitioning.py
  daft/sql/sql_connection.py
  daft/sql/sql_scan.py
  daft/table/table_io.py
  pyproject.toml
  requirements-dev.txt
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/python.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-scan/src/file_format.rs
  tests/integration/sql/test_sql.py
Labels: enhancement

#2159 [FEAT] hide stack traces of wrappers for pytest / ipython
  daft/analytics.py
  daft/api_annotations.py
Labels: enhancement

#2163 [CHORE] Fix style build on main
  .pre-commit-config.yaml
Labels: chore

#2161 [BUG] Fix tuple inputs in UDF
  daft/udf.py
  tests/expressions/test_udf.py
Labels: bug

#2160 [CHORE] Enforce physical types in logical array
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/date.rs
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/array_impl/logical_array.rs
Labels: chore

#2165 [BUG] Fix empty inputs case for string kernels
  src/daft-core/src/array/ops/utf8.rs
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_replace.py
Labels: bug

#2162 [FEAT] Allow for variadic kwargs in UDFs
  daft/udf.py
  tests/expressions/test_udf.py
Labels: enhancement

#2145 [CHORE] improve recursive listing error msg
  src/daft-scan/src/glob.rs
Labels: chore

#2081 [CHORE] Add usr msg for df.explain(show_all=True)
  daft/dataframe/dataframe.py
Labels: chore

#2175 [PERF] Refactor TreeNode to be native to Arc<TreeNode>
  src/common/treenode/src/lib.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/treenode.rs
  src/daft-parquet/src/metadata.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/mod.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/treenode.rs
  src/daft-scan/src/expr_rewriter.rs
Labels: performance

#2167 [PERF] Move `with_column` and `exclude` function logic to Rust side, add `with_columns`
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  docs/source/api_docs/dataframe.rst
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_optimization/logical_plan_tracker.rs
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/project.rs
  tests/dataframe/test_with_columns.py
Labels: documentation, enhancement, performance

#2177 [CHORE] enable codespell and fix mispellings
  .pre-commit-config.yaml
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/expressions/expressions.py
  daft/expressions/testing.py
  daft/pickle/cloudpickle.py
  daft/sql/sql_scan.py
  daft/udf.py
  docs/source/user_guide/integrations/aws.rst
  docs/source/user_guide/integrations/iceberg.rst
  docs/source/user_guide/poweruser/memory.rst
  pyproject.toml
  src/daft-core/src/array/ops/image.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/ffi.rs
  src/daft-core/src/kernels/utf8.rs
  src/daft-csv/src/read.rs
  src/daft-io/src/s3_like.rs
  src/daft-json/src/inference.rs
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/read.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-table/src/ops/joins/merge_join.rs
  tests/dataframe/test_monotonically_increasing_id.py
  tests/series/test_hash.py
  tests/series/test_size_bytes.py
  tests/table/test_table_aggs.py
Labels: documentation, chore

#2169 [DOCS] add Dask migration guide
  docs/CONTRIBUTING.md
  docs/source/index.rst
  docs/source/migration_guides/coming_from_dask.md
  docs/source/migration_guides/index.rst
Labels: documentation

#2168 [FEAT] Add logarithmic expressions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/log.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/log.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-dsl/src/functions/numeric/log.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/test_eval.py
Labels: documentation, enhancement

#2146 [FEAT] Enhance temporal arithmetic functionalities
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/ops/downcast.rs
  tests/dataframe/test_temporals.py
  tests/expressions/typing/test_arithmetic.py
Labels: enhancement

#2158 [FEAT] Timestamp Truncation
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/date.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/date.rs
  src/daft-dsl/src/functions/temporal/mod.rs
  src/daft-dsl/src/functions/temporal/truncate.rs
  src/daft-dsl/src/python.rs
  tests/series/test_temporal_ops.py
  tests/table/test_table_aggs.py
Labels: documentation, enhancement

#2186 [CHORE] upgrade dask for tests for 3.11
  .github/workflows/python-package.yml
  requirements-dev.txt
  tests/ray/test_dask.py
Labels: chore

#2189 [CHORE] add ray min version for windows to remove upper pin on pyarrow
  .github/workflows/python-package.yml
  pyproject.toml
Labels: chore

#2191 [CHORE] remove fsspec http filesystem
  pyproject.toml
Labels: chore

#2193 [CHORE] upgrade dask again for publish pipeline
  requirements-dev.txt
Labels: chore

#2194 [BUG] bump arrow2 to use copy ptr instead of from_raw_parts
  Cargo.lock
  Cargo.toml
Labels: bug

#2192 [CHORE] Upgrade Rust toolchain to 2024 04 01
  Cargo.lock
  rust-toolchain.toml
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/growable/python_growable.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/json.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/mean.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/array/ops/sum.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/array/pseudo_arrow/mod.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/count_mode.rs
  src/daft-core/src/datatypes/image_format.rs
  src/daft-core/src/datatypes/image_mode.rs
  src/daft-core/src/ffi.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/utils/display_table.rs
  src/daft-csv/src/read.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/optimization.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/http.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-json/src/decoding.rs
  src/daft-json/src/read.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/statistics/column_range.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/treenode.rs
  src/daft-scan/src/expr_rewriter.rs
  src/daft-scan/src/py_object_serde.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-table/src/ffi.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/explode.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/ops/sort.rs
Labels: chore

#2149 [FEAT] Improve Hudi support for more scenarios
  daft/hudi/hudi_scan.py
  daft/hudi/pyhudi/filegroup.py
  daft/hudi/pyhudi/table.py
  daft/hudi/pyhudi/utils.py
  docs/source/user_guide/integrations/hudi.rst
  pyproject.toml
  tests/io/hudi/conftest.py
  tests/io/hudi/data/0.x_cow_partitioned.zip
  tests/io/hudi/data/v6_complexkeygen_hivestyle.datagen.sql
  tests/io/hudi/data/v6_complexkeygen_hivestyle.zip
  tests/io/hudi/data/v6_nonpartitioned.datagen.sql
  tests/io/hudi/data/v6_nonpartitioned.zip
  tests/io/hudi/data/v6_simplekeygen_hivestyle_no_metafields.datagen.sql
  tests/io/hudi/data/v6_simplekeygen_hivestyle_no_metafields.zip
  tests/io/hudi/data/v6_simplekeygen_nonhivestyle.datagen.sql
  tests/io/hudi/data/v6_simplekeygen_nonhivestyle.zip
  tests/io/hudi/data/v6_timebasedkeygen_nonhivestyle.sql
  tests/io/hudi/data/v6_timebasedkeygen_nonhivestyle.zip
  tests/io/hudi/test_table_read.py
Labels: bug, documentation, enhancement

#2206 [FEAT] Enable anonymous S3 access for Delta
  daft/delta_lake/delta_lake_scan.py
Labels: enhancement

#2208 [DOCS] Add Hudi integration entry
  docs/source/user_guide/integrations.rst
Labels: documentation

#2197 [FEAT] Rust side exceptions for Transient Errors
  daft/exceptions.py
  src/common/error/src/error.rs
  src/common/error/src/lib.rs
  src/common/error/src/python.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/s3_like.rs
  src/lib.rs
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_url_download_public_aws_s3.py
Labels: enhancement

#2213 [CHORE]: statically link liblzma
  Cargo.lock
  Cargo.toml
Labels: chore
