Repository Eventual-Inc/Daft, pull requests merged in 2024-01, with the labels that each got.

#1761 [BUG] Add check for protocol S3A (s3 compatible)
  src/daft-io/src/lib.rs
  tests/integration/io/conftest.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/io/test_list_files_s3_minio.py
  tests/integration/io/test_url_download_private_aws_s3.py
  tests/integration/io/test_url_download_public_aws_s3.py
Labels: bug

#1762 [DOCS] Documentation reorganization
  daft/context.py
  docs/source/10-min.ipynb
  docs/source/api_docs/creation.rst
  docs/source/api_docs/dataframe.rst
  docs/source/api_docs/index.rst
  docs/source/api_docs/input_output.rst
  docs/source/api_docs/io_configs.rst
  docs/source/faq/benchmarks.rst
  docs/source/faq/dataframe_comparison.rst
  docs/source/faq/index.rst
  docs/source/faq/technical_architecture.rst
  docs/source/faq/telemetry.rst
  docs/source/index.rst
  docs/source/learn/index.rst
  docs/source/learn/key_concepts.rst
  docs/source/learn/user_guides.rst
  docs/source/user_guide/basic_concepts.rst
  docs/source/user_guide/basic_concepts/dataframe_introduction.rst
  docs/source/user_guide/basic_concepts/expressions.rst
  docs/source/user_guide/basic_concepts/introduction.rst
  docs/source/user_guide/basic_concepts/read-and-write.rst
  docs/source/user_guide/cheatsheet.rst
  docs/source/user_guide/daft_in_depth.rst
  docs/source/user_guide/daft_in_depth/aggregations.rst
  docs/source/user_guide/daft_in_depth/dataframe-operations.rst
  docs/source/user_guide/daft_in_depth/datatypes.rst
  docs/source/user_guide/daft_in_depth/udf.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/poweruser.rst
  docs/source/user_guide/poweruser/memory.rst
  docs/source/user_guide/poweruser/partitioning.rst
  docs/source/user_guide/poweruser/scaling-up.rst
  docs/source/user_guide/tutorials.rst
Labels: documentation

#1769 [DOCS] Add documentation for read_iceberg
  daft/io/_iceberg.py
  docs/source/api_docs/creation.rst
  docs/source/user_guide/basic_concepts/read-and-write.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/data_catalogs.rst
Labels: documentation

#1772 [BUG] Invalidate PartitionSpec when we run Explode on it
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
Labels: bug

#1774 [DOCS] Fix broken links on readme
  README.rst
Labels: documentation

#1770 [FEAT] Add sample function for Dataframe
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/table/micropartition.py
  daft/table/table.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-micropartition/src/ops/take.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_ops/sample.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/sample.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/python.rs
  tests/dataframe/test_sample.py
  tests/table/test_sorting.py
Labels: enhancement

#1777 [FEAT] Not_Null Expression
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/null.rs
  src/daft-core/src/series/series_like.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/treenode.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-scan/src/expr_rewriter.rs
  src/daft-table/src/lib.rs
  tests/expressions/typing/test_null.py
  tests/table/test_eval.py
Labels: enhancement

#1778 [FEAT] Iceberg Murmur3 Hash function
  Cargo.lock
  daft/daft.pyi
  daft/series.py
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/ops/hash.rs
  tests/series/test_hash.py
Labels: enhancement

#1779 [PERF] Iceberg Hash Bucket Transform
  daft/daft.pyi
  daft/iceberg/iceberg_scan.py
  daft/series.py
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-dsl/src/functions/partitioning/mod.rs
  src/daft-scan/src/expr_rewriter.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  tests/series/test_partitioning.py
Labels: performance

#1775 [FEAT] Add getter for Struct and List expressions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/struct_.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/struct_.rs
  src/daft-core/src/series/series_like.rs
  src/daft-dsl/src/functions/list/get.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/struct_/get.rs
  src/daft-dsl/src/functions/struct_/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-io/src/lib.rs
  tests/table/list/test_list_get.py
  tests/table/struct/__init__.py
  tests/table/struct/test_struct_get.py
Labels: documentation, enhancement

#1782 [CHORE] Add not_null to docs
  docs/source/api_docs/expressions.rst
Labels: documentation, chore

#1781 [CHORE] Add sample to docs
  docs/source/api_docs/dataframe.rst
Labels: documentation, chore

#1783 [PERF] Iceberg Truncate Transform
  daft/daft.pyi
  daft/iceberg/iceberg_scan.py
  daft/series.py
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/truncate.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-dsl/src/functions/partitioning/mod.rs
  src/daft-scan/src/expr_rewriter.rs
  src/daft-scan/src/python.rs
  tests/integration/iceberg/test_partition_pruning.py
  tests/series/test_partitioning.py
Labels: performance

#1780 [BUG] Materialize Dataframes created from in-memory data
  daft/daft.pyi
  daft/dataframe/dataframe.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  tests/conftest.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_show.py
  tests/ray/test_dask.py
  tests/ray/test_datasets.py
Labels: bug

#1786 [DOCS] Update README.rst for broken links
  README.rst
Labels: documentation

#1787 [DOCS] Fix docs build for sphinxcontrib-applehelp versioning
  requirements-dev.txt
Labels: documentation

#1785 [BUG] Materialize Dataframes created from file writes
  daft/dataframe/dataframe.py
  tests/cookbook/test_write.py
Labels: bug

#1789 [DOCS] Upgrade version of docs sphinx-book-theme dependency
  .github/release-drafter.yml
  docs/source/_static/header.css
  docs/source/conf.py
  requirements-dev.txt
Labels: documentation

#1795 [CHORE] Update docs to reflect materialized Dataframes from writes and in-memory reads
  docs/source/10-min.ipynb
  docs/source/user_guide/basic_concepts/dataframe_introduction.rst
  docs/source/user_guide/daft_in_depth/udf.rst
Labels: documentation, chore

#1802 [DOCS] Update README.rst to remove beta disclaimer
  README.rst
Labels: documentation

#1808 [DOCS] Add warning during repartition to use into_partitions instead
  daft/dataframe/dataframe.py
Labels: documentation

#1812 [BUG] Fix scheduler deadlock on concurrent broadcast joins.
  daft/execution/physical_plan.py
Labels: bug

#1794 [FEAT] Support Hive-Style Partitioned Writes for Tabular Writes
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/expressions/expressions.py
  daft/series.py
  daft/table/micropartition.py
  daft/table/table.py
  daft/table/table_io.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-core/src/array/ops/arrow2/comparison.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-core/src/series/ops/take.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  src/daft-dsl/src/python.rs
  src/daft-micropartition/src/ops/partition.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-table/src/ops/partition.rs
  src/daft-table/src/python.rs
  tests/cookbook/test_write.py
Labels: enhancement

#1814 [BUG] bugfix for empty partitions when writing out empty partitions
  daft/table/table_io.py
Labels: bug

#1815 [BUG] Fix for Iceberg schema projection
  src/daft-micropartition/src/micropartition.rs
  src/daft-scan/src/lib.rs
  tests/integration/iceberg/docker-compose/Dockerfile
  tests/integration/iceberg/docker-compose/provision.py
  tests/integration/iceberg/test_table_load.py
Labels: bug

#1817 [FEAT] Dataframe __contains__ magic method
  daft/dataframe/dataframe.py
  tests/dataframe/test_accessors.py
Labels: enhancement

#1811 [FEAT] is_in expression
  Cargo.lock
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  daft/table/table.py
  daft/utils.py
  src/daft-core/Cargo.toml
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/ops/is_in.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/is_in.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/utils/display_table.rs
  src/daft-core/src/utils/hashable_float_wrapper.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/treenode.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-table/src/lib.rs
  tests/expressions/test_expressions.py
  tests/table/test_is_in.py
Labels: enhancement

#1819 [CHORE] Add is_in to docs
  docs/source/api_docs/expressions.rst
Labels: documentation, chore

#1755 [FEAT] [Join Optimizations] Add sort-merge join.
  daft/context.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/partitioning.py
  daft/table/micropartition.py
  daft/table/table.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-core/src/kernels/search_sorted.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/python.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/join.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/optimization/rules/push_down_filter.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/sort_merge_join.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/planner.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/joins/merge_join.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/python.rs
  tests/conftest.py
  tests/cookbook/test_joins.py
  tests/dataframe/test_joins.py
  tests/table/test_joins.py
Labels: enhancement
