Repository Eventual-Inc/Daft, pull requests merged in 2024-08, with the labels that each got.

#2586 [BUG] Fix parquet reads when a top-level column's final row spans more than one data page
  src/arrow2/src/io/parquet/read/deserialize/binary/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/boolean/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/dictionary/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/fixed_size_binary/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/mod.rs
  src/arrow2/src/io/parquet/read/deserialize/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/nested_utils.rs
  src/arrow2/src/io/parquet/read/deserialize/null/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/primitive/nested.rs
  src/arrow2/src/io/parquet/read/row_group.rs
  src/daft-parquet/src/file.rs
  tests/io/test_parquet.py
Labels: bug

#2593 [FEAT] Make the `end` argument for `.list.slice()` optional
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/functions/list/slice.rs
  tests/table/list/test_list_slice.py
Labels: enhancement

#2595 [CHORE]: ignore ".zed" directory
  .gitignore
Labels: chore

#2600 [CHORE] Fix imports on jupyter notebook examples
  docs/source/10-min.ipynb
  docs/source/user_guide/fotw/fotw-000-data-access.ipynb
  tutorials/mnist.ipynb
Labels: documentation, chore

#2594 [FEAT] Add support for pyiceberg v0.7
  .github/workflows/python-package.yml
  benchmarking/parquet/benchmark-requirements.txt
  daft/dataframe/dataframe.py
  daft/table/table_io.py
  requirements-dev.txt
  tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
Labels: enhancement

#2604 [FEAT] Add comparison of timestamps with same timezone
  src/arrow2/src/array/ord.rs
  tests/dataframe/test_temporals.py
  tests/series/test_comparisons.py
Labels: enhancement

#2605 [BUG]: remove simsimd dependency
  Cargo.lock
  src/daft-functions/Cargo.toml
  src/daft-functions/src/distance/cosine.rs
Labels: bug

#2592 [FEAT] Streaming Local Parquet Reads
  Cargo.lock
  src/daft-csv/src/read.rs
  src/daft-json/src/read.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-physical-plan/src/translate.rs
  tests/benchmarks/test_local_tpch.py
Labels: enhancement

#2597 [CHORE] Refactor UDFs to separate stateful and stateless
  Cargo.lock
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/udf.py
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/partial_udf.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-table/src/ops/agg.rs
Labels: chore

#2609 [CHORE] Use parquet for native tpch benchmarks
  tests/benchmarks/test_local_tpch.py
Labels: chore

#2490 docs: Add fotw tutorial on working with images
  docs/source/user_guide/fotw/fotw-001-images.ipynb
Labels: documentation

#2589 [FEAT] Add `.list.sort()` for sorting lists within a list column
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/list_sort.rs
  tests/series/test_list.py
  tests/table/list/test_list_sort.py
Labels: documentation, enhancement

#2618 [PERF] Dyn Compare + Probe Table
  src/arrow2/src/array/dyn_ord.rs
  src/arrow2/src/array/mod.rs
  src/daft-core/src/schema.rs
  src/daft-core/src/utils/dyn_compare.rs
  src/daft-core/src/utils/mod.rs
  src/daft-table/src/growable/mod.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/ops/mod.rs
  src/daft-table/src/probe_table/mod.rs
Labels: performance

#2622 [BUG] Fix pushdown past monotonically increasing id
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
Labels: bug

#2624 [BUG] Fix Expr::with_new_children for ScalarFunction
  src/daft-dsl/src/expr.rs
Labels: bug

#2621 [FEAT] Enable broadcast strategy on anti and semi joins
  daft/dataframe/dataframe.py
  src/daft-plan/src/physical_planner/translate.rs
  tests/dataframe/test_joins.py
Labels: enhancement

#2601 [FEAT] Add ActorPoolProject logical and physical plans
  daft/daft.pyi
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/expressions/expressions.py
  daft/udf.py
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/Cargo.toml
  src/daft-plan/Cargo.toml
  src/daft-plan/src/logical_ops/actor_pool_project.rs
  src/daft-plan/src/logical_ops/mod.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/actor_pool_project.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_optimization/rules/reorder_partition_keys.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
Labels: enhancement

#2599 [PERF] Swordfish Dynamic Pipelines
  Cargo.lock
  src/daft-core/src/array/growable/mod.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/sink.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-table/src/probe_table/mod.rs
Labels: performance

#2619 [FEAT]: mermaid formatter
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/dataframe/display.py
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/utils.py
  src/common/display/Cargo.toml
  src/common/display/src/lib.rs
  src/common/display/src/mermaid.rs
  src/common/display/src/tree.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
Labels: enhancement

#2630 [CHORE] Split resource-request and hashable-float-wrapper into utility crates
  Cargo.lock
  Cargo.toml
  src/common/hashable-float-wrapper/Cargo.toml
  src/common/hashable-float-wrapper/src/lib.rs
  src/common/resource-request/Cargo.toml
  src/common/resource-request/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/is_in.rs
  src/daft-core/src/utils/mod.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/numeric/mod.rs
  src/daft-dsl/src/lit.rs
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/local_plan.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/actor_pool_project.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_ops/actor_pool_project.rs
  src/daft-plan/src/physical_ops/project.rs
  src/lib.rs
Labels: chore

#2633 [CHORE] Track memory for swordfish tpch
  requirements-dev.txt
  tests/benchmarks/conftest.py
  tests/benchmarks/test_local_tpch.py
Labels: chore

#2635 [BUG] Fix projection pushdowns not working with limits
  src/daft-plan/src/logical_optimization/optimizer.rs
Labels: bug

#2620 [FEAT] Remote parquet streaming
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/parquet2/src/read/page/stream.rs
Labels: enhancement

#2636 [FEAT] factor mermaid builder into it's own module to use independently
  src/common/display/src/mermaid.rs
Labels: enhancement

#2629 [FEAT] Add wildcards in column expressions
  Cargo.lock
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  docs/source/user_guide/basic_concepts/expressions.rst
  docs/source/user_guide/daft_in_depth/dataframe-operations.rst
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/resolve_expr.rs
  src/daft-plan/src/logical_ops/filter.rs
  src/daft-plan/src/logical_ops/pivot.rs
  tests/dataframe/test_wildcard.py
Labels: documentation, enhancement

#2639 [CHORE] Upgrade Rust toolchain to 2024-08-01
  Cargo.lock
  daft/expressions/expressions.py
  rust-toolchain.toml
  src/arrow2/Cargo.toml
  src/arrow2/src/array/dictionary/typed_iterator.rs
  src/arrow2/src/array/mod.rs
  src/arrow2/src/bitmap/utils/zip_validity.rs
  src/arrow2/src/buffer/immutable.rs
  src/arrow2/src/compute/cast/mod.rs
  src/arrow2/src/compute/comparison/mod.rs
  src/arrow2/src/compute/sort/row/interner.rs
  src/arrow2/src/datatypes/mod.rs
  src/arrow2/src/io/csv/write/mod.rs
  src/arrow2/src/io/json/write/mod.rs
  src/arrow2/src/io/parquet/read/indexes/mod.rs
  src/arrow2/src/io/parquet/write/utils.rs
  src/arrow2/src/lib.rs
  src/arrow2/src/scalar/fixed_size_list.rs
  src/arrow2/src/temporal_conversions.rs
  src/common/treenode/src/lib.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-dsl/src/lit.rs
  src/parquet2/src/read/compression.rs
  tests/table/numeric/test_numeric.py
  tools/check_for_rustls.sh
Labels: chore

#2632 [FEAT] Move resource requests to UDFs instead of on with_column
  Cargo.lock
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/execution/rust_physical_plan_shim.py
  daft/expressions/expressions.py
  daft/logical/builder.py
  daft/udf.py
  docs/source/user_guide/daft_in_depth/udf.rst
  src/common/resource-request/src/lib.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/logical_ops/actor_pool_project.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/actor_pool_project.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_optimization/rules/reorder_partition_keys.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
  tests/test_resource_requests.py
  tutorials/delta_lake/1-local-image-batch-inference.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
Labels: documentation, enhancement

#2641 [CHORE] Add toolchain check to Makefile
  Makefile
Labels: chore

#2634 [FEAT] Support __init__ arguments for StatefulUDFs
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/udf.py
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/pyobj_serde.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/python.rs
  tests/expressions/test_udf.py
Labels: documentation, enhancement

#2631 [BUG] Fix join op names and join key definition
  Cargo.lock
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/join.rs
  src/daft-dsl/src/lib.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_ops/join.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/ops/mod.rs
  tests/dataframe/test_joins.py
  tests/table/test_joins.py
Labels: bug

#2643 [BUG] Fix nested parquet reads for .show() and .limit()
  src/arrow2/src/io/parquet/read/deserialize/nested_utils.rs
  tests/io/test_parquet.py
Labels: bug

#2642 [CHORE] Add ignore for helix editor
  .gitignore
Labels: chore

#2596 [FEAT]: more sql functions
  Cargo.lock
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lit.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/error.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
Labels: enhancement

#2645 [FEAT] use ObfuscatedString to hide creds when Display IOConfig
  Cargo.lock
  src/common/io-config/Cargo.toml
  src/common/io-config/src/azure.rs
  src/common/io-config/src/gcs.rs
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/s3_like.rs
Labels: enhancement

#2628 [CHORE] Improve swordfish error handling
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/intermediate_ops/state.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-physical-plan/src/local_plan.rs
Labels: chore

#2652 [BUG] Fix issues where we check "is_ray_runner" on non-initialized contexts
  daft/context.py
Labels: bug

#2647 [CHORE] Set `Expression.str.normalize()` options to False by default
  daft/expressions/expressions.py
  daft/series.py
Labels: chore

#2651 [FEAT] Add input batching for UDFs
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/udf.py
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  tests/expressions/test_udf.py
Labels: enhancement

#2661 [CHORE]: fix feature flags
  src/daft-plan/Cargo.toml
Labels: chore

#2659 [BUG] Fix filter pushdown into non-inner joins
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_plan.rs
  tests/integration/iceberg/docker-compose/docker-compose.yml
  tests/integration/io/docker-compose/docker-compose.yml
Labels: bug

#2654 [FEAT] Deprecates usage of resource_request on df.with_column API
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-plan/src/builder.rs
  tests/test_resource_requests.py
Labels: enhancement

#2664 [CHORE] bump dev version to 0.3.0
  Cargo.lock
  Cargo.toml
Labels: chore

#2665 [CHORE]: Drop use of deprecated form "default_features"
  src/arrow2/Cargo.toml
  src/common/io-config/Cargo.toml
  src/daft-io/Cargo.toml
  src/daft-scheduler/Cargo.toml
Labels: chore

#2656 [FEAT]: `daft.sql_expr`
  daft/__init__.py
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/sql/sql.py
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  tests/dataframe/test_filter.py
  tests/sql/test_sql.py
Labels: enhancement

#2657 [FEAT] Add hashing and groupby on structs
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/datatypes/matching.rs
  tests/series/test_hash.py
  tests/table/test_table_aggs.py
Labels: enhancement

#2662 [FEAT] Add `to_struct` function for merging columns into a struct
  daft/__init__.py
  daft/daft.pyi
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  src/daft-dsl/src/expr.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/to_struct.rs
  tests/dataframe/test_to_struct.py
  tests/table/struct/test_to_struct.py
Labels: documentation, enhancement

#2640 [FEAT]: refactor tree display to get more info into physicalplan
  .history
  Cargo.lock
  src/common/display/Cargo.toml
  src/common/display/src/ascii.rs
  src/common/display/src/lib.rs
  src/common/display/src/mermaid.rs
  src/common/display/src/tree.rs
  src/common/treenode/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/schema.rs
  src/daft-dsl/src/treenode.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/drop_repartition.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/actor_pool_project.rs
  src/daft-plan/src/physical_ops/agg.rs
  src/daft-plan/src/physical_ops/broadcast_join.rs
  src/daft-plan/src/physical_ops/coalesce.rs
  src/daft-plan/src/physical_ops/concat.rs
  src/daft-plan/src/physical_ops/csv.rs
  src/daft-plan/src/physical_ops/deltalake_write.rs
  src/daft-plan/src/physical_ops/empty_scan.rs
  src/daft-plan/src/physical_ops/explode.rs
  src/daft-plan/src/physical_ops/fanout.rs
  src/daft-plan/src/physical_ops/filter.rs
  src/daft-plan/src/physical_ops/flatten.rs
  src/daft-plan/src/physical_ops/hash_join.rs
  src/daft-plan/src/physical_ops/iceberg_write.rs
  src/daft-plan/src/physical_ops/in_memory.rs
  src/daft-plan/src/physical_ops/json.rs
  src/daft-plan/src/physical_ops/lance_write.rs
  src/daft-plan/src/physical_ops/limit.rs
  src/daft-plan/src/physical_ops/mod.rs
  src/daft-plan/src/physical_ops/monotonically_increasing_id.rs
  src/daft-plan/src/physical_ops/parquet.rs
  src/daft-plan/src/physical_ops/pivot.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_ops/reduce.rs
  src/daft-plan/src/physical_ops/sample.rs
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-plan/src/physical_ops/sort.rs
  src/daft-plan/src/physical_ops/sort_merge_join.rs
  src/daft-plan/src/physical_ops/split.rs
  src/daft-plan/src/physical_ops/unpivot.rs
  src/daft-plan/src/physical_optimization/plan_context.rs
  src/daft-plan/src/physical_optimization/rules/drop_repartition.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-plan/src/treenode.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/lib.rs
  src/daft-table/src/lib.rs
Labels: enhancement, chore

#2671 [FEAT] Support passing in column name strings to `to_struct`
  daft/expressions/expressions.py
  tests/table/struct/test_to_struct.py
Labels: enhancement

#2653 [FEAT] Changes the default count() behavior to perform a global row count instead
  daft/dataframe/dataframe.py
  tests/cookbook/test_count_rows.py
  tests/io/test_parquet.py
Labels: enhancement

#2673 [BUG] Fix struct `.hash()` naming bug
  src/daft-core/src/array/ops/hash.rs
  tests/table/test_hash.py
Labels: bug

#2666 [FEAT]: sql like & ilike
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
Labels: enhancement

#2675 [DOCS]: add docs for cosine_distance
  docs/source/api_docs/expressions.rst
Labels: documentation

#2668 [FEAT] (ACTORS-1) Add DAFT_ENABLE_ACTOR_POOL_PROJECTS=1 feature flag and specifying concurrency
  daft/context.py
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/udf.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/logical_ops/actor_pool_project.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/physical_ops/actor_pool_project.rs
  src/daft-plan/src/physical_optimization/rules/reorder_partition_keys.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
Labels: enhancement

#2648 [FEAT] Example Analyze for Local Execution Engine
  Cargo.lock
  src/common/display/src/lib.rs
  src/common/display/src/mermaid.rs
  src/common/display/src/utils.rs
  src/daft-io/src/stats.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-plan/src/display.rs
Labels: enhancement

#2660 [CHORE] Add error snafus for local executor
  Cargo.lock
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
Labels: chore

#2678 [BUG] Fix swordfish inner joins
  src/daft-local-execution/src/sinks/hash_join.rs
Labels: bug

#2681 [FEAT]: add to_arrow_iter
  daft/dataframe/dataframe.py
  tests/table/test_from_py.py
Labels: enhancement

#2685 [FEAT] Add dataframe iteration on rows and change default buffer size
  daft/dataframe/dataframe.py
  docs/source/api_docs/dataframe.rst
Labels: documentation, enhancement

#2670 [BUG] Add timeout to analytics client
  daft/analytics.py
  tests/test_analytics.py
Labels: bug

#2655 [CHORE] Deprecate schema hints
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  tests/dataframe/test_creation.py
  tests/io/test_parquet.py
Labels: chore

#2691 [DOCS] Add join types, renaming behavior, and example to join docs
  daft/dataframe/dataframe.py
Labels: documentation

#2693 [BUG] Use Daft Pickle instead of Ray Pickle and use bincode for serializing
  Cargo.lock
  src/common/py-serde/src/python.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit.rs
  src/daft-dsl/src/pyobj_serde.rs
  src/daft-dsl/src/pyobject.rs
Labels: bug

#2688 [BUG]: repr mermaid fix
  daft/daft.pyi
  daft/dataframe/display.py
  daft/logical/builder.py
  daft/plan_scheduler/physical_plan_scheduler.py
  src/common/display/src/lib.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-scheduler/src/scheduler.rs
Labels: bug

#2676 [FEAT] Allow user provided schema and schema inference length for read_sql
  daft/daft.pyi
  daft/io/_sql.py
  daft/logical/schema.py
  daft/sql/sql_connection.py
  daft/sql/sql_scan.py
  src/daft-core/src/python/schema.rs
  tests/integration/sql/conftest.py
  tests/integration/sql/test_sql.py
Labels: enhancement

#2695 [FEAT] Ellipsize scan task sources if too many
  src/daft-scan/src/lib.rs
Labels: enhancement

#2697 [CHORE] Fix FOTW #001 images notebook
  docs/source/user_guide/fotw/fotw-001-images.ipynb
Labels: documentation, chore

#2699 [PERF] Add ability to automatically choose broadcast for anti/semi joins
  src/daft-plan/src/physical_planner/translate.rs
Labels: performance

#2658 [BUG] Fix Parquet reads with chunk sizing
  daft/daft.pyi
  daft/io/_parquet.py
  src/arrow2/src/io/parquet/read/deserialize/binary/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/boolean/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/dictionary/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/fixed_size_binary/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/nested_utils.rs
  src/arrow2/src/io/parquet/read/deserialize/null/nested.rs
  src/arrow2/src/io/parquet/read/deserialize/primitive/nested.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-scan/src/file_format.rs
  tests/integration/io/parquet/test_reads_public_data.py
  tests/io/test_parquet.py
Labels: bug

#2700 [CHORE] fix merge conflict in repr tests
  src/daft-scan/src/lib.rs
Labels: chore

#2696 [CHORE] Enable codspeed benchmarking
  .github/workflows/python-package.yml
  CONTRIBUTING.md
  benchmarking/parquet/README.md
  pyproject.toml
  requirements-dev.txt
  tests/benchmarks/conftest.py
  tests/benchmarks/test_concat.py
  tests/benchmarks/test_local_tpch.py
Labels: chore

#2707 [BUG] Fix Resource Request Serialization and factor our Serialize Object as bincode
  Cargo.lock
  src/common/py-serde/Cargo.toml
  src/common/py-serde/src/lib.rs
  src/common/py-serde/src/python.rs
  src/common/resource-request/Cargo.toml
  src/common/resource-request/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/count_mode.rs
  src/daft-core/src/join.rs
  src/daft-core/src/python/datatype.rs
  src/daft-core/src/python/field.rs
  src/daft-core/src/python/schema.rs
  src/daft-core/src/utils/mod.rs
  src/daft-csv/Cargo.toml
  src/daft-csv/src/options.rs
  src/daft-dsl/src/python.rs
  src/daft-json/Cargo.toml
  src/daft-json/src/options.rs
  src/daft-plan/src/source_info/file_info.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/storage_config.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
  src/parquet2/src/lib.rs
  tests/test_resource_requests.py
Labels: bug

#2706 [CHORE] Speed up parquet integration test
  tests/io/test_parquet.py
Labels: chore

#2694 [PERF] Fix excessive parquet metadata reading
  Cargo.lock
  daft/daft.pyi
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/Cargo.toml
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  src/parquet2/Cargo.toml
  src/parquet2/src/metadata/column_chunk_metadata.rs
  src/parquet2/src/metadata/file_metadata.rs
  src/parquet2/src/metadata/mod.rs
  src/parquet2/src/read/mod.rs
Labels: performance

#2711 [CHORE] Add no benchmark flag for integration io tests
  .github/workflows/nightlies-tests.yml
  .github/workflows/python-package.yml
Labels: chore

#2701 [FEAT]: huggingface integration
  Cargo.lock
  daft/daft.pyi
  docs/source/user_guide/integrations.rst
  docs/source/user_guide/integrations/huggingface.rst
  src/common/io-config/src/http.rs
  src/common/io-config/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/file_format.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/huggingface.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/sink.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
Labels: documentation, enhancement

#2667 [FEAT] Stream results from native executor into python
  Cargo.lock
  daft/context.py
  daft/daft.pyi
  daft/execution/native_executor.py
  daft/runners/pyrunner.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/buffer.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/state.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/src/ops/slice.rs
Labels: enhancement

#2715 Update PreCommit Hooks
  .pre-commit-config.yaml
  benchmarking/tpch/data_generation.py
  benchmarking/tpch/pipelined_data_generation.py
  daft/context.py
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  docs/source/10-min.ipynb
  docs/source/user_guide/fotw/fotw-000-data-access.ipynb
  docs/source/user_guide/fotw/fotw-001-images.ipynb
  tests/expressions/test_udf.py
  tests/integration/io/test_list_files_s3_minio.py
  tutorials/delta_lake/1-local-image-batch-inference.ipynb
  tutorials/delta_lake/2-distributed-batch-inference.ipynb
  tutorials/delta_lake/3-pytorch-ray-single-node-training.ipynb
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
  tutorials/flyte/notebook.ipynb
  tutorials/image_querying/top_n_red_color.ipynb
  tutorials/intro.ipynb
  tutorials/mnist.ipynb
  tutorials/talks_and_demos/data-ai-summit-2024.ipynb
  tutorials/talks_and_demos/iceberg_summit_2024.ipynb
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
  tutorials/talks_and_demos/pydata_global_2023.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
  tutorials/text_to_image/using_cloud_with_ray.ipynb
Labels: documentation

#2713 [BUG] Add a with_execution/planning_config context manager and fix tests for splitting of parquet
  daft/__init__.py
  daft/context.py
  daft/runners/ray_runner.py
  docs/source/api_docs/configs.rst
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/read.rs
  tests/benchmarks/test_local_tpch.py
  tests/conftest.py
  tests/cookbook/test_write.py
  tests/dataframe/test_aggregations.py
  tests/integration/io/parquet/test_reads_public_data.py
  tests/integration/sql/test_sql.py
  tests/io/delta_lake/test_table_read.py
  tests/io/delta_lake/test_table_write.py
  tests/io/test_merge_scan_tasks.py
  tests/io/test_split_scan_tasks.py
  tests/ray/runner.py
Labels: bug, documentation

#2716 [CHORE] switch CI to use UV
  .github/workflows/daft-profiling.yml
  .github/workflows/nightlies-tests.yml
  .github/workflows/python-package.yml
  .github/workflows/python-publish.yml
  .github/workflows/ray-compatibility.yml
Labels: chore

#2627 [FEAT] (ACTORS-2) Add optimization pass to split Project into ActorPoolProject
  Cargo.lock
  Cargo.toml
  daft/udf.py
  src/daft-dsl/src/expr.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/logical_optimization/optimizer.rs
  src/daft-plan/src/logical_optimization/rules/mod.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
  src/daft-plan/src/logical_optimization/test/mod.rs
Labels: documentation, enhancement

#2717 [DOCS] Partitioning user guide and small doc fixes
  daft/expressions/expressions.py
  docs/source/api_docs/dataframe.rst
  docs/source/migration_guides/coming_from_dask.rst
  docs/source/user_guide/integrations/delta_lake.rst
  docs/source/user_guide/integrations/hudi.rst
  docs/source/user_guide/integrations/huggingface.rst
  docs/source/user_guide/integrations/microsoft-azure.rst
  docs/source/user_guide/integrations/sql.rst
  docs/source/user_guide/poweruser/distributed-computing.rst
  docs/source/user_guide/poweruser/partitioning.rst
Labels: documentation

#2705 [BUG] Use python logging level
  daft/daft.pyi
  daft/logging.py
  src/lib.rs
  tests/test_logger.py
Labels: bug

#2680 [FEAT] Fix projection pushdowns in actor pool project
  src/daft-plan/src/logical_ops/actor_pool_project.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
Labels: enhancement

#2724 [BUG]: use recordbatch instead of table for `df.to_arrow_iter`
  daft/dataframe/dataframe.py
  tests/table/test_from_py.py
Labels: bug

#2721 [DOCS] Fix small typo in partitioning.rst
  docs/source/user_guide/poweruser/partitioning.rst
Labels: documentation

#2674 [FEAT] (ACTORS-3) Propagate feature flags from Planning Config through to logical optimizer
  Cargo.lock
  daft/daft.pyi
  daft/logical/builder.py
  daft/sql/sql.py
  src/common/daft-config/src/lib.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/display.rs
  src/daft-plan/src/logical_optimization/mod.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
Labels: enhancement

#2728 [DOCS]: Fix typos in UDF documentation
  daft/udf.py
Labels: documentation

#2732 [CHORE] add benchmarks for interactive reads
  .github/workflows/python-package.yml
  tests/benchmarks/test_interactive_reads.py
  tests/microbenchmarks/__init__.py
  tests/microbenchmarks/test_concat.py
  tests/microbenchmarks/test_df_arithmetic.py
  tests/microbenchmarks/test_file_read.py
  tests/microbenchmarks/test_filter.py
  tests/microbenchmarks/test_groups_and_aggs.py
  tests/microbenchmarks/test_if_else.py
  tests/microbenchmarks/test_join.py
  tests/microbenchmarks/test_repartition.py
  tests/microbenchmarks/test_sort.py
  tests/microbenchmarks/test_take.py
Labels: chore

#2729 [BUG]: fsl to list with validity
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/get.rs
Labels: bug

#2726 [BUG] Add marker prefixes to filter during reads
  src/daft-io/src/object_store_glob.rs
  tests/integration/io/parquet/test_reads_s3_minio.py
Labels: bug

#2733 [BUG] Fix `count("*")` behavior
  daft/dataframe/dataframe.py
  tests/dataframe/test_count.py
Labels: bug

#2745 [CHORE] disables aqe tests in CI
  .github/workflows/python-package.yml
Labels: chore

#2744 [CHORE] add large fake files for benchmarks (disabled)
  tests/benchmarks/test_interactive_reads.py
  tests/benchmarks/test_local_tpch.py
Labels: chore

#2748 [CHORE] early terminate read parquet bulk
  src/daft-parquet/src/read.rs
Labels: chore

#2750 [CHORE] Add .lldbinit for debugging
  .lldbinit
Labels: chore

#2752 [CHORE]: remove this file
  .history
Labels: chore

#2725 [FEAT] Adds SQL function modules
  Cargo.lock
  Cargo.toml
  src/daft-sql/Cargo.toml
  src/daft-sql/src/error.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-sql/src/modules/float.rs
  src/daft-sql/src/modules/image.rs
  src/daft-sql/src/modules/json.rs
  src/daft-sql/src/modules/list.rs
  src/daft-sql/src/modules/map.rs
  src/daft-sql/src/modules/mod.rs
  src/daft-sql/src/modules/numeric.rs
  src/daft-sql/src/modules/partitioning.rs
  src/daft-sql/src/modules/python.rs
  src/daft-sql/src/modules/sketch.rs
  src/daft-sql/src/modules/structs.rs
  src/daft-sql/src/modules/temporal.rs
  src/daft-sql/src/modules/utf8.rs
Labels: enhancement

#2759 [BUG] Fix `set_execution_config` not setting `hash_join_partition_size_leniency`
  daft/context.py
Labels: bug

#2762 [FEAT] expose more type info
  daft/daft.pyi
  daft/datatype.py
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/python/datatype.rs
Labels: enhancement

#1809 [DOCS] Fix struct accessors in tutorial examples
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Labels: documentation

#2719 [CHORE] Refactor local hash joins + pipeline connections
  Cargo.lock
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
Labels: chore

#2687 [BUG] Enable Spawn Functions for IO and Compute Functions
  Cargo.lock
  daft/io/__init__.py
  src/daft-csv/src/metadata.rs
  src/daft-csv/src/read.rs
  src/daft-functions/src/tokenize/bpe.rs
  src/daft-functions/src/uri/download.rs
  src/daft-functions/src/uri/upload.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/lib.rs
  src/daft-io/src/python.rs
  src/daft-io/src/s3_like.rs
  src/daft-json/src/read.rs
  src/daft-json/src/schema.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/glob.rs
  src/daft-scan/src/scan_task_iters.rs
  src/daft-scan/src/storage_config.rs
  tests/integration/io/test_url_download_public_aws_s3.py
Labels: bug

#2755 [FEAT] Add support for sum aggregation for decimal128 type
  src/daft-core/src/array/ops/sum.rs
  src/daft-core/src/datatypes/agg_ops.rs
  src/daft-core/src/series/ops/agg.rs
  tests/dataframe/test_decimals.py
  tests/expressions/typing/conftest.py
  tests/expressions/typing/test_aggs.py
Labels: enhancement

#2761 [CHORE] Fix conditional compilation for UDFs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/functions/python/runtime_py_object.rs
  src/daft-dsl/src/functions/python/udf.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/Cargo.toml
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/logical_optimization/rules/split_actor_pool_projects.rs
  src/daft-scheduler/src/scheduler.rs
Labels: chore

#2735 [BUG] Fix ScanTask memory estimations when limits are provided
  daft/daft.pyi
  daft/execution/execution_step.py
  src/daft-plan/src/physical_ops/scan.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
Labels: bug

#2718 [FEAT] Add an `approx_count_distinct` expression (using the HLL algorithm)
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-core/Cargo.toml
  src/daft-core/src/array/from.rs
  src/daft-core/src/array/ops/approx_count_distinct.rs
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/array/ops/hll_merge.rs
  src/daft-core/src/array/ops/hll_sketch.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/hash.rs
  src/daft-core/src/utils/identity_hash_set.rs
  src/daft-core/src/utils/mod.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/resolve_expr.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/hash.rs
  src/daft-table/src/probe_table/mod.rs
  src/hyperloglog/Cargo.toml
  src/hyperloglog/src/lib.rs
  tests/dataframe/test_approx_count_distinct.py
Labels: enhancement

#2758 [PERF] Make merging of ScanTasks be more conservative when provided with a LIMIT
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/io/test_merge_scan_tasks.py
Labels: performance

#2751 [BUG] Fix parquet reads with limit across row groups
  src/daft-parquet/src/stream_reader.rs
  tests/io/test_parquet.py
Labels: bug
