Repository Eventual-Inc/Daft, pull requests merged in 2024-07, with the labels that each got.

#2465 [FEAT] Microsoft Fabric support in AzureConfig
  daft/daft.pyi
  daft/io/object_store_options.py
  docs/source/user_guide/integrations/microsoft-azure.rst
  src/common/io-config/src/azure.rs
  src/common/io-config/src/python.rs
  src/daft-io/src/azure_blob.rs
Labels: documentation, enhancement

#2467 [DOCS] Fix broken example URL
  src/common/io-config/src/python.rs
Labels: documentation

#2462 [DOCS] Adds RunLLM widget
  docs/source/_static/custom.js
  docs/source/conf.py
Labels: documentation

#2480 [CHORE] Add a helpful message in build-artifact-s3 workflow
  .github/workflows/build-artifact-s3.yml
Labels: chore

#2453 [FEAT] add bit shift functions
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/apply.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/shift.rs
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/shift.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/python.rs
  src/daft-table/src/lib.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/conftest.py
  tests/expressions/typing/test_arithmetic.py
  tests/table/numeric/test_numeric.py
  tests/table/test_eval.py
Labels: documentation, enhancement

#2479 [FEAT] List slice expression
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/functions/list/slice.rs
  src/daft-dsl/src/python.rs
  tests/table/list/test_list_slice.py
Labels: enhancement

#2388 [CHORE] Add better typing for class UDFs
  daft/udf.py
Labels: chore

#2360 [DOCS] Enhance Dataframe / Expressions examples
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
Labels: documentation

#2461 [FEAT] Add upload functionality to binary columns
  Cargo.lock
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/uri/mod.rs
  src/daft-dsl/src/functions/uri/upload.rs
  src/daft-dsl/src/python.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-io/src/stats.rs
  tests/integration/io/test_files_roundtrip_s3_minio.py
  tests/integration/io/test_url_download_s3_minio.py
  tests/io/test_url_upload_local.py
Labels: enhancement

#2488 [BUG] Support delta-rs version >0.17.4 in deltalake writes
  daft/table/table_io.py
  requirements-dev.txt
Labels: bug

#2486 [BUG] Use Daft s3 credentials chain for deltalake reads
  daft/delta_lake/delta_lake_scan.py
Labels: bug

#2464 [FEAT] Implement hashing and groupby on lists
  src/daft-core/src/array/ops/groups.rs
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/series/ops/groups.rs
  src/daft-core/src/series/ops/hash.rs
  tests/series/test_hash.py
  tests/table/test_table_aggs.py
Labels: enhancement

#2437 [FEAT] New Local Execution Model
  Cargo.lock
  Cargo.toml
  daft/runners/pyrunner.py
  src/daft-execution/src/stage/run.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/create_pipeline.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/mod.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
Labels: enhancement

#2489 [PERF] Local Execution Plan
  Cargo.lock
  Cargo.toml
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_ops/source.rs
  src/daft-plan/src/logical_optimization/rules/push_down_filter.rs
  src/daft-plan/src/logical_optimization/rules/push_down_limit.rs
  src/daft-plan/src/logical_optimization/rules/push_down_projection.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-plan/src/source_info/mod.rs
  src/daft-scan/src/lib.rs
Labels: performance

#2466 [FEAT]: dyn function registry
  Cargo.lock
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/functions/hash.rs
  src/daft-dsl/src/functions/json/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/registry.rs
  src/daft-dsl/src/functions/scalar.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-plan/src/logical_ops/project.rs
  src/daft-plan/src/partitioning.rs
  src/daft-table/src/lib.rs
Labels: enhancement

#2497 [FEAT] Refactors and agg improvements for new local execution model
  Cargo.lock
  daft/daft.pyi
  daft/execution/native_executor.py
  daft/runners/pyrunner.py
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/create_pipeline.rs
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/physical_planner/mod.rs
  src/daft-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/scheduler.rs
  src/lib.rs
Labels: enhancement

#2491 [FEAT] List chunk expression
  daft/daft.pyi
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/datatypes/field.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/functions/list/chunk.rs
  src/daft-dsl/src/functions/list/mod.rs
  src/daft-dsl/src/python.rs
  tests/table/list/test_list_chunk.py
Labels: documentation, enhancement

#2508 [BUG] Add retries for write timeout errors
  daft/table/table_io.py
Labels: bug

#2384 [DOCS] Tutorial: FOTW data access
  .pre-commit-config.yaml
  docs/source/user_guide/fotw/data/census001.csv
  docs/source/user_guide/fotw/data/census002.csv
  docs/source/user_guide/fotw/data/census003.csv
  docs/source/user_guide/fotw/data/sample_taxi.parquet
  docs/source/user_guide/fotw/data/sampled-tpch.jsonl
  docs/source/user_guide/fotw/fotw-000-data-access.ipynb
  docs/source/user_guide/fotw/index.rst
  docs/source/user_guide/index.rst
Labels: documentation

#2498 [FEAT] adding transform functionality
  daft/dataframe/dataframe.py
  docs/source/api_docs/dataframe.rst
  tests/dataframe/test_transform.py
Labels: documentation, enhancement

#2358 [PERF]: dont read parquet metadata multiple times
  Cargo.lock
  daft/daft.pyi
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/common.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-plan/src/physical_planner/planner.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
Labels: performance

#2517 [BUG] merge conflict for python catalog scan task
  src/daft-execution/src/test/mod.rs
  src/daft-scan/src/python.rs
Labels: bug

#2516 [CHORE] Disable Python as default feature and have maturin enable it by default
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.toml
  pyproject.toml
  src/common/daft-config/Cargo.toml
  src/common/error/Cargo.toml
  src/common/io-config/Cargo.toml
  src/common/py-serde/Cargo.toml
  src/common/system-info/Cargo.toml
  src/common/treenode/Cargo.toml
  src/daft-core/Cargo.toml
  src/daft-csv/Cargo.toml
  src/daft-dsl/Cargo.toml
  src/daft-execution/Cargo.toml
  src/daft-functions/Cargo.toml
  src/daft-io/Cargo.toml
  src/daft-json/Cargo.toml
  src/daft-local-execution/Cargo.toml
  src/daft-micropartition/Cargo.toml
  src/daft-parquet/Cargo.toml
  src/daft-plan/Cargo.toml
  src/daft-scan/Cargo.toml
  src/daft-scheduler/Cargo.toml
  src/daft-stats/Cargo.toml
  src/daft-table/Cargo.toml
Labels: chore

#2515 [CHORE] fix incremental builds with vscode rust analyzer
  .gitignore
  .vscode/settings.json
  Makefile
Labels: chore

#2507 [FEAT] Math Ops for FixedSizeList / FixedShapeTensor / Embedding Type
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/datatypes/binary_ops.rs
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/lib.rs
  src/daft-core/src/series/array_impl/binary_ops.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/repeat.rs
  tests/dataframe/test_tensor_math.py
Labels: enhancement

#2519 [FEAT] Add concat to new execution model + buffered intermediate ops
  Cargo.lock
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/create_pipeline.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/sink.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
Labels: enhancement

#2522 [FEAT] Decouple pipeline building and running from new executor
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
Labels: enhancement

#2523 [CHORE] add pytest benchmarking for local testing of execution engine
  daft/runners/pyrunner.py
  tests/benchmarks/test_local_tpch.py
Labels: chore

#2528 [BUG] With_new_children not implemented for sample
  src/daft-plan/src/logical_plan.rs
  tests/dataframe/test_sample.py
Labels: bug

#2514 [BUG] Allow for Parquet reading from files with differing schemas
  daft/table/table.py
  src/daft-csv/src/read.rs
  src/daft-execution/src/task/mod.rs
  src/daft-execution/src/test/mod.rs
  src/daft-json/src/local.rs
  src/daft-json/src/read.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-plan/src/source_info/file_info.rs
  src/daft-stats/src/table_stats.rs
  src/daft-table/src/ffi.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/agg.rs
  src/daft-table/src/ops/explode.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/ops/pivot.rs
  src/daft-table/src/ops/unpivot.rs
  src/daft-table/src/python.rs
  tests/dataframe/test_creation.py
  tests/integration/io/parquet/test_reads_s3_minio.py
  tests/table/table_io/test_parquet.py
Labels: bug

#2531 [BUG] Fix bug with multi-partition `any_value`
  src/daft-plan/src/physical_planner/translate.rs
  tests/dataframe/test_aggregations.py
Labels: bug

#2502 [BUG] Use shared thread pool for multiple running instances of df on pyrunner
  daft/runners/pyrunner.py
Labels: bug

#2532 [BUG] Fix bug with map_groups UDFs that return more than 1 output row for empty partitions
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-table/src/ops/agg.rs
  tests/dataframe/test_map_groups.py
Labels: bug

#2518 [CHORE]: move minhash to daft-functions
  daft/daft.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/minhash.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/minhash.rs
Labels: chore

#2538 [DOCS] Build PDF and htmlzip formats of docs for offline consumption
  .readthedocs.yaml
Labels: documentation

#2539 [DOCS] Do not generate PDFs
  .readthedocs.yaml
Labels: documentation

#2530 [FEAT] Add hashjoin, sort, and hashagg ops to new executor
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-physical-plan/src/local_plan.rs
  src/daft-physical-plan/src/translate.rs
  src/daft-plan/src/lib.rs
  tests/benchmarks/test_local_tpch.py
Labels: enhancement

#2529 [BUG] Enable sorting bool columns
  src/daft-core/src/kernels/search_sorted.rs
  src/daft-plan/src/logical_ops/sort.rs
  tests/dataframe/test_sort.py
Labels: bug

#2534 [FEAT]: support optional rowgroups to `read_parquet`
  daft/daft.pyi
  daft/io/_parquet.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/file_format.rs
  src/daft-scan/src/glob.rs
  tests/io/test_parquet.py
Labels: enhancement

#2542 [BUG] Fix table filters with scalar mask
  src/daft-table/src/lib.rs
  tests/table/test_filter.py
Labels: bug

#2503 [FEAT] Add string tokenize expression
  Cargo.lock
  Cargo.toml
  daft/daft.pyi
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  pyproject.toml
  requirements-dev.txt
  src/daft-core/src/series/ops/utf8.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/lib.rs
  src/daft-functions/src/tokenize/bpe.rs
  src/daft-functions/src/tokenize/decode.rs
  src/daft-functions/src/tokenize/encode.rs
  src/daft-functions/src/tokenize/mod.rs
  src/daft-functions/src/tokenize/special_tokens.rs
  tests/assets/tokens/bad_base64.tiktoken
  tests/assets/tokens/bad_rank.tiktoken
  tests/assets/tokens/bad_token.tiktoken
  tests/assets/tokens/empty.tiktoken
  tests/assets/tokens/tokens_5k.tiktoken
  tests/expressions/test_expressions.py
  tests/integration/test_file_tokenize.py
  tests/table/test_tokenize.py
Labels: documentation, enhancement

#2299 [CHORE] Add TPC-H questions 11-22 to benchmarks (currently skipped)
  .github/workflows/daft-profiling.yml
  benchmarking/tpch/__main__.py
  benchmarking/tpch/answers.py
  tests/assets/tpch-sqlite-queries/11.sql
  tests/assets/tpch-sqlite-queries/12.sql
  tests/assets/tpch-sqlite-queries/13.sql
  tests/assets/tpch-sqlite-queries/14.sql
  tests/assets/tpch-sqlite-queries/15.sql
  tests/assets/tpch-sqlite-queries/16.sql
  tests/assets/tpch-sqlite-queries/17.sql
  tests/assets/tpch-sqlite-queries/18.sql
  tests/assets/tpch-sqlite-queries/19.sql
  tests/assets/tpch-sqlite-queries/20.sql
  tests/assets/tpch-sqlite-queries/21.sql
  tests/assets/tpch-sqlite-queries/22.sql
  tests/integration/conftest.py
  tests/integration/test_tpch.py
Labels: chore

#2544 [DOCS] Fix notebook CI
  docs/source/user_guide/fotw/fotw-000-data-access.ipynb
Labels: documentation

#2540 [FEAT] Create file when writing dataframe with no rows
  daft/daft.pyi
  daft/dataframe/dataframe.py
  daft/table/table_io.py
  src/daft-scan/src/file_format.rs
  tests/cookbook/test_write.py
Labels: enhancement

#2556 [FEAT] Add tracing to local execution engine
  Cargo.lock
  Cargo.toml
  src/common/tracing/Cargo.toml
  src/common/tracing/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/aggregate.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/hash_join.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/sink.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/lib.rs
Labels: enhancement

#2560 [CHORE] Enable all features for rust-analyzer
  .vscode/settings.json
Labels: chore

#2559 [FEAT] Initializes daft-sql and defines the daft.sql(..) function.
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/daft.pyi
  daft/io/_sql.py
  daft/sql/__init__.py
  daft/sql/sql.py
  src/daft-sql/Cargo.toml
  src/daft-sql/src/analyzer.rs
  src/daft-sql/src/catalog.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/parser.rs
  src/daft-sql/src/python.rs
  src/lib.rs
  tests/sql/test_sql.py
Labels: enhancement

#2564 [DOCS] Update Ray Dataset link
  daft/dataframe/dataframe.py
Labels: documentation

#2558 [FEAT]: daft sql
  Cargo.lock
  Cargo.toml
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/schema.rs
  src/daft-dsl/src/expr.rs
  src/daft-plan/src/builder.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/logical_plan.rs
  src/daft-plan/src/partitioning.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/catalog.rs
  src/daft-sql/src/error.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/parser.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  tests/sql/test_sql.py
Labels: enhancement

#2553 [CHORE] Remove daft-execution
  Cargo.lock
  Cargo.toml
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/pyrunner.py
  src/daft-execution/Cargo.toml
  src/daft-execution/src/executor/local/local_executor.rs
  src/daft-execution/src/executor/local/local_partition_ref.rs
  src/daft-execution/src/executor/local/mod.rs
  src/daft-execution/src/executor/mod.rs
  src/daft-execution/src/executor/ray/mod.rs
  src/daft-execution/src/executor/ray/ray_executor.rs
  src/daft-execution/src/executor/ray/ray_partition_ref.rs
  src/daft-execution/src/executor/resource_manager.rs
  src/daft-execution/src/lib.rs
  src/daft-execution/src/ops/filter.rs
  src/daft-execution/src/ops/fused.rs
  src/daft-execution/src/ops/join.rs
  src/daft-execution/src/ops/limit.rs
  src/daft-execution/src/ops/mod.rs
  src/daft-execution/src/ops/monotonically_increasing_id.rs
  src/daft-execution/src/ops/project.rs
  src/daft-execution/src/ops/scan.rs
  src/daft-execution/src/ops/shuffle.rs
  src/daft-execution/src/ops/sort.rs
  src/daft-execution/src/partition/mod.rs
  src/daft-execution/src/partition/partition_ref.rs
  src/daft-execution/src/partition/virtual_partition.rs
  src/daft-execution/src/scheduler/bulk.rs
  src/daft-execution/src/scheduler/channel.rs
  src/daft-execution/src/scheduler/mod.rs
  src/daft-execution/src/scheduler/streaming.rs
  src/daft-execution/src/scheduler/task_state.rs
  src/daft-execution/src/stage/exchange/collect.rs
  src/daft-execution/src/stage/exchange/mod.rs
  src/daft-execution/src/stage/exchange/shuffle.rs
  src/daft-execution/src/stage/exchange/sort.rs
  src/daft-execution/src/stage/mod.rs
  src/daft-execution/src/stage/planner.rs
  src/daft-execution/src/stage/run.rs
  src/daft-execution/src/stage/runner.rs
  src/daft-execution/src/stage/sink/collect.rs
  src/daft-execution/src/stage/sink/limit.rs
  src/daft-execution/src/stage/sink/mod.rs
  src/daft-execution/src/task/mod.rs
  src/daft-execution/src/test/mod.rs
  src/daft-execution/src/tree/builder.rs
  src/daft-execution/src/tree/mod.rs
  src/daft-execution/src/tree/op_state_tree.rs
  src/daft-execution/src/tree/op_tree.rs
  src/daft-execution/src/tree/queue.rs
  src/daft-execution/src/tree/topological_sort.rs
  src/daft-execution/src/tree/translate.rs
  src/daft-scheduler/Cargo.toml
  src/daft-scheduler/src/scheduler.rs
  src/lib.rs
Labels: chore

#2124 [DOCS] quickstart-revision
  docs/source/10-min.ipynb
Labels: documentation

#2563 [FEAT] Support Reading Iceberg Merge-on-Read Position Deletes
  daft/daft.pyi
  daft/delta_lake/delta_lake_scan.py
  daft/hudi/hudi_scan.py
  daft/iceberg/iceberg_scan.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-scan/src/scan_task_iters.rs
  tests/integration/iceberg/test_table_load.py
Labels: enhancement

#2565 [FEAT] Streaming CSV Reads
  Cargo.lock
  src/daft-csv/src/lib.rs
  src/daft-csv/src/read.rs
  src/daft-io/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/sink.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
Labels: enhancement

#2579 [BUG] Fix `.str.length()` on Unicode strings
  src/daft-core/src/array/ops/utf8.rs
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_length.py
Labels: bug

#2526 [FEAT]: `embedding.cosine_distance` function
  Cargo.lock
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/udf.py
  src/daft-core/src/datatypes/dtype.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/mod.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/distance/cosine.rs
  src/daft-functions/src/distance/mod.rs
  src/daft-functions/src/lib.rs
  tests/expressions/test_cosine_distance.py
Labels: enhancement

#2582 [FEAT]: streaming json
  src/daft-csv/src/read.rs
  src/daft-json/src/read.rs
  src/daft-micropartition/src/micropartition.rs
Labels: enhancement

#2577 [DOCS]: small update to "scaling-up"
  docs/source/conf.py
  docs/source/migration_guides/coming_from_dask.rst
  docs/source/user_guide/poweruser.rst
  docs/source/user_guide/poweruser/distributed-computing.rst
  docs/source/user_guide/poweruser/scaling-up.rst
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
  tutorials/intro.ipynb
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
Labels: documentation

#2580 [FEAT] Add `.str.count_matches()`
  Cargo.lock
  daft/daft.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/source/api_docs/expressions.rst
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/utf8.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/utf8.rs
  src/daft-functions/src/count_matches.rs
  src/daft-functions/src/lib.rs
  tests/series/test_utf8_ops.py
  tests/table/utf8/test_count_matches.py
Labels: documentation, enhancement

#2567 [FEAT] Fix resource accounting in PyRunner
  daft/runners/pyrunner.py
Labels: enhancement

#2583 [BUG]: accept "iterable[pa.Table]" for from_arrow
  daft/convert.py
  daft/dataframe/dataframe.py
  tests/table/test_from_py.py
Labels: bug

#2557 [PERF] Add physical plan optimizer and optimization
  daft/context.py
  daft/daft.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-dsl/src/expr.rs
  src/daft-dsl/src/lib.rs
  src/daft-plan/src/lib.rs
  src/daft-plan/src/physical_ops/project.rs
  src/daft-plan/src/physical_optimization/mod.rs
  src/daft-plan/src/physical_optimization/optimizer.rs
  src/daft-plan/src/physical_optimization/plan_context.rs
  src/daft-plan/src/physical_optimization/rules/drop_repartition.rs
  src/daft-plan/src/physical_optimization/rules/mod.rs
  src/daft-plan/src/physical_optimization/rules/reorder_partition_keys.rs
  src/daft-plan/src/physical_optimization/rules/rule.rs
  src/daft-plan/src/physical_plan.rs
  src/daft-plan/src/physical_planner/mod.rs
  src/daft-plan/src/physical_planner/translate.rs
Labels: performance
