Repository Eventual-Inc/Daft, pull requests merged in 2025-02, with the labels that each got.

#3750 feat: better sql datatype support
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_sql.py
Labels: feat

#3755 refactor: renames to_struct to just struct
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/expressions/__init__.py
  daft/expressions/expressions.py
  docs/sphinx/source/expressions.rst
  src/daft-dsl/src/expr/mod.rs
  src/daft-functions/src/python/misc.rs
  src/daft-functions/src/to_struct.rs
  tests/dataframe/test_to_struct.py
  tests/table/struct/test_to_struct.py
Labels: refactor

#3760 fix: catalog table names
  Cargo.lock
  src/daft-catalog/Cargo.toml
  src/daft-catalog/src/errors.rs
  src/daft-catalog/src/lib.rs
  tests/sql/test_catalog.py
Labels: fix

#3742 ci: send slack notification for broken links
  .github/workflows/broken-link-checker.yml
Labels: ci

#3764 docs: add footer and update broken links
  docs/mkdocs.yml
  docs/sphinx/source/_templates/sections/header.html
Labels: docs

#3688 feat(optimizer): Brute force join ordering
  src/common/scan-info/src/test/mod.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/mod.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
  src/daft-logical-plan/src/test/mod.rs
  src/daft-physical-plan/src/test/mod.rs
Labels: feat

#3766 build(docs): fix docgen failed workflow
  .github/workflows/build-docs.yml
Labels: build

#3770 fix: boolean casts to strings and null propagation
  src/arrow2/src/compute/cast/boolean_to.rs
  tests/expressions/test_list_.py
  tests/series/test_cast.py
Labels: fix

#3763 feat(catalog): Defines an identifier for use across catalogs
  daft/__init__.py
  daft/catalog/__init__.py
  daft/daft/catalog.pyi
  src/daft-catalog/src/errors.rs
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/lib.rs
  src/daft-catalog/src/python.rs
  src/daft-sql/src/planner.rs
  tests/catalog/test_identifier.py
  tests/sql/test_catalog.py
Labels: feat

#3729 ci: Record info for TPCH benchmarks
  benchmarking/tpch/ray_job_runner.py
Labels: ci

#3767 refactor: port DaftContext to rust side
  Cargo.lock
  Cargo.toml
  daft/context.py
  daft/daft/__init__.pyi
  src/common/daft-config/Cargo.toml
  src/common/resource-request/Cargo.toml
  src/common/scan-info/Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/execute.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-context/Cargo.toml
  src/daft-context/src/lib.rs
  src/daft-context/src/python.rs
  src/daft-core/Cargo.toml
  src/daft-local-execution/Cargo.toml
  src/daft-local-plan/Cargo.toml
  src/daft-physical-plan/Cargo.toml
  src/daft-py-runners/Cargo.toml
  src/daft-py-runners/src/lib.rs
  src/daft-ray-execution/src/lib.rs
  src/daft-sql/Cargo.toml
  src/lib.rs
  tests/connect/test_io.py
Labels: refactor

#3754 feat: implement bool_and and bool_or
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  docs/sphinx/source/expressions.rst
  src/daft-core/src/array/ops/bool_agg.rs
  src/daft-core/src/array/ops/list.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/list.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/list/bool_and.rs
  src/daft-functions/src/list/bool_or.rs
  src/daft-functions/src/list/mod.rs
  src/daft-functions/src/python/list.rs
  src/daft-functions/src/python/mod.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-table/src/lib.rs
  tests/dataframe/test_aggregations.py
  tests/table/list/test_list_bool_aggs.py
  tests/table/test_table_aggs.py
Labels: feat

#3777 ci: Allow TPCH benchmarks to use ARM cluster profile
  tools/tpch.py
Labels: ci

#3779 docs: update links in readme
  README.rst
Labels: docs

#3782 feat(catalog): Defines a session for connection state
  Cargo.lock
  Cargo.toml
  src/daft-catalog/python-catalog/src/python.rs
  src/daft-catalog/src/data_catalog.rs
  src/daft-catalog/src/data_catalog_table.rs
  src/daft-catalog/src/error.rs
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/lib.rs
  src/daft-connect/Cargo.toml
  src/daft-connect/src/config.rs
  src/daft-connect/src/connect_service.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/response_builder.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-session/Cargo.toml
  src/daft-session/src/error.rs
  src/daft-session/src/lib.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
Labels: feat

#3780 feat: add functions to daft-connect
  Cargo.lock
  Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/functions.rs
  src/daft-connect/src/functions/aggregate.rs
  src/daft-connect/src/functions/core.rs
  src/daft-connect/src/functions/math.rs
  src/daft-connect/src/functions/partition_transform.rs
  src/daft-connect/src/functions/string.rs
  src/daft-functions/src/float/mod.rs
  src/daft-functions/src/numeric/round.rs
  src/daft-functions/src/python/numeric.rs
  src/daft-sql/src/modules/numeric.rs
Labels: feat

#3789 feat: nulls first kernels
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  src/daft-core/src/array/ops/arrow2/sort/primitive/common.rs
  src/daft-core/src/array/ops/arrow2/sort/primitive/indices.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/series/ops/sort.rs
  src/daft-core/src/utils/mod.rs
  tests/dataframe/test_sort.py
Labels: feat

#3799 feat(connect): add temporal functions
  src/daft-connect/src/functions.rs
  src/daft-connect/src/functions/core.rs
  src/daft-connect/src/functions/datetime.rs
  src/daft-connect/src/functions/math.rs
  src/daft-connect/src/functions/partition_transform.rs
  src/daft-connect/src/functions/string.rs
Labels: feat

#3797 build: update python-publish workflow
  .github/workflows/python-publish.yml
Labels: build

#3803 docs: update README.rst diagram
  README.rst
Labels: docs

#3784 perf: Use parquet metadata from schema inference for accurate scan task statistics
  src/daft-parquet/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
Labels: perf

#3735 feat: Sequentially materialize left and right sides during hash join
  daft/execution/physical_plan.py
Labels: feat

#3593 perf(swordfish): Parallel expression evaluation
  Cargo.lock
  src/daft-dsl/src/expr/mod.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/dispatcher.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-recordbatch/Cargo.toml
  src/daft-recordbatch/src/lib.rs
Labels: perf

#3794 feat(session): Replaces direct usage of DaftCatalog with Session
  Cargo.lock
  daft/catalog/__init__.py
  daft/daft/catalog.pyi
  src/daft-catalog/src/catalog.rs
  src/daft-catalog/src/error.rs
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/lib.rs
  src/daft-catalog/src/python.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-session/Cargo.toml
  src/daft-session/src/error.rs
  src/daft-session/src/lib.rs
  src/daft-session/src/options.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  tests/catalog/test_identifier.py
  tests/sql/test_catalog.py
Labels: feat

#3809 feat(session): Adds session class to python
  Cargo.lock
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/session.py
  src/daft-session/Cargo.toml
  src/daft-session/src/lib.rs
  src/daft-session/src/python.rs
  src/lib.rs
  tests/test_session.py
Labels: feat

#3806 fix: unity managed table reads
  CONTRIBUTING.md
  daft/unity_catalog/unity_catalog.py
Labels: fix

#3768 docs: Update distributed docs to add byoc mode, change name to daft cli
  docs/mkdocs/distributed.md
Labels: docs

#3814 feat(sql): SELECT without FROM
  src/daft-sql/src/planner.rs
  tests/sql/test_select_expr.py
Labels: feat

#3810 feat: Adds .summarize() to compute statistics
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  docs/sphinx/source/dataframe.rst
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/ops/summarize.rs
  tests/dataframe/test_summarize.py
Labels: feat

#3773 docs: add scarf analytics
  README.rst
  daft/__init__.py
  daft/context.py
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/scarf_telemetry.py
  docs/mkdocs.yml
  docs/mkdocs/index.md
  docs/mkdocs/integrations/delta_lake.md
  docs/mkdocs/resources/telemetry.md
  docs/sphinx/source/_templates/sections/header.html
  docs/sphinx/source/_templates/sections/mobile-menu.html
  tests/test_scarf_telemetry.py
Labels: docs

#3824 docs: fix readthedocs build
  .gitignore
  docs/mkdocs.yml
  requirements-docs.txt
Labels: docs

#3807 perf(optimizer): Infer additional join graph edges during join reordering
  src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
  src/daft-scan/src/lib.rs
Labels: perf

#3829 fix: create series of np.datetime64['D']
  daft/series.py
  tests/series/test_series.py
Labels: fix

#3832 fix: Grab Daft config from environment variables for new contexts
  src/daft-context/src/lib.rs
Labels: fix

#3835 feat(sql): supports array of paths in read_ table-value functions
  src/daft-dsl/src/expr/mod.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/table_provider/mod.rs
  src/daft-sql/src/table_provider/read_csv.rs
  src/daft-sql/src/table_provider/read_json.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  tests/assets/json-data/sample1.jsonl
  tests/assets/json-data/sample2.jsonl
  tests/sql/test_sql_read_iceberg.py
  tests/sql/test_sql_table_functions.py
  tests/sql/test_table_functions/__init__.py
  tests/sql/test_table_functions/test_table_functions.py
Labels: feat

#3836 feat(sql): supports schemas in read_json, read_csv, read_parquet
  Cargo.lock
  src/daft-dsl/src/lit.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/schema.rs
  src/daft-sql/src/table_provider/read_csv.rs
  src/daft-sql/src/table_provider/read_json.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  tests/sql/test_sql_table_functions.py
Labels: feat

#3834 fix: Add excludes to broken link checker
  .github/workflows/broken-link-checker.yml
  docs/mkdocs/migration/dask_migration.md
Labels: fix

#3820 feat(catalog): Prepare existing catalog APIs for integration [1/3]
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__unity.py
  daft/catalog/pyiceberg.py
  daft/catalog/python_catalog.py
  daft/catalog/unity.py
  daft/daft/__init__.pyi
  src/daft-catalog/src/python.rs
  tests/catalog/test_catalog.py
  tests/sql/test_sql_catalog.py
Labels: feat

#3839 fix: Reduce number of nodes in random join graph test
  src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
Labels: fix

#3825 feat(catalog): Integrate session and catalog actions alongside existing APIs [2/3]
  Cargo.lock
  Cargo.toml
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__unity.py
  daft/daft/__init__.pyi
  daft/session.py
  src/daft-catalog/Cargo.toml
  src/daft-catalog/src/bindings.rs
  src/daft-catalog/src/catalog.rs
  src/daft-catalog/src/lib.rs
  src/daft-catalog/src/python.rs
  src/daft-catalog/src/table.rs
  src/daft-connect/src/execute.rs
  src/daft-session/Cargo.toml
  src/daft-session/src/options.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/error.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  src/lib.rs
  tests/catalog/__init__.py
  tests/catalog/test_catalog.py
  tests/test_session.py
Labels: feat

#3845 chore: remove accidental printlins
  src/daft-core/src/array/ops/comparison.rs
  src/daft-logical-plan/src/builder/mod.rs
Labels: chore

#3848 fix: LogicalPlan::get_schema_for_alias should stop when it hits any alias
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
Labels: fix

#3842 feat(sql): select from multiple joins
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
Labels: sql, feat

#3851 fix: protocol in iceberg writes
  daft/io/writer.py
Labels: fix

#3854 chore: minor cleanup to table-value functions
  src/daft-sql/src/planner.rs
  src/daft-sql/src/table_provider/read_csv.rs
  src/daft-sql/src/table_provider/read_json.rs
  src/daft-sql/src/table_provider/read_parquet.rs
  tests/sql/__init__.py
  tests/sql/test_sql_table_functions.py
Labels: chore

#3791 feat(connect): read csv/parquet/json options
  src/daft-connect/src/error.rs
  src/daft-connect/src/spark_analyzer.rs
  tests/conftest.py
  tests/connect/test_io.py
Labels: feat

#3857 chore: replace anaconda with S3 for nightly build publish
  .github/ci-scripts/generate_simple_py_index.py
  .github/workflows/build-wheel.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/python-publish.yml
Labels: chore

#3858 fix: build wheel Github action inputs
  .github/ci-scripts/generate_simple_py_index.py
  .github/workflows/build-wheel.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/publish-pypi.yml
Labels: fix

#3830 feat(catalog): Cutover deprecated APIs to use session, catalog, table abstractions [3/3]
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__unity.py
  daft/daft/__init__.pyi
  daft/daft/catalog.pyi
  daft/session.py
  src/daft-catalog/Cargo.toml
  src/daft-catalog/python-catalog/Cargo.toml
  src/daft-catalog/python-catalog/src/lib.rs
  src/daft-catalog/python-catalog/src/python.rs
  src/daft-catalog/src/catalog.rs
  src/daft-catalog/src/data_catalog.rs
  src/daft-catalog/src/data_catalog_table.rs
  src/daft-catalog/src/error.rs
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/lib.rs
  src/daft-catalog/src/python.rs
  src/daft-catalog/src/table.rs
  src/daft-session/Cargo.toml
  src/daft-session/src/error.rs
  src/daft-session/src/options.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  src/lib.rs
  tests/catalog/test_catalog_iceberg.py
  tests/connect/test_basics.py
Labels: feat

#3833 docs: Update configuration docs to show `set_runner_native`
  daft/context.py
  docs/mkdocs/advanced/memory.md
  docs/mkdocs/integrations/iceberg.md
  docs/mkdocs/resources/architecture.md
  docs/sphinx/source/configs.rst
  tests/test_context.py
  tutorials/intro.ipynb
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
Labels: docs

#3856 docs: respect daft analytics env var
  daft/scarf_telemetry.py
Labels: docs

#3860 feat(sql): adds session sql for leveraging attached catalogs
  daft/daft/__init__.pyi
  daft/session.py
  src/daft-catalog/src/python.rs
  src/daft-session/src/python.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/python.rs
  tests/sql/test_sess_sql.py
Labels: feat

#3781 feat: Stageify plan on shuffle boundaries
  .github/workflows/python-package.yml
  daft/daft/__init__.pyi
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/ray_runner.py
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/eliminate_cross_join.rs
  src/daft-logical-plan/src/optimization/rules/simplify_expressions.rs
  src/daft-logical-plan/src/source_info/mod.rs
  src/daft-physical-plan/src/display.rs
  src/daft-physical-plan/src/ops/in_memory.rs
  src/daft-physical-plan/src/ops/mod.rs
  src/daft-physical-plan/src/ops/previous_stage_scan.rs
  src/daft-physical-plan/src/optimization/rules/reorder_partition_keys.rs
  src/daft-physical-plan/src/physical_planner/display.rs
  src/daft-physical-plan/src/physical_planner/mod.rs
  src/daft-physical-plan/src/physical_planner/planner.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-scheduler/src/adaptive.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/lib.rs
Labels: feat

#3862 fix: pypi publish workflow
  .github/workflows/publish-pypi.yml
Labels: fix

#3852 feat: Emit children of join before shuffle + add stats to explain analyze
  Cargo.lock
  daft/daft/__init__.pyi
  daft/plan_scheduler/physical_plan_scheduler.py
  daft/runners/ray_runner.py
  src/common/display/src/mermaid.rs
  src/daft-logical-plan/src/display.rs
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/lib.rs
  src/daft-physical-plan/src/physical_planner/display.rs
  src/daft-physical-plan/src/physical_planner/mod.rs
  src/daft-physical-plan/src/physical_planner/planner.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-scheduler/src/adaptive.rs
Labels: feat

#3863 fix: sql round without precision
  src/daft-sql/src/modules/numeric.rs
  tests/sql/test_exprs.py
Labels: fix

#3861 feat(connect): `daft.pyspark` module
  daft/pyspark/__init__.py
  tests/connect/conftest.py
Labels: feat

#3849 feat(connect): joins
  src/common/daft-config/src/lib.rs
  src/daft-connect/src/functions.rs
  src/daft-connect/src/functions/aggregate.rs
  src/daft-connect/src/functions/core.rs
  src/daft-connect/src/functions/math.rs
  src/daft-connect/src/functions/partition_transform.rs
  src/daft-connect/src/functions/string.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-connect/src/spark_analyzer/expr_analyzer.rs
  src/daft-connect/src/spark_analyzer/literal.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/actor_pool_project.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/concat.rs
  src/daft-logical-plan/src/ops/distinct.rs
  src/daft-logical-plan/src/ops/explode.rs
  src/daft-logical-plan/src/ops/filter.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/limit.rs
  src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
  src/daft-logical-plan/src/ops/pivot.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/ops/repartition.rs
  src/daft-logical-plan/src/ops/sample.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/ops/sink.rs
  src/daft-logical-plan/src/ops/sort.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/ops/unpivot.rs
  src/daft-logical-plan/src/optimization/rules/simplify_expressions.rs
  src/daft-logical-plan/src/treenode.rs
  tests/connect/conftest.py
  tests/connect/test_spark_joins.py
Labels: feat

#3865 fix: Update dashboard import
  daft/dashboard.py
  daft_dashboard/daft_dashboard/__init__.py
  daft_dashboard/pyproject.toml
Labels: fix

#3869 fix: Add metadata to subgraph options in python
  daft/dataframe/display.py
Labels: fix

#3875 feat: Enable capturing and broadcasting logs when running on the `Native` runner
  daft/dashboard.py
  daft/dataframe/dataframe.py
  daft_dashboard/daft_dashboard/__init__.py
  daft_dashboard/src/lib.rs
Labels: feat

#3831 perf: Fix join cost estimates
  src/daft-dsl/src/expr/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
Labels: perf

#3872 feat: union ops
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/daft-connect/src/spark_analyzer.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-sql/src/planner.rs
  tests/connect/conftest.py
  tests/connect/test_spark_set_ops.py
  tests/dataframe/test_set_ops.py
Labels: feat

#3870 fix: arrow to Series for nested map array
  src/arrow2/src/compute/cast/mod.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/utils/arrow.rs
  src/daft-schema/src/dtype.rs
  tests/dataframe/test_creation.py
  tests/series/test_if_else.py
Labels: fix

#3874 fix: Fix ray data link
  docs/mkdocs/resources/dataframe_comparison.md
Labels: fix

#3838 feat(functions): add monotonically_increasing_id expression function
  daft/functions/__init__.py
  daft/functions/functions.py
  src/daft-dsl/src/functions/scalar.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/sequence.rs
  src/daft-functions/src/sequence/mod.rs
  src/daft-functions/src/sequence/monotonically_increasing_id.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/detect_monotonic_id.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  tests/dataframe/test_monotonically_increasing_id.py
Labels: feat
