Repository Eventual-Inc/Daft, pull requests merged in 2025-09, with the labels that each got.

#5105 docs: add noindex tag to non-stable pages
  docs/hooks.py
  docs/overrides/main.html
  mkdocs.yml
Labels: docs

#5111 chore: Remove docs codeowners
  .github/CODEOWNERS
Labels: chore

#5103 feat(embed_text): Support LM Studio as a provider
  daft/ai/openai/__init__.py
  daft/ai/openai/text_embedder.py
  daft/ai/provider.py
  docs/modalities/text.md
  tests/ai/test_lm_studio.py
Labels: feat

#5116 docs: Add batch inference use case
  docs/SUMMARY.md
  docs/connectors/custom.md
  docs/use-case/batch-inference.md
Labels: docs

#5118 docs: fix flickering typewriter animation on overview page
  docs/index.md
Labels: docs

#5114 fix: Remove flotilla fallback
  daft/context.py
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/runners/ray_runner.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-distributed/src/pipeline_node/join/translate_join.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-local-plan/src/translate.rs
  tests/actor_pool/test_actor_cuda_devices.py
  tests/cookbook/test_joins.py
  tests/dataframe/test_aggregations.py
  tests/dataframe/test_decimals.py
  tests/dataframe/test_into_batches.py
  tests/dataframe/test_joins.py
  tests/dataframe/test_pivot.py
  tests/dataframe/test_shuffles.py
  tests/expressions/test_legacy_udf.py
  tests/sql/test_joins.py
  tests/sql/test_window.py
  tests/test_resource_requests.py
  tests/window/test_order_by_only.py
  tests/window/test_partition_only.py
  tests/window/test_partition_order_by_lag_lead.py
  tests/window/test_partition_order_by_rank.py
  tests/window/test_running_agg.py
Labels: fix

#5119 ci: Always run the `unit-tests` required check
  .github/workflows/pr-test-suite.yml
Labels: ci

#5121 docs: fix navigation labels to match section names
  docs/SUMMARY.md
Labels: docs

#5124 chore: Add AGENTS.md
  .github/workflows/pr-test-suite.yml
  .gitignore
  AGENTS.md
Labels: chore

#5038 perf: Implement count pushdown for parquet
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/push_down_aggregation.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
Labels: perf

#5131 fix: Undo skipcheck change
  .github/workflows/pr-test-suite.yml
Labels: fix

#5122 ci: Truncate the # of concurrent jobs in PR CI
  .github/workflows/pr-test-suite.yml
  tests/integration/delta_lake/__init__.py
  tests/integration/delta_lake/conftest.py
  tests/integration/delta_lake/test_table_read.py
  tests/integration/delta_lake/test_table_read_pushdowns.py
  tests/integration/delta_lake/test_table_write.py
  tests/integration/delta_lake/utils.py
  tests/integration/unity/conftest.py
Labels: ci

#5130 fix: flaky test test_transformers_image_embedder_other
  tests/ai/test_transformers.py
Labels: fix

#5132 feat: unnest param on @daft.func
  daft/udf/__init__.py
  daft/udf/generator.py
  daft/udf/row_wise.py
  tests/udf/test_generator_udf.py
  tests/udf/test_row_wise_udf.py
Labels: feat

#5120 perf: Use `count_rows` on fragment to reduce lance scans with limit pushdowns only
  daft/io/lance/lance_scan.py
  tests/io/lancedb/test_lancedb_reads.py
Labels: perf

#5129 ci: Aggregate test durations
  .github/workflows/pr-test-suite.yml
  tests/test_context.py
  tools/aggregate_test_durations.py
  tools/capture-durations.sh
Labels: ci

#5143 feat: Add Arrow IPC conversion for RecordBatches
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/python.rs
Labels: feat

#5113 feat: adds support for classify_text
  daft/ai/_expressions.py
  daft/ai/protocols.py
  daft/ai/provider.py
  daft/ai/transformers/protocols/image_embedder.py
  daft/ai/transformers/protocols/text_classifier.py
  daft/ai/transformers/provider.py
  daft/ai/typing.py
  daft/ai/utils.py
  daft/functions/__init__.py
  daft/functions/ai/__init__.py
  docs/api/ai.md
  tests/ai/openai/test_openai_text_embedder.py
  tests/ai/transformers/__init__.py
  tests/ai/transformers/test_transformers.py
  tests/ai/transformers/test_transformers_image_embedder.py
  tests/ai/transformers/test_transformers_text_classifier.py
Labels: feat

#5164 docs: improve explode method documentation with null/empty list examples
  daft/dataframe/dataframe.py
Labels: docs

#5135 feat(flotilla): no shuffle for hash join if conditions are met
  src/daft-distributed/src/pipeline_node/join/hash_join.rs
  src/daft-distributed/src/pipeline_node/join/translate_join.rs
Labels: feat

#4987 fix: Account for unschedulable udf actors
  daft/context.py
  daft/daft/__init__.pyi
  daft/execution/ray_actor_pool_udf.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-local-execution/src/intermediate_ops/cross_join.rs
  src/daft-local-execution/src/intermediate_ops/distributed_actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/explode.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/into_batches.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/intermediate_ops/udf.rs
  src/daft-local-execution/src/intermediate_ops/unpivot.rs
  tests/expressions/test_legacy_udf.py
Labels: fix

#5181 docs: add TrendShift badge to README
  README.rst
Labels: docs

#5178 ci: Reduce free disk space time
  .github/workflows/pr-test-suite.yml
Labels: ci

#5202 docs: add Examples link to getting started sections
  README.rst
  docs/index.md
Labels: docs

#5211 chore: Split `.str.split` into `.str.split` and `.str.regexp_split`
  daft/expressions/expressions.py
  daft/series.py
  tests/recordbatch/utf8/test_split.py
  tests/series/test_utf8_ops.py
  tests/sql/test_utf8_exprs.py
Labels: chore

#5086 feat: migrate first batch of daft functions
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/functions/__init__.py
  daft/functions/agg.py
  daft/functions/ai/__init__.py
  daft/functions/binary.py
  daft/functions/bitwise.py
  daft/functions/columnar.py
  daft/functions/datetime.py
  daft/functions/embedding.py
  daft/functions/image.py
  daft/functions/list.py
  daft/functions/llm.py
  daft/functions/misc.py
  daft/functions/numeric.py
  daft/functions/str.py
  daft/functions/url.py
  daft/functions/window.py
  docs/gen_pages/gen_function_pages.py
  docs/gen_pages/templates/functions.md.j2
  src/daft-connect/src/functions/string.rs
  src/daft-core/src/array/ops/arithmetic.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/kernels/binary.rs
  src/daft-core/src/kernels/mod.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-functions-binary/src/concat.rs
  src/daft-functions-binary/src/kernels.rs
  src/daft-functions-binary/src/length.rs
  src/daft-functions-binary/src/lib.rs
  src/daft-functions-binary/src/utils.rs
  src/daft-functions-utf8/src/length.rs
  src/daft-functions-utf8/src/lib.rs
  src/daft-functions/src/length.rs
  src/daft-functions/src/lib.rs
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  src/lib.rs
  tests/dataframe/test_morsels.py
  tests/expressions/typing/test_arithmetic.py
  tests/functions/test_codecs.py
  tests/recordbatch/binary/test_concat.py
  tests/recordbatch/binary/test_fixed_size_binary_concat.py
  tests/recordbatch/binary/test_fixed_size_binary_length.py
Labels: feat

#5184 chore: Remove `reset_runner` option
  .github/workflows/pr-test-suite.yml
  daft/context.py
  daft/daft/__init__.pyi
  src/daft-context/src/lib.rs
  src/daft-context/src/python.rs
  tests/actor_pool/test_actor_cuda_devices.py
  tests/integration/ray/autoscaling_cluster.py
  tests/integration/ray/fake_cluster.yaml
  tests/integration/ray/test_autoscaling.py
Labels: chore

#5194 perf: Drop local limit tasks global limit reached
  src/daft-distributed/src/pipeline_node/limit.rs
Labels: perf

#5205 fix: remove unnecessary field renaming in ListMap scalar UDF
  src/daft-functions-list/src/list_map.rs
  tests/functions/test_list_map.py
Labels: fix

#5218 fix: rename index function to find
  daft/expressions/expressions.py
  daft/functions/__init__.py
  daft/functions/str.py
Labels: fix

#5219 feat: allow for functions module to be accessed from daft import
  daft/__init__.py
Labels: feat

#5199 feat(flotilla): Distributed Pivot
  src/daft-distributed/src/pipeline_node/aggregate.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/pivot.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-dsl/src/expr/bound_expr.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/ops/pivot.rs
  tests/dataframe/test_pivot.py
Labels: feat

#5153 fix: write_iceberg should handle write.data.path
  daft/logical/builder.py
  tests/integration/iceberg/docker-compose/docker-compose.yml
  tests/integration/iceberg/test_iceberg_writes.py
Labels: fix

#5179 feat: retry eof error in S3 multipart upload
  src/daft-io/src/s3_like.rs
Labels: feat

#5234 feat: migrate remaining basic expressions
  daft/expressions/expressions.py
  daft/functions/__init__.py
  daft/functions/image.py
  daft/functions/numeric.py
Labels: feat

#5231 chore: Don't log failures in url download if `on_error="null"`
  src/daft-functions-uri/src/download.rs
  src/daft-functions-uri/src/upload.rs
  src/daft-io/src/lib.rs
Labels: chore

#5233 feat: migrate nested constructors, get, slice, to_unix_epoch, partitioning functions
  daft/expressions/expressions.py
  daft/functions/__init__.py
  daft/functions/datetime.py
  daft/functions/list.py
  daft/functions/misc.py
  daft/functions/partition.py
  daft/functions/struct.py
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-functions-binary/src/kernels.rs
  src/daft-functions-binary/src/lib.rs
  src/daft-functions-binary/src/slice.rs
  src/daft-functions-binary/src/utils.rs
  src/daft-functions-list/src/kernels.rs
  src/daft-functions-list/src/lib.rs
  src/daft-functions-list/src/series.rs
  src/daft-functions-list/src/slice.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/slice.rs
  src/daft-sql/src/planner.rs
  tests/recordbatch/binary/test_fixed_size_binary_slice.py
  tests/recordbatch/binary/test_slice.py
  tests/recordbatch/list/test_list_slice.py
  tests/sql/test_list_exprs.py
Labels: feat

#5239 docs: add pipeline visualization and fix grammar in batch inference docs
  docs/use-case/batch-inference.md
  docs/use-case/daft-pipeline-visualization.png
Labels: docs

#5226 feat: add File.to_tempfile method and optimize range requests
  daft/daft/__init__.pyi
  daft/file.py
  src/daft-file/src/python.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/huggingface.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-io/src/unity.rs
  tests/file/test_file_basics.py
Labels: feat

#5245 docs: AI benchmarks
  .pre-commit-config.yaml
  benchmarking/ai/README.md
  benchmarking/ai/audio_transcription/README.md
  benchmarking/ai/audio_transcription/cluster.yaml
  benchmarking/ai/audio_transcription/daft_main.py
  benchmarking/ai/audio_transcription/pyproject.toml
  benchmarking/ai/audio_transcription/ray_data_main.py
  benchmarking/ai/audio_transcription/spark.ipynb
  benchmarking/ai/document_embedding/README.md
  benchmarking/ai/document_embedding/cluster.yaml
  benchmarking/ai/document_embedding/daft_main.py
  benchmarking/ai/document_embedding/pyproject.toml
  benchmarking/ai/document_embedding/ray_data_main.py
  benchmarking/ai/document_embedding/spark.ipynb
  benchmarking/ai/image_classification/README.md
  benchmarking/ai/image_classification/cluster.yaml
  benchmarking/ai/image_classification/daft_main.py
  benchmarking/ai/image_classification/pyproject.toml
  benchmarking/ai/image_classification/ray_data_main.py
  benchmarking/ai/image_classification/spark.ipynb
  benchmarking/ai/video_object_detection/README.md
  benchmarking/ai/video_object_detection/cluster.yaml
  benchmarking/ai/video_object_detection/daft_main.py
  benchmarking/ai/video_object_detection/pyproject.toml
  benchmarking/ai/video_object_detection/ray_data_main.py
  benchmarking/ai/video_object_detection/spark.ipynb
  docs/benchmarks/index.md
Labels: docs

#5254 feat: Add WARC-Target-URI as a top-level column for WARC reads
  daft/io/_warc.py
  src/daft-warc/src/lib.rs
  tests/io/test_warc.py
Labels: feat

#5241 chore: remove old documentation about daft cli
  docs/distributed.md
Labels: chore

#5270 feat: allow PythonArray to be serialized
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/series.py
  src/common/py-serde/src/lib.rs
  src/common/py-serde/src/python.rs
  src/daft-core/src/array/file_array.rs
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/from.rs
  src/daft-core/src/array/from_iter.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/growable/python_growable.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/as_arrow.rs
  src/daft-core/src/array/ops/broadcast.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/compare_agg.rs
  src/daft-core/src/array/ops/concat.rs
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/array/ops/count.rs
  src/daft-core/src/array/ops/filter.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/full.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/get_lit.rs
  src/daft-core/src/array/ops/if_else.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/list_agg.rs
  src/daft-core/src/array/ops/null.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/array/prelude.rs
  src/daft-core/src/array/pseudo_arrow/compute.rs
  src/daft-core/src/array/pseudo_arrow/mod.rs
  src/daft-core/src/array/pseudo_arrow/python.rs
  src/daft-core/src/array/serdes.rs
  src/daft-core/src/array/struct_array.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/datatypes/prelude.rs
  src/daft-core/src/datatypes/python.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/mod.rs
  src/daft-core/src/series/array_impl/python_array.rs
  src/daft-core/src/series/from_lit.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/serdes.rs
  src/daft-dsl/src/python_udf.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/field.rs
  tests/dataframe/test_creation.py
  tests/dataframe/test_iter.py
  tests/recordbatch/test_table_aggs.py
Labels: feat

#5274 chore(deps): Upgrade aws lc rs
  .github/workflows/pr-test-suite.yml
  Cargo.lock
Labels: chore

#5271 docs: improve copy and consistency on index page
  docs/index.md
Labels: docs

#5261 refactor: add fragment_group_size to reduce lance scan task
  daft/io/lance/_lance.py
  daft/io/lance/lance_scan.py
  tests/io/lancedb/test_lancedb_reads.py
Labels: refactor

#5281 docs: Update readme with new benchmarks
  README.rst
  assets/benchmark.png
Labels: docs

#5283 feat: when function
  daft/expressions/__init__.py
  daft/expressions/expressions.py
  daft/functions/__init__.py
  daft/functions/misc.py
  docs/api/expressions.md
Labels: feat

#5201 feat!: unify Python -> Daft type conversions
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  daft/functions/misc.py
  daft/functions/str.py
  daft/series.py
  daft/udf/generator.py
  daft/udf/legacy.py
  daft/udf/row_wise.py
  daft/utils.py
  docs/SUMMARY.md
  docs/api/datatypes.md
  docs/api/datatypes/index.md
  docs/api/datatypes/type_conversions.md
  docs/api/index.md
  docs/sql/datatypes.md
  src/common/image/Cargo.toml
  src/common/image/src/image.rs
  src/common/image/src/lib.rs
  src/common/image/src/python.rs
  src/common/ndarray/Cargo.toml
  src/common/ndarray/src/lib.rs
  src/common/ndarray/src/python.rs
  src/daft-catalog/Cargo.toml
  src/daft-catalog/src/python/mod.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/file_array.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/concat_agg.rs
  src/daft-core/src/array/ops/get_lit.rs
  src/daft-core/src/lit/deserializer.rs
  src/daft-core/src/lit/mod.rs
  src/daft-core/src/lit/python.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/from.rs
  src/daft-core/src/series/from_lit.rs
  src/daft-core/src/series/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/utils/supertype.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-image/Cargo.toml
  src/daft-ir/src/proto/rex.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/config.rs
  src/daft-sql/src/planner.rs
  tests/cookbook/test_literals.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_logical_type.py
  tests/expressions/test_expressions.py
  tests/recordbatch/test_table_aggs.py
  tests/series/test_cast.py
  tests/series/test_image.py
  tests/series/test_series.py
  tests/test_datatype_inference.py
  tests/test_datatypes.py
Labels: feat, breaking change

#5286 test: Complete coverage for array comparisons
  src/daft-core/src/array/ops/comparison.rs
Labels: test

#5289 fix: Use {} for dashboard dynamic route
  src/daft-dashboard/src/lib.rs
Labels: fix

#5285 feat: Add rows written stat for sinks
  src/daft-local-execution/src/sinks/write.rs
  src/daft-writers/src/batch.rs
  src/daft-writers/src/file.rs
  src/daft-writers/src/ipc.rs
  src/daft-writers/src/json_writer.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
  src/daft-writers/src/partition.rs
  src/daft-writers/src/pyarrow.rs
  src/daft-writers/src/sink.rs
  src/daft-writers/src/test.rs
Labels: feat

#5294 fix: Pass io config when grabbing Common Crawl manifest
  daft/datasets/common_crawl.py
  tests/datasets/test_common_crawl_mocked.py
  tests/integration/io/test_common_crawl_integration.py
Labels: fix

#5296 test: Temporarily remove Common Crawl integration test
  tests/integration/io/test_common_crawl_integration.py
Labels: test
