Repository Eventual-Inc/Daft, pull requests merged in 2025-04, with the labels that each got.

#4116 feat: adds verbose and documents no format behavior
  daft/dataframe/dataframe.py
Labels: feat

#4122 chore(optimizer): move join type simplification into new rule
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/simplify_null_filtered_join.rs
Labels: chore

#4123 perf(optimizer): push-down join predicate
  src/daft-core/src/join.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_join_predicate.rs
Labels: perf

#4127 fix: skip drop_nan when no float columns
  daft/dataframe/dataframe.py
  tests/expressions/test_expressions.py
Labels: fix

#4133 fix(join ordering): Fix bug with aliasing columns between joins
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  tests/dataframe/test_joins.py
Labels: fix

#4128 feat: add dt.{millisecond,microsecond,nanosecond}
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/time.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/temporal.rs
  src/daft-functions/src/temporal/mod.rs
  src/daft-sql/src/modules/temporal.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_temporal_exprs.py
Labels: feat

#4000 docs: Make wording around distinct more consistent
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  docs/sphinx/source/dataframe.rst
  docs/sphinx/source/expressions.rst
  tests/dataframe/test_distinct.py
  tests/recordbatch/list/test_list_distinct.py
Labels: docs

#4129 feat: add dt.day_of_year
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/arrow2/src/compute/temporal.rs
  src/daft-connect/src/functions/datetime.rs
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/time.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/temporal.rs
  src/daft-functions/src/temporal/mod.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/temporal.rs
  src/daft-sql/src/planner.rs
  tests/dataframe/test_temporals.py
  tests/series/test_temporal_ops.py
  tests/sql/test_temporal_exprs.py
Labels: feat

#4132 perf(optimizer): anti/semi join pushdown rule
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_anti_semi_join.rs
Labels: perf

#4140 chore: simplify rust identifier to a string vector
  daft/catalog/__init__.py
  daft/daft/__init__.pyi
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/python.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/exec.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/statement.rs
Labels: chore

#4137 fix: ignore hugging face in broken link workflow
  .github/workflows/broken-link-checker.yml
Labels: fix

#4142 ci: Native doc tests
  .github/workflows/python-package.yml
  Makefile
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/expressions/expressions.py
  daft/functions/functions.py
Labels: ci

#4004 feat: Implement flight server in rust
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/execution/shuffles/flight_shuffle/flight_server.py
  daft/execution/shuffles/flight_shuffle/flight_shuffle.py
  src/daft-connect/Cargo.toml
  src/daft-shuffles/Cargo.toml
  src/daft-shuffles/src/lib.rs
  src/daft-shuffles/src/python.rs
  src/daft-shuffles/src/server/flight_server.rs
  src/daft-shuffles/src/server/mod.rs
  src/daft-shuffles/src/server/stream.rs
  src/generated/spark-connect/Cargo.toml
Labels: feat

#4099 feat: add io config for spark
  Cargo.lock
  docs/mkdocs/spark_connect.md
  src/common/daft-config/src/lib.rs
  src/common/io-config/src/lib.rs
  src/daft-connect/Cargo.toml
  src/daft-connect/src/execute.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-context/src/lib.rs
  src/daft-io/src/lib.rs
Labels: feat

#4101 perf: Optimize shuffle cache
  Cargo.lock
  daft/daft/__init__.pyi
  daft/execution/shuffles/flight_shuffle/flight_shuffle.py
  src/common/runtime/src/lib.rs
  src/daft-shuffles/Cargo.toml
  src/daft-shuffles/src/python.rs
  src/daft-shuffles/src/shuffle_cache.rs
  src/daft-writers/src/ipc.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/test.rs
Labels: perf

#4070 docs: documents iceberg integration
  docs/mkdocs/integrations/delta_lake.md
  docs/mkdocs/integrations/iceberg.md
  pyproject.toml
Labels: docs

#4154 fix: sorting with nulls_first
  src/daft-core/src/array/ops/arrow2/sort/primitive/common.rs
  src/daft-core/src/array/ops/sort.rs
  tests/dataframe/test_sort.py
Labels: fix

#4155 fix: Fix list aggregates on empty series
  src/daft-core/src/array/ops/list.rs
  tests/recordbatch/list/test_list_numeric_aggs.py
Labels: fix

#4130 feat: add `unix_timestamp` function
  daft/daft/__init__.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/time.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/temporal.rs
  src/daft-functions/src/temporal/mod.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-sql/src/modules/temporal.rs
  tests/dataframe/test_temporals.py
  tests/series/test_temporal_ops.py
  tests/sql/test_temporal_exprs.py
Labels: feat

#4141 feat: add `is_t` and inner property methods to `DataType`
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/recordbatch/recordbatch.py
  daft/runners/ray_runner.py
  daft/series.py
  daft/sql/sql_scan.py
  src/daft-functions/src/distance/cosine.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/python/datatype.rs
  tests/expressions/typing/conftest.py
  tests/expressions/typing/test_arithmetic.py
  tests/expressions/typing/test_dt.py
  tests/series/test_arithmetic.py
  tests/test_datatypes.py
Labels: feat

#4160 fix: Re-enable mypy
  .gitignore
  .pre-commit-config.yaml
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__s3tables.py
  daft/catalog/__unity.py
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/dataframe/preview.py
  daft/datatype.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/shuffles/flight_shuffle/flight_shuffle.py
  daft/io/_range.py
  daft/logical/schema.py
  daft/pyspark/__init__.py
  daft/runners/partitioning.py
  daft/session.py
  daft/window.py
Labels: fix

#4097 feat(window): Add window partition execution
  daft/window.py
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/window_partition_only.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/optimization/rules/extract_window_function.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/ops/mod.rs
  src/daft-recordbatch/src/ops/window.rs
  tests/window/test_partition_only.py
Labels: feat

#4149 feat: adds case-sensitive and case-normalized catalog and table identifiers [1/3]
  docs/mkdocs.yml
  docs/mkdocs/sql/identifiers.md
  src/daft-catalog/src/bindings.rs
  src/daft-catalog/src/catalog.rs
  src/daft-catalog/src/error.rs
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/table.rs
  src/daft-session/src/error.rs
  src/daft-session/src/options.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/modules/aggs.rs
  src/daft-sql/src/planner.rs
  tests/sql/test_sql_identifiers.py
Labels: feat

#4161 docs: Fix tutorial notebooks
  docs/mkdocs/resources/tutorials.md
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
Labels: docs

#4146 feat: add `strftime`
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/arrow2/src/compute/temporal.rs
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/time.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/temporal.rs
  src/daft-functions/src/temporal/mod.rs
  src/daft-sql/src/modules/temporal.rs
  tests/dataframe/test_temporals.py
  tests/series/test_temporal_ops.py
  tests/sql/test_temporal_exprs.py
Labels: feat

#4169 chore: Update bug_report.yml to use native runner
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#4170 feat: Set num threads for local runners
  daft/context.py
  daft/daft/__init__.pyi
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  src/common/runtime/src/lib.rs
  src/daft-context/src/lib.rs
  src/daft-context/src/python.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/grouped_aggregate.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sinks/window_partition_only.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-py-runners/src/lib.rs
  src/lib.rs
Labels: feat

#4175 docs: Fix incorrect device in tutorial notebook
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Labels: docs

#4186 ci: fix vllm import on arm and skip test if not imported
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/python-package.yml
  requirements-dev.txt
  tests/functions/test_llm_generate.py
Labels: ci

#4159 fix: multicolumn sorts
  daft/dataframe/dataframe.py
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/kernels/search_sorted.rs
  tests/dataframe/test_sort.py
Labels: fix

#4181 fix(iceberg): partition field names and day transform type
  daft/expressions/expressions.py
  daft/iceberg/iceberg_scan.py
  daft/iceberg/iceberg_write.py
  src/daft-core/src/series/ops/partitioning.rs
  src/daft-dsl/src/functions/partitioning/evaluators.rs
  tests/cookbook/test_write.py
  tests/series/test_partitioning.py
Labels: fix

#4188 ci: upgrade runners to ubuntu-latest
  .github/workflows/python-package.yml
  tests/connect/test_config.py
  tests/dataframe/test_shuffles.py
  tests/test_resource_requests.py
Labels: ci

#4194 fix: Fix local writes with relative dir
  daft/filesystem.py
  tests/io/test_write_modes.py
Labels: fix

#4197 ci: reduce notebook data size to avoid errors
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Labels: ci

#4185 ci: cleanup Github Actions workflows
  .github/ci-scripts/constants.py
  .github/ci-scripts/get_wheel_name_from_s3.py
  .github/ci-scripts/job_runner.py
  .github/ci-scripts/read_inline_metadata.py
  .github/ci-scripts/templatize_ray_config.py
  .github/ci-scripts/upload_wheel_to_s3.py
  .github/ci-scripts/wheellib.py
  .github/workflows/benchmark-distributed-tpch.yml
  .github/workflows/benchmark-local-tpch.yml
  .github/workflows/build-commit.yaml
  .github/workflows/build-docs.yml
  .github/workflows/build-wheel.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/pr-test-suite.yml
  .github/workflows/publish-dev-s3.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/run-cluster.yaml
  .github/working-dir/README.md
  .github/working-dir/shuffle_testing.py
  .github/working-dir/simple.py
  tools/tpcds.py
  tools/tpch.py
Labels: ci

#4168 feat(window): Add window expression definitions
  daft/expressions/expressions.py
  daft/functions/__init__.py
  daft/functions/functions.py
  daft/window.py
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/expr/window.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/sequence.rs
  src/daft-functions/src/sequence/mod.rs
  src/daft-functions/src/sequence/row_number.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/window_partition_only.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/ops/window.rs
  src/daft-logical-plan/src/optimization/rules/extract_window_function.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/ops/window.rs
  tests/window/test_partition_only.py
Labels: feat

#4200 fix: Add httpx pin for `daft[unity]` install
  pyproject.toml
Labels: fix

#4172 chore: Add warc workload to benchmarking
  benchmarking/common_crawl/extract.py
Labels: chore

#4187 feat: implements GlueCatalog with custom table registration
  daft/catalog/__glue.py
  daft/catalog/__init__.py
  docs/integrations/glue.md
  mkdocs.yml
  requirements-dev.txt
  tests/catalog/test_glue.py
Labels: feat

#4148 docs: reformat docstrings to md
  daft/catalog/__init__.py
  daft/context.py
  daft/convert.py
  daft/datatype.py
  daft/expressions/expressions.py
  daft/functions/functions.py
  daft/functions/llm_generate.py
  daft/io/_csv.py
  daft/io/_iceberg.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/_warc.py
  daft/runners/ray_runner.py
  daft/session.py
  daft/udf.py
  mkdocs.yml
Labels: docs

#4174 feat: sql udfs
  Cargo.lock
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/session.py
  daft/sql/sql.py
  daft/udf.py
  src/daft-catalog/src/bindings.rs
  src/daft-catalog/src/error.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-session/Cargo.toml
  src/daft-session/src/options.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/exec.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/python.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  tests/sql/test_sql_udfs.py
Labels: feat

#4212 chore: fix badge in readme
  README.rst
Labels: chore

#4217 feat: Support pairwise cosine distance
  daft/expressions/expressions.py
  src/daft-functions/src/distance/cosine.rs
  tests/expressions/test_cosine_distance.py
Labels: feat

#4209 fix: Propagate set runner errors
  src/daft-context/src/python.rs
  tests/test_context.py
Labels: fix

#4225 chore: Pin pyarrow <= 16.0.0
  pyproject.toml
Labels: chore

#4229 docs: Add sort to row number doc test
  daft/functions/functions.py
Labels: docs

#4231 docs: small fixes
  daft/udf.py
  docs/catalogs.md
  docs/integrations/iceberg.md
Labels: docs

#4222 fix: Serialize / Deserialize micropartitions into shared memory for actor pool UDF
  daft/daft/__init__.pyi
  daft/execution/actor_pool_udf.py
  daft/recordbatch/micropartition.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  tests/expressions/test_udf.py
Labels: fix

#4202 test: Add Glue/Iceberg to Pytorch dataloading test
  tests/integration/iceberg/docker-compose/Dockerfile
  tests/integration/io/test_dataloading.py
Labels: test

#4203 feat: defines pushdown terms for python
  daft/daft/__init__.pyi
  daft/io/pushdowns.py
  daft/io/scan.py
  docs/advanced/pushdowns.md
  docs/api/io.md
  docs/api/pushdowns.md
  mkdocs.yml
  src/common/scan-info/src/python.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  tests/io/test_iceberg_pushdowns.py
  tests/io/test_pushdowns.py
Labels: feat

#4190 feat(window): partition and order by window rank / dense rank and agg functions
  daft/functions/__init__.py
  daft/functions/functions.py
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/sequence.rs
  src/daft-functions/src/sequence/mod.rs
  src/daft-functions/src/sequence/row_number.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-recordbatch/src/ops/window.rs
  tests/window/test_partition_order_by_rank.py
Labels: feat

#4236 test: Small cleanup for the Glue/Iceberg to Pytorch dataloading test
  tests/integration/io/test_dataloading.py
Labels: test

#4240 refactor: Rework SQLPlanner to use session references
  src/daft-catalog/src/bindings.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/exec.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  src/daft-sql/src/statement.rs
Labels: refactor

#4237 feat: Allow GlueCatalog to be created from a botocore session
  daft/catalog/__glue.py
  tests/catalog/test_glue.py
Labels: feat

#4233 feat(catalog): support arbitrary properties in create_table
  daft/catalog/__glue.py
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__s3tables.py
  daft/catalog/__unity.py
  daft/session.py
  docs/sessions.md
  tests/catalog/test_catalog.py
Labels: feat

#4238 test: Add integration test for pandas to daft to glue iceberg
  tests/integration/iceberg/test_glue_iceberg.py
Labels: test

#4191 feat(window): partition and order by lag / lead window functions
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-recordbatch/src/ops/window.rs
  tests/window/test_partition_order_by_lag_lead.py
Labels: feat

#4248 docs: Fix typo s/emedding/embedding/
  docs/api/expressions.md
Labels: docs

#4247 fix: Use _name for shared memory unregistration
  daft/execution/actor_pool_udf.py
Labels: fix

#4214 fix: Read/Write Lance files on S3 error in ray mode
  daft/io/_lance.py
  daft/io/object_store_options.py
  requirements-dev.txt
  tests/io/lancedb/test_lancedb_writes.py
Labels: fix

#4192 perf: Don't concat in `micropartition.to_arrow()`
  daft/daft/__init__.pyi
  daft/dataframe/preview.py
  daft/delta_lake/delta_lake_scan.py
  daft/hudi/hudi_scan.py
  daft/iceberg/iceberg_scan.py
  daft/io/_generator.py
  daft/io/_lance.py
  daft/io/file_path.py
  daft/recordbatch/micropartition.py
  daft/recordbatch/recordbatch.py
  daft/runners/ray_runner.py
  daft/sql/sql_scan.py
  src/daft-micropartition/src/python.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/pyarrow.rs
  tests/recordbatch/test_monotonically_increasing_id.py
  tests/utils.py
Labels: perf

#4252 docs: add usage examples to Catalog class and from_ methods
  daft/catalog/__init__.py
Labels: docs

#4259 docs: add usage examples to Session docstring
  daft/session.py
Labels: docs

#4255 fix: Allow PNGs to be displayed notebooks
  src/daft-image/src/ops.rs
Labels: fix

#4262 docs: fix doc typos
  .github/CODEOWNERS
  daft/catalog/__init__.py
  daft/session.py
Labels: docs

#4257 chore: Upgrade supported pyarrow version to 19.0.0
  .github/workflows/pr-test-suite.yml
  benchmarking/parquet/benchmark-requirements.txt
  pyproject.toml
  requirements-dev.txt
  src/daft-core/src/datatypes/logical.rs
  src/daft-schema/src/dtype.rs
  tests/integration/io/docker-compose/retry_server/retry-server-requirements.txt
Labels: chore

#4230 docs(window): add window function documentation
  daft/expressions/expressions.py
  daft/window.py
  docs/api/window.md
  docs/core_concepts.md
  docs/sql/window_functions.md
  mkdocs.yml
Labels: docs

#4269 refactor(ordinals): add bound column variant
  src/common/scan-info/src/python.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-schema/src/schema.rs
  src/daft-sql/src/modules/aggs.rs
Labels: refactor
