Repository Eventual-Inc/Daft, pull requests merged in 2025-06, with the labels that each got.

#4466 ci: remove py runner from nightly test matrix and pin aiohttp
  .github/workflows/nightly-publish-s3.yml
  requirements-dev.txt
Labels: ci

#4398 refactor(exprs): move over binary functions
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/arrow2/Cargo.toml
  src/daft-core/src/array/ops/mod.rs
  src/daft-decoding/Cargo.toml
  src/daft-functions-binary/Cargo.toml
  src/daft-functions-binary/src/codecs.rs
  src/daft-functions-binary/src/concat.rs
  src/daft-functions-binary/src/decode.rs
  src/daft-functions-binary/src/encode.rs
  src/daft-functions-binary/src/kernels.rs
  src/daft-functions-binary/src/length.rs
  src/daft-functions-binary/src/lib.rs
  src/daft-functions-binary/src/slice.rs
  src/daft-functions-binary/src/utils.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/binary/concat.rs
  src/daft-functions/src/binary/decode.rs
  src/daft-functions/src/binary/encode.rs
  src/daft-functions/src/binary/length.rs
  src/daft-functions/src/binary/mod.rs
  src/daft-functions/src/binary/slice.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/python/binary.rs
  src/daft-functions/src/python/mod.rs
  src/daft-local-execution/Cargo.toml
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  src/lib.rs
Labels: refactor

#4469 ci: Update base url in broken link checker
  .github/workflows/broken-link-checker.yml
Labels: ci

#4468 docs: cleanup part 2
  README.rst
  daft/context.py
  daft/execution/shuffles/flight_shuffle/flight_shuffle.py
  daft/expressions/expressions.py
  daft/filesystem.py
  daft/runners/ray_metrics.py
  daft/runners/ray_runner.py
  daft/udf.py
  docs/core_concepts.md
  docs/img/favicon.png
  docs/index.md
  docs/integrations/aws.md
  docs/integrations/azure.md
  docs/integrations/unity_catalog.md
  mkdocs.yml
  tutorials/window_functions/window_functions.ipynb
Labels: docs

#4471 docs: Dynamic execution docs
  docs/core_concepts.md
Labels: docs

#4455 refactor(exprs): move uri functions into own crate
  Cargo.lock
  Cargo.toml
  src/daft-functions-uri/Cargo.toml
  src/daft-functions-uri/src/download.rs
  src/daft-functions-uri/src/lib.rs
  src/daft-functions-uri/src/upload.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/lib.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/lib.rs
Labels: refactor

#4459 feat(flotilla): Flotilla runner
  .github/workflows/pr-test-suite.yml
  Cargo.lock
  daft/daft/__init__.pyi
  daft/runners/distributed_swordfish.py
  daft/runners/flotilla.py
  daft/runners/ray_runner.py
  src/common/scan-info/src/lib.rs
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/plan/runner.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-distributed/src/utils/joinset.rs
  src/daft-local-plan/src/plan.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/actor_pool_project.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/concat.rs
  src/daft-logical-plan/src/ops/distinct.rs
  src/daft-logical-plan/src/ops/explode.rs
  src/daft-logical-plan/src/ops/filter.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/limit.rs
  src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
  src/daft-logical-plan/src/ops/pivot.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/ops/repartition.rs
  src/daft-logical-plan/src/ops/sample.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/ops/sink.rs
  src/daft-logical-plan/src/ops/sort.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/ops/top_n.rs
  src/daft-logical-plan/src/ops/unpivot.rs
  src/daft-logical-plan/src/ops/window.rs
  src/daft-logical-plan/src/sink_info.rs
  src/daft-logical-plan/src/source_info.rs
  tests/actor_pool/test_actor_cuda_devices.py
Labels: feat

#4476 feat: url download for unity catalog volumes
  .github/workflows/pr-test-suite.yml
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/io/__init__.py
  daft/unity_catalog/unity_catalog.py
  docs/integrations/unity_catalog.md
  src/common/io-config/src/config.rs
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/common/io-config/src/unity.rs
  src/daft-connect/src/session.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/unity.rs
  tests/integration/unity/__init__.py
  tests/integration/unity/conftest.py
  tests/integration/unity/test_volumes.py
Labels: feat

#4470 feat: adds .jq expression with complex use-case examples
  Cargo.lock
  Cargo.toml
  daft/expressions/expressions.py
  src/daft-functions-json/Cargo.toml
  src/daft-functions-json/src/jq.rs
  src/daft-functions-json/src/json_query.rs
  src/daft-functions-json/src/lib.rs
  src/daft-functions-serde/src/format/json.rs
  tests/expressions/conftest.py
  tests/functions/conftest.py
  tests/functions/json/__init__.py
  tests/functions/json/test_jq.py
  tests/recordbatch/json/test_jq.py
  tests/sql/test_nested_access.py
Labels: feat

#4484 chore: add test case over #4180
  tests/sql/test_select_expr.py
Labels: chore

#4485 feat: add id and plan_id to otel subscribers, and add method for getting tree hierarchy for a pipeline
  Cargo.lock
  daft/daft/__init__.pyi
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/source.rs
Labels: feat

#4500 feat: `f""` string style string concatenation
  daft/functions/__init__.py
  daft/functions/functions.py
  tests/dataframe/test_format_function.py
Labels: feat

#4509 ci: Add a dbg check in precommit
  Cargo.toml
Labels: ci

#4504 feat: regexp replace posix groups and single regex speedup
  src/daft-functions-utf8/src/replace.rs
  tests/expressions/conftest.py
  tests/expressions/test_utf8.py
Labels: feat

#4521 chore: add better messaging for missing spark functions
  src/daft-connect/src/functions.rs
  src/daft-connect/src/functions/core.rs
  src/daft-connect/src/functions/datetime.rs
  src/daft-connect/src/functions/math.rs
  src/daft-connect/src/functions/string.rs
Labels: chore

#4523 perf: add harness for benchmarking parquet writes
  daft/context.py
  daft/daft/__init__.pyi
  src/common/daft-config/src/python.rs
  tests/benchmarks/test_parquet_writes.py
Labels: perf

#4524 feat(connect): add support for spark when/otherwise
  src/daft-connect/src/functions/core.rs
  tests/connect/test_basics.py
Labels: feat

#4497 feat(flotilla): Actor pool project
  daft/daft/__init__.pyi
  daft/execution/ray_actor_pool_udf.py
  daft/runners/flotilla.py
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/intermediate.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/python/ray/worker.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/mod.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/scheduling/worker.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-distributed/src/utils/joinset.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-local-execution/src/intermediate_ops/distributed_actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  tests/integration/iceberg/test_iceberg_reads.py
  tests/integration/iceberg/test_partition_pruning.py
Labels: feat

#4493 feat: Add a native remote parquet writer
  Cargo.lock
  src/common/daft-config/src/lib.rs
  src/common/runtime/src/lib.rs
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/huggingface.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/s3_like.rs
  src/daft-io/src/unity.rs
  src/daft-writers/Cargo.toml
  src/daft-writers/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
  src/daft-writers/src/physical.rs
Labels: feat

#4528 docs: fix bad markdown links
  daft/expressions/expressions.py
Labels: docs

#4517 feat(flotilla): Plan explain
  Cargo.lock
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/intermediate.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/plan/runner.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-local-plan/src/plan.rs
Labels: feat

#4488 docs: reorganize integrations
  docs/api/catalogs_tables.md
  docs/api/io.md
  docs/catalogs/glue.md
  docs/catalogs/index.md
  docs/catalogs/s3tables.md
  docs/catalogs/unity_catalog.md
  docs/core_concepts.md
  docs/css/extra.css
  docs/integrations.md
  docs/io/aws.md
  docs/io/azure.md
  docs/io/delta_lake.md
  docs/io/hudi.md
  docs/io/huggingface.md
  docs/io/iceberg.md
  docs/io/index.md
  docs/io/sql.md
  docs/js/custom.js
  docs/js/runllm.js
  docs/quickstart.md
  docs/sql_overview.md
  mkdocs.yml
  requirements-dev.txt
  requirements-doc.txt
Labels: docs

#4531 fix: Fix chrome trace
  src/common/tracing/src/lib.rs
  src/daft-local-execution/src/run.rs
Labels: fix

#4536 chore: Refactor storage backends for native writers
  src/daft-writers/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
  src/daft-writers/src/storage_backend.rs
  src/daft-writers/src/utils.rs
Labels: chore

#4519 chore: change unity volume prefix to "vol+dbfs:/"
  daft/expressions/expressions.py
  docs/catalogs/unity_catalog.md
  src/daft-io/src/lib.rs
  src/daft-io/src/unity.rs
  tests/integration/unity/test_volumes.py
Labels: chore

#4543 chore(flotilla): PipelineNode `.start` accept `Arc<Self>` to simplify cloning
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/intermediate.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/translate.rs
Labels: chore

#4508 chore!: upgrade AWS sdk and remove vendored OpenSSL
  .github/workflows/build-wheel.yml
  .pre-commit-config.yaml
  Cargo.lock
  src/common/io-config/Cargo.toml
  src/daft-connect/src/connect_service.rs
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/s3_like.rs
  tests/integration/io/docker-compose/retry_server/routers/rate_limited_echo_gets_bucket.py
  tools/check_for_openssl.sh
  tools/check_for_rustls.sh
Labels: chore, breaking change

#4545 fix: Resolve mismatch with Thrift compact protocol
  src/parquet-format-safe/Cargo.toml
  src/parquet-format-safe/src/parquet_format.rs
  src/parquet-format-safe/src/thrift/errors.rs
  src/parquet-format-safe/src/thrift/protocol/compact.rs
  src/parquet-format-safe/src/thrift/protocol/compact_write.rs
  src/parquet-format-safe/src/thrift/protocol/mod.rs
  src/parquet-format-safe/src/thrift/protocol/stream.rs
  tests/assets/parquet-data/databricks-generated.parquet
  tests/io/test_parquet.py
Labels: fix

#4473 chore: add @publicapi decorators to all public expr methods
  daft/api_annotations.py
  daft/expressions/expressions.py
Labels: chore

#4551 docs: Fix docstring for DataFrame.sort()
  daft/dataframe/dataframe.py
Labels: docs

#4555 feat(flotilla): Make one node per physical operator
  Cargo.lock
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/explode.rs
  src/daft-distributed/src/pipeline_node/filter.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/intermediate.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/project.rs
  src/daft-distributed/src/pipeline_node/sample.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/sink.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/pipeline_node/unpivot.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/python/ray/worker.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/linear.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/scheduling/worker.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/utils/joinset.rs
  src/daft-distributed/src/utils/stream.rs
  src/daft-local-plan/src/plan.rs
Labels: feat

#4548 fix: url download retry test io config
  tests/integration/io/conftest.py
Labels: fix

#4558 fix: add missing distinct field
  src/daft-ir/src/lib.rs
Labels: fix

#4560 perf: Improve efficiency of `to_arrow` for struct / fixed size lists
  daft/series.py
  daft/utils.py
  src/common/arrow-ffi/src/lib.rs
  src/daft-core/src/python/series.rs
Labels: perf

#4567 fix: fix ray connection issues with ray:// protocol
  daft/pyspark/__init__.py
  daft/runners/ray_runner.py
  docs/distributed.md
  docs/spark_connect.md
Labels: fix

#4563 feat: add some throttling error for tos
  src/daft-io/src/s3_like.rs
Labels: feat

#4562 fix: fix pypi image url
  README.rst
Labels: fix

#4561 fix: Fix `get_or_create_runner` deadlock
  daft/utils.py
  src/daft-catalog/src/impls/memory.rs
  src/daft-connect/src/execute.rs
  src/daft-context/src/lib.rs
  src/daft-context/src/partition_cache.rs
  src/daft-context/src/python.rs
  tests/test_context.py
Labels: fix

#4570 fix: Fix daft.range partitioning logic
  daft/io/_range.py
  tests/io/test_range.py
Labels: fix

#4483 feat: Support file-based sharding
  Cargo.lock
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/common/scan-info/Cargo.toml
  src/common/scan-info/src/lib.rs
  src/common/scan-info/src/pushdowns.rs
  src/common/scan-info/src/python.rs
  src/common/scan-info/src/scan_operator.rs
  src/common/scan-info/src/scan_task.rs
  src/common/scan-info/src/sharder.rs
  src/common/scan-info/src/test/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-ir/src/proto/rel.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/display/json.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/ops/shard.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/push_down_shard.rs
  src/daft-logical-plan/src/optimization/rules/shard_scans.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-scan/src/python.rs
  src/daft-writers/Cargo.toml
  tests/dataframe/test_sharding.py
Labels: feat

#4565 chore: improve the stability of unit test
  tests/io/conftest.py
  tests/io/delta_lake/conftest.py
  tests/io/test_s3_credentials_refresh.py
  tests/io/test_url_upload_local.py
  tests/recordbatch/numeric/test_numeric.py
  tests/test_datatypes.py
Labels: chore

#4581 fix: daft spark-connect server on windows hangs
  daft/pyspark/__init__.py
Labels: fix

#4574 chore: Update various Rust dependencies
  Cargo.lock
  Cargo.toml
  src/common/display/Cargo.toml
  src/common/io-config/Cargo.toml
  src/common/io-config/src/s3.rs
  src/common/macros/Cargo.toml
  src/common/system-info/Cargo.toml
  src/common/system-info/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/join.rs
  src/daft-decoding/Cargo.toml
  src/daft-decoding/src/deserialize.rs
  src/daft-decoding/src/inference.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-functions-tokenize/src/bpe.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/sink_info.rs
  src/daft-schema/Cargo.toml
  src/daft-schema/src/image_mode.rs
  src/daft-schema/src/schema.rs
Labels: chore

#4569 feat: Commit write sink
  Cargo.lock
  src/daft-distributed/src/lib.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/sink.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/commit_write.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-plan/Cargo.toml
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  tests/io/test_write_modes.py
Labels: feat

#4578 feat: support daft schema to arrow schema with metadata
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/dataframe/lance_data_sink.py
  daft/schema.py
  src/common/display/src/table_display.rs
  src/daft-schema/src/python/field.rs
  src/daft-schema/src/python/schema.rs
  src/daft-schema/src/schema.rs
  tests/io/lancedb/test_lancedb_writes.py
  tests/test_schema.py
Labels: feat

#4601 chore: Improve codecov
  .github/workflows/pr-test-suite.yml
  codecov.yml
  daft/filesystem.py
  daft/runners/flotilla.py
  daft/runners/ray_runner.py
  daft/utils.py
  tests/benchmarks/test_local_tpch.py
Labels: chore

#4576 fix: missing libpython when using pyo3 in cargo test
  CONTRIBUTING.md
Labels: fix

#4572 fix: Typing of DataFrame.__getitem__
  daft/dataframe/dataframe.py
Labels: fix

#4608 ci: Deflake series iter memory test
  tests/series/test_series.py
Labels: ci

#3992 perf: Split projections after optimizer passes
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
Labels: perf

#4606 feat(flotilla): Flotilla autoscaling
  daft/runners/flotilla.py
  src/daft-distributed/src/python/ray/worker.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/autoscaler.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/mod.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/linear.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/worker.rs
Labels: feat

#4546 feat: Support nulls first/last ordering for window functions
  daft/daft/__init__.pyi
  daft/window.py
  docs/sql/window_functions.md
  src/daft-dsl/src/expr/window.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/window_order_by_only.rs
  src/daft-local-execution/src/sinks/window_partition_and_dynamic_frame.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/ops/window.rs
  src/daft-sql/src/functions.rs
  tests/sql/test_window.py
  tests/window/test_order_by_only.py
  tests/window/test_partition_order_by_lag_lead.py
  tests/window/test_partition_order_by_rank.py
Labels: feat

#4616 feat: adds daft expr to pyarrow compute translator
  daft/daft/__init__.pyi
  daft/dependencies.py
  daft/expressions/expressions.py
  daft/expressions/visitor.py
  src/daft-dsl/src/python.rs
  tests/expressions/test_to_arrow_expr.py
Labels: feat

#4607 feat(flotilla): Concurrent flotilla tasks
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/task.rs
Labels: feat

#4630 feat: Enable native remote writer by default
  src/common/daft-config/src/lib.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
  src/daft-writers/src/physical.rs
Labels: feat

#4628 feat(flotilla): Fault tolerance
  daft/daft/__init__.pyi
  daft/execution/ray_actor_pool_udf.py
  daft/runners/constants.py
  daft/runners/flotilla.py
  daft/runners/progress_bar.py
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/plan/runner.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/progress_bar.rs
  src/daft-distributed/src/python/ray/mod.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/python/ray/worker.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/autoscaler.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/mod.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/linear.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/scheduling/worker.rs
  src/daft-distributed/src/statistics/mod.rs
  src/daft-distributed/src/utils/channel.rs
  tests/expressions/test_udf.py
Labels: feat

#4621 feat: Add more lance.dataset kwargs to daft.read_lance()
  daft/io/_lance.py
Labels: feat

#4629 feat(flotilla): Logging
  Cargo.lock
  Cargo.toml
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
Labels: feat

#4659 fix: Dependabot tweaks
  .github/dependabot.yml
Labels: fix
