Repository Eventual-Inc/Daft, pull requests merged in 2025-01, with the labels that each got.

#3638 chore: Clean up join order iteration
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
Labels: chore

#3628 feat(scantask-2): Implement new module for splitting Parquet ScanTask
  src/daft-scan/src/scan_task_iters/mod.rs
  src/daft-scan/src/scan_task_iters/split_parquet/fetch_parquet_metadata.rs
  src/daft-scan/src/scan_task_iters/split_parquet/mod.rs
  src/daft-scan/src/scan_task_iters/split_parquet/split_parquet_decision.rs
  src/daft-scan/src/scan_task_iters/split_parquet/split_parquet_file.rs
Labels: feat

#3511 fix(swordfish): Track future poll times for explain analyze
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/cross_join.rs
  src/daft-local-execution/src/intermediate_ops/explode.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/intermediate_ops/unpivot.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/cross_join_collect.rs
  src/daft-local-execution/src/sinks/grouped_aggregate.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/monotonically_increasing_id.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sinks/write.rs
Labels: fix

#3642 feat(optimizer): Add join reordering as an optimizer rule
  src/common/daft-config/src/lib.rs
  src/daft-logical-plan/src/builder.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/optimization/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/enrich_with_stats.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/mod.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
  src/daft-physical-plan/src/physical_planner/planner.rs
Labels: feat

#3643 feat: Allow building probe table for either side of anti semi joins
  src/daft-local-execution/src/intermediate_ops/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
Labels: feat

#3651 fix: special characters in GCS urls
  src/daft-io/src/google_cloud.rs
  tests/integration/io/test_url_download_public_gcs.py
Labels: fix

#3617 feat(connect): `printSchema`
  Cargo.toml
  src/daft-connect/src/display.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/translation.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-core/src/array/ops/from_arrow.rs
  tests/connect/test_print_schema.py
Labels: feat

#3650 build: Publish A Long Term Support CPU Release of Daft
  .github/workflows/python-publish.yml
Labels: build

#3654 ci: Improve visualization of tpcds + tpch benchmarking outputs
  benchmarking/tpcds/ray_entrypoint.py
  tools/tpcds.py
  tools/tpch.py
Labels: ci

#3657 fix: Run filter null join key optimization once
  src/daft-logical-plan/src/optimization/optimizer.rs
Labels: fix

#3655 perf: Improve stats for join side determination
  src/common/scan-info/src/pushdowns.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/distinct.rs
  src/daft-logical-plan/src/ops/explode.rs
  src/daft-logical-plan/src/ops/filter.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/limit.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/ops/unpivot.rs
  src/daft-logical-plan/src/stats.rs
  src/daft-physical-plan/src/ops/filter.rs
  src/daft-physical-plan/src/physical_planner/planner.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-scan/src/lib.rs
  src/daft-scheduler/src/scheduler.rs
Labels: perf

#3666 feat(connect): Rust ray exec
  Cargo.lock
  Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/display.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/op.rs
  src/daft-connect/src/op/execute/root.rs
  src/daft-connect/src/op/execute/write.rs
  src/daft-connect/src/response_builder.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/translation/datatype.rs
  src/daft-connect/src/translation/expr.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/range.rs
  src/daft-connect/src/translation/logical_plan/read.rs
  src/daft-connect/src/translation/logical_plan/read/data_source.rs
  src/daft-connect/src/translation/mod.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-micropartition/src/partitioning.rs
  src/daft-micropartition/src/python.rs
  src/daft-ray-execution/Cargo.toml
  src/daft-ray-execution/src/lib.rs
  src/daft-scheduler/src/scheduler.rs
Labels: feat

#3679 feat(sql): Adds FROM source check for string paths
  .pre-commit-config.yaml
  src/daft-sql/src/planner.rs
  tests/assets/json-data/small.jsonl
  tests/sql/test_table_funcs.py
Labels: feat

#3676 chore(connect): consolidate multiple files in tests/connect
  tests/connect/test_alias.py
  tests/connect/test_analyze_plan.py
  tests/connect/test_basic_column.py
  tests/connect/test_basics.py
  tests/connect/test_collect.py
  tests/connect/test_config.py
  tests/connect/test_create.py
  tests/connect/test_drop.py
  tests/connect/test_filter.py
  tests/connect/test_get_attr.py
  tests/connect/test_group_by.py
  tests/connect/test_io.py
  tests/connect/test_limit_simple.py
  tests/connect/test_parquet.py
  tests/connect/test_print_schema.py
  tests/connect/test_range_simple.py
  tests/connect/test_schema.py
  tests/connect/test_select.py
  tests/connect/test_show.py
  tests/connect/test_take.py
  tests/connect/test_unresolved.py
  tests/connect/test_with_column.py
  tests/connect/test_with_columns_renamed.py
Labels: chore

#3648 feat: support using S3Config.credentials_provider for writes
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/filesystem.py
  src/common/io-config/Cargo.toml
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/common/io-config/src/s3.rs
  tests/io/test_s3_credentials_refresh.py
Labels: feat

#3665 ci: Add new benchmarking cluster profile
  .github/ci-scripts/job_runner.py
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/run-cluster.yaml
  benchmarking/tpcds/ray_entrypoint.py
  tools/git_utils.py
  tools/tpcds.py
Labels: ci

#3675 chore(connect): better error propagation & handling
  src/daft-connect/src/config.rs
  src/daft-connect/src/connect_service.rs
  src/daft-connect/src/err.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/response_builder.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/read.rs
  src/daft-connect/src/translation/logical_plan/read/data_source.rs
  src/daft-connect/src/util.rs
Labels: chore

#3663 feat(core): Implement null-safe equality operator
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  src/arrow2/src/bitmap/bitmap_ops.rs
  src/daft-connect/src/translation/expr/unresolved_function.rs
  src/daft-core/src/array/ops/comparison.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/series/ops/comparison.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions/src/list/list_fill.rs
  src/daft-sql/src/planner.rs
  src/daft-stats/src/column_stats/comparison.rs
  src/daft-table/src/lib.rs
  tests/expressions/test_null_safe_equals.py
  tests/sql/test_sql_null_safe_equals.py
Labels: feat

#3677 feat(connect): distinct + sort
  src/daft-connect/src/translation/expr/unresolved_function.rs
  src/daft-connect/src/translation/logical_plan.rs
  tests/connect/test_distinct.py
Labels: feat

#3690 feat(sql): Adds url_download and url_upload to daft-sql
  Cargo.lock
  daft/expressions/expressions.py
  src/daft-functions/Cargo.toml
  src/daft-functions/src/python/uri.rs
  src/daft-functions/src/uri/download.rs
  src/daft-functions/src/uri/mod.rs
  src/daft-functions/src/uri/upload.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/image/decode.rs
  src/daft-sql/src/modules/mod.rs
  src/daft-sql/src/modules/uri/mod.rs
  src/daft-sql/src/modules/uri/url_download.rs
  src/daft-sql/src/modules/uri/url_upload.rs
  tests/sql/test_uri_exprs.py
Labels: feat

#3678 docs: add daft launcher docs to docs v2
  docs-v2/advanced/distributed.md
  docs-v2/core_concepts.md
  docs-v2/core_concepts/aggregations.md
  docs-v2/core_concepts/dataframe.md
  docs-v2/core_concepts/datatypes.md
  docs-v2/core_concepts/expressions.md
  docs-v2/core_concepts/read_write.md
  docs-v2/core_concepts/sql.md
  docs-v2/core_concepts/udf.md
  docs-v2/distributed.md
  docs-v2/integrations/delta_lake.md
  docs-v2/integrations/hudi.md
  docs-v2/integrations/ray.md
  docs-v2/integrations/sql.md
  docs-v2/migration/dask_migration.md
  docs-v2/quickstart.md
  mkdocs.yml
Labels: docs

#3668 fix(optimizer): Fix issues with join graph construction
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/naive_left_deep_join_order.rs
Labels: fix

#3680 refactor(connect): internal refactoring to make connect code more organized & extensible
  Cargo.lock
  src/daft-connect/Cargo.toml
  src/daft-connect/src/connect_service.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/functions.rs
  src/daft-connect/src/functions/core.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-connect/src/spark_analyzer/datatype.rs
  src/daft-connect/src/spark_analyzer/literal.rs
  src/daft-connect/src/translation/expr.rs
  src/daft-connect/src/translation/expr/unresolved_function.rs
  src/daft-connect/src/translation/logical_plan.rs
  src/daft-connect/src/translation/logical_plan/aggregate.rs
  src/daft-connect/src/translation/logical_plan/drop.rs
  src/daft-connect/src/translation/logical_plan/filter.rs
  src/daft-connect/src/translation/logical_plan/local_relation.rs
  src/daft-connect/src/translation/logical_plan/project.rs
  src/daft-connect/src/translation/logical_plan/range.rs
  src/daft-connect/src/translation/logical_plan/read.rs
  src/daft-connect/src/translation/logical_plan/to_df.rs
  src/daft-connect/src/translation/logical_plan/with_columns.rs
  src/daft-connect/src/translation/logical_plan/with_columns_renamed.rs
  src/daft-connect/src/translation/mod.rs
  src/daft-connect/src/translation/schema.rs
  src/daft-dsl/src/expr/mod.rs
Labels: refactor

#3684 refactor: logical op constructor+builder boundary
  Cargo.lock
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/builder/tests.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/lib.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/actor_pool_project.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/concat.rs
  src/daft-logical-plan/src/ops/explode.rs
  src/daft-logical-plan/src/ops/filter.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
  src/daft-logical-plan/src/ops/pivot.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/ops/repartition.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/ops/sink.rs
  src/daft-logical-plan/src/ops/sort.rs
  src/daft-logical-plan/src/ops/unpivot.rs
  src/daft-logical-plan/src/optimization/rules/eliminate_cross_join.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  tests/sql/test_binary_op_exprs.py
Labels: refactor

#3693 build(docs): Adds make docs phony target
  CONTRIBUTING.md
  Makefile
  requirements-docs.txt
Labels: build

#3692 ci: Remove daft tracing
  .github/ci-scripts/format_env_vars.py
  .github/ci-scripts/job_runner.py
  .github/workflows/run-cluster.yaml
Labels: ci

#3697 docs: higher quality daft diagram for readme
  README.rst
Labels: docs

#3646 feat: add binary string operations (length and concatenation)
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  docs/source/api_docs/expressions.rst
  pyproject.toml
  src/daft-core/src/array/ops/binary.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/series/ops/binary.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-functions/src/binary/concat.rs
  src/daft-functions/src/binary/length.rs
  src/daft-functions/src/binary/mod.rs
  src/daft-functions/src/binary/slice.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/python/binary.rs
  src/daft-functions/src/python/mod.rs
  tests/table/binary/test_concat.py
  tests/table/binary/test_fixed_size_binary_concat.py
  tests/table/binary/test_fixed_size_binary_length.py
  tests/table/binary/test_fixed_size_binary_slice.py
  tests/table/binary/test_length.py
  tests/table/binary/test_slice.py
Labels: feat

#3696 feat(connect): sql
  Cargo.lock
  daft/catalog/__init__.py
  src/daft-catalog/python-catalog/src/python.rs
  src/daft-catalog/src/data_catalog.rs
  src/daft-catalog/src/lib.rs
  src/daft-catalog/src/python.rs
  src/daft-connect/Cargo.toml
  src/daft-connect/src/connect_service.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/session.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/catalog.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  tests/connect/test_spark_sql.py
Labels: feat

#3702 feat(docs): Adds copy-to-clipboard to code samples
  docs-v2/terms.md
  mkdocs.yml
Labels: feat

#3687 feat: Overwrite partitions mode
  daft/dataframe/dataframe.py
  daft/filesystem.py
  tests/io/test_write_modes.py
Labels: feat

#3701 feat(iceberg): Adds support for read_iceberg with metadata_location to Daft-SQL
  .gitignore
  daft/io/_iceberg.py
  src/daft-scan/src/builder.rs
  src/daft-scan/src/storage_config.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/table_provider/mod.rs
  src/daft-sql/src/table_provider/read_deltalake.rs
  src/daft-sql/src/table_provider/read_iceberg.rs
  tests/sql/test_table_functions/__init__.py
  tests/sql/test_table_functions/test_read_iceberg.py
  tests/sql/test_table_functions/test_table_functions.py
Labels: feat

#3545 perf(shuffles): Incrementally retrieve metadata in reduce
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
Labels: perf

#3689 refactor(execution): NativeExecutor refactor
  Cargo.lock
  daft/daft/__init__.pyi
  daft/execution/native_executor.py
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  src/common/runtime/src/lib.rs
  src/daft-connect/Cargo.toml
  src/daft-connect/src/execute.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/session.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/progress_bar.rs
  src/daft-local-execution/src/run.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/builder/mod.rs
Labels: refactor

#3709 feat(core): make micropartition streamable over tables
  Cargo.lock
  src/daft-connect/src/execute.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-table/src/lib.rs
  src/daft-table/src/ops/explode.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  src/daft-table/src/ops/unpivot.rs
Labels: feat

#3681 feat: Add column format option to iter rows
  daft/dataframe/dataframe.py
  tests/dataframe/test_iter.py
Labels: feat

#3715 chore: Pin sql server version in docker compose
  tests/integration/sql/docker-compose/docker-compose.yml
Labels: chore

#3719 refactor: remove eyre from daft-connect
  Cargo.lock
  src/daft-connect/Cargo.toml
  src/daft-connect/src/connect_service.rs
  src/daft-connect/src/display.rs
  src/daft-connect/src/err.rs
  src/daft-connect/src/error.rs
  src/daft-connect/src/execute.rs
  src/daft-connect/src/functions.rs
  src/daft-connect/src/functions/core.rs
  src/daft-connect/src/lib.rs
  src/daft-connect/src/response_builder.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-connect/src/spark_analyzer/datatype.rs
  src/daft-connect/src/spark_analyzer/literal.rs
  src/daft-connect/src/util.rs
Labels: refactor

#3720 feat: Adds .describe() to DataFrame and DESCRIBE to SQL
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  docs/source/api_docs/dataframe.rst
  src/common/display/src/table_display.rs
  src/daft-connect/src/spark_analyzer.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-schema/src/schema.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/statement.rs
  tests/dataframe/test_describe.py
  tests/dataframe/test_repr.py
  tests/sql/test_describe.py
  tests/test_schema.py
Labels: feat

#3728 fix: to_cnf and to_dnf functions
  src/daft-algebra/src/boolean.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
Labels: fix

#3732 feat: with_column(s)_renamed expression for DataFrame
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  docs/source/api_docs/dataframe.rst
  src/daft-logical-plan/src/builder/mod.rs
  tests/dataframe/test_with_column_renamed.py
  tests/dataframe/test_with_columns_renamed.py
Labels: feat

#3716 fix(join): joining on different types
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/arrow2/src/array/dyn_ord.rs
  src/arrow2/src/array/ord.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/join.rs
  src/daft-dsl/src/join/mod.rs
  src/daft-dsl/src/join/tests.rs
  src/daft-dsl/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/lib.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/optimization/rules/eliminate_cross_join.rs
  src/daft-logical-plan/src/optimization/rules/filter_null_join_key.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-logical-plan/src/treenode.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/ops/joins/hash_join.rs
  src/daft-table/src/ops/joins/mod.rs
  tests/dataframe/test_joins.py
  tests/utils.py
Labels: fix

#3714 feat: Expose parquet chunk size to swordfish reads
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
Labels: feat

#3731 perf: simplify boolean expression rules
  Cargo.lock
  src/common/treenode/src/lib.rs
  src/daft-algebra/Cargo.toml
  src/daft-algebra/src/simplify.rs
  src/daft-algebra/src/simplify/boolean.rs
  src/daft-algebra/src/simplify/mod.rs
  src/daft-algebra/src/simplify/null.rs
  src/daft-algebra/src/simplify/numeric.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/simplify_expressions.rs
  src/daft-logical-plan/src/treenode.rs
Labels: perf

#3695 feat: Limit number of sources in merged scan task
  daft/context.py
  daft/daft/__init__.pyi
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-scan/src/scan_task_iters/mod.rs
  tests/io/test_merge_scan_tasks.py
Labels: feat

#3674 feat(shuffles): Determination logic for pre shuffle merge
  daft/context.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-physical-plan/src/ops/shuffle_exchange.rs
Labels: feat

#3694 fix: Set filter selectivity estimate lower bound
  src/daft-dsl/src/expr/mod.rs
Labels: fix

#3730 ci: Allow upstream git refs to be used for benchmarking
  tools/git_utils.py
Labels: ci

#3744 ci: skip tests during publishing of release
  .github/workflows/python-publish.yml
  tests/io/mock_aws_server.py
Labels: ci

#3741 feat: add spark explain
  src/daft-connect/src/connect_service.rs
  src/daft-connect/src/response_builder.rs
  tests/connect/test_basics.py
Labels: feat

#3739 feat: spark connect set operations
  src/daft-connect/src/spark_analyzer.rs
  tests/connect/test_spark_set_ops.py
Labels: feat

#3737 feat: Adds list constructor to Expression and SQL APIs
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/expressions/__init__.py
  daft/expressions/expressions.py
  docs/sphinx/source/expressions.rst
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/zip.rs
  src/daft-dsl/src/expr/display.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/optimization.rs
  src/daft-dsl/src/python.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-sql/src/planner.rs
  src/daft-table/src/lib.rs
  tests/expressions/test_list_.py
  tests/sql/test_list_exprs.py
Labels: feat
