Repository Eventual-Inc/Daft, pull requests merged in 2025-08, with the labels that each got.

#4884 feat: supports passing a projection kwargs in select
  daft/dataframe/dataframe.py
  daft/utils.py
  docs/core_concepts.md
  tests/dataframe/test_select.py
  tests/io/test_warc.py
  tests/recordbatch/json/test_jq.py
Labels: feat

#4892 fix: azure storage resource url
  src/daft-io/src/azure_blob.rs
Labels: fix

#4886 perf: Add parallel execution for Python UDFs with batched GIL acquisitions
  Cargo.lock
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/python_udf.rs
Labels: perf

#4895 docs: Remove redirect for installation page
  mkdocs.yml
Labels: docs

#4888 fix: Use planning config instead of env variables during filter pushdowns
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
Labels: fix

#4835 feat: Interactive jupyter display
  Cargo.lock
  daft/daft/dashboard.pyi
  daft/dashboard/__init__.py
  daft/dataframe/dataframe.py
  daft/dataframe/preview.py
  src/daft-cli/Cargo.toml
  src/daft-cli/src/python.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-dashboard/Cargo.toml
  src/daft-dashboard/src/lib.rs
  src/daft-dashboard/src/python.rs
  src/daft-dashboard/src/response.rs
  src/daft-image/src/ops.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/repr_html.rs
  tests/dataframe/test_repr.py
  tests/test_schema.py
  tests/utils.py
Labels: feat

#4896 chore: change series literal to list
  Cargo.lock
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-algebra/src/simplify/mod.rs
  src/daft-core/src/utils/display.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit/conversions.rs
  src/daft-dsl/src/lit/deserializer.rs
  src/daft-dsl/src/lit/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-functions-utf8/src/count_matches.rs
  src/daft-ir/src/proto/rex.rs
  src/daft-sql/src/modules/python.rs
  src/daft-stats/src/partition_spec.rs
  tests/expressions/test_expressions.py
  tests/expressions/test_null_safe_equals.py
  tests/expressions/test_visitor.py
  tests/recordbatch/test_between.py
  tests/recordbatch/test_is_in.py
  tests/series/test_hash.py
  tests/series/test_utf8_ops.py
Labels: chore

#4903 docs: add examples to docs
  docs/SUMMARY.md
  docs/examples/index.md
  docs/index.md
  mkdocs.yml
Labels: docs

#4640 feat: Add support for specifying hash algorithm used in expression.hash() func.
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/hash.rs
  src/daft-core/src/kernels/hashing.rs
  src/daft-core/src/series/ops/hash.rs
  src/daft-functions/src/hash.rs
  tests/expressions/test_expressions.py
  tests/recordbatch/test_hash.py
Labels: feat

#4854 docs: add docstrings to I/O & DataFrame methods (issue Eventual-Inc#4124)
  daft/convert.py
  daft/dataframe/dataframe.py
Labels: docs

#4909 docs: adds coalesce to docs
  docs/api/expressions.md
Labels: docs

#4910 chore: add warning on repartition in native runner
  daft/dataframe/dataframe.py
Labels: chore

#4837 fix: Refactor Progress Bar to be a RuntimeStatSubscriber
  Cargo.lock
  Cargo.toml
  src/common/metrics/Cargo.toml
  src/common/metrics/src/lib.rs
  src/daft-csv/Cargo.toml
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/dispatcher.rs
  src/daft-local-execution/src/intermediate_ops/cross_join.rs
  src/daft-local-execution/src/intermediate_ops/distributed_actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/explode.rs
  src/daft-local-execution/src/intermediate_ops/filter.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/intermediate_ops/udf.rs
  src/daft-local-execution/src/intermediate_ops/unpivot.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/ops.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/progress_bar.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats/mod.rs
  src/daft-local-execution/src/runtime_stats/subscribers.rs
  src/daft-local-execution/src/runtime_stats/subscribers/dashboard.rs
  src/daft-local-execution/src/runtime_stats/subscribers/debug.rs
  src/daft-local-execution/src/runtime_stats/subscribers/opentelemetry.rs
  src/daft-local-execution/src/runtime_stats/subscribers/progress_bar.rs
  src/daft-local-execution/src/runtime_stats/values.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/commit_write.rs
  src/daft-local-execution/src/sinks/cross_join_collect.rs
  src/daft-local-execution/src/sinks/dedup.rs
  src/daft-local-execution/src/sinks/grouped_aggregate.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-local-execution/src/sinks/repartition.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/top_n.rs
  src/daft-local-execution/src/sinks/window_order_by_only.rs
  src/daft-local-execution/src/sinks/window_partition_and_dynamic_frame.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-local-execution/src/sinks/window_partition_only.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-execution/src/sources/empty_scan.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-local-execution/src/streaming_sink/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/streaming_sink/base.rs
  src/daft-local-execution/src/streaming_sink/concat.rs
  src/daft-local-execution/src/streaming_sink/limit.rs
  src/daft-local-execution/src/streaming_sink/monotonically_increasing_id.rs
  src/daft-local-execution/src/streaming_sink/outer_hash_join_probe.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/schema.rs
Labels: fix

#4902 feat: model resource plumbing for ml model-based functions
  daft/__init__.py
  daft/ai/__init__.py
  daft/ai/_expressions.py
  daft/ai/protocols.py
  daft/ai/provider.py
  daft/ai/sentence_transformers/__init__.py
  daft/ai/sentence_transformers/text_embedder.py
  daft/ai/typing.py
  daft/daft/__init__.pyi
  daft/functions/ai/__init__.py
  daft/session.py
  src/daft-session/src/options.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  tests/ai/__init__.py
  tests/ai/test_sentence_transformers.py
Labels: feat

#4706 feat: Add offset operator support to DataFrame for Ray Runner
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  src/daft-physical-plan/src/ops/limit.rs
  src/daft-physical-plan/src/ops/top_n.rs
  src/daft-physical-plan/src/optimization/optimizer.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-scheduler/src/scheduler.rs
  tests/dataframe/test_limit_offset.py
Labels: feat

#4924 docs: improve navigation for functions doc pages
  docs/gen_pages/gen_function_pages.py
  docs/gen_pages/templates/function_page.md.j2
  docs/gen_pages/templates/functions.md.j2
  docs/overrides/partials/nav-item.html
  docs/overrides/partials/toc-item.html
  docs/overrides/partials/toc.html
  docs/plugins/README.md
  docs/plugins/nav_hide_children/__init__.py
  docs/plugins/nav_hide_children/plugin.py
  docs/plugins/setup.py
  mkdocs.yml
  requirements-dev.txt
  requirements-doc.txt
Labels: docs

#4932 fix: Batch RuntimeSubscriber updates for all nodes
  Cargo.lock
  Cargo.toml
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats/mod.rs
  src/daft-local-execution/src/runtime_stats/subscribers.rs
  src/daft-local-execution/src/runtime_stats/subscribers/dashboard.rs
  src/daft-local-execution/src/runtime_stats/subscribers/debug.rs
  src/daft-local-execution/src/runtime_stats/subscribers/opentelemetry.rs
  src/daft-local-execution/src/runtime_stats/subscribers/progress_bar.rs
  src/daft-local-execution/src/sources/source.rs
Labels: fix

#4931 perf: scalar udfs use same optimizations as legacy udfs
  Cargo.lock
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-dsl/src/python_udf.rs
  src/daft-local-execution/src/intermediate_ops/udf.rs
  src/daft-recordbatch/src/lib.rs
Labels: perf

#4934 docs: Add embeddings generation example
  docs/SUMMARY.md
  docs/examples/text-embeddings.md
  docs/img/text-embed-gpu-utilization.jpeg
Labels: docs

#4936 docs: Pull colab examples into pages
  docs/SUMMARY.md
  docs/examples/document-processing.md
  docs/examples/image-generation.md
  docs/examples/index.md
  docs/examples/llms-red-pajamas.md
  docs/examples/mnist.md
  docs/examples/querying-images.md
  docs/examples/text-embeddings.md
  docs/examples/window-functions.md
  docs/img/window-functions-image-1.jpeg
  docs/img/window-functions-image-2.png
  docs/img/window-functions-image-3.png
  docs/img/window-functions-image-4.png
  docs/img/window-functions-image-5.png
  docs/img/window-functions-image-6.png
  docs/img/window-functions-image-7.jpeg
Labels: docs

#4937 docs: Generate files for llms.txt
  docs/examples/document-processing.md
  docs/examples/window-functions.md
  docs/gen_pages/gen_txt_files.py
  docs/gen_pages/generate_llms_txt.py
  mkdocs.yml
Labels: docs

#4941 docs: fix link for pandas
  docs/index.md
Labels: docs

#4942 docs: improve daft.func documentation and type inference
  daft/udf/__init__.py
  daft/udf/row_wise.py
  docs/quickstart.md
Labels: docs

#4867 feat: Flotilla broadcast join
  src/daft-distributed/src/pipeline_node/gather.rs
  src/daft-distributed/src/pipeline_node/join/broadcast_join.rs
  src/daft-distributed/src/pipeline_node/join/hash_join.rs
  src/daft-distributed/src/pipeline_node/join/mod.rs
  src/daft-distributed/src/pipeline_node/join/translate_join.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/repartition.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
Labels: feat

#4952 fix: raise error on invalid cross join parameters
  daft/dataframe/dataframe.py
Labels: fix

#4935 feat: implement into_batches on the swordfish native daft runner
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-ir/src/proto/rel.rs
  src/daft-local-execution/src/intermediate_ops/into_batches.rs
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/ops.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/display/json.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/into_batches.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/drop_into_batches.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  tests/dataframe/test_into_batches.py
Labels: feat

#4956 fix: use associate type for swordfish into_batches operator state
  src/daft-local-execution/src/intermediate_ops/into_batches.rs
Labels: fix

#4954 chore: Remove Err Case for Series and RecordBatch `size_bytes`
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/array_impl/data_array.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/array_impl/nested_array.rs
  src/daft-core/src/series/ops/len.rs
  src/daft-core/src/series/series_like.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/partitioning.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/python.rs
  src/daft-shuffles/src/shuffle_cache.rs
  src/daft-stats/src/column_stats/mod.rs
  src/daft-writers/src/batch.rs
  src/daft-writers/src/file.rs
  src/daft-writers/src/ipc.rs
  src/daft-writers/src/json_writer.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/test.rs
Labels: chore

#4948 fix: Coerce arrow schema for parquet decoding
  src/daft-core/src/utils/arrow.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  tests/integration/io/parquet/test_reads_public_data.py
  tests/recordbatch/recordbatch_io/test_parquet.py
Labels: fix

#4918 feat: Add offset support to Flotilla Engine
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/top_n.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
Labels: feat

#4945 fix: Don't use wildcard for logical plan match in pushdown rules
  src/daft-logical-plan/src/optimization/rules/push_down_anti_semi_join.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/optimization/rules/push_down_shard.rs
Labels: fix

#4946 docs: update links in document processing example
  daft/expressions/expressions.py
  docs/examples/document-processing.md
Labels: docs

#4967 fix: Dudep lance read required columns
  daft/io/lance/lance_scan.py
  tests/io/lancedb/test_lancedb_reads.py
Labels: fix

#4707 feat: Add offset syntax support to SQL
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/dataframe/test_limit_offset.py
  tests/sql/test_limit_offset.py
Labels: feat

#4970 fix: Add handle for swordfish runtime stats manager
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/lib.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats/mod.rs
  src/daft-local-execution/src/streaming_sink/base.rs
Labels: fix

#4978 fix: Always just use actor for flotilla scheduler
  daft/daft/__init__.pyi
  daft/runners/flotilla.py
  daft/runners/ray_runner.py
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/progress_bar.rs
  tests/dataframe/test_async_context.py
Labels: fix

#4972 feat: unify all Daft type to Python type conversions
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/series.py
  docs/SUMMARY.md
  docs/api/datatypes.md
  src/common/image/Cargo.toml
  src/common/image/src/image.rs
  src/common/ndarray/Cargo.toml
  src/common/ndarray/src/lib.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/get_lit.rs
  src/daft-core/src/lit/deserializer.rs
  src/daft-core/src/lit/mod.rs
  src/daft-core/src/lit/python.rs
  src/daft-core/src/python/mod.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/from_lit.rs
  src/daft-core/src/series/mod.rs
  src/daft-ir/src/proto/rex.rs
  src/daft-sql/src/modules/python.rs
  tests/expressions/test_visitor.py
  tests/series/test_cast.py
Labels: feat

#4959 feat: new `daft.File` datatype
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/datatype.py
  daft/file.py
  daft/functions/__init__.py
  daft/functions/misc.py
  docs/examples/audio_transcription.md
  src/common/file/Cargo.toml
  src/common/file/src/lib.rs
  src/daft-connect/src/display.rs
  src/daft-core/Cargo.toml
  src/daft-core/src/array/growable/logical_growable.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/file.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/get_lit.rs
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/matching.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/lit/deserializer.rs
  src/daft-core/src/lit/mod.rs
  src/daft-core/src/lit/python.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/from_lit.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-core/src/series/serdes.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-file/Cargo.toml
  src/daft-file/src/lib.rs
  src/daft-file/src/python.rs
  src/daft-functions/src/lib.rs
  src/daft-ir/src/proto/rex.rs
  src/daft-ir/src/proto/schema.rs
  src/daft-recordbatch/src/repr_html.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/python/datatype.rs
  src/daft-stats/src/column_stats/mod.rs
  src/lib.rs
  tests/file/test_file_udfs.py
Labels: feat

#4962 feat: Add offset support to Spark Connect
  src/daft-connect/src/spark_analyzer.rs
  tests/connect/test_basics.py
  tests/connect/test_spark_sql.py
Labels: feat

#4979 feat: adds video frame streaming source
  daft/__init__.py
  daft/ai/typing.py
  daft/filesystem.py
  daft/io/__init__.py
  daft/io/av/__init__.py
  daft/io/av/_read_video_frames.py
  docs/SUMMARY.md
  docs/api/io.md
  docs/connectors/index.md
  docs/modalities/index.md
  docs/modalities/videos.md
Labels: feat

#4969 feat(optimizer): Add Lance count() pushdown optimization
  Cargo.lock
  daft/daft/__init__.pyi
  daft/io/lance/lance_scan.py
  daft/io/scan.py
  src/common/scan-info/Cargo.toml
  src/common/scan-info/src/pushdowns.rs
  src/common/scan-info/src/python.rs
  src/common/scan-info/src/scan_operator.rs
  src/common/scan-info/src/test/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/push_down_aggregation.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/shard_scans.rs
  src/daft-logical-plan/src/optimization/rules/split_udfs.rs
  src/daft-logical-plan/src/test/mod.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-physical-plan/src/test/mod.rs
  src/daft-scan/src/anonymous.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
  tests/io/lancedb/test_lancedb_reads.py
Labels: feat

#4940 fix: lance schema does not work
  daft/io/lance/lance_data_sink.py
  tests/io/lancedb/test_lancedb_writes.py
Labels: fix

#4999 fix: Lazily import pyarrow when importing daft
  daft/datatype.py
  daft/expressions/expressions.py
  daft/expressions/pyarrow_visitor.py
  daft/expressions/visitor.py
  daft/extension_type.py
  tests/test_import.py
Labels: fix

#4996 feat: basic read_huggingface functionality
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/io/__init__.py
  daft/io/_huggingface.py
  daft/udf/generator.py
  docs/connectors/huggingface.md
  requirements-dev.txt
  src/common/io-config/src/config.rs
  src/common/io-config/src/huggingface.rs
  src/common/io-config/src/lib.rs
  src/common/io-config/src/python.rs
  src/daft-connect/src/session.rs
  src/daft-io/src/huggingface.rs
  src/daft-io/src/lib.rs
  tests/integration/io/test_read_huggingface.py
  tests/integration/test_huggingface.py
Labels: feat

#4998 feat!: RowWiseUdf.eval for eager evaluation
  daft/udf/__init__.py
  daft/udf/row_wise.py
  tests/udf/test_row_wise_udf.py
Labels: feat, breaking change

#4991 feat: implement distributed sort in flotilla engine
  Cargo.lock
  daft/runners/flotilla.py
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/sample.rs
  src/daft-distributed/src/pipeline_node/shuffles/repartition.rs
  src/daft-distributed/src/pipeline_node/shuffles/translate_shuffle.rs
  src/daft-distributed/src/pipeline_node/sort.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/ray/mod.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-distributed/src/utils/mod.rs
  src/daft-distributed/src/utils/transpose.rs
  src/daft-local-execution/src/intermediate_ops/sample.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/repartition.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/partitioning.rs
  src/daft-recordbatch/src/lib.rs
  tests/dataframe/test_decimals.py
Labels: feat

#4850 feat: add clickhouse data sink
  daft/dataframe/dataframe.py
  daft/io/clickhouse/__init__.py
  daft/io/clickhouse/clickhouse_data_sink.py
  pyproject.toml
  requirements-dev.txt
  tests/io/clickhouse/__init__.py
  tests/io/clickhouse/test_clickhouse_writes.py
Labels: feat

#5010 fix(blc): Attempt to fix the broken link checker.
  .github/workflows/broken-link-checker.yml
Labels: fix

#5002 feat: daft.File object store support
  Cargo.lock
  Cargo.toml
  daft/daft/__init__.pyi
  daft/file.py
  daft/functions/misc.py
  src/common/file/Cargo.toml
  src/common/file/src/lib.rs
  src/common/file/src/python.rs
  src/daft-core/src/array/file_array.rs
  src/daft-core/src/array/growable/mod.rs
  src/daft-core/src/array/mod.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/file.rs
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/array/ops/get_lit.rs
  src/daft-core/src/array/ops/len.rs
  src/daft-core/src/array/ops/repr.rs
  src/daft-core/src/array/ops/sort.rs
  src/daft-core/src/array/ops/take.rs
  src/daft-core/src/datatypes/logical.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/lit/conversions.rs
  src/daft-core/src/lit/mod.rs
  src/daft-core/src/lit/python.rs
  src/daft-core/src/series/array_impl/logical_array.rs
  src/daft-core/src/series/from_lit.rs
  src/daft-core/src/series/ops/downcast.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-file/Cargo.toml
  src/daft-file/src/lib.rs
  src/daft-file/src/python.rs
  src/daft-functions/src/lib.rs
  src/daft-io/src/lib.rs
  src/daft-schema/src/dtype.rs
  src/lib.rs
  tests/file/test_file_udfs.py
  tests/integration/test_file_udfs_s3.py
Labels: feat

#4997 feat: implements an openai provider with embed_text
  .github/workflows/pr-test-suite.yml
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/ai/openai/__init__.py
  daft/ai/openai/text_embedder.py
  daft/ai/openai/typing.py
  daft/ai/provider.py
  daft/ai/sentence_transformers/__init__.py
  daft/ai/sentence_transformers/text_embedder.py
  daft/ai/typing.py
  daft/context.py
  daft/daft/__init__.pyi
  daft/functions/__init__.py
  daft/functions/ai/__init__.py
  daft/io/av/_read_video_frames.py
  daft/session.py
  docs/SUMMARY.md
  docs/api/ai.md
  docs/api/index.md
  docs/api/sessions.md
  docs/gen_pages/gen_function_pages.py
  pyproject.toml
  src/daft-ai/Cargo.toml
  src/daft-ai/src/lib.rs
  src/daft-ai/src/provider.rs
  src/daft-ai/src/python.rs
  src/daft-session/Cargo.toml
  src/daft-session/src/options.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/lib.rs
  tests/ai/openai/__init__.py
  tests/ai/openai/test_openai_provider.py
  tests/ai/openai/test_openai_text_embedder.py
  tests/ai/test_sentence_transformers.py
  tests/catalog/test_iceberg.py
  tests/integration/ai/__init__.py
  tests/integration/ai/test_openai.py
  tests/test_context.py
  tests/test_session.py
Labels: feat

#5047 fix: subprocess UDF inherits current process env
  daft/ai/openai/text_embedder.py
  daft/execution/udf.py
  requirements-dev.txt
Labels: fix

#5049 docs: add reo script to docs
  docs/js/reo.js
  mkdocs.yml
Labels: docs

#5036 feat: basic generator udf
  daft/expressions/expressions.py
  daft/udf/__init__.py
  daft/udf/_internal.py
  daft/udf/generator.py
  daft/udf/row_wise.py
  tests/udf/test_generator_udf.py
  tests/udf/test_row_wise_udf.py
Labels: feat

#5039 chore: random the counter during creating DistributedActorPoolProject…
  src/daft-local-execution/src/intermediate_ops/distributed_actor_pool_project.rs
Labels: chore

#4983 fix: correct Modin query optimizer value in comparison tables
  README.rst
  docs/resources/engine_comparison.md
Labels: fix

#5040 chore: disable hugging face library progress bars
  daft/io/huggingface/sink.py
Labels: chore

#5056 docs: remove runllm widget
  docs/js/runllm.js
  mkdocs.yml
Labels: docs

#5055 fix: clean notebook output before running tests & tweak doc proc notebook
  .github/workflows/notebook-checker.yml
  tutorials/document_processing/document_processing_tutorial.ipynb
Labels: fix, on-call

#4710 feat: pushdown for lance scan
  daft/context.py
  daft/daft/__init__.pyi
  daft/io/lance/lance_scan.py
  src/common/daft-config/src/python.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  tests/io/lancedb/test_lancedb_reads.py
Labels: feat

#4994 docs: fix formatting
  docs/modalities/videos.md
Labels: docs

#5059 fix: require uv as prerequisite for development setup
  CONTRIBUTING.md
  Makefile
Labels: fix

#5057 ci: Don't run pr test suite on non-code changes fr
  .github/workflows/pr-test-suite.yml
Labels: ci

#5062 docs: remove core_concepts.md and broken anchor link references
  docs/api/aggregations.md
  docs/api/dataframe.md
  docs/api/datatypes.md
  docs/api/expressions.md
  docs/api/schema.md
  docs/api/window.md
  docs/core_concepts.md
  docs/migration/dask_migration.md
  docs/quickstart.md
Labels: docs

#5063 docs: Add better description in overview page
  docs/index.md
Labels: docs

#5067 docs: Make overview page legible for light mode
  docs/index.md
Labels: docs

#5068 revert: Temporarily revert "Remove deprecated APIs for 0.6"
  benchmarking/tpcds/__main__.py
  benchmarking/tpcds/helpers.py
  benchmarking/tpch/answers_sql.py
  daft/__init__.py
  daft/catalog/__glue.py
  daft/catalog/__iceberg.py
  daft/catalog/__unity.py
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/catalog.py
  daft/recordbatch/micropartition.py
  daft/series.py
  daft/sql/__init__.py
  daft/sql/sql.py
  docs/api/expressions.md
  docs/examples/window-functions.md
  docs/modalities/json.md
  src/daft-scan/src/builder.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/python.rs
  src/daft-sql/src/table_provider/read_csv.rs
  src/daft-sql/src/table_provider/read_json.rs
  tests/benchmarks/test_local_tpch.py
  tests/recordbatch/list/test_list_count_length.py
  tests/sql/set_ops.py
  tests/sql/test_exprs.py
  tests/sql/test_float_exprs.py
  tests/sql/test_joins.py
  tests/sql/test_list_exprs.py
  tests/sql/test_partitioning_exprs.py
  tests/sql/test_sql_catalog.py
  tests/sql/test_sql_null_safe_equals.py
  tests/sql/test_sql_udfs.py
  tests/sql/test_temporal_exprs.py
  tests/sql/test_window.py
  tutorials/window_functions/window_functions.ipynb
Labels: revert

#5061 fix: Use cachebusting and range request fallback for HTTP requests to Hugging Face CDNs
  src/daft-io/src/huggingface.rs
  src/daft-io/src/lib.rs
  tests/integration/io/huggingface/test_read_huggingface.py
Labels: fix

#5073 fix: Fix venv command for windows build
  .github/workflows/build-wheel.yml
Labels: fix

#5017 fix: Implement Multi-Column Aggregations with List-like columns
  src/daft-core/src/array/fixed_size_list_array.rs
  src/daft-core/src/array/list_array.rs
  src/daft-core/src/array/ops/arrow2/comparison.rs
  tests/dataframe/test_aggregations.py
  tests/expressions/test_expressions.py
Labels: fix

#4727 feat: add mcap datasource reader
  daft/__init__.py
  daft/io/__init__.py
  daft/io/mcap/_mcap.py
  daft/io/mcap/mcap_json_decoder.py
  pyproject.toml
  tests/io/mcap/test_mcap.py
Labels: feat

#5082 perf(embed_text): Let Sentence Transformers select the best available device
  daft/ai/sentence_transformers/text_embedder.py
  tests/ai/test_sentence_transformers.py
Labels: perf

#5084 revert!: "revert: Temporarily revert "Remove deprecated APIs for 0.6"
  benchmarking/tpcds/__main__.py
  benchmarking/tpcds/helpers.py
  benchmarking/tpch/answers_sql.py
  daft/__init__.py
  daft/catalog/__glue.py
  daft/catalog/__iceberg.py
  daft/catalog/__unity.py
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/io/_csv.py
  daft/io/_json.py
  daft/io/_parquet.py
  daft/io/catalog.py
  daft/recordbatch/micropartition.py
  daft/series.py
  daft/sql/__init__.py
  daft/sql/sql.py
  docs/api/expressions.md
  docs/examples/window-functions.md
  docs/modalities/json.md
  src/daft-scan/src/builder.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/python.rs
  src/daft-sql/src/table_provider/read_csv.rs
  src/daft-sql/src/table_provider/read_json.rs
  tests/benchmarks/test_local_tpch.py
  tests/recordbatch/list/test_list_count_length.py
  tests/sql/set_ops.py
  tests/sql/test_exprs.py
  tests/sql/test_float_exprs.py
  tests/sql/test_joins.py
  tests/sql/test_list_exprs.py
  tests/sql/test_partitioning_exprs.py
  tests/sql/test_sql_catalog.py
  tests/sql/test_sql_null_safe_equals.py
  tests/sql/test_sql_udfs.py
  tests/sql/test_temporal_exprs.py
  tests/sql/test_window.py
  tutorials/window_functions/window_functions.ipynb
Labels: breaking change, revert

#5075 fix: Handle Unserializable Errors in Process UDFs
  daft/execution/udf.py
  daft/execution/udf_worker.py
  tests/expressions/test_legacy_udf.py
Labels: fix

#5070 perf: Split UDFs from Filters
  src/daft-dsl/src/expr/mod.rs
  src/daft-local-execution/src/intermediate_ops/udf.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/ops/udf.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/split_udfs.rs
Labels: perf

#5092 docs: Document write_turbopuffer in the user guide
  docs/SUMMARY.md
  docs/connectors/turbopuffer.md
Labels: docs

#5091 fix: Check if UDFs are Serializable
  daft/execution/udf.py
  daft/execution/udf_worker.py
  daft/io/lance/lance_merge_column.py
  daft/pickle/cloudpickle.py
  daft/pickle/cloudpickle_fast.py
  daft/pickle/compat.py
  daft/pickle/pickle.py
  daft/udf/_internal.py
  daft/udf/generator.py
  daft/udf/legacy.py
  daft/udf/row_wise.py
  tests/expressions/test_legacy_udf.py
  uv.lock
Labels: fix

#5095 docs: More fixes to the overview page in light mode
  docs/index.md
Labels: docs

#5094 docs: Improve installation instructions
  docs/SUMMARY.md
  docs/install.md
  docs/js/install-tool.js
  mkdocs.yml
  pyproject.toml
Labels: docs

#5096 ci: Do not skip postmerge tests
  .github/workflows/pr-test-suite.yml
Labels: ci

#5102 docs: Add text guide
  docs/connectors/turbopuffer.md
  docs/modalities/text.md
Labels: docs
