Repository Eventual-Inc/Daft, pull requests merged in 2025-07, with the labels that each got.

#4668 fix: Fix setting `min_cpu_per_task` when using `daft.context.set_execution_config`
  daft/context.py
Labels: fix

#4540 feat: Add support for JSON writes in the native runner
  Cargo.lock
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/arrow2/src/datatypes/mod.rs
  src/common/daft-config/src/lib.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-writers/Cargo.toml
  src/daft-writers/src/json_writer.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
  src/daft-writers/src/physical.rs
  tests/integration/io/test_write_files_s3_minio.py
  tests/io/test_json_roundtrip.py
Labels: feat

#4635 feat: move lakehouse source to io directory
  daft/catalog/__glue.py
  daft/catalog/__iceberg.py
  daft/catalog/__unity.py
  daft/dataframe/dataframe.py
  daft/io/__init__.py
  daft/io/delta_lake/__init__.py
  daft/io/delta_lake/_deltalake.py
  daft/io/delta_lake/delta_lake_scan.py
  daft/io/delta_lake/delta_lake_write.py
  daft/io/hudi/__init__.py
  daft/io/hudi/_hudi.py
  daft/io/hudi/hudi_scan.py
  daft/io/hudi/pyhudi/__init__.py
  daft/io/hudi/pyhudi/filegroup.py
  daft/io/hudi/pyhudi/table.py
  daft/io/hudi/pyhudi/timeline.py
  daft/io/hudi/pyhudi/utils.py
  daft/io/iceberg/__init__.py
  daft/io/iceberg/_iceberg.py
  daft/io/iceberg/iceberg_scan.py
  daft/io/iceberg/iceberg_write.py
  daft/io/iceberg/schema_field_id_mapping_visitor.py
  daft/io/lance/_lance.py
  daft/io/writer.py
  daft/logical/builder.py
  daft/recordbatch/recordbatch_io.py
Labels: feat

#4696 fix: Picking MicroPartitions with duplicate column names
  daft/recordbatch/micropartition.py
  daft/recordbatch/recordbatch.py
  tests/recordbatch/test_micropartition.py
Labels: fix

#4709 fix(flotilla): Add back autoscaling function
  daft/runners/flotilla.py
Labels: fix

#4715 fix(flotilla): Change MaterializedOutput to return a Vec<Partitions>
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/utils/stream.rs
  tests/integration/iceberg/docker-compose/docker-compose.yml
Labels: fix

#4626 feat(flotilla): Repartition
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/explode.rs
  src/daft-distributed/src/pipeline_node/filter.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/project.rs
  src/daft-distributed/src/pipeline_node/repartition.rs
  src/daft-distributed/src/pipeline_node/sample.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/sink.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/pipeline_node/unpivot.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/aggregate.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/commit_write.rs
  src/daft-local-execution/src/sinks/cross_join_collect.rs
  src/daft-local-execution/src/sinks/dedup.rs
  src/daft-local-execution/src/sinks/grouped_aggregate.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/pivot.rs
  src/daft-local-execution/src/sinks/repartition.rs
  src/daft-local-execution/src/sinks/sort.rs
  src/daft-local-execution/src/sinks/top_n.rs
  src/daft-local-execution/src/sinks/window_order_by_only.rs
  src/daft-local-execution/src/sinks/window_partition_and_dynamic_frame.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-local-execution/src/sinks/window_partition_only.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-micropartition/src/ops/concat.rs
Labels: feat

#4714 docs: Add debugging udfs docs
  docs/core_concepts.md
Labels: docs

#4721 chore: disable another flaky test
  src/daft-local-execution/src/runtime_stats/mod.rs
Labels: chore

#4686 feat(flotilla): support task progress for logical plan graph
  Cargo.lock
  daft/dashboard/__init__.py
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/explode.rs
  src/daft-distributed/src/pipeline_node/filter.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/project.rs
  src/daft-distributed/src/pipeline_node/repartition.rs
  src/daft-distributed/src/pipeline_node/sample.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/sink.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/pipeline_node/unpivot.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/plan/runner.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/progress_bar.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/statistics/http_subscriber.rs
  src/daft-distributed/src/statistics/http_subscriber_test.rs
  src/daft-distributed/src/statistics/mod.rs
  src/daft-ir/src/lib.rs
  src/daft-local-execution/src/run.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/actor_pool_project.rs
  src/daft-logical-plan/src/ops/agg.rs
  src/daft-logical-plan/src/ops/concat.rs
  src/daft-logical-plan/src/ops/distinct.rs
  src/daft-logical-plan/src/ops/explode.rs
  src/daft-logical-plan/src/ops/filter.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/limit.rs
  src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
  src/daft-logical-plan/src/ops/pivot.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/ops/repartition.rs
  src/daft-logical-plan/src/ops/sample.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/ops/shard.rs
  src/daft-logical-plan/src/ops/sink.rs
  src/daft-logical-plan/src/ops/sort.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/ops/top_n.rs
  src/daft-logical-plan/src/ops/unpivot.rs
  src/daft-logical-plan/src/ops/window.rs
  src/daft-logical-plan/src/optimization/rules/simplify_expressions.rs
  src/daft-logical-plan/src/treenode.rs
Labels: feat

#4730 chore(flotilla): Refactor task naming for clarity
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/linear.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
Labels: chore

#4733 fix: update readme banner image link
  README.rst
Labels: fix

#4738 fix: `DAFT_FLOTILLA` env var should check for false conditions now
  src/common/daft-config/src/lib.rs
  tests/window/test_partition_only.py
  tests/window/test_partition_order_by_lag_lead.py
  tests/window/test_partition_order_by_rank.py
  tests/window/test_running_agg.py
Labels: fix

#4717 feat(flotilla): Add monotonically_increasing_id.
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/monotonically_increasing_id.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/streaming_sink/monotonically_increasing_id.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/display/json.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
  src/daft-logical-plan/src/optimization/rules/detect_monotonic_id.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
Labels: feat

#4700 feat(flotilla): Hash Join
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/distinct.rs
  src/daft-distributed/src/pipeline_node/explode.rs
  src/daft-distributed/src/pipeline_node/filter.rs
  src/daft-distributed/src/pipeline_node/groupby_agg.rs
  src/daft-distributed/src/pipeline_node/hash_join.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/monotonically_increasing_id.rs
  src/daft-distributed/src/pipeline_node/project.rs
  src/daft-distributed/src/pipeline_node/repartition.rs
  src/daft-distributed/src/pipeline_node/sample.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/sink.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/pipeline_node/unpivot.rs
  src/daft-distributed/src/pipeline_node/window.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-local-plan/src/plan.rs
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  tests/connect/test_spark_joins.py
  tests/dataframe/test_monotonically_increasing_id.py
  tests/dataframe/test_pipe.py
  tests/sql/test_joins.py
  tests/sql/test_sql_null_safe_equals.py
  tests/utils.py
Labels: feat

#4750 docs: Add document processing notebook tutorial
  docs/core_concepts.md
  docs/resources/tutorials.md
  tutorials/document_processing/document_processing_tutorial.ipynb
Labels: docs

#4748 feat(flotilla): Added concat
  src/daft-distributed/src/pipeline_node/concat.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
Labels: feat

#4752 fix: populate query graph nodes even if they lack task progress
  src/daft-distributed/src/statistics/http_subscriber.rs
Labels: fix

#4751 feat: explode expression
  daft/expressions/expressions.py
  src/daft-dsl/src/functions/scalar.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
  src/daft-logical-plan/src/optimization/rules/split_explode_from_project.rs
  tests/expressions/test_explode.py
Labels: feat

#4761 fix: Swap arg order for list_fill
  src/daft-functions-list/src/list_fill.rs
  src/daft-logical-plan/src/ops/set_operations.rs
Labels: fix

#4764 fix: fix explode expr doc test
  daft/expressions/expressions.py
Labels: fix

#4762 fix: Put to_partition_tasks call in try block
  daft/runners/ray_runner.py
Labels: fix

#4757 fix(flotilla): Add multiple notify tokens to task
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  tests/expressions/test_udf.py
Labels: fix

#4701 feat(flotilla): Support Gather Variants of Aggs
  src/daft-distributed/src/pipeline_node/aggregate.rs
  src/daft-distributed/src/pipeline_node/gather.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/pipeline_node/window.rs
  src/daft-distributed/src/stage/stage_builder.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/ops/joins/mod.rs
  tests/sql/test_window.py
  tests/window/test_order_by_only.py
Labels: feat

#4767 fix: Change dashboard warning to info
  src/daft-distributed/src/python/mod.rs
Labels: fix

#4734 feat(flotilla): Sort & Top-N
  src/daft-distributed/src/pipeline_node/hash_join.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/sort.rs
  src/daft-distributed/src/pipeline_node/top_n.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/stage_builder.rs
Labels: feat

#4766 fix: Ignore partition refs if they are empty
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/repartition.rs
Labels: fix

#4688 feat: support suffix range get
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/azure_blob.rs
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/http.rs
  src/daft-io/src/huggingface.rs
  src/daft-io/src/integrations.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/local.rs
  src/daft-io/src/object_io.rs
  src/daft-io/src/range.rs
  src/daft-io/src/s3_like.rs
  src/daft-io/src/unity.rs
Labels: feat

#4758 fix: document processing notebook and explode expression docs
  .github/workflows/notebook-checker.yml
  daft/expressions/expressions.py
  tutorials/document_processing/document_processing_tutorial.ipynb
  tutorials/flyte/notebook.ipynb
  tutorials/window_functions/window_functions.ipynb
Labels: fix

#4779 feat: Add experimental turbopuffer sink
  daft/io/turbopuffer/__init__.py
  daft/io/turbopuffer/turbopuffer_data_sink.py
Labels: feat

#4787 ci: enable building wheels without LTO
  .github/workflows/build-wheel.yml
  .github/workflows/publish-dev-s3.yml
Labels: ci

#4789 fix(repr): avoid crashing notebook UI when visualizing large strings
  .vscode/settings.json
  src/daft-core/src/array/ops/repr.rs
  tests/series/test_html_repr.py
Labels: fix

#4790 fix: use pc.field in turbopuffer sink
  daft/io/turbopuffer/turbopuffer_data_sink.py
Labels: fix

#4788 fix: Improve UDF Error Messaging
  daft/__init__.py
  daft/api_annotations.py
  daft/dataframe/dataframe.py
  daft/errors.py
  daft/execution/actor_pool_udf.py
  daft/udf.py
  tests/dataframe/test_iter.py
  tests/expressions/test_udf.py
Labels: fix

#4799 fix: mark all pending nodes completed when plan completes
  src/daft-distributed/src/statistics/http_subscriber.rs
Labels: fix

#4800 fix: Propagate worker failures to scheduler
  daft/execution/ray_actor_pool_udf.py
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  tests/expressions/test_udf.py
Labels: fix

#4802 feat: Spread actor udf tasks
  daft/datatype.py
  daft/execution/ray_actor_pool_udf.py
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-local-execution/src/intermediate_ops/distributed_actor_pool_project.rs
Labels: feat

#4804 chore: remove dbg from tests
  src/daft-functions-list/src/list_fill.rs
Labels: chore

#4805 fix: LSP handling for `daft.context` and `daft.io`
  daft/__init__.py
Labels: fix

#4807 chore: add DAFT_LOG env indicates log level
  CONTRIBUTING.md
  src/lib.rs
Labels: chore

#4815 feat: struct Expression.unnest()
  daft/expressions/expressions.py
Labels: feat

#4823 fix: add custom robots.txt
  docs/robots.txt
Labels: fix

#4825 feat(turbopuffer): Add client and write kwargs
  daft/dataframe/dataframe.py
  daft/io/turbopuffer/turbopuffer_data_sink.py
Labels: feat

#4817 fix: Fix `File writer must be created before bytes_written can be called` bug in native parquet writer
  src/daft-writers/src/parquet_writer.rs
Labels: fix

#4838 docs: categorize functions and make each function its own page
  Makefile
  daft/functions/__init__.py
  daft/functions/columnar.py
  daft/functions/functions.py
  daft/functions/llm.py
  daft/functions/misc.py
  daft/functions/window.py
  docs/SUMMARY.md
  docs/api/functions.md
  docs/api/index.md
  docs/api/window.md
  docs/gen_pages/gen_function_pages.py
  docs/gen_pages/templates/function_page.md.j2
  docs/gen_pages/templates/functions.md.j2
  mkdocs.yml
  requirements-dev.txt
  requirements-doc.txt
  tests/dataframe/test_horizontal.py
  tests/functions/test_llm_generate.py
Labels: docs

#4834 fix: read/write embeddings for Parquet and Lance
  daft/io/writer.py
  src/daft-core/src/array/ops/cast.rs
  tests/io/test_roundtrip_embeddings.py
  tests/series/test_cast.py
  tests/utils.py
Labels: fix

#4775 feat: optimize read parquet metadata logic via suffix-range get
  src/daft-io/src/lib.rs
  src/daft-io/src/object_io.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/metadata.rs
  src/daft-parquet/src/read_planner.rs
  tests/integration/io/docker-compose/retry_server/main.py
  tests/integration/io/docker-compose/retry_server/routers/head_retries_parquet_bucket.py
  tests/integration/io/docker-compose/retry_server/routers/retries_parquet_bucket.py
  tests/integration/io/docker-compose/retry_server/utils/request_range.py
  tests/integration/io/parquet/test_reads_local_fixtures.py
Labels: feat

#4678 ci: update daft domain
  .github/workflows/broken-link-checker.yml
Labels: ci

#4836 feat: Use daft-decoding for hive value deserialization
  src/daft-decoding/src/deserialize.rs
  src/daft-scan/src/hive.rs
  tests/io/test_hive_style_partitions.py
Labels: feat

#4845 feat: Support multiple namespaces in the turbopuffer writer
  daft/dataframe/dataframe.py
  daft/io/turbopuffer/turbopuffer_data_sink.py
Labels: feat

#4855 fix: Allow anonymous mode to be used for S3 uploads
  src/daft-io/src/s3_like.rs
  tests/integration/io/conftest.py
  tests/integration/io/test_files_roundtrip_s3_minio.py
  tests/integration/io/test_write_files_s3_minio.py
Labels: fix

#4852 fix: concat chunked array safety
  daft/series.py
  daft/udf.py
  tests/expressions/test_udf.py
Labels: fix

#4858 fix: Handle unserializable exceptions from data sinks
  daft/io/sink.py
  src/daft-writers/src/sink.rs
  tests/io/test_sink.py
Labels: fix

#4853 fix: add cachebusting parameter to huggingface urls
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-io/src/huggingface.rs
  tests/integration/test_huggingface.py
Labels: fix

#4856 docs: add more docs for UDF concurrency
  daft/udf/legacy.py
  docs/core_concepts.md
  tutorials/document_processing/document_processing_tutorial.ipynb
Labels: docs

#4863 fix: Fix list sorting when operating on a morsel slice
  src/daft-functions-list/src/kernels.rs
  tests/recordbatch/list/test_list_sort.py
Labels: fix

#4810 feat: Add `get_or_infer_runner_type` to support getting runner type from context
  daft/context.py
  daft/daft/__init__.pyi
  daft/utils.py
  src/daft-context/src/lib.rs
  src/daft-context/src/python.rs
  src/daft-py-runners/src/lib.rs
  tests/test_context.py
Labels: feat

#4877 fix(runtime): Reduce thread name length for compute and I/O threadpools
  src/common/runtime/src/lib.rs
Labels: fix
