Repository Eventual-Inc/Daft, pull requests merged in 2025-05, with the labels that each got.

#4279 ci: Fix nightly tests
  .github/workflows/nightly-publish-s3.yml
Labels: ci

#4266 docs: small fixes
  docs/api/aggregations.md
  docs/api/expressions.md
  docs/api/functions.md
  docs/api/index.md
  docs/api/window.md
  docs/sql_overview.md
  mkdocs.yml
Labels: docs

#4272 ci: compile release build with glibc 2.24
  .github/workflows/build-wheel.yml
  .github/workflows/pr-test-suite.yml
  src/daft-dashboard/build.rs
Labels: ci

#4282 ci: add bun build step to CI profiling workflow
  .github/workflows/daft-profiling.yml
Labels: ci

#4267 feat: adds DataFrame pipe method
  daft/dataframe/dataframe.py
  tests/dataframe/test_pipe.py
Labels: feat

#4285 refactor: move FileInfo/FileInfos definitions to daft-recordbatch
  Cargo.lock
  src/daft-logical-plan/src/lib.rs
  src/daft-logical-plan/src/source_info.rs
  src/daft-recordbatch/Cargo.toml
  src/daft-recordbatch/src/file_info.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/python.rs
Labels: refactor

#4250 feat: Flotilla scaffolding
  Cargo.lock
  Cargo.toml
  daft/context.py
  daft/daft/__init__.pyi
  daft/execution/native_executor.py
  daft/runners/constants.py
  daft/runners/distributed_swordfish.py
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/utils.py
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/common/partitioning/src/lib.rs
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/channel.rs
  src/daft-distributed/src/lib.rs
  src/daft-distributed/src/pipeline_node/collect.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/ray/mod.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/runtime.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/mod.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/scheduling/worker.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/run.rs
  src/daft-local-plan/Cargo.toml
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/python.rs
  src/daft-micropartition/src/partitioning.rs
  src/daft-shuffles/Cargo.toml
  src/lib.rs
Labels: feat

#4287 chore: Use native runner if config is set regardless of ray initialization
  src/daft-context/src/lib.rs
Labels: chore

#4289 ci: Fix uv issues for nightly TPCH benchmarks
  .github/workflows/benchmark-distributed-tpch.yml
  .github/workflows/benchmark-local-tpch.yml
Labels: ci

#4261 feat: allow making multiplication arithmetics with Interval data type
  src/arrow2/src/compute/arithmetics/time.rs
  src/daft-core/src/array/from.rs
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/datatypes/infer_datatype.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-sql/src/lib.rs
  tests/sql/test_exprs.py
Labels: feat

#4291 ci: add bun run build to property based testing
  .github/workflows/property-based-tests.yml
Labels: ci

#4271 refactor(exprs): 1 of N -- simplify expr logic
  daft/daft/__init__.pyi
  daft/series.py
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/float.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-functions/src/float/fill_nan.rs
  src/daft-functions/src/float/is_inf.rs
  src/daft-functions/src/float/is_nan.rs
  src/daft-functions/src/float/mod.rs
  src/daft-functions/src/float/not_nan.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/python.rs
  tests/expressions/typing/test_float.py
  tests/series/test_float.py
Labels: refactor

#4277 refactor: 2 of N simplify expr & series
  daft/daft/__init__.pyi
  daft/series.py
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/cbrt.rs
  src/daft-core/src/series/ops/ceil.rs
  src/daft-core/src/series/ops/clip.rs
  src/daft-core/src/series/ops/exp.rs
  src/daft-core/src/series/ops/mod.rs
  src/daft-core/src/series/ops/round.rs
  src/daft-core/src/series/ops/sign.rs
  src/daft-core/src/series/ops/sqrt.rs
  src/daft-core/src/series/ops/trigonometry.rs
  src/daft-functions/src/numeric/abs.rs
  src/daft-functions/src/numeric/cbrt.rs
  src/daft-functions/src/numeric/ceil.rs
  src/daft-functions/src/numeric/clip.rs
  src/daft-functions/src/numeric/exp.rs
  src/daft-functions/src/numeric/floor.rs
  src/daft-functions/src/numeric/round.rs
  src/daft-functions/src/numeric/sign.rs
  src/daft-functions/src/numeric/sqrt.rs
  src/daft-functions/src/numeric/trigonometry.rs
Labels: refactor

#4299 docs: Specify what script the debug config uses in `CONTRIBUTING.md`
  CONTRIBUTING.md
  tools/attach_debugger.py
Labels: docs

#4305 chore: Update supported python version in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore

#4306 feat: Flotilla stage redesign
  Cargo.lock
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/collect.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/stage/stage_builder.rs
Labels: feat

#4253 feat(window): dynamic window frame incremental updates
  daft/expressions/expressions.py
  docs/api/window.md
  docs/core_concepts.md
  docs/sql/window_functions.md
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-local-plan/src/translate.rs
  src/daft-recordbatch/src/ops/mod.rs
  src/daft-recordbatch/src/ops/window.rs
  src/daft-recordbatch/src/ops/window_states/count.rs
  src/daft-recordbatch/src/ops/window_states/count_distinct.rs
  src/daft-recordbatch/src/ops/window_states/mean.rs
  src/daft-recordbatch/src/ops/window_states/minmax.rs
  src/daft-recordbatch/src/ops/window_states/mod.rs
  src/daft-recordbatch/src/ops/window_states/sum.rs
  tests/sql/test_window.py
  tests/window/test_partition_order_by_lag_lead.py
  tests/window/test_partition_order_by_rank.py
  tests/window/test_running_agg.py
Labels: feat

#4298 feat: temporal functions `quarter`, `unix_date`, `unix_micros`, `unix_millis`, `unix_seconds`
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-connect/src/functions/datetime.rs
  src/daft-core/src/array/ops/time.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/time.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/temporal.rs
  src/daft-functions/src/temporal/mod.rs
  src/daft-sql/src/modules/temporal.rs
  src/daft-sql/src/planner.rs
  tests/expressions/test_expressions.py
  tests/series/test_temporal_ops.py
  tests/sql/test_temporal_exprs.py
Labels: feat

#4297 refactor(ordinals): move column binding out of daft-recordbatch
  Cargo.lock
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-csv/src/local.rs
  src/daft-csv/src/read.rs
  src/daft-dsl/src/expr/bound_expr.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-json/src/local.rs
  src/daft-json/src/read.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/sinks/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/sinks/hash_join_build.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/window_partition_and_dynamic_frame.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-local-execution/src/sinks/window_partition_only.rs
  src/daft-micropartition/src/ops/agg.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/ops/partition.rs
  src/daft-micropartition/src/ops/pivot.rs
  src/daft-micropartition/src/ops/sort.rs
  src/daft-micropartition/src/ops/unpivot.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/ops/agg.rs
  src/daft-recordbatch/src/ops/explode.rs
  src/daft-recordbatch/src/ops/joins/hash_join.rs
  src/daft-recordbatch/src/ops/joins/mod.rs
  src/daft-recordbatch/src/ops/partition.rs
  src/daft-recordbatch/src/ops/pivot.rs
  src/daft-recordbatch/src/ops/sort.rs
  src/daft-recordbatch/src/ops/unpivot.rs
  src/daft-recordbatch/src/ops/window.rs
  src/daft-recordbatch/src/ops/window_states/mod.rs
  src/daft-recordbatch/src/python.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/glob.rs
  src/daft-scan/src/python.rs
  src/daft-schema/src/schema.rs
  src/daft-warc/src/lib.rs
  src/daft-writers/src/partition.rs
Labels: refactor

#4320 feat: Make file writers async
  Cargo.lock
  src/daft-io/Cargo.toml
  src/daft-local-execution/src/sinks/write.rs
  src/daft-shuffles/src/shuffle_cache.rs
  src/daft-writers/Cargo.toml
  src/daft-writers/src/batch.rs
  src/daft-writers/src/catalog.rs
  src/daft-writers/src/file.rs
  src/daft-writers/src/ipc.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/partition.rs
  src/daft-writers/src/physical.rs
  src/daft-writers/src/pyarrow.rs
  src/daft-writers/src/test.rs
Labels: feat

#4325 perf: Perform Local Distinct list_agg in count_distinct aggregations
  src/daft-physical-plan/src/physical_planner/translate.rs
Labels: perf

#4316 feat(window): fix window copy issue
  daft/window.py
  tests/window/test_running_agg.py
Labels: feat

#4322 feat: add support for OTEL metrics and tracing
  Cargo.lock
  Cargo.toml
  src/common/tracing/Cargo.toml
  src/common/tracing/src/lib.rs
  src/daft-csv/Cargo.toml
  src/daft-dashboard/Cargo.toml
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/run.rs
  src/daft-local-execution/src/runtime_stats.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/streaming_sink.rs
  src/daft-local-execution/src/sources/source.rs
  src/lib.rs
  tests/observability/__init__.py
  tests/observability/test_opentelemetry.py
  tools/observability/opentelemetry/README.md
  tools/observability/opentelemetry/docker-compose.yml
  tools/observability/opentelemetry/otelcol-config.yml
  tools/observability/opentelemetry/prometheus.yml
Labels: feat

#4331 docs(window): window function tutorial / demo
  tutorials/window_functions/demo.ipynb
  tutorials/window_functions/image1.png
  tutorials/window_functions/image2.png
  tutorials/window_functions/image3.png
  tutorials/window_functions/image4.png
  tutorials/window_functions/image5.png
  tutorials/window_functions/image6.png
  tutorials/window_functions/output.csv
Labels: docs

#4283 feat(window): tpc-ds queries
  benchmarking/tpcds/__main__.py
  benchmarking/tpcds/datagen.py
Labels: feat

#4318 refactor(ordinals): use indices in RecordBatch::get_column(s)
  daft/daft/__init__.pyi
  daft/execution/execution_step.py
  daft/io/writer.py
  daft/recordbatch/micropartition.py
  daft/recordbatch/partitioning.py
  daft/recordbatch/recordbatch.py
  daft/recordbatch/recordbatch_io.py
  daft/runners/ray_runner.py
  daft/series.py
  src/daft-csv/src/local.rs
  src/daft-csv/src/read.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-json/src/read.rs
  src/daft-local-execution/src/intermediate_ops/inner_hash_join_probe.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/read.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-recordbatch/src/ffi.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/ops/explode.rs
  src/daft-recordbatch/src/ops/joins/hash_join.rs
  src/daft-recordbatch/src/ops/joins/mod.rs
  src/daft-recordbatch/src/ops/mod.rs
  src/daft-recordbatch/src/ops/search_sorted.rs
  src/daft-recordbatch/src/ops/unpivot.rs
  src/daft-recordbatch/src/ops/window.rs
  src/daft-recordbatch/src/ops/window_states/mean.rs
  src/daft-recordbatch/src/ops/window_states/mod.rs
  src/daft-recordbatch/src/ops/window_states/sum.rs
  src/daft-recordbatch/src/python.rs
  src/daft-scan/src/python.rs
  src/daft-shuffles/src/shuffle_cache.rs
  src/daft-stats/src/partition_spec.rs
  src/daft-stats/src/table_stats.rs
  src/daft-warc/src/lib.rs
  src/daft-writers/src/batch.rs
  tests/expressions/test_expressions.py
  tests/expressions/test_null_safe_equals.py
  tests/recordbatch/numeric/test_numeric.py
  tests/recordbatch/temporal/test_temporal.py
  tests/recordbatch/test_from_py.py
  tests/recordbatch/test_if_else.py
  tests/recordbatch/test_joins.py
  tests/recordbatch/test_partitioning.py
  tests/recordbatch/test_sorting.py
  tests/recordbatch/test_table_aggs.py
Labels: refactor

#4294 refactor: 4 of N move all image exprs to new way of writing expressions
  Cargo.lock
  daft/daft/__init__.pyi
  daft/daft/image.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/scalar.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/float/mod.rs
  src/daft-functions/src/image/crop.rs
  src/daft-functions/src/image/decode.rs
  src/daft-functions/src/image/encode.rs
  src/daft-functions/src/image/mod.rs
  src/daft-functions/src/image/resize.rs
  src/daft-functions/src/image/to_mode.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/numeric/mod.rs
  src/daft-functions/src/python/image.rs
  src/daft-functions/src/python/mod.rs
  src/daft-image/Cargo.toml
  src/daft-image/src/functions/crop.rs
  src/daft-image/src/functions/decode.rs
  src/daft-image/src/functions/encode.rs
  src/daft-image/src/functions/mod.rs
  src/daft-image/src/functions/resize.rs
  src/daft-image/src/functions/to_mode.rs
  src/daft-image/src/lib.rs
  src/daft-image/src/python.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-logical-plan/src/partitioning.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/image/mod.rs
  src/daft-sql/src/modules/mod.rs
  src/lib.rs
  tests/series/test_image.py
Labels: refactor

#4324 feat(window): order by with no partition by row number impl
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/window_order_by_only.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-recordbatch/src/ops/window.rs
  tests/window/test_order_by_only.py
Labels: feat

#4336 feat(window): order by-only ranking
  src/daft-local-execution/src/intermediate_ops/mod.rs
  src/daft-local-execution/src/intermediate_ops/window_order_by_only.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/window_order_by_only.rs
  src/daft-local-execution/src/sinks/window_partition_and_dynamic_frame.rs
  src/daft-local-execution/src/sinks/window_partition_and_order_by.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-recordbatch/src/ops/window.rs
  tests/sql/test_window.py
  tests/window/test_order_by_only.py
Labels: feat

#4335 chore: removes requirements-docs.txt
  .readthedocs.yaml
  Makefile
  requirements-docs.txt
Labels: chore

#4334 chore: updates mypy to 1.15.0
  .pre-commit-config.yaml
  daft/daft/__init__.pyi
Labels: chore

#4307 perf: TopN Operator and Optimization
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/mod.rs
  src/daft-local-execution/src/sinks/top_n.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/mod.rs
  src/daft-logical-plan/src/ops/top_n.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-micropartition/src/ops/sort.rs
  src/daft-physical-plan/src/display.rs
  src/daft-physical-plan/src/ops/mod.rs
  src/daft-physical-plan/src/ops/top_n.rs
  src/daft-physical-plan/src/optimization/rules/reorder_partition_keys.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-recordbatch/src/ops/sort.rs
  src/daft-scheduler/src/scheduler.rs
  tests/dataframe/test_sort.py
Labels: perf

#4337 chore: Add daft-dashboard frontend build step to Makefile
  Makefile
Labels: chore

#4339 fix: Add pip installs to window demo
  tutorials/window_functions/demo.ipynb
Labels: fix

#4278 feat: adds expression visitor
  daft/daft/__init__.pyi
  daft/expressions/__init__.py
  daft/expressions/visitor.py
  daft/iceberg/iceberg_write.py
  docs/api/expressions.md
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/python.rs
  src/daft-dsl/src/visitor.rs
  tests/expressions/test_visitor.py
Labels: feat

#4254 feat: adds user-defined dataframe source apis
  daft/__init__.py
  daft/dataframe/dataframe.py
  daft/io/__init__.py
  daft/io/__shim.py
  daft/io/_range.py
  daft/io/pushdowns.py
  daft/io/scan.py
  daft/io/source.py
  daft/logical/schema.py
  daft/schema.py
  docs/advanced/pushdowns.md
  docs/api/dataframe_creation.md
  docs/api/io.md
  docs/api/pushdowns.md
  docs/api/schema.md
  docs/io.md
  mkdocs.yml
  requirements-dev.txt
  src/daft-connect/src/spark_analyzer.rs
  tests/catalog/test_catalog.py
  tests/catalog/test_glue.py
  tests/io/test_pushdowns.py
  tests/io/test_range.py
Labels: feat

#4330 docs: add algolia search, separate primary & secondary nav, stylistic changes
  daft/daft/__init__.pyi
  docs/api/config.md
  docs/core_concepts.md
  docs/css/docsearch.css
  docs/css/extra.css
  docs/js/custom.js
  docs/js/docsearch.js
  docs/overrides/partials/header.html
  docs/overrides/partials/nav-item.html
  docs/overrides/partials/search.html
  docs/quickstart.md
  mkdocs.yml
  src/daft-schema/src/image_mode.rs
Labels: docs

#4244 feat: Add generic interface for custom data sinks
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/dataframe/lance_data_sink.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/io/__init__.py
  daft/io/sink.py
  daft/logical/builder.py
  docs/io.md
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/lib.rs
  src/daft-logical-plan/src/ops/sink.rs
  src/daft-logical-plan/src/sink_info.rs
  src/daft-physical-plan/src/display.rs
  src/daft-physical-plan/src/ops/data_sink_write.rs
  src/daft-physical-plan/src/ops/mod.rs
  src/daft-physical-plan/src/optimization/rules/reorder_partition_keys.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-physical-plan/src/plan.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/sink.rs
Labels: feat

#4346 feat: Add `Expr.skew`
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/mod.rs
  src/daft-core/src/array/ops/skew.rs
  src/daft-core/src/datatypes/agg_ops.rs
  src/daft-core/src/datatypes/mod.rs
  src/daft-core/src/series/ops/agg.rs
  src/daft-core/src/utils/stats.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/python.rs
  src/daft-logical-plan/src/ops/project.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-sql/src/modules/aggs.rs
  tests/dataframe/test_aggregations.py
Labels: feat

#4302 refactor: 5 of N expression refactor (json functions)
  Cargo.lock
  daft/expressions/expressions.py
  src/daft-functions-json/Cargo.toml
  src/daft-functions-json/src/expr.rs
  src/daft-functions-json/src/lib.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/mod.rs
  src/lib.rs
Labels: refactor

#4350 docs: fix readthedocs timeouts
  .readthedocs.yaml
  daft/catalog/__init__.py
  daft/io/__shim.py
  daft/io/pushdowns.py
  daft/session.py
  docs/api/dataframe_creation.md
  docs/api/expressions.md
  docs/api/io.md
  docs/io.md
  mkdocs.yml
  requirements-dev.txt
  requirements-doc.txt
Labels: docs

#4342 refactor(ordinals): bound expressions in table statistics
  Cargo.lock
  daft/daft/__init__.pyi
  daft/recordbatch/micropartition.py
  daft/recordbatch/recordbatch.py
  daft/recordbatch/recordbatch_io.py
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/ops/cast_to_schema.rs
  src/daft-micropartition/src/ops/eval_expressions.rs
  src/daft-micropartition/src/ops/filter.rs
  src/daft-micropartition/src/ops/join.rs
  src/daft-micropartition/src/python.rs
  src/daft-parquet/src/file.rs
  src/daft-parquet/src/lib.rs
  src/daft-parquet/src/statistics/table_stats.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/python.rs
  src/daft-scan/src/lib.rs
  src/daft-schema/src/schema.rs
  src/daft-stats/Cargo.toml
  src/daft-stats/src/table_stats.rs
Labels: refactor

#4345 feat: Flotilla utils
  Cargo.lock
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/lib.rs
  src/daft-distributed/src/pipeline_node/collect.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/runtime.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/utils/channel.rs
  src/daft-distributed/src/utils/joinset.rs
  src/daft-distributed/src/utils/mod.rs
  src/daft-distributed/src/utils/runtime.rs
  src/daft-distributed/src/utils/stream.rs
Labels: feat

#4343 chore: cleanup pushdowns
  daft/daft/__init__.pyi
  daft/delta_lake/delta_lake_scan.py
  daft/hudi/hudi_scan.py
  daft/iceberg/iceberg_scan.py
  daft/io/__shim.py
  daft/io/_generator.py
  daft/io/_lance.py
  daft/io/pushdowns.py
  daft/io/scan.py
  daft/sql/sql_scan.py
  docs/advanced/pushdowns.md
  docs/api/io.md
  src/common/scan-info/src/python.rs
  src/daft-csv/src/read.rs
  tests/io/test_iceberg_pushdowns.py
  tests/io/test_pushdowns.py
Labels: chore

#4363 fix: CSV read with disjoint predicate pushdown
  src/daft-csv/src/read.rs
  src/daft-json/src/read.rs
  tests/integration/io/csv/test_read_pushdowns.py
Labels: fix

#4367 fix: mirror raw.githubusercontent via S3 to avoid CI throttling
  tests/integration/io/parquet/test_reads_public_data.py
Labels: fix

#4365 fix: ignores tests/integration for make test target
  Makefile
  tests/sql/test_uri_exprs.py
Labels: fix

#4351 chore(exprs): add helper methods for extracting scalars from function args
  Cargo.lock
  daft/expressions/expressions.py
  src/common/io-config/Cargo.toml
  src/daft-connect/src/execute.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/function_args.rs
  src/daft-dsl/src/lit/conversions.rs
  src/daft-dsl/src/lit/deserializer.rs
  src/daft-dsl/src/lit/mod.rs
  src/daft-dsl/src/lit/serializer.rs
  src/daft-dsl/src/python.rs
  src/daft-sql/src/modules/python.rs
Labels: chore

#4354 feat: add a `repr_json` for logical plans.
  Cargo.lock
  daft/daft/__init__.pyi
  src/daft-logical-plan/Cargo.toml
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/display/json.rs
  src/daft-logical-plan/src/ops/set_operations.rs
Labels: feat

#4352 refactor(exprs): url upload/download to new pattern
  daft/expressions/expressions.py
  src/daft-functions/src/uri/download.rs
  src/daft-functions/src/uri/mod.rs
  src/daft-functions/src/uri/upload.rs
  src/daft-sql/src/functions.rs
  src/daft-sql/src/modules/mod.rs
  src/daft-sql/src/modules/uri/mod.rs
  src/daft-sql/src/modules/uri/url_download.rs
  src/daft-sql/src/modules/uri/url_upload.rs
  src/lib.rs
  tests/io/test_url_upload_local.py
Labels: refactor

#4368 feat: Add optional spark dependency for pyspark connector
  docs/spark_connect.md
  pyproject.toml
Labels: feat

#4364 refactor(exprs): remove unused sql json module
  Cargo.lock
  src/daft-sql/Cargo.toml
  src/daft-sql/src/modules/json.rs
Labels: refactor

#4374 fix: Remove dbg! in url download
  src/daft-functions/src/uri/mod.rs
Labels: fix

#4275 feat: Flotilla plan result
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-distributed/src/utils/channel.rs
  src/daft-distributed/src/utils/joinset.rs
Labels: feat

#4260 feat: Add a native local parquet writer
  Cargo.lock
  daft/recordbatch/partitioning.py
  src/arrow2/src/datatypes/mod.rs
  src/common/daft-config/src/lib.rs
  src/common/error/Cargo.toml
  src/common/error/src/error.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-recordbatch/Cargo.toml
  src/daft-recordbatch/src/lib.rs
  src/daft-writers/Cargo.toml
  src/daft-writers/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
  src/daft-writers/src/physical.rs
  src/daft-writers/src/utils.rs
  tests/cookbook/test_write.py
Labels: feat

#4344 perf: Morsel size ranges for project and filter operators
  src/daft-local-execution/src/buffer.rs
  src/daft-local-execution/src/dispatcher.rs
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/sinks/anti_semi_hash_join_probe.rs
  src/daft-local-execution/src/sinks/blocking_sink.rs
  src/daft-local-execution/src/sinks/concat.rs
  src/daft-local-execution/src/sinks/limit.rs
  src/daft-local-execution/src/sinks/monotonically_increasing_id.rs
  src/daft-local-execution/src/sinks/outer_hash_join_probe.rs
  src/daft-local-execution/src/sinks/write.rs
Labels: perf

#4348 refactor(exprs): proc macro for parsing arguments into structs
  Cargo.lock
  Cargo.toml
  src/common/macros/Cargo.toml
  src/common/macros/src/function_args.rs
  src/common/macros/src/lib.rs
  src/daft-dsl/Cargo.toml
  src/daft-dsl/src/functions/function_args.rs
  src/daft-dsl/src/functions/macro_tests.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-functions/src/numeric/abs.rs
  src/daft-functions/src/numeric/cbrt.rs
  src/daft-functions/src/numeric/ceil.rs
  src/daft-functions/src/numeric/clip.rs
  src/daft-functions/src/numeric/exp.rs
  src/daft-functions/src/numeric/floor.rs
  src/daft-functions/src/numeric/log.rs
  src/daft-functions/src/numeric/mod.rs
  src/daft-functions/src/numeric/sign.rs
  src/daft-functions/src/numeric/sqrt.rs
  src/daft-functions/src/numeric/trigonometry.rs
Labels: refactor

#4371 fix: adds HTTP and HF retry logic based upon exist GCS retry logic
  src/common/io-config/src/http.rs
  src/daft-io/src/http.rs
  src/daft-io/src/huggingface.rs
  src/daft-sql/src/modules/config.rs
Labels: fix

#4358 docs: rearrange integrations section into I/O
  daft/catalog/__init__.py
  docs/10min.ipynb
  docs/api/config.md
  docs/api/dataframe_creation.md
  docs/api/expressions.md
  docs/api/index.md
  docs/api/io.md
  docs/core_concepts.md
  docs/css/extra.css
  docs/distributed.md
  docs/index.md
  docs/integrations/ray.md
  docs/io.md
  docs/quickstart.md
  mkdocs.yml
  requirements-doc.txt
Labels: docs

#4328 perf: Use url_download max_connections for projection batch size
  src/daft-local-execution/src/intermediate_ops/project.rs
Labels: perf

#4382 fix: Add Rust Testing Import
  Cargo.lock
  src/daft-local-execution/Cargo.toml
Labels: fix

#4385 chore: Fix some strict mypy errors
  daft/delta_lake/delta_lake_write.py
  daft/dependencies.py
  daft/iceberg/iceberg_write.py
  daft/io/_generator.py
  daft/io/catalog.py
  daft/io/writer.py
  daft/lazy_import.py
Labels: chore

#4386 fix(mypy): part of the mypy strict mode errors
  daft/analytics.py
  daft/context.py
  daft/convert.py
  daft/daft/__init__.pyi
  daft/daft/dashboard.pyi
  daft/dashboard/__init__.py
  daft/dataframe/dataframe.py
  daft/dataframe/display.py
  daft/session.py
  daft/utils.py
Labels: fix

#4384 fix: mypy catalog fixes
  daft/catalog/__glue.py
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__s3tables.py
  daft/catalog/__unity.py
Labels: fix

#4369 fix: Remove botocore dependency when working with deltalake
  daft/delta_lake/delta_lake_scan.py
Labels: fix

#4395 chore: add repr json to dashboard broadcast & make url settable
  daft/dashboard/__init__.py
  daft/dataframe/dataframe.py
  src/daft-dashboard/src/lib.rs
  src/daft-logical-plan/src/display/json.rs
Labels: chore

#4397 fix: skip flaky actor pool GPU test
  tests/actor_pool/test_actor_cuda_devices.py
Labels: fix

#4377 docs: add roadmap
  docs/index.md
  docs/integrations/delta_lake.md
  docs/integrations/hudi.md
  docs/integrations/iceberg.md
  docs/integrations/unity_catalog.md
  docs/roadmap.md
  mkdocs.yml
Labels: docs

#4360 feat: Add put_multipart to s3_like
  src/daft-io/src/s3_like.rs
Labels: feat

#4329 perf: Split projections with expressions that need granular batching
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/optimization/optimizer.rs
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  src/daft-logical-plan/src/optimization/rules/mod.rs
Labels: perf

#4403 ci: Remove `py` runner tests from PR CI
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/pr-test-suite.yml
Labels: ci

#4407 fix(ci): import matplotlib for window function tutorial
  .github/workflows/notebook-checker.yml
Labels: fix

#4406 docs: fix readthedocs version dropdown
  docs/index.md
  docs/js/readthedocs.js
  docs/roadmap.md
Labels: docs

#4408 fix(tests): add retry to pyarrow parquet read
  tests/integration/io/parquet/test_reads_public_data.py
Labels: fix

#4405 fix: Add s3n to parse_url
  src/daft-io/src/lib.rs
  src/daft-writers/src/parquet_writer.rs
Labels: fix

#4391 feat: Add duration expressions
  Cargo.lock
  Cargo.toml
  daft/expressions/expressions.py
  daft/series.py
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/series/ops/arithmetic.rs
  src/daft-functions-temporal/Cargo.toml
  src/daft-functions-temporal/src/lib.rs
  src/daft-functions-temporal/src/total.rs
  src/lib.rs
  tests/expressions/test_temporal.py
Labels: feat

#4410 ci: Cancel ongoing PR tests on push
  .github/workflows/pr-test-suite.yml
Labels: ci

#4401 refactor(exprs): literal support for FunctionArgs proc macro
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/common/io-config/src/python.rs
  src/common/macros/src/function_args.rs
  src/common/macros/src/lib.rs
  src/daft-core/src/count_mode.rs
  src/daft-dsl/src/functions/function_args.rs
  src/daft-dsl/src/functions/macro_tests.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-dsl/src/lit/conversions.rs
  src/daft-dsl/src/lit/deserializer.rs
  src/daft-dsl/src/lit/mod.rs
  src/daft-dsl/src/lit/serializer.rs
  src/daft-dsl/src/python.rs
  src/daft-functions-list/src/count.rs
  src/daft-functions-list/src/lib.rs
  src/daft-functions/src/numeric/clip.rs
  src/daft-functions/src/numeric/round.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/uri.rs
  src/daft-functions/src/uri/download.rs
  src/daft-functions/src/uri/mod.rs
  src/daft-functions/src/uri/upload.rs
  src/daft-image/src/functions/decode.rs
  src/daft-image/src/functions/encode.rs
  src/daft-image/src/functions/to_mode.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-schema/src/image_format.rs
  src/daft-schema/src/image_mode.rs
  tests/recordbatch/numeric/test_numeric.py
  tests/sql/test_exprs.py
Labels: refactor

#4392 fix(mypy): mypy fixes for daft.runners
  .pre-commit-config.yaml
  daft/execution/execution_step.py
  daft/execution/native_executor.py
  daft/execution/physical_plan.py
  daft/hudi/pyhudi/utils.py
  daft/recordbatch/recordbatch.py
  daft/recordbatch/recordbatch_io.py
  daft/runners/distributed_swordfish.py
  daft/runners/partitioning.py
  daft/runners/profiler.py
  daft/runners/progress_bar.py
  daft/runners/pyrunner.py
  daft/runners/ray_metrics.py
  daft/runners/ray_runner.py
  daft/runners/ray_tracing.py
  daft/runners/runner.py
  daft/series.py
  daft/udf.py
  daft/viz/html_viz_hooks.py
  pyproject.toml
  tests/io/test_list_files_local.py
Labels: fix

#4416 feat: adds functions prelude and clean up contributing notes.
  CONTRIBUTING.md
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/prelude.rs
Labels: feat

#4417 build: make dashboard self contained again, except when running in ci
  .github/workflows/build-wheel.yml
  Makefile
  src/daft-dashboard/build.rs
Labels: build

#4419 docs: Fix docs generation for `Expression.embedding.cosine_distance`
  daft/expressions/expressions.py
Labels: docs

#4418 fix(spark-connect): withColumnRenamed now preserves non-renamed columns
  src/daft-connect/src/spark_analyzer.rs
  tests/connect/test_basics.py
Labels: fix

#4421 fix: Progress bar no longer panics
  daft/runners/progress_bar.py
Labels: fix

#4428 fix: Fix iceberg docker compose entrypoint command
  tests/integration/iceberg/docker-compose/docker-compose.yml
Labels: fix

#4415 fix: substr with null args
  src/daft-functions-utf8/src/substr.rs
  src/daft-schema/src/dtype.rs
  tests/expressions/conftest.py
  tests/expressions/test_utf8.py
Labels: fix

#4394 feat(catalogs): enable Rust usage of Python catalogs and tables
  daft/catalog/__glue.py
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__rust.py
  daft/catalog/__s3tables.py
  daft/catalog/__unity.py
  daft/daft/__init__.pyi
  daft/sql/sql.py
  src/daft-catalog/src/catalog.rs
  src/daft-catalog/src/error.rs
  src/daft-catalog/src/identifier.rs
  src/daft-catalog/src/python.rs
  src/daft-catalog/src/python/mod.rs
  src/daft-catalog/src/python/wrappers.rs
  src/daft-catalog/src/table.rs
  src/daft-session/src/error.rs
  src/daft-session/src/python.rs
  src/daft-session/src/session.rs
  src/daft-sql/src/error.rs
  src/daft-sql/src/exec.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  tests/catalog/test_catalog.py
  tests/catalog/test_glue.py
  tests/catalog/test_s3tables.py
  tests/test_session.py
Labels: feat

#4424 fix: Improve UDF errors
  daft/udf.py
  tests/dataframe/test_iter.py
  tests/expressions/test_udf.py
Labels: fix

#4440 fix: update broken-link-checker.yml
  .github/workflows/broken-link-checker.yml
Labels: fix

#4439 feat(flotilla): Additional PipelineNodes for map pipelines
  Cargo.lock
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/collect.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/intermediate.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/plan/mod.rs
  src/daft-distributed/src/plan/runner.rs
  src/daft-distributed/src/python/mod.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-plan/Cargo.toml
  src/daft-local-plan/src/plan.rs
Labels: feat

#4431 feat: enables scalar function lowering e.g. function overloads
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/functions/function_args.rs
  src/daft-dsl/src/functions/mod.rs
  src/daft-dsl/src/functions/scalar.rs
  src/daft-functions/src/python/mod.rs
  src/daft-sql/src/functions.rs
Labels: feat

#4375 feat: Flotilla scheduler and dispatcher actors
  Cargo.lock
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/python/ray/worker.rs
  src/daft-distributed/src/python/ray/worker_manager.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/scheduling/worker.rs
  src/daft-distributed/src/utils/joinset.rs
Labels: feat

#4442 feat(flotilla): LogicalPlan to PipelineNode translation
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/stage/mod.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/optimization/rules/granular_projections.rs
  src/daft-logical-plan/src/test/mod.rs
Labels: feat

#4449 feat: adds python partition fields to the DataSource API
  daft/io/__shim.py
  daft/io/source.py
Labels: feat

#4457 feat(flotilla): Materialize pipeline
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/intermediate.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/materialize.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/python/ray/task.rs
  src/daft-distributed/src/scheduling/dispatcher.rs
  src/daft-distributed/src/scheduling/mod.rs
  src/daft-distributed/src/scheduling/scheduler/default.rs
  src/daft-distributed/src/scheduling/scheduler/mod.rs
  src/daft-distributed/src/scheduling/scheduler/scheduler_actor.rs
  src/daft-distributed/src/scheduling/task.rs
  src/daft-distributed/src/scheduling/tests.rs
  src/daft-distributed/src/scheduling/worker.rs
  src/daft-distributed/src/stage/mod.rs
Labels: feat
