Repository Eventual-Inc/Daft, pull requests merged in 2025-10, with the labels that each got.

#5300 docs: Document Common Crawl dataset
  docs/SUMMARY.md
  docs/api/datasets.md
  docs/api/index.md
  docs/datasets/common-crawl.md
Labels: docs

#5303 fix: decimal format for handling scientific notation
  src/daft-core/src/lit/python.rs
  tests/test_datatype_inference.py
Labels: fix

#5313 docs: Add docs and values reference for quickstart chart
  k8s/charts/quickstart/README.md
  k8s/charts/quickstart/values.yaml
Labels: docs

#5315 chore: Refactor DistributedPipelineNode to implement TreeDisplay
  src/daft-distributed/src/pipeline_node/actor_udf.rs
  src/daft-distributed/src/pipeline_node/aggregate.rs
  src/daft-distributed/src/pipeline_node/concat.rs
  src/daft-distributed/src/pipeline_node/distinct.rs
  src/daft-distributed/src/pipeline_node/explode.rs
  src/daft-distributed/src/pipeline_node/filter.rs
  src/daft-distributed/src/pipeline_node/in_memory_source.rs
  src/daft-distributed/src/pipeline_node/into_batches.rs
  src/daft-distributed/src/pipeline_node/into_partitions.rs
  src/daft-distributed/src/pipeline_node/join/broadcast_join.rs
  src/daft-distributed/src/pipeline_node/join/cross_join.rs
  src/daft-distributed/src/pipeline_node/join/hash_join.rs
  src/daft-distributed/src/pipeline_node/join/translate_join.rs
  src/daft-distributed/src/pipeline_node/limit.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/monotonically_increasing_id.rs
  src/daft-distributed/src/pipeline_node/pivot.rs
  src/daft-distributed/src/pipeline_node/project.rs
  src/daft-distributed/src/pipeline_node/sample.rs
  src/daft-distributed/src/pipeline_node/scan_source.rs
  src/daft-distributed/src/pipeline_node/shuffles/gather.rs
  src/daft-distributed/src/pipeline_node/shuffles/pre_shuffle_merge.rs
  src/daft-distributed/src/pipeline_node/shuffles/repartition.rs
  src/daft-distributed/src/pipeline_node/shuffles/translate_shuffle.rs
  src/daft-distributed/src/pipeline_node/sink.rs
  src/daft-distributed/src/pipeline_node/sort.rs
  src/daft-distributed/src/pipeline_node/top_n.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-distributed/src/pipeline_node/udf.rs
  src/daft-distributed/src/pipeline_node/unpivot.rs
  src/daft-distributed/src/pipeline_node/window.rs
  src/daft-distributed/src/python/mod.rs
Labels: chore

#5304 feat: make file-array serializable
  src/daft-core/src/array/ops/from_arrow.rs
  src/daft-schema/src/dtype.rs
Labels: feat

#5319 perf: Support parallel CSV parsing when files contain carriage returns
  src/daft-csv/src/local.rs
Labels: perf

#5324 docs: Add docs to broken link checker
  .github/workflows/broken-link-checker.yml
Labels: docs

#5325 ci: fix property test column name
  tests/property_based_testing/strategies.py
Labels: ci

#5320 docs: Add architecture docs
  docs/SUMMARY.md
  docs/architecture/index.md
  docs/img/architecture.png
  docs/img/execution_model.png
  docs/img/flotilla.png
  docs/img/in_memory_data_representation.png
  docs/img/optimizer.png
  docs/img/swordfish.png
  docs/optimization/architecture.md
  mkdocs.yml
Labels: docs

#5327 ci: Only fail broken link checker on 404s
  .github/workflows/broken-link-checker.yml
Labels: ci

#5266 feat: Dashboard Query Subscriber
  Cargo.lock
  Cargo.toml
  daft/daft/dashboard.pyi
  daft/dataframe/dataframe.py
  daft/subscribers/__init__.py
  daft/subscribers/dashboard.py
  src/common/metrics/src/lib.rs
  src/daft-cli/Cargo.toml
  src/daft-cli/src/python.rs
  src/daft-context/Cargo.toml
  src/daft-context/src/lib.rs
  src/daft-context/src/python.rs
  src/daft-context/src/subscribers/dashboard.rs
  src/daft-context/src/subscribers/debug.rs
  src/daft-context/src/subscribers/mod.rs
  src/daft-context/src/subscribers/python.rs
  src/daft-dashboard/Cargo.toml
  src/daft-dashboard/src/client.rs
  src/daft-dashboard/src/engine.rs
  src/daft-dashboard/src/lib.rs
  src/daft-dashboard/src/python.rs
  src/daft-dashboard/src/state.rs
  src/daft-distributed/Cargo.toml
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/runtime_stats/mod.rs
  src/daft-local-execution/src/runtime_stats/subscribers.rs
  src/daft-local-execution/src/runtime_stats/subscribers/dashboard.rs
  src/daft-local-execution/src/runtime_stats/subscribers/opentelemetry.rs
  src/daft-local-execution/src/runtime_stats/subscribers/query.rs
  src/daft-schema/src/dtype.rs
Labels: feat

#5328 fix: Fix the make docs warnings
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/io/_csv.py
  daft/io/lance/_lance.py
  daft/schema.py
  docs/CONTRIBUTING.md
  docs/connectors/turbopuffer.md
  docs/datasets/common-crawl.md
  docs/examples/minhash-dedupe.md
  docs/examples/text-embeddings.md
  docs/examples/window-functions.md
  docs/integrations.md
  docs/modalities/json.md
  docs/quickstart.md
  docs/sql_overview.md
  docs/use-case/batch-inference.md
Labels: fix

#5335 docs: add daft.func docs page and APIs
  docs/SUMMARY.md
  docs/api/udf.md
  docs/custom-code/func.md
  docs/custom-code/udfs.md
Labels: docs

#5333 docs: add casting matrix
  daft/functions/misc.py
  docs/SUMMARY.md
  docs/api/datatypes/casting.md
Labels: docs

#5235 feat: Lazy `from_glob_path`
  Cargo.lock
  daft/daft/__init__.pyi
  daft/io/file_path.py
  daft/logical/builder.py
  src/common/metrics/src/ops.rs
  src/daft-distributed/Cargo.toml
  src/daft-distributed/src/pipeline_node/glob_scan_source.rs
  src/daft-distributed/src/pipeline_node/mod.rs
  src/daft-distributed/src/pipeline_node/translate.rs
  src/daft-ir/Cargo.toml
  src/daft-ir/src/proto/rel.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/channel.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sources/empty_scan.rs
  src/daft-local-execution/src/sources/glob_scan.rs
  src/daft-local-execution/src/sources/in_memory.rs
  src/daft-local-execution/src/sources/mod.rs
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-local-execution/src/sources/source.rs
  src/daft-local-plan/Cargo.toml
  src/daft-local-plan/src/lib.rs
  src/daft-local-plan/src/plan.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/ops/source.rs
  src/daft-logical-plan/src/optimization/rules/push_down_aggregation.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/push_down_limit.rs
  src/daft-logical-plan/src/optimization/rules/push_down_projection.rs
  src/daft-logical-plan/src/optimization/rules/push_down_shard.rs
  src/daft-logical-plan/src/source_info.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-proto/proto/v1/daft.proto
  src/daft-proto/src/generated/daft.v1.rs
  tests/cookbook/test_dataloading.py
Labels: feat

#5340 perf: use bincode instead of python for io_conf serialization in FileArray
  src/daft-core/src/array/file_array.rs
  src/daft-core/src/array/ops/get.rs
  src/daft-core/src/series/from_lit.rs
  src/daft-schema/src/dtype.rs
Labels: perf

#5337 ci: Add ai benchmarks ci
  .github/ci-scripts/distributed_tpch.py
  .github/ci-scripts/run_ai_benchmark.py
  .github/workflows/benchmark-ai.yml
  benchmarking/ai/audio_transcription/cluster.yaml
  benchmarking/ai/document_embedding/cluster.yaml
  benchmarking/ai/image_classification/cluster.yaml
  benchmarking/ai/video_object_detection/cluster.yaml
  tools/ci_bench_utils.py
Labels: ci
