Repository Eventual-Inc/Daft, pull requests merged in 2025-03, with the labels that each got.

#3877 perf: Clear task inputs upon dispatch
  daft/runners/ray_runner.py
Labels: perf

#3881 fix: Add check for numpy in from_pylist
  daft/series.py
Labels: fix

#3871 feat: Add WARC reader
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.toml
  daft/__init__.py
  daft/daft/__init__.pyi
  daft/io/__init__.py
  daft/io/_warc.py
  docs/sphinx/source/creation.rst
  pyproject.toml
  src/arrow2/src/array/binary/mutable.rs
  src/arrow2/src/array/binary/mutable_values.rs
  src/common/file-formats/src/file_format.rs
  src/common/file-formats/src/file_format_config.rs
  src/common/file-formats/src/lib.rs
  src/common/file-formats/src/python.rs
  src/daft-compression/src/compression.rs
  src/daft-local-execution/Cargo.toml
  src/daft-local-execution/src/sources/scan_task.rs
  src/daft-logical-plan/src/lib.rs
  src/daft-micropartition/Cargo.toml
  src/daft-micropartition/src/micropartition.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-scan/src/glob.rs
  src/daft-scan/src/lib.rs
  src/daft-warc/Cargo.toml
  src/daft-warc/src/lib.rs
  src/parquet2/src/compression.rs
  tests/assets/example.warc
  tests/assets/example.warc.gz
  tests/io/test_warc.py
Labels: feat

#3884 feat: trig functions csc and sec
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  src/daft-connect/src/functions/math.rs
  src/daft-core/src/array/ops/trigonometry.rs
  src/daft-core/src/python/series.rs
  src/daft-functions/src/numeric/trigonometry.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/numeric.rs
  src/daft-sql/src/modules/numeric.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/recordbatch/numeric/test_numeric.py
Labels: feat

#3888 fix: remove dashboard imports and dep
  daft/dataframe/dataframe.py
  pyproject.toml
Labels: fix

#3887 feat: Functions log1p and expm1
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/daft-connect/src/functions/math.rs
  src/daft-core/src/array/ops/exp.rs
  src/daft-core/src/array/ops/log.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/exp.rs
  src/daft-core/src/series/ops/log.rs
  src/daft-functions/src/numeric/exp.rs
  src/daft-functions/src/numeric/log.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/numeric.rs
  src/daft-sql/src/modules/numeric.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/recordbatch/numeric/test_numeric.py
Labels: feat

#3864 ci: replace build-artifact-s3 with new workflow, add local tpch benches
  .github/ci-scripts/local_tpch.py
  .github/workflows/benchmark-local-tpch.yml
  .github/workflows/build-artifact-s3.yml
  .github/workflows/nightlies-tests.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/publish-dev-s3.yml
  tools/generate_whl_html_manifest.py
  tools/patch_package_version.py
Labels: ci

#3900 docs: remove cairo
  docs/mkdocs.yml
Labels: docs

#3880 docs: Add documentation for functions module
  docs/mkdocs/core_concepts.md
  docs/sphinx/source/functions.rst
  docs/sphinx/source/index.rst
Labels: docs

#3903 feat: functions sinh, cosh, tanh
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/daft-connect/src/functions/math.rs
  src/daft-core/src/array/ops/trigonometry.rs
  src/daft-core/src/python/series.rs
  src/daft-functions/src/numeric/trigonometry.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/numeric.rs
  src/daft-sql/src/modules/numeric.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/recordbatch/numeric/test_numeric.py
Labels: feat

#3892 fix: map.get on empty dataset
  src/daft-core/src/array/ops/map.rs
  tests/recordbatch/map/test_map_get.py
Labels: fix

#3899 fix: small fix for pyspark+ray.
  daft/pyspark/__init__.py
  daft/runners/ray_runner.py
Labels: fix

#3908 fix: coalesce panics, supertype handling, and null handling bugs
  src/daft-core/src/utils/supertype.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-functions/src/coalesce.rs
  tests/sql/test_coalesce.py
Labels: fix

#3901 feat(catalog): adds additional table sources for Catalog.from_pydict
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__unity.py
  daft/session.py
  daft/unity_catalog/unity_catalog.py
  tests/catalog/test_catalog.py
Labels: feat

#3889 feat(catalog): adds append and overwrite to table apis
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__unity.py
  daft/logical/schema.py
  daft/session.py
  tests/catalog/test_iceberg.py
  tests/integration/iceberg/test_iceberg_reads.py
  tests/integration/iceberg/test_iceberg_table.py
  tests/integration/iceberg/test_iceberg_writes.py
Labels: feat

#3913 build: build and publish daft package
  .github/workflows/build-wheel.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/publish-dev-s3.yml
  .github/workflows/publish-pypi.yml
  daft/__init__.py
  pyproject.toml
  requirements-dev.txt
Labels: build

#3909 chore: move dashboard in to main project
  .github/workflows/python-package.yml
  Cargo.lock
  Cargo.toml
  Makefile
  daft/daft/dashboard.pyi
  daft/dashboard.py
  daft/dashboard/__init__.py
  daft_dashboard/pyproject.toml
  src/daft-dashboard/Cargo.toml
  src/daft-dashboard/build.rs
  src/daft-dashboard/frontend/.gitignore
  src/daft-dashboard/frontend/README.md
  src/daft-dashboard/frontend/bun.lockb
  src/daft-dashboard/frontend/components.json
  src/daft-dashboard/frontend/eslint.config.mjs
  src/daft-dashboard/frontend/next.config.ts
  src/daft-dashboard/frontend/out/.gitkeep
  src/daft-dashboard/frontend/package.json
  src/daft-dashboard/frontend/postcss.config.mjs
  src/daft-dashboard/frontend/src/app/favicon.ico
  src/daft-dashboard/frontend/src/app/globals.css
  src/daft-dashboard/frontend/src/app/layout.tsx
  src/daft-dashboard/frontend/src/app/page.tsx
  src/daft-dashboard/frontend/src/app/queries/page.tsx
  src/daft-dashboard/frontend/src/app/queries/query/page.tsx
  src/daft-dashboard/frontend/src/atoms/queryInfo.ts
  src/daft-dashboard/frontend/src/components/app-sidebar.tsx
  src/daft-dashboard/frontend/src/components/search-form.tsx
  src/daft-dashboard/frontend/src/components/status-badge.tsx
  src/daft-dashboard/frontend/src/components/ui/badge.tsx
  src/daft-dashboard/frontend/src/components/ui/breadcrumb.tsx
  src/daft-dashboard/frontend/src/components/ui/button.tsx
  src/daft-dashboard/frontend/src/components/ui/card.tsx
  src/daft-dashboard/frontend/src/components/ui/checkbox.tsx
  src/daft-dashboard/frontend/src/components/ui/collapsible.tsx
  src/daft-dashboard/frontend/src/components/ui/dropdown-menu.tsx
  src/daft-dashboard/frontend/src/components/ui/input.tsx
  src/daft-dashboard/frontend/src/components/ui/label.tsx
  src/daft-dashboard/frontend/src/components/ui/select.tsx
  src/daft-dashboard/frontend/src/components/ui/separator.tsx
  src/daft-dashboard/frontend/src/components/ui/sheet.tsx
  src/daft-dashboard/frontend/src/components/ui/sidebar.tsx
  src/daft-dashboard/frontend/src/components/ui/skeleton.tsx
  src/daft-dashboard/frontend/src/components/ui/spinner.tsx
  src/daft-dashboard/frontend/src/components/ui/table.tsx
  src/daft-dashboard/frontend/src/components/ui/tooltip.tsx
  src/daft-dashboard/frontend/src/components/version-switcher.tsx
  src/daft-dashboard/frontend/src/hooks/use-mobile.tsx
  src/daft-dashboard/frontend/src/lib/utils.ts
  src/daft-dashboard/frontend/tailwind.config.ts
  src/daft-dashboard/frontend/tsconfig.json
  src/daft-dashboard/src/lib.rs
  src/daft-dashboard/src/python.rs
  src/daft-dashboard/src/response.rs
  src/lib.rs
Labels: chore

#3916 chore: use stdlib importlib.metadata for python>3.9
  daft/__init__.py
  pyproject.toml
Labels: chore

#3912 feat(sql): adds the 'use' sql session statement
  daft/catalog/__init__.py
  daft/daft/__init__.pyi
  daft/session.py
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  src/daft-sql/src/python.rs
  src/daft-sql/src/statement.rs
  tests/catalog/test_identifier.py
  tests/test_session.py
Labels: feat

#3902 feat(catalog): adds catalog ddl actions like create_table and create_namespace
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__unity.py
  daft/session.py
  tests/catalog/test_iceberg.py
Labels: feat

#3918 fix(dashboard): get dashboard working again
  CONTRIBUTING.md
  Cargo.lock
  daft/daft/dashboard.pyi
  daft/dashboard/__init__.py
  daft/dataframe/dataframe.py
  src/daft-dashboard/Cargo.toml
  src/daft-dashboard/src/lib.rs
  src/daft-dashboard/src/python.rs
Labels: fix

#3919 docs: add spark connect doc page
  docs/mkdocs.yml
  docs/mkdocs/spark_connect.md
Labels: docs

#3907 feat: adds encode and decode for deflate, gzip, zlib
  Cargo.lock
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  docs/sphinx/source/expressions.rst
  src/daft-core/src/array/ops/binary.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/binary/codecs.rs
  src/daft-functions/src/binary/decode.rs
  src/daft-functions/src/binary/encode.rs
  src/daft-functions/src/binary/mod.rs
  src/daft-functions/src/lib.rs
  src/daft-functions/src/python/binary.rs
  src/daft-functions/src/python/mod.rs
  tests/functions/__init__.py
  tests/functions/test_codecs.py
Labels: feat

#3924 fix: write_lance append mode when storage_options required
  daft/dataframe/dataframe.py
  tests/io/lancedb/test_lancedb_writes.py
Labels: fix

#3915 ci: update all --release workflows
  .github/workflows/build-commit.yaml
  .github/workflows/build-wheel.yml
  .github/workflows/daft-profiling.yml
  .github/workflows/property-based-tests.yml
Labels: ci

#3917 fix: Don't use `_position_to_field_name`
  daft/iceberg/iceberg_scan.py
  pyproject.toml
Labels: fix

#3926 docs: adds additional catalog and session documentation
  daft/__init__.py
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/session.py
  docs/mkdocs.yml
  docs/mkdocs/catalogs.md
  docs/mkdocs/css/extra.css
  docs/mkdocs/sessions.md
Labels: docs

#3928 fix: allow resolving tables at catalog root
  src/daft-session/src/session.rs
  tests/sql/test_sess_sql.py
Labels: fix

#3932 fix: bun install in build-wheel.yml
  .github/workflows/build-wheel.yml
Labels: fix

#3930 fix: add retry to getting GCS client config
  src/daft-io/src/google_cloud.rs
  src/daft-io/src/lib.rs
  src/daft-io/src/retry.rs
  src/daft-io/src/s3_like.rs
Labels: fix

#3898 fix: nightly build and local tpch benchmark workflow
  .github/ci-scripts/local_tpch.py
  .github/workflows/benchmark-local-tpch.yml
  .github/workflows/nightlies-tests.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/publish-dev-s3.yml
  benchmarking/tpch/answers.py
Labels: fix

#3937 chore: use ref name instead of ref in tpch bench metadata
  .github/ci-scripts/local_tpch.py
Labels: chore

#3935 perf: Reduce memory consumption for WARC reads and improve estimates
  Cargo.lock
  daft/daft/__init__.pyi
  daft/io/_warc.py
  daft/recordbatch/micropartition.py
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/python.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/src/lib.rs
  src/daft-warc/Cargo.toml
  src/daft-warc/src/lib.rs
Labels: perf

#3939 chore: Favor OnceLock over lazy_static for WARC column sizes
  Cargo.lock
  src/daft-scan/Cargo.toml
  src/daft-scan/src/lib.rs
Labels: chore

#3914 fix: Pass CommitProperties object custom metadata in deltalake
  daft/dataframe/dataframe.py
  pyproject.toml
  tests/io/delta_lake/test_table_write.py
Labels: p1, fix

#3946 fix: Count bytes read correctly for local WARC reads
  .pre-commit-config.yaml
  src/daft-io/src/counting_reader.rs
  src/daft-io/src/lib.rs
  src/daft-parquet/src/stream_reader.rs
  src/daft-warc/src/lib.rs
  src/daft-warc/test/example.warc
  src/daft-warc/test/example.warc.gz
Labels: fix

#3948 fix: Add target dialect when making subquery in read_sql
  daft/sql/sql_connection.py
  tests/integration/sql/conftest.py
  tests/integration/sql/test_sql.py
Labels: fix

#3951 feat: cast using a string type
  daft/daft/__init__.pyi
  daft/datatype.py
  daft/expressions/expressions.py
  src/daft-sql/src/lib.rs
  src/daft-sql/src/python.rs
  tests/expressions/test_expressions.py
Labels: feat

#3950 fix: fix error when casting monotonically_increasing_id directly
  src/daft-dsl/src/expr/mod.rs
  tests/dataframe/test_monotonically_increasing_id.py
Labels: fix

#3952 fix(ci): slack failure notification parameters
  .github/workflows/daft-profiling.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/notebook-checker.yml
  .github/workflows/property-based-tests.yml
  .github/workflows/python-package.yml
  .github/workflows/ray-compatibility.yml
Labels: fix

#3962 fix: depend on pylance instead of lancedb
  pyproject.toml
  requirements-dev.txt
Labels: fix

#3966 chore: fix slack link in readme
  README.rst
Labels: chore

#3967 fix(ci): distributed tpch benchmark
  .github/assets/tpch-bench.yaml
  .github/ci-scripts/distributed_tpch.py
  .github/workflows/benchmark-distributed-tpch.yml
  .github/workflows/nightly-publish-s3.yml
  benchmarking/tpch/answers_sql.py
Labels: fix

#3968 ci: fix typo in nightly workflow
  .github/workflows/nightly-publish-s3.yml
Labels: ci

#3956 feat: daft.range function
  daft/__init__.py
  daft/io/__init__.py
  daft/io/_range.py
  tests/io/test_range.py
Labels: feat

#3931 chore: dashboard build cleanup
  src/daft-dashboard/build.rs
  src/daft-dashboard/frontend/out/.gitkeep
  src/daft-dashboard/frontend/package.json
  src/daft-dashboard/src/lib.rs
Labels: chore

#3953 fix: Add more retries to sql server connection in test
  tests/integration/sql/conftest.py
Labels: fix

#3971 ci: update distributed tpch benchmark
  .github/assets/tpch-bench.yaml
  .github/ci-scripts/distributed_tpch.py
  .github/workflows/benchmark-distributed-tpch.yml
  benchmarking/tpch/answers_sql.py
Labels: ci

#3974 docs: fix docs examples and add missing docs
  daft/dataframe/dataframe.py
  daft/datatype.py
  daft/io/_lance.py
  daft/udf.py
  docs/sphinx/source/dataframe.rst
  docs/sphinx/source/expressions.rst
Labels: docs

#3972 fix: tutorial code
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
Labels: fix

#3981 chore: add pr template
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
Labels: chore

#3904 feat: Flight shuffle
  Cargo.lock
  Cargo.toml
  daft/context.py
  daft/daft/__init__.pyi
  daft/dependencies.py
  daft/execution/shuffles/flight_shuffle/flight_server.py
  daft/execution/shuffles/flight_shuffle/flight_shuffle.py
  src/arrow2/src/io/ipc/write/stream.rs
  src/common/daft-config/src/lib.rs
  src/common/daft-config/src/python.rs
  src/daft-physical-plan/Cargo.toml
  src/daft-physical-plan/src/ops/shuffle_exchange.rs
  src/daft-physical-plan/src/optimization/rules/drop_repartition.rs
  src/daft-physical-plan/src/optimization/rules/reorder_partition_keys.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-shuffles/Cargo.toml
  src/daft-shuffles/src/lib.rs
  src/daft-shuffles/src/python.rs
  src/daft-shuffles/src/shuffle_cache.rs
  src/daft-writers/Cargo.toml
  src/daft-writers/src/batch.rs
  src/daft-writers/src/file.rs
  src/daft-writers/src/ipc.rs
  src/daft-writers/src/lance.rs
  src/daft-writers/src/lib.rs
  src/daft-writers/src/partition.rs
  src/daft-writers/src/pyarrow.rs
  src/daft-writers/src/test.rs
  src/lib.rs
  tests/dataframe/test_shuffles.py
Labels: feat

#3988 fix: Fix incorrect numeric identity optimizations
  src/daft-algebra/src/simplify/numeric.rs
Labels: fix

#3987 fix: datetime deprecation
  daft/analytics.py
  tests/test_analytics.py
Labels: fix

#3999 chore(dashboard): update Next.js dependency to version 15.2.2
  src/daft-dashboard/frontend/bun.lockb
  src/daft-dashboard/frontend/package.json
Labels: chore

#3990 fix: Fix list sort with groupby
  src/daft-core/src/array/ops/list.rs
  tests/recordbatch/list/test_list_sort.py
Labels: fix

#3725 feat: offset indices in sparse tensor
  daft/daft/__init__.pyi
  daft/datatype.py
  src/daft-connect/src/display.rs
  src/daft-core/src/array/ops/cast.rs
  src/daft-core/src/array/ops/sparse_tensor.rs
  src/daft-core/src/array/ops/tensor.rs
  src/daft-recordbatch/src/repr_html.rs
  src/daft-schema/src/dtype.rs
  src/daft-schema/src/python/datatype.rs
  tests/series/test_cast.py
  tests/series/test_sparse_tensor.py
Labels: feat

#3929 feat(catalog): adds native s3tables read and catalog apis
  daft/catalog/__init__.py
  daft/catalog/__s3tables.py
  requirements-dev.txt
  tests/catalog/test_s3tables.py
Labels: feat

#4005 chore: create in-memory scans using rust arrow arrays
  .vscode/settings.json
  Cargo.lock
  daft/dataframe/dataframe.py
  daft/logical/builder.py
  src/common/partitioning/src/lib.rs
  src/daft-core/src/series/mod.rs
  src/daft-micropartition/src/micropartition.rs
  src/daft-micropartition/src/partitioning.rs
  src/daft-micropartition/src/python.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-scan/Cargo.toml
  src/daft-scan/README.md
  src/daft-schema/src/schema.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/table_provider/in_memory.rs
  src/daft-sql/src/table_provider/mod.rs
  tests/dataframe/test_describe.py
Labels: chore

#3986 docs: change all mentions of getdaft -> daft
  .github/assets/tpch-bench.yaml
  .github/ci-scripts/templatize_ray_config.py
  .github/workflows/benchmark-local-tpch.yml
  .github/workflows/build-wheel.yml
  .github/workflows/nightly-publish-s3.yml
  .github/workflows/publish-dev-s3.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/python-package.yml
  README.rst
  benchmarking/parquet/README.md
  benchmarking/tpch/ray_job_runner.py
  daft/analytics.py
  daft/catalog/__init__.py
  daft/dataframe/dataframe.py
  daft/filesystem.py
  daft/io/_lance.py
  daft/runners/ray_metrics.py
  daft/runners/ray_runner.py
  docs/mkdocs/10min.ipynb
  docs/mkdocs/install.md
  docs/mkdocs/integrations/delta_lake.md
  docs/mkdocs/integrations/hudi.md
  docs/mkdocs/integrations/ray.md
  docs/mkdocs/integrations/sql.md
  docs/mkdocs/integrations/unity_catalog.md
  docs/mkdocs/quickstart.ipynb
  docs/mkdocs/quickstart.md
  pyproject.toml
  tests/test_analytics.py
  tutorials/delta_lake/3-pytorch-ray-single-node-training.ipynb
  tutorials/embeddings/daft_tutorial_embeddings_stackexchange.ipynb
  tutorials/flyte/Dockerfile
  tutorials/image_querying/top_n_red_color.ipynb
  tutorials/intro.ipynb
  tutorials/mnist.ipynb
  tutorials/talks_and_demos/data-ai-summit-2024.ipynb
  tutorials/talks_and_demos/iceberg_summit_2024.ipynb
  tutorials/talks_and_demos/linkedin-03-05-2024.ipynb
  tutorials/text_to_image/text_to_image_generation.ipynb
  tutorials/text_to_image/using_cloud_with_ray.ipynb
Labels: docs

#4011 feat(sql): adds show tables statement and documentation
  daft/daft/__init__.pyi
  daft/runners/partitioning.py
  docs/mkdocs.yml
  docs/mkdocs/sql/statements/show.md
  src/daft-catalog/src/catalog.rs
  src/daft-catalog/src/python.rs
  src/daft-micropartition/src/python.rs
  src/daft-sql/src/exec.rs
  src/daft-sql/src/lib.rs
  src/daft-sql/src/python.rs
  src/daft-sql/src/statement.rs
  src/daft-sql/src/table_provider/in_memory.rs
  src/daft-sql/src/table_provider/mod.rs
  tests/sql/test_sql_show_tables.py
Labels: feat

#4013 feat(sql): namespace support with in-memory catalog
  daft/catalog/__memory.py
  tests/catalog/test_catalog.py
Labels: feat

#3941 feat: Functions: sign, signum, positive, negative, negate
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  daft/series.py
  docs/sphinx/source/expressions.rst
  src/daft-connect/src/functions/math.rs
  src/daft-core/src/array/ops/sign.rs
  src/daft-core/src/python/series.rs
  src/daft-core/src/series/ops/sign.rs
  src/daft-functions/src/numeric/sign.rs
  src/daft-functions/src/python/mod.rs
  src/daft-functions/src/python/numeric.rs
  src/daft-sql/src/modules/numeric.rs
  tests/expressions/test_expressions.py
  tests/expressions/typing/test_arithmetic.py
  tests/recordbatch/numeric/test_numeric.py
Labels: feat

#4010 perf: Refactor selectivity estimates
  src/daft-dsl/src/expr/mod.rs
Labels: perf

#4016 fix: Fix boolean expression simplifier
  src/daft-algebra/src/simplify/boolean.rs
Labels: fix

#4017 chore: Upgrade kanal to 0.1
  Cargo.lock
  src/daft-local-execution/Cargo.toml
Labels: chore

#4020 feat: adds gz as gzip alias for encode, decode methods
  daft/expressions/expressions.py
  src/daft-functions/src/binary/codecs.rs
  tests/functions/test_codecs.py
Labels: feat

#4018 feat(catalog): adds s3tables iceberg rest endpoint
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__s3tables.py
  docs/mkdocs.yml
  docs/mkdocs/integrations/s3tables.md
  tests/catalog/test_s3tables.py
Labels: feat

#4003 perf: Favor smaller relations on the left for join ordering
  src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
Labels: perf

#4025 docs: Fix s3 tables docs
  docs/mkdocs/integrations/s3tables.md
Labels: docs

#4006 feat: Add a memory-efficient iterator for Series
  daft/dataframe/dataframe.py
  daft/expressions/expressions.py
  daft/filesystem.py
  daft/io/writer.py
  daft/series.py
  daft/udf.py
  docs/mkdocs/10min.ipynb
  docs/mkdocs/core_concepts.md
  tests/series/test_series.py
Labels: feat

#4026 docs: update install instructions for daft-lts and nightly
  docs/mkdocs/install.md
Labels: docs

#4028 fix: Fix join condition swaps when left/right sides swap
  src/daft-logical-plan/src/optimization/rules/reorder_joins/brute_force_join_order.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
Labels: fix

#4027 feat: syntactic sugar for Python list and struct gets
  daft/expressions/expressions.py
  docs/mkdocs/core_concepts.md
  docs/sphinx/source/expressions.rst
  tests/expressions/test_getitem.py
Labels: feat

#4024 chore: Track imports on scarf
  daft/__init__.py
  daft/runners/native_runner.py
  daft/runners/pyrunner.py
  daft/runners/ray_runner.py
  daft/scarf_telemetry.py
  tests/test_scarf_telemetry.py
Labels: chore

#4022 feat(sql): Add basic ROLLUP support
  src/daft-sql/src/planner.rs
  tests/sql/test_aggs.py
Labels: feat

#4009 feat: add `llm_generate` expr
  daft/functions/__init__.py
  daft/functions/llm_generate.py
  daft/udf.py
  docs/sphinx/source/functions.rst
  requirements-dev.txt
  tests/functions/test_llm_generate.py
Labels: feat

#4056 docs: fix broken links and clarify contributing
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
  docs/mkdocs/core_concepts.md
  docs/mkdocs/sql/datatypes.md
  docs/mkdocs/sql/overview.md
Labels: docs

#4042 feat: Set batch size as morsel size for project
  src/daft-dsl/src/functions/python/mod.rs
  src/daft-local-execution/src/intermediate_ops/actor_pool_project.rs
  src/daft-local-execution/src/intermediate_ops/intermediate_op.rs
  src/daft-local-execution/src/intermediate_ops/project.rs
  src/daft-local-execution/src/pipeline.rs
Labels: feat

#4015 feat(dashboard): Add Daft CLI with dashboard command
  Cargo.lock
  Cargo.toml
  daft/cli.py
  daft/daft/__init__.pyi
  pyproject.toml
  src/daft-cli/Cargo.toml
  src/daft-cli/src/lib.rs
  src/daft-cli/src/python.rs
  src/daft-dashboard/src/lib.rs
  src/daft-dashboard/src/python.rs
  src/lib.rs
Labels: feat

#4051 fix: dashboard flaking
  src/daft-dashboard/build.rs
Labels: fix

#4061 fix: Collect iterators in read_generator to list
  daft/io/_generator.py
  tests/io/test_range.py
Labels: fix

#4064 fix: only install vllm in requirements-dev.txt for linux
  requirements-dev.txt
Labels: fix

#4066 fix: Fix local to ray runner switch test
  tests/test_context.py
Labels: fix

#4068 chore: Remove ray compatibility workflow
  .github/workflows/ray-compatibility.yml
Labels: chore

#4057 docs: Adjusted SQL TYPE docu and adjusted tests accordings
  docs/mkdocs/sql/datatypes.md
  tests/expressions/test_expressions.py
Labels: docs

#4054 docs: add link to sql reference page inside cast
  daft/expressions/expressions.py
Labels: docs

#4037 fix: improve column error messages + add PlanRef to outer column
  src/daft-dsl/src/expr/mod.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-sql/src/lib.rs
Labels: fix

#4073 fix: surface non 'NotFound' errors during table resolution
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__unity.py
  daft/session.py
  src/daft-catalog/src/python.rs
  tests/test_session.py
Labels: fix

#4071 feat: Cross column exprs
  .github/workflows/python-package.yml
  daft/functions/__init__.py
  daft/functions/functions.py
  docs/sphinx/source/functions.rst
  tests/dataframe/test_horizontal.py
Labels: feat

#4023 perf(optimizer): simplify join types with null-eliminating filter predicates
  src/daft-algebra/src/boolean.rs
  src/daft-core/src/join.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
Labels: perf

#3922 feat: non-equi join in the logical plan
  Cargo.lock
  Cargo.toml
  src/daft-connect/Cargo.toml
  src/daft-connect/src/spark_analyzer.rs
  src/daft-dsl/src/expr/mod.rs
  src/daft-dsl/src/lib.rs
  src/daft-local-plan/src/translate.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/builder/resolve_expr.rs
  src/daft-logical-plan/src/display.rs
  src/daft-logical-plan/src/logical_plan.rs
  src/daft-logical-plan/src/ops/join.rs
  src/daft-logical-plan/src/ops/set_operations.rs
  src/daft-logical-plan/src/optimization/join_key_set.rs
  src/daft-logical-plan/src/optimization/rules/eliminate_cross_join.rs
  src/daft-logical-plan/src/optimization/rules/filter_null_join_key.rs
  src/daft-logical-plan/src/optimization/rules/push_down_filter.rs
  src/daft-logical-plan/src/optimization/rules/reorder_joins/join_graph.rs
  src/daft-logical-plan/src/optimization/rules/unnest_subquery.rs
  src/daft-logical-plan/src/treenode.rs
  src/daft-physical-plan/src/physical_planner/translate.rs
  src/daft-schema/src/schema.rs
  src/daft-sql/Cargo.toml
  src/daft-sql/src/lib.rs
  src/daft-sql/src/planner.rs
  tests/connect/test_spark_joins.py
Labels: feat

#4084 docs: s3tables typo fixes
  docs/mkdocs/integrations/s3tables.md
Labels: docs

#4086 docs: permalink works and takes to docs site
  daft/expressions/expressions.py
Labels: docs

#4088 feat: adds has_table and has_namespace catalog methods
  daft/__init__.py
  daft/catalog/__iceberg.py
  daft/catalog/__init__.py
  daft/catalog/__memory.py
  daft/catalog/__s3tables.py
  daft/catalog/__unity.py
  daft/session.py
  docs/mkdocs/sessions.md
  requirements-dev.txt
  tests/catalog/test_iceberg.py
  tests/catalog/test_s3tables.py
Labels: feat

#4060 feat: adds try_encode and try_decode with utf-8 special-case
  Cargo.lock
  daft/daft/__init__.pyi
  daft/expressions/expressions.py
  src/daft-core/src/array/ops/binary.rs
  src/daft-core/src/array/ops/utf8.rs
  src/daft-functions/Cargo.toml
  src/daft-functions/src/binary/codecs.rs
  src/daft-functions/src/binary/decode.rs
  src/daft-functions/src/binary/encode.rs
  src/daft-functions/src/python/binary.rs
  src/daft-functions/src/python/mod.rs
  tests/functions/test_codecs.py
Labels: feat

#4091 feat: adds create_table_if_not_exists and create_namespace_if_not_exists
  daft/__init__.py
  daft/catalog/__init__.py
  daft/session.py
  docs/mkdocs/sessions.md
  tests/catalog/test_iceberg.py
  tests/catalog/test_identifier.py
Labels: feat

#4089 feat(connect): overwrite mode for writing csv & parquet
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/execution/execution_step.py
  daft/execution/physical_plan.py
  daft/execution/rust_physical_plan_shim.py
  daft/filesystem.py
  daft/io/writer.py
  daft/logical/builder.py
  src/common/file-formats/src/file_format.rs
  src/common/file-formats/src/lib.rs
  src/common/file-formats/src/python.rs
  src/daft-connect/src/execute.rs
  src/daft-local-execution/src/pipeline.rs
  src/daft-local-execution/src/sinks/write.rs
  src/daft-logical-plan/src/builder/mod.rs
  src/daft-logical-plan/src/sink_info.rs
  src/daft-scheduler/src/scheduler.rs
  src/daft-writers/src/lib.rs
  tests/connect/test_io.py
Labels: feat

#4103 docs: Add numbering rows section
  docs/mkdocs/core_concepts.md
Labels: docs

#4110 fix: Use io-runtime for task in remote parquet reader
  src/daft-parquet/src/file.rs
Labels: fix

#4100 feat: adds formatting arguments to show
  .pre-commit-config.yaml
  Cargo.lock
  daft/daft/__init__.pyi
  daft/dataframe/dataframe.py
  daft/dataframe/preview.py
  daft/execution/execution_step.py
  daft/recordbatch/micropartition.py
  daft/viz/__init__.py
  daft/viz/dataframe_display.py
  src/daft-micropartition/src/python.rs
  src/daft-recordbatch/Cargo.toml
  src/daft-recordbatch/src/ffi.rs
  src/daft-recordbatch/src/lib.rs
  src/daft-recordbatch/src/preview.rs
  src/daft-recordbatch/src/python.rs
  src/daft-scan/src/python.rs
  tests/cookbook/test_write.py
  tests/dataframe/test_creation.py
  tests/dataframe/test_repr.py
  tests/dataframe/test_show.py
  tests/ray/test_dask.py
  tests/ray/test_datasets.py
Labels: feat

#4102 fix: Allow aliased monotonically increasing id functions to coexist with columns named "id"
  src/daft-logical-plan/src/ops/monotonically_increasing_id.rs
  src/daft-logical-plan/src/optimization/rules/detect_monotonic_id.rs
Labels: fix

#4119 docs: fix deltalake type docs
  docs/mkdocs/integrations/delta_lake.md
Labels: docs

#4115 fix: Disable warc merging
  src/daft-scan/src/scan_task_iters/mod.rs
  tests/io/test_merge_scan_tasks.py
Labels: fix

#4121 feat: @nikkthegreek adds support for creating managed tables
  daft/unity_catalog/unity_catalog.py
Labels: feat
